In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2015.csv",sep=";" )
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILGISAYAR_MASAUSTU,BT_BILGISAYAR_TASINABILIR,BT_TELEFON_CEP,BT_OYUNKONSOL,BT_TELEFON_SABIT,BT_FOTOGRAF_KAMERA,BT_DVD_VCD_OYNATICI,BT_INTBAGLANAN_TV,...,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_DIGER,HANE_GELIR_AYLIK,HHB,HANE_FAKTOR,IBBS_1,CEVAPLILIK_DURUM,HANE_DURUM,MEKTUP_BROSUR
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,KAPSAMICI,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,KAPSAMICI,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,KAPSAMICI,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,...,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,KAPSAMICI,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,KAPSAMICI,1.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12210 entries, 0 to 12209
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   12210 non-null  int64
 1   BULTEN_NO                      12210 non-null  int64
 2   BT_BILGISAYAR_MASAUSTU         9847 non-null   float64
 3   BT_BILGISAYAR_TASINABILIR      9847 non-null   float64
 4   BT_TELEFON_CEP                 9847 non-null   float64
 5   BT_OYUNKONSOL                  9847 non-null   float64
 6   BT_TELEFON_SABIT               9847 non-null   float64
 7   BT_FOTOGRAF_KAMERA             9847 non-null   float64
 8   BT_DVD_VCD_OYNATICI            9847 non-null   float64
 9   BT_INTBAGLANAN_TV              9847 non-null   float64
 10  BT_DIGER                       9847 non-null   float64
 11  HANE_BILGISAYAR_KULLANIM       9847 non-null   float64
 12  HANE_INTERNET_ERISIM_DURUMU    9847 non-null   float64
 13  HANE_INTERNET_ERISIM_KULLANIM  6424 non-null   float64
 14  INT_BAGLANMA_MASAUSTU          6424 non-null   float64
 15  INT_BAGLANMA_TASINABILIR       6424 non-null   float64
 16  INT_BAGLANMA_TELEFON_CEP       6424 non-null   float64
 17  INT_BAGLANMA_OYUNKONSOL        6424 non-null   float64
 18  INT_BAGLANMA_TV                6424 non-null   float64
 19  INT_BAGLANMA_DIGER_CIHAZ       6424 non-null   float64
 20  INT_BAGLANTI_ADSL              6424 non-null   float64
 21  KABLOLU_SABIT_UYDU             6424 non-null   float64
 22  KABLOLU_SABIT_FIBER            6424 non-null   float64
 23  INT_BAGLANTI_KABLOSUZ_SABIT    6424 non-null   float64
 24  INT_BAGLANTI_TELEFON_3G        6424 non-null   float64
 25  INT_BAGLANTI_MODEM_3G          6424 non-null   float64
 26  INT_BAGLANTI_CEVIRMELI_ISDN    6424 non-null   float64
 27  INT_BAGLANTI_TELEFON_DARBANT   6424 non-null   float64
 28  INT_BAGLANMAMA_BASKAYER        3265 non-null   float64
 29  INT_BAGLANMAMA_GEREKYOK        3265 non-null   float64
 30  INT_BAGLANMAMA_FIYAT_CIHAZ     3265 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_BAGLANTI  3265 non-null   float64
 32  INT_BAGLANMAMA_BILMEME         3265 non-null   float64
 33  INT_BAGLANMAMA_GIZLILIK        3265 non-null   float64
 34  INT_BAGLANMAMA_IMKAN_YOK       3265 non-null   float64
 35  INT_BAGLANMAMA_DIGER           3265 non-null   float64
 36  HANE_GELIR_AYLIK               9847 non-null   float64
 37  HHB                            12210 non-null  int64
 38  HANE_FAKTOR                    12210 non-null  str
 39  IBBS_1                         12210 non-null  str
 40  CEVAPLILIK_DURUM               12210 non-null  int64
 41  HANE_DURUM                     12210 non-null  str
 42  MEKTUP_BROSUR                  10326 non-null  float64
dtypes: float64(36), int64(4), str(3)
memory usage: 4.0 MB

In [15]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TELEFON_SABIT": "hanede sabit telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"HANE_DURUM": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TELEFON_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)
df.rename(columns={"BT_TELEFON_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_OYUNKONSOL": "evde olan oyun konsolunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_ADSL": "internet bağlantı türü adsl"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_UYDU": "internet bağlantı türü kablo tv altyapısı üzerinden kablolu"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_FIBER": "internet bağlantı türü fiber bağlantı, ethernet, PLC vb"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_KABLOSUZ_SABIT": "internet bağlantı türü kablolu sabit internet "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_3G": "internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MODEM_3G": "internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb."}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_DARBANT": "internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS) "}, inplace=True)

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,KAPSAMICI,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,KAPSAMICI,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,KAPSAMICI,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,KAPSAMICI,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,KAPSAMICI,1.0

In [17]:
df["kapsam içi/dışı"].value_counts()

kapsam içi/dışı
KAPSAMICI    9847
CEVAPSIZ     1884
KAPSAMDIS     479
Name: count, dtype: int64

In [24]:
import numpy as np
df["kapsam içi/dışı"] = df["kapsam içi/dışı"].replace({
    "Kapsam içi": 1,
    "Kapsam dışı": 2,
    "Cevapsız": np.nan 
})

In [25]:
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,1,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,1,1.0

In [26]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2015temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2015temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,1.0,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,1.0,1.0