In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2015.csv",sep=";" )
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILGISAYAR_MASAUSTU,BT_BILGISAYAR_TASINABILIR,BT_TELEFON_CEP,BT_OYUNKONSOL,BT_TELEFON_SABIT,BT_FOTOGRAF_KAMERA,BT_DVD_VCD_OYNATICI,BT_INTBAGLANAN_TV,...,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_DIGER,HANE_GELIR_AYLIK,HHB,HANE_FAKTOR,IBBS_1,CEVAPLILIK_DURUM,HANE_DURUM,MEKTUP_BROSUR
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,KAPSAMICI,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,KAPSAMICI,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,KAPSAMICI,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,...,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,KAPSAMICI,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,KAPSAMICI,1.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12210 entries, 0 to 12209
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   12210 non-null  int64
 1   BULTEN_NO                      12210 non-null  int64
 2   BT_BILGISAYAR_MASAUSTU         9847 non-null   float64
 3   BT_BILGISAYAR_TASINABILIR      9847 non-null   float64
 4   BT_TELEFON_CEP                 9847 non-null   float64
 5   BT_OYUNKONSOL                  9847 non-null   float64
 6   BT_TELEFON_SABIT               9847 non-null   float64
 7   BT_FOTOGRAF_KAMERA             9847 non-null   float64
 8   BT_DVD_VCD_OYNATICI            9847 non-null   float64
 9   BT_INTBAGLANAN_TV              9847 non-null   float64
 10  BT_DIGER                       9847 non-null   float64
 11  HANE_BILGISAYAR_KULLANIM       9847 non-null   float64
 12  HANE_INTERNET_ERISIM_DURUMU    9847 non-null   float64
 13  HANE_INTERNET_ERISIM_KULLANIM  6424 non-null   float64
 14  INT_BAGLANMA_MASAUSTU          6424 non-null   float64
 15  INT_BAGLANMA_TASINABILIR       6424 non-null   float64
 16  INT_BAGLANMA_TELEFON_CEP       6424 non-null   float64
 17  INT_BAGLANMA_OYUNKONSOL        6424 non-null   float64
 18  INT_BAGLANMA_TV                6424 non-null   float64
 19  INT_BAGLANMA_DIGER_CIHAZ       6424 non-null   float64
 20  INT_BAGLANTI_ADSL              6424 non-null   float64
 21  KABLOLU_SABIT_UYDU             6424 non-null   float64
 22  KABLOLU_SABIT_FIBER            6424 non-null   float64
 23  INT_BAGLANTI_KABLOSUZ_SABIT    6424 non-null   float64
 24  INT_BAGLANTI_TELEFON_3G        6424 non-null   float64
 25  INT_BAGLANTI_MODEM_3G          6424 non-null   float64
 26  INT_BAGLANTI_CEVIRMELI_ISDN    6424 non-null   float64
 27  INT_BAGLANTI_TELEFON_DARBANT   6424 non-null   float64
 28  INT_BAGLANMAMA_BASKAYER        3265 non-null   float64
 29  INT_BAGLANMAMA_GEREKYOK        3265 non-null   float64
 30  INT_BAGLANMAMA_FIYAT_CIHAZ     3265 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_BAGLANTI  3265 non-null   float64
 32  INT_BAGLANMAMA_BILMEME         3265 non-null   float64
 33  INT_BAGLANMAMA_GIZLILIK        3265 non-null   float64
 34  INT_BAGLANMAMA_IMKAN_YOK       3265 non-null   float64
 35  INT_BAGLANMAMA_DIGER           3265 non-null   float64
 36  HANE_GELIR_AYLIK               9847 non-null   float64
 37  HHB                            12210 non-null  int64
 38  HANE_FAKTOR                    12210 non-null  str
 39  IBBS_1                         12210 non-null  str
 40  CEVAPLILIK_DURUM               12210 non-null  int64
 41  HANE_DURUM                     12210 non-null  str
 42  MEKTUP_BROSUR                  10326 non-null  float64
dtypes: float64(36), int64(4), str(3)
memory usage: 4.0 MB

In [15]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TELEFON_SABIT": "hanede sabit telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"HANE_DURUM": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TELEFON_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)
df.rename(columns={"BT_TELEFON_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_OYUNKONSOL": "evde olan oyun konsolunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_ADSL": "internet bağlantı türü adsl"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_UYDU": "internet bağlantı türü kablo tv altyapısı üzerinden kablolu"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_FIBER": "internet bağlantı türü fiber bağlantı, ethernet, PLC vb"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_KABLOSUZ_SABIT": "internet bağlantı türü kablolu sabit internet "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_3G": "internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MODEM_3G": "internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb."}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_DARBANT": "internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS) "}, inplace=True)

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,KAPSAMICI,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,KAPSAMICI,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,KAPSAMICI,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,KAPSAMICI,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,KAPSAMICI,1.0

In [17]:
df["kapsam içi/dışı"].value_counts()

kapsam içi/dışı
KAPSAMICI    9847
CEVAPSIZ     1884
KAPSAMDIS     479
Name: count, dtype: int64

In [24]:
import numpy as np
df["kapsam içi/dışı"] = df["kapsam içi/dışı"].replace({
    "Kapsam içi": 1,
    "Kapsam dışı": 2,
    "Cevapsız": np.nan 
})

In [25]:
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,1,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,1,1.0

In [26]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2015temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2015temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,1.0,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,1.0,1.0

# 2015 fert-hane crosss tabloları

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2015.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,...,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0

In [5]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,3540,48.2,1143,31.99
erkek,3805,51.8,2430,68.01
toplam,7345,100.0,3573,100.00

In [3]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,43,41.75,1359,43.2
erkek,60,58.25,1787,56.8
toplam,103,100.00,3146,100.0

In [7]:
import pandas as pd

# ======================================================
# GELİR GRUBU OLUŞTURMA
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = Var
# 2 = Yok
#
# cinsiyet:
# 1 = Erkek
# 2 = Kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    # ---------------- VAR ----------------

    var_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ---------------- YOK ----------------

    yok_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ---------------- TABLO ----------------

    sonuc.append({

        "yıl": 2015,
        "gelir": gelir,

        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            round(
                var_cinsiyet.get(1, 0)
                + var_cinsiyet.get(2, 0),
                2
            ),

        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            round(
                yok_cinsiyet.get(1, 0)
                + yok_cinsiyet.get(2, 0),
                2
            )
    })

# ======================================================
# DATAFRAME
# ======================================================

gelir_saglik_2015 = pd.DataFrame(sonuc)

display(gelir_saglik_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,43.84,56.16,100.0,27.07,72.93,100.0
1,2015,2,47.06,52.94,100.0,29.80,70.20,100.0
2,2015,3,49.23,50.77,100.0,30.18,69.82,100.0
3,2015,4,47.77,52.23,100.0,35.01,64.99,100.0
4,2015,5,48.95,51.05,100.0,35.85,64.15,100.0

In [9]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# TABLO
# sağlık bilgisi arama
#
# 1 = var
# 2 = yok
#
# cinsiyet
# 1 = erkek
# 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    # =========================
    # VAR
    # =========================

    var_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # =========================
    # YOK
    # =========================

    yok_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # =========================
    # SONUÇ
    # =========================

    sonuc.append({

        "yıl": 2015,
        "gelir": gelir,

        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)
    })

# ======================================================
# DATAFRAME
# ======================================================

gelir_saglik_2015 = pd.DataFrame(sonuc)

display(gelir_saglik_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,43.84,56.16,406,27.07,72.93,458
1,2015,2,47.06,52.94,799,29.80,70.20,698
2,2015,3,49.23,50.77,1355,30.18,69.82,845
3,2015,4,47.77,52.23,1972,35.01,64.99,897
4,2015,5,48.95,51.05,2813,35.85,64.15,675

In [10]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
#
# 1 = var
# 2 = yok
#
# cinsiyet
# 1 = erkek
# 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    # =========================
    # VAR
    # =========================

    var_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # =========================
    # YOK
    # =========================

    yok_df = alt_df[
        alt_df["online sağlık hizmeti kullanımı"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # =========================
    # SONUÇ
    # =========================

    sonuc.append({

        "yıl": 2015,
        "gelir": gelir,

        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)
    })

# ======================================================
# DATAFRAME
# ======================================================

gelir_online_saglik_2015 = pd.DataFrame(sonuc)

# ======================================================
# TOPLAM SATIRI
# ======================================================

toplam_var = df[
    df["online sağlık hizmeti kullanımı"] == 1
]

toplam_yok = df[
    df["online sağlık hizmeti kullanımı"] == 2
]

toplam_var_cinsiyet = (
    toplam_var["cinsiyet"]
    .value_counts(normalize=True) * 100
)

toplam_yok_cinsiyet = (
    toplam_yok["cinsiyet"]
    .value_counts(normalize=True) * 100
)

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,
    "gelir": "frekans",

    "var kadın":
        round(toplam_var_cinsiyet.get(2, 0), 2),

    "var erkek":
        round(toplam_var_cinsiyet.get(1, 0), 2),

    "var toplam":
        len(toplam_var),

    "yok kadın":
        round(toplam_yok_cinsiyet.get(2, 0), 2),

    "yok erkek":
        round(toplam_yok_cinsiyet.get(1, 0), 2),

    "yok toplam":
        len(toplam_yok)
}])

# ======================================================
# BİRLEŞTİR
# ======================================================

gelir_online_saglik_2015 = pd.concat(
    [gelir_online_saglik_2015, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,43.84,56.16,406,27.07,72.93,458
1,2015,2,47.06,52.94,799,29.80,70.20,698
2,2015,3,49.23,50.77,1355,30.18,69.82,845
3,2015,4,47.77,52.23,1972,35.01,64.99,897
4,2015,5,48.95,51.05,2813,35.85,64.15,675
5,2015,frekans,48.20,51.80,7345,31.99,68.01,3573

In [11]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 1]
    yok_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2015,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2015 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["online sağlık hizmeti kullanımı"] == 1]
toplam_yok = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2015,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2015 = pd.concat(
    [gelir_online_saglik_2015, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,43.84,56.16,406,27.07,72.93,458
1,2015,2,47.06,52.94,799,29.80,70.20,698
2,2015,3,49.23,50.77,1355,30.18,69.82,845
3,2015,4,47.77,52.23,1972,35.01,64.99,897
4,2015,5,48.95,51.05,2813,35.85,64.15,675
5,2015,frekans,3540.00,3805.00,7345,1143.00,2430.00,3573

In [5]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,50.00,50.00,4,46.32,53.68,95
1,2015,2,33.33,66.67,3,40.96,59.04,249
2,2015,3,43.75,56.25,16,42.32,57.68,456
3,2015,4,33.33,66.67,21,41.49,58.51,776
4,2015,5,44.07,55.93,59,44.46,55.54,1570
5,2015,toplam,43.00,60.00,103,1359.00,1787.00,3146

In [4]:
# =========================================================
# YAŞ GRUBU x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUBU OLUŞTUR
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ONLINE SAĞLIK HİZMETİ KULLANIMI VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK HİZMETİ KULLANIMI YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2015,

        "yaş": yas,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "yaş": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_online_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_online_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_8988\3050251590.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,15-30,53.44,46.56,3097,35.68,64.32,1791
1,2015,31-45,46.81,53.19,2978,28.81,71.19,1208
2,2015,46-60,39.69,60.31,1144,29.04,70.96,489
3,2015,60+,29.37,70.63,126,16.47,83.53,85
4,2015,toplam,3540.00,3805.00,7345,1143.00,2430.00,3573

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2015.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,...,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0

In [2]:
# =========================================================
# EĞİTİM x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM KATEGORİLERİ
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    # İLKOKUL VE ALTI
    elif x in [0, 1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [5, 6, 511, 512]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [7, 52, 53]:
        return "üniversiteüstü"

    else:
        return None

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    alt = df[df["egitim_grup"] == egitim]

    # ONLINE SAĞLIK VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2016,

        "eğitim": egitim,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2016,

    "eğitim": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_online_2016 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_online_2016)

C:\Users\dilara\AppData\Local\Temp\ipykernel_4756\988942446.py:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2016,ilkokulvealtı,50.79,49.21,2465,32.08,67.92,2232
1,2016,ortaokul/lise,47.58,52.42,3138,31.30,68.70,1083
2,2016,üniversite,45.76,54.24,1685,34.13,65.87,252
3,2016,üniversiteüstü,42.11,57.89,57,33.33,66.67,6
4,2016,toplam,3540.00,3805.00,7345,1143.00,2430.00,3573

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # ilkokul ve altı
    if x in [0, 1]:
        return "ilkokulvealtı"

    # ortaokul / lise
    elif x in [2, 3, 4]:
        return "ortaokul/lise"

    # üniversite
    elif x in [51, 52]:
        return "üniversite"

    # üniversite üstü
    elif x == 53:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ DEĞİŞKENİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # VAR
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2015,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{
    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()
}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_29092\2992515238.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_29092\2992515238.py:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2015,ilkokulvealtı,5,6,11,82,119,201
1,2015,ortaokul/lise,22,24,46,782,1042,1824
2,2015,üniversite,0,0,0,0,0,0
3,2015,üniversiteüstü,0,0,0,0,0,0
4,,toplam,27,30,57,864,1161,2025

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,7,11,18,283,383,666
1,2025,ortaokul/lise,20,19,39,581,778,1359
2,2025,üniversite,16,29,45,479,602,1081
3,2025,üniversiteüstü,0,1,1,16,24,40
4,,toplam,43,60,103,1359,1787,3146

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2015.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,...,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0

In [2]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_3764\3164738277.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_label"] = df["cinsiyet"].replace({

  cinsiyet  toplam   yüzde
0    Erkek   17740   49.48
1    Kadın   18110   50.52
2   Toplam   35850  100.00

In [3]:
import pandas as pd
import numpy as np

gelir_col = "hane gelir aylık"  # gerekirse burayı değiştir

df["gelir_raw"] = (
    df[gelir_col]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .str.extract(r"(\d+\.?\d*)")[0]
)

df["gelir_raw"] = pd.to_numeric(df["gelir_raw"], errors="coerce")

print(df["gelir_raw"].isna().sum())
print(df["gelir_raw"].describe())

temiz = df[df["gelir_raw"].notna()].copy()

temiz["gelir_5li_esit"] = pd.qcut(
    temiz["gelir_raw"].rank(method="first"),
    q=5,
    labels=["1. grup", "2. grup", "3. grup", "4. grup", "5. grup"]
)

df.loc[temiz.index, "gelir_5li_esit"] = temiz["gelir_5li_esit"]

gelir_tablo = pd.DataFrame({
    "toplam": df["gelir_5li_esit"].value_counts().sort_index(),
    "yüzde": round(df["gelir_5li_esit"].value_counts(normalize=True).sort_index() * 100, 2)
})

gelir_tablo.loc["toplam"] = [gelir_tablo["toplam"].sum(), 100]

display(gelir_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_3764\1670307786.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_raw"] = (

629
count    35221.000000
mean      1958.949235
std       1785.517719
min          1.000000
25%       1000.000000
50%       1500.000000
75%       2500.000000
max      30000.000000
Name: gelir_raw, dtype: float64

C:\Users\dilara\AppData\Local\Temp\ipykernel_3764\1670307786.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[temiz.index, "gelir_5li_esit"] = temiz["gelir_5li_esit"]

                toplam  yüzde
gelir_5li_esit
1. grup           7045   20.0
2. grup           7044   20.0
3. grup           7044   20.0
4. grup           7044   20.0
5. grup           7044   20.0
toplam           35221  100.0

In [4]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_3764\3341891636.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

                toplam   yüzde
ilkokulvealtı    15665   68.18
ortaokul/lise     5200   22.63
üniversite        2049    8.92
üniversiteüstü      63    0.27
toplam           22977  100.00

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_3764\1794991821.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

        toplam   yüzde
15-30     8582   23.94
31-45     7832   21.85
46-60     6283   17.53
60+      13153   36.69
toplam   35850  100.00

### 14 mayıs probit

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2015.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,...,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,...,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,...,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,...,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0

In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT
# Bağımlı değişken:
# Online sağlık hizmeti kullanımı
# =====================================================

# -----------------------------------------------------
# ONLINE SAĞLIK (0-1)
# -----------------------------------------------------

df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# -----------------------------------------------------
# CİNSİYET
# Erkek=0 Kadın=1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# YAŞ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

# YAŞ KATEGORİLERİ

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[0, 30, 45, 60, 100],
    labels=[
        "15-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

# DUMMY DEĞİŞKENLER
yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas",
    drop_first=True
)

# -----------------------------------------------------
# EĞİTİM
# -----------------------------------------------------

egitim_map = {
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    51: 4,
    52: 4,
    53: 5
}

df["egitim_kategori"] = df["eğitim"].replace(egitim_map)

# -----------------------------------------------------
# GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "online_saglik",
                "cinsiyet_kadin",
                "egitim_kategori",
                "log_gelir"
            ]
        ],
        yas_dummy
    ],
    axis=1
)

model_df = model_df.dropna()

# -----------------------------------------------------
# X ve Y
# -----------------------------------------------------

X = model_df.drop(columns=["online_saglik"])

X = sm.add_constant(X)

y = model_df["online_saglik"]

# -----------------------------------------------------
# PROBIT MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# SONUÇ
# -----------------------------------------------------

print(result.summary())

C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:38: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:42: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:74: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_kategori"] = df["eğitim"].replace(egitim_map)
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:80: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\17042284.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

In [4]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT
# Bağımlı değişken: Online sağlık hizmeti kullanımı
# Bağımsız değişkenler: Cinsiyet, Yaş grubu, Eğitim, Gelir
# =====================================================

# -----------------------------------------------------
# 1) ONLINE SAĞLIK HİZMETİ KULLANIMI
# -----------------------------------------------------

df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1,
    "Hayır": 0,
    "evet": 1,
    "hayır": 0,
    "EVET": 1,
    "HAYIR": 0,
    1: 1,
    2: 0,
    0: 0
})

# -----------------------------------------------------
# 2) CİNSİYET
# Erkek = 0, Kadın = 1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    "erkek": 0,
    "kadın": 1,
    "KADIN": 1,
    "ERKEK": 0,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# 3) YAŞ KATEGORİSİ
# Referans grup: 15-30
# -----------------------------------------------------

df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas",
    drop_first=True
)

# -----------------------------------------------------
# 4) EĞİTİM
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

egitim_map = {
    0: 0,
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    51: 4,
    52: 4,
    53: 5
}

df["egitim_kategori"] = df["egitim_sayi"].replace(egitim_map)

# -----------------------------------------------------
# 5) GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# 6) MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "online_saglik",
                "cinsiyet_kadin",
                "egitim_kategori",
                "log_gelir"
            ]
        ],
        yas_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# 7) TÜM DEĞİŞKENLERİ SAYISALA ÇEVİR
# Object hatasını çözen ana bölüm burası
# -----------------------------------------------------

model_df = model_df.apply(pd.to_numeric, errors="coerce")

# Eksik değerleri sil
model_df = model_df.dropna()

# -----------------------------------------------------
# 8) X ve y
# -----------------------------------------------------

y = model_df["online_saglik"]

X = model_df.drop(columns=["online_saglik"])

X = sm.add_constant(X)

# Probit için tüm değişkenleri float yap
X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# 9) KONTROL
# -----------------------------------------------------

print("Modelde kullanılan gözlem sayısı:", len(model_df))
print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nDeğişken tipleri:")
print(X.dtypes)

# -----------------------------------------------------
# 10) PROBIT MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

print(result.summary())

Modelde kullanılan gözlem sayısı: 10918

Bağımlı değişken dağılımı:
online_saglik
1.0    7345
0.0    3573
Name: count, dtype: int64

Değişken tipleri:
const              float64
cinsiyet_kadin     float64
egitim_kategori    float64
log_gelir          float64
yas_31-45          float64
yas_46-60          float64
yas_60+            float64
dtype: object
Optimization terminated successfully.
         Current function value: 0.570398
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.09778
Time:                        16:10:45   Log-Likelihood:                -6227.6
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                1.684e-288
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -1.9130      0.151    -12.663      0.000      -2.209      -1.617
cinsiyet_kadin      0.4223      0.027     15.735      0.000       0.370       0.475
egitim_kategori     0.2005      0.009     21.877      0.000       0.183       0.218
log_gelir           0.2264      0.021     10.871      0.000       0.186       0.267
yas_31-45           0.2104      0.029      7.263      0.000       0.154       0.267
yas_46-60           0.1538      0.040      3.876      0.000       0.076       0.232
yas_60+            -0.1938      0.093     -2.094      0.036      -0.375      -0.012
===================================================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\2938415538.py:66: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

In [5]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.09778
Time:                        16:13:38   Log-Likelihood:                -6227.6
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                1.684e-288
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -1.9130      0.151    -12.663      0.000      -2.209      -1.617
cinsiyet_kadin      0.4223      0.027     15.735      0.000       0.370       0.475
egitim_kategori     0.2005      0.009     21.877      0.000       0.183       0.218
log_gelir           0.2264      0.021     10.871      0.000       0.186       0.267
yas_31-45           0.2104      0.029      7.263      0.000       0.154       0.267
yas_46-60           0.1538      0.040      3.876      0.000       0.076       0.232
yas_60+            -0.1938      0.093     -2.094      0.036      -0.375      -0.012
===================================================================================

In [6]:
from typing import Optional


def get_summary_text(result) -> Optional[str]:
    """result nesnesinden özet metni güvenli şekilde alır."""
    try:
        summary = result.summary()
        if summary is None:
            print("[UYARI] summary() None döndürdü.")
            return None

        text = summary.as_text()
        if not isinstance(text, str) or not text.strip():
            print("[UYARI] Özet metni boş veya geçersiz.")
            return None

        return text.strip()

    except AttributeError as e:
        print(f"[HATA] Geçersiz nesne yapısı: {e}")
        return None
    except Exception as e:
        print(f"[HATA] Beklenmeyen bir hata oluştu: {e}")
        return None


if summary_text := get_summary_text(result):
    print(summary_text)

Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.09778
Time:                        16:16:57   Log-Likelihood:                -6227.6
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                1.684e-288
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -1.9130      0.151    -12.663      0.000      -2.209      -1.617
cinsiyet_kadin      0.4223      0.027     15.735      0.000       0.370       0.475
egitim_kategori     0.2005      0.009     21.877      0.000       0.183       0.218
log_gelir           0.2264      0.021     10.871      0.000       0.186       0.267
yas_31-45           0.2104      0.029      7.263      0.000       0.154       0.267
yas_46-60           0.1538      0.040      3.876      0.000       0.076       0.232
yas_60+            -0.1938      0.093     -2.094      0.036      -0.375      -0.012
===================================================================================

In [7]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - GELİŞTİRİLMİŞ PROBIT MODEL
# =====================================================

# -----------------------------------------------------
# ONLINE SAĞLIK
# -----------------------------------------------------

df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# -----------------------------------------------------
# CİNSİYET
# Erkek=0 Kadın=1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# YAŞ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas",
    drop_first=True
)

# -----------------------------------------------------
# EĞİTİM KATEGORİLERİ
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):

    if x in [0, 1, 2]:
        return "Ilkokul_ve_alti"

    elif x in [3, 4]:
        return "Orta_Lise"

    elif x in [51, 52]:
        return "Universite"

    elif x == 53:
        return "Doktora"

    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

# REFERANS:
# Ilkokul_ve_alti

egitim_dummy = pd.get_dummies(
    df["egitim_grup"],
    prefix="egitim",
    drop_first=True
)

# -----------------------------------------------------
# GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "online_saglik",
                "cinsiyet_kadin",
                "log_gelir"
            ]
        ],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# NUMERIC
# -----------------------------------------------------

model_df = model_df.apply(
    pd.to_numeric,
    errors="coerce"
)

model_df = model_df.dropna()

# -----------------------------------------------------
# X VE Y
# -----------------------------------------------------

y = model_df["online_saglik"]

X = model_df.drop(
    columns=["online_saglik"]
)

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# PROBIT MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# SONUÇ
# -----------------------------------------------------

print(result.summary())

Optimization terminated successfully.
         Current function value: 0.586837
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.07178
Time:                        16:20:33   Log-Likelihood:                -6407.1
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                8.006e-211
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -2.9596      0.141    -20.942      0.000      -3.237      -2.683
cinsiyet_kadin       0.4016      0.026     15.174      0.000       0.350       0.453
log_gelir            0.4000      0.019     21.338      0.000       0.363       0.437
yas_31-45            0.1978      0.029      6.917      0.000       0.142       0.254
yas_46-60            0.1005      0.039      2.572      0.010       0.024       0.177
yas_60+             -0.1450      0.091     -1.594      0.111      -0.323       0.033
egitim_Orta_Lise     0.3260      0.027     12.182      0.000       0.274       0.378
====================================================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_19732\382621258.py:73: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

In [8]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT
# Bağımlı değişken: Online sağlık hizmeti kullanımı
# Referanslar:
# Cinsiyet: Erkek
# Yaş: 15-30
# Eğitim: İlkokul ve altı
# =====================================================

# ONLINE SAĞLIK
df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1, "Hayır": 0,
    "evet": 1, "hayır": 0,
    1: 1, 2: 0, 0: 0
})

# CİNSİYET
df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0, "Kadın": 1,
    "erkek": 0, "kadın": 1,
    1: 0, 2: 1
})

# YAŞ KATEGORİSİ
df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(df["yas_grup"], prefix="yas")

# Referans yaş grubu: 15-30
yas_dummy = yas_dummy.drop(columns=["yas_15-30"], errors="ignore")

# EĞİTİM KATEGORİSİ
df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):
    if x in [0, 1, 2]:
        return "Ilkokul_ve_alti"
    elif x in [3, 4]:
        return "Orta_Lise"
    elif x in [51, 52]:
        return "Universite"
    elif x == 53:
        return "Doktora"
    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

egitim_dummy = pd.get_dummies(df["egitim_grup"], prefix="egitim")

# Referans eğitim grubu: İlkokul ve altı
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# GELİR
df["gelir"] = pd.to_numeric(df["hane gelir aylık"], errors="coerce")
df["log_gelir"] = np.log1p(df["gelir"])

# MODEL DATAFRAME
model_df = pd.concat(
    [
        df[["online_saglik", "cinsiyet_kadin", "log_gelir"]],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# SAYISALA ÇEVİR
model_df = model_df.apply(pd.to_numeric, errors="coerce")
model_df = model_df.dropna()

# X ve y
y = model_df["online_saglik"]
X = model_df.drop(columns=["online_saglik"])

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# KONTROL
print("Modelde kullanılan gözlem sayısı:", len(model_df))
print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nModel değişkenleri:")
print(X.columns)

# PROBIT MODEL
probit_model = sm.Probit(y, X)
result = probit_model.fit()

print(result.summary().as_text())

Modelde kullanılan gözlem sayısı: 10918

Bağımlı değişken dağılımı:
online_saglik
1.0    7345
0.0    3573
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Orta_Lise'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.586837
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.07178
Time:                        16:21:56   Log-Likelihood:                -6407.1
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                8.006e-211
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -2.9596      0.141    -20.942      0.000      -3.237      -2.683
cinsiyet_kadin       0.4016      0.026     15.174      0.000       0.350       0.453
log_gelir            0.4000      0.019     21.338      0.000       0.363       0.437
yas_31-45            0.1978      0.029      6.917      0.000       0.142       0.254
yas_46-60            0.1005      0.039      2.572      0.010       0.024       0.177
yas_60+             -0.1450      0.091     -1.594      0.111      -0.323       0.033
egitim_Orta_Lise     0.3260      0.027     12.182      0.000       0.274       0.378
====================================================================================

In [9]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10911
Method:                           MLE   Df Model:                            6
Date:                Thu, 14 May 2026   Pseudo R-squ.:                 0.07178
Time:                        16:22:14   Log-Likelihood:                -6407.1
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                8.006e-211
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -2.9596      0.141    -20.942      0.000      -3.237      -2.683
cinsiyet_kadin       0.4016      0.026     15.174      0.000       0.350       0.453
log_gelir            0.4000      0.019     21.338      0.000       0.363       0.437
yas_31-45            0.1978      0.029      6.917      0.000       0.142       0.254
yas_46-60            0.1005      0.039      2.572      0.010       0.024       0.177
yas_60+             -0.1450      0.091     -1.594      0.111      -0.323       0.033
egitim_Orta_Lise     0.3260      0.027     12.182      0.000       0.274       0.378
====================================================================================

In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT MODEL
# Bağımlı değişken:
# Online sağlık hizmeti kullanımı
#
# Referans Gruplar:
# Cinsiyet -> Erkek
# Yaş -> 15-30
# Eğitim -> İlkokul ve altı
# =====================================================

# -----------------------------------------------------
# 1) ONLINE SAĞLIK HİZMETİ KULLANIMI
# -----------------------------------------------------

df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1,
    "Hayır": 0,
    "evet": 1,
    "hayır": 0,
    1: 1,
    2: 0,
    0: 0
})

# -----------------------------------------------------
# 2) CİNSİYET
# Erkek = 0
# Kadın = 1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    "erkek": 0,
    "kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# 3) YAŞ KATEGORİLERİ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(
    df["yaş"],
    errors="coerce"
)

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=[
        "15-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas"
)

# REFERANS GRUP: 15-30
yas_dummy = yas_dummy.drop(
    columns=["yas_15-30"],
    errors="ignore"
)

# -----------------------------------------------------
# 4) EĞİTİM KATEGORİLERİ
# 2015 kod yapısına göre
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(
    df["eğitim"],
    errors="coerce"
)

def egitim_kategori(x):

    # REFERANS GRUP
    if x in [0, 1]:
        return "Ilkokul_ve_alti"

    elif x in [2, 3]:
        return "Orta_Lise"

    elif x in [4, 5, 6]:
        return "Universite"

    elif x == 7:
        return "Doktora"

    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(
    egitim_kategori
)

egitim_dummy = pd.get_dummies(
    df["egitim_grup"],
    prefix="egitim"
)

# REFERANS GRUP:
# İlkokul ve altı

egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# -----------------------------------------------------
# 5) GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

# LOG GELİR
df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# 6) MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "online_saglik",
                "cinsiyet_kadin",
                "log_gelir"
            ]
        ],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# 7) TÜM DEĞİŞKENLERİ SAYISALA ÇEVİR
# -----------------------------------------------------

model_df = model_df.apply(
    pd.to_numeric,
    errors="coerce"
)

# Eksik gözlemleri temizle
model_df = model_df.dropna()

# -----------------------------------------------------
# 8) X ve y
# -----------------------------------------------------

y = model_df["online_saglik"]

X = model_df.drop(
    columns=["online_saglik"]
)

# CONSTANT
X = sm.add_constant(X)

# Float yap
X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# 9) KONTROLLER
# -----------------------------------------------------

print("Modelde kullanılan gözlem sayısı:")
print(len(model_df))

print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nModel değişkenleri:")
print(X.columns)

# -----------------------------------------------------
# 10) PROBIT MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# 11) SONUÇLAR
# -----------------------------------------------------

summary_text = result.summary().as_text()

print(summary_text)

Modelde kullanılan gözlem sayısı:
10918

Bağımlı değişken dağılımı:
online_saglik
1.0    7345
0.0    3573
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Doktora', 'egitim_Orta_Lise', 'egitim_Universite'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.575179
         Iterations 6
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10909
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.09022
Time:                        19:47:40   Log-Likelihood:                -6279.8
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                1.385e-263
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.2525      0.151    -14.921      0.000      -2.548      -1.957
cinsiyet_kadin        0.4233      0.027     15.798      0.000       0.371       0.476
log_gelir             0.2618      0.020     12.798      0.000       0.222       0.302
yas_31-45             0.2686      0.031      8.799      0.000       0.209       0.328
yas_46-60             0.2065      0.041      5.057      0.000       0.126       0.286
yas_60+              -0.1288      0.093     -1.384      0.166      -0.311       0.054
egitim_Doktora        0.9398      0.228      4.126      0.000       0.493       1.386
egitim_Orta_Lise      0.3840      0.035     10.833      0.000       0.314       0.453
egitim_Universite     0.8539      0.043     19.652      0.000       0.769       0.939
=====================================================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:49: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:54: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:81: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:104: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:125: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_1184\506983523.py:131: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

In [4]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                10918
Model:                         Probit   Df Residuals:                    10909
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.09022
Time:                        19:47:44   Log-Likelihood:                -6279.8
converged:                       True   LL-Null:                       -6902.6
Covariance Type:            nonrobust   LLR p-value:                1.385e-263
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.2525      0.151    -14.921      0.000      -2.548      -1.957
cinsiyet_kadin        0.4233      0.027     15.798      0.000       0.371       0.476
log_gelir             0.2618      0.020     12.798      0.000       0.222       0.302
yas_31-45             0.2686      0.031      8.799      0.000       0.209       0.328
yas_46-60             0.2065      0.041      5.057      0.000       0.126       0.286
yas_60+              -0.1288      0.093     -1.384      0.166      -0.311       0.054
egitim_Doktora        0.9398      0.228      4.126      0.000       0.493       1.386
egitim_Orta_Lise      0.3840      0.035     10.833      0.000       0.314       0.453
egitim_Universite     0.8539      0.043     19.652      0.000       0.769       0.939
=====================================================================================

In [5]:
# 10) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          online_saglik
Method:                          dydx
At:                           overall
=====================================================================================
                       dy/dx    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
cinsiyet_kadin        0.1385      0.008     16.326      0.000       0.122       0.155
log_gelir             0.0856      0.007     13.063      0.000       0.073       0.098
yas_31-45             0.0878      0.010      8.884      0.000       0.068       0.107
yas_46-60             0.0675      0.013      5.073      0.000       0.041       0.094
yas_60+              -0.0421      0.030     -1.384      0.166      -0.102       0.018
egitim_Doktora        0.3074      0.074      4.134      0.000       0.162       0.453
egitim_Orta_Lise      0.1256      0.011     11.014      0.000       0.103       0.148
egitim_Universite     0.2793      0.014     20.660      0.000       0.253       0.306
=====================================================================================

In [10]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 2 - PROBIT MODEL
# Bağımlı değişken: E-ticaretten ilaç alışverişi
# Gelir değişkeni: hane gelir aylık
# =====================================================

# 1) BAĞIMLI DEĞİŞKEN
df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1, "Hayır": 0,
    "evet": 1, "hayır": 0,
    "EVET": 1, "HAYIR": 0,
    1: 1,
    2: 0,
    0: 0
})

# 2) CİNSİYET
df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0, "Kadın": 1,
    "erkek": 0, "kadın": 1,
    "ERKEK": 0, "KADIN": 1,
    1: 0,
    2: 1
})

# 3) YAŞ KATEGORİLERİ
df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(df["yas_grup"], prefix="yas")
yas_dummy = yas_dummy.drop(columns=["yas_15-30"], errors="ignore")

# 4) EĞİTİM KATEGORİLERİ
df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):
    if x in [0, 1]:
        return "Ilkokul_ve_alti"
    elif x in [2, 3]:
        return "Orta_Lise"
    elif x in [4, 5, 6]:
        return "Universite"
    elif x == 7:
        return "Doktora"
    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

egitim_dummy = pd.get_dummies(df["egitim_grup"], prefix="egitim")
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# 5) GELİR
df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# 6) MODEL DATAFRAME
model_df = pd.concat(
    [
        df[["eticaret_ilac", "cinsiyet_kadin", "log_gelir"]],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# 7) SAYISALA ÇEVİR VE TEMİZLE
model_df = model_df.apply(pd.to_numeric, errors="coerce")

print("Dropna öncesi satır sayısı:", len(model_df))
print("\nEksik değer sayıları:")
print(model_df.isna().sum())

model_df = model_df.dropna()

print("\nDropna sonrası satır sayısı:", len(model_df))

# 8) X ve y
y = model_df["eticaret_ilac"]
X = model_df.drop(columns=["eticaret_ilac"])

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# 9) KONTROLLER
print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nEğitim grubu dağılımı:")
print(df["egitim_grup"].value_counts(dropna=False))

print("\nGelir dağılımı:")
print(df["gelir"].value_counts(dropna=False).head(20))

print("\nModel değişkenleri:")
print(X.columns)

# 10) PROBIT MODEL
probit_model = sm.Probit(y, X)
result = probit_model.fit()

print(result.summary().as_text())

Dropna öncesi satır sayısı: 35850

Eksik değer sayıları:
eticaret_ilac        32601
cinsiyet_kadin           0
log_gelir              629
yas_31-45                0
yas_46-60                0
yas_60+                  0
egitim_Doktora           0
egitim_Orta_Lise         0
egitim_Universite        0
dtype: int64

Dropna sonrası satır sayısı: 3249

Bağımlı değişken dağılımı:
eticaret_ilac
0.0    3146
1.0     103
Name: count, dtype: int64

Eğitim grubu dağılımı:
egitim_grup
NaN                12873
Ilkokul_ve_alti    11574
Orta_Lise           8243
Universite          3097
Doktora               63
Name: count, dtype: int64

Gelir dağılımı:
gelir
1000.0    4288
1500.0    3637
2000.0    3599
3000.0    2239
2500.0    2044
500.0     1357
900.0     1269
1200.0    1208
800.0     1045
5000.0     961
4000.0     822
300.0      686
3500.0     683
1300.0     645
NaN        629
600.0      622
700.0      575
950.0      534
1800.0     531
1100.0     485
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Doktora', 'egitim_Orta_Lise', 'egitim_Universite'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.136144
         Iterations 7
                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 3249
Model:                         Probit   Df Residuals:                     3240
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.03176
Time:                        20:10:50   Log-Likelihood:                -442.33
converged:                       True   LL-Null:                       -456.84
Covariance Type:            nonrobust   LLR p-value:                 0.0003145
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.1599      0.547     -3.948      0.000      -3.232      -1.087
cinsiyet_kadin        0.0181      0.090      0.201      0.841      -0.159       0.195
log_gelir             0.0526      0.071      0.738      0.460      -0.087       0.192
yas_31-45             0.0426      0.105      0.407      0.684      -0.163       0.248
yas_46-60             0.4821      0.128      3.781      0.000       0.232       0.732
yas_60+               0.6481      0.325      1.996      0.046       0.012       1.285
egitim_Doktora       -0.4814      0.447     -1.077      0.281      -1.357       0.395
egitim_Orta_Lise     -0.3543      0.169     -2.095      0.036      -0.686      -0.023
egitim_Universite    -0.1660      0.168     -0.988      0.323      -0.495       0.163
=====================================================================================

In [8]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 3249
Model:                         Probit   Df Residuals:                     3240
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.03176
Time:                        20:10:27   Log-Likelihood:                -442.33
converged:                       True   LL-Null:                       -456.84
Covariance Type:            nonrobust   LLR p-value:                 0.0003145
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.1599      0.547     -3.948      0.000      -3.232      -1.087
cinsiyet_kadin        0.0181      0.090      0.201      0.841      -0.159       0.195
log_gelir             0.0526      0.071      0.738      0.460      -0.087       0.192
yas_31-45             0.0426      0.105      0.407      0.684      -0.163       0.248
yas_46-60             0.4821      0.128      3.781      0.000       0.232       0.732
yas_60+               0.6481      0.325      1.996      0.046       0.012       1.285
egitim_Doktora       -0.4814      0.447     -1.077      0.281      -1.357       0.395
egitim_Orta_Lise     -0.3543      0.169     -2.095      0.036      -0.686      -0.023
egitim_Universite    -0.1660      0.168     -0.988      0.323      -0.495       0.163
=====================================================================================

In [9]:
# 11) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          eticaret_ilac
Method:                          dydx
At:                           overall
=====================================================================================
                       dy/dx    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
cinsiyet_kadin        0.0013      0.006      0.201      0.841      -0.011       0.013
log_gelir             0.0036      0.005      0.737      0.461      -0.006       0.013
yas_31-45             0.0030      0.007      0.407      0.684      -0.011       0.017
yas_46-60             0.0334      0.009      3.665      0.000       0.016       0.051
yas_60+               0.0449      0.023      1.979      0.048       0.000       0.089
egitim_Doktora       -0.0333      0.031     -1.074      0.283      -0.094       0.027
egitim_Orta_Lise     -0.0245      0.012     -2.074      0.038      -0.048      -0.001
egitim_Universite    -0.0115      0.012     -0.986      0.324      -0.034       0.011
=====================================================================================

In [13]:
df["eticaret ilaç alışverişi"].isnull().sum()

np.int64(32601)

In [14]:
df["eticaret ilaç alışverişi"].value_counts()

eticaret ilaç alışverişi
2.0    3146
1.0     103
Name: count, dtype: int64