In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2016.csv" , encoding="latin1" , sep=";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,IBBS_1,HANE_GELIR_AYLIK,HHB,HANE_FAKTOR
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13700 entries, 0 to 13699
Data columns (total 42 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   13700 non-null  int64
 1   BULTEN_NO                      13700 non-null  int64
 2   CEVAPLILIK_DURUM               13700 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           11874 non-null  float64
 4   MEKTUP_BROSUR                  11874 non-null  float64
 5   BT_BILG_MASAUSTU               11276 non-null  float64
 6   BT_BILG_TASINABILIR            11276 non-null  float64
 7   BT_TABLET                      11276 non-null  float64
 8   BT_TEL_CEP                     11276 non-null  float64
 9   BT_OYUNKONSOL                  11276 non-null  float64
 10  BT_TEL_SABIT                   11276 non-null  float64
 11  BT_FOTOGRAF_KAMERA             11276 non-null  float64
 12  BT_DVD_VCD_OYNATICI            11276 non-null  float64
 13  BT_INTBAGLANAN_TV              11276 non-null  float64
 14  BT_DIGER                       11276 non-null  float64
 15  BT_ACIKLAMA                    12 non-null     str
 16  HANE_BILGISAYAR_KULLANIM       11276 non-null  float64
 17  HANE_INTERNET_ERISIM_DURUMU    11276 non-null  float64
 18  HANE_INTERNET_ERISIM_KULLANIM  8081 non-null   float64
 19  INT_BAGLANMA_MASAUSTU          8081 non-null   float64
 20  INT_BAGLANMA_TASINABILIR       8081 non-null   float64
 21  INT_BAGLANMA_TABLET            8081 non-null   float64
 22  INT_BAGLANMA_TEL_CEP           8081 non-null   float64
 23  INT_BAGLANMA_DIGER_CIHAZ       8081 non-null   float64
 24  INT_BAGLANMA_TV                8081 non-null   float64
 25  INT_BAGLANTI_SABIT_GENIS       8081 non-null   float64
 26  INT_BAGLANTI_MOBIL_GENIS       8081 non-null   float64
 27  INT_BAGLANTI_CEVIRMELI_ISDN    8081 non-null   float64
 28  INT_BAGLANTI_TEL_DARBANT       8081 non-null   float64
 29  INT_BAGLANMAMA_BASKAYER        3140 non-null   float64
 30  INT_BAGLANMAMA_GEREKYOK        3140 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_CIHAZ     3140 non-null   float64
 32  INT_BAGLANMAMA_FIYAT_BAGLANTI  3140 non-null   float64
 33  INT_BAGLANMAMA_BILMEME         3140 non-null   float64
 34  INT_BAGLANMAMA_GIZLILIK        3140 non-null   float64
 35  INT_BAGLANMAMA_IMKAN_YOK       3140 non-null   float64
 36  INT_BAGLANMAMA_ENGEL           3140 non-null   float64
 37  INT_BAGLANMAMA_DIGER           3141 non-null   float64
 38  IBBS_1                         13700 non-null  str
 39  HANE_GELIR_AYLIK               11276 non-null  float64
 40  HHB                            11874 non-null  float64
 41  HANE_FAKTOR                    11874 non-null  str
dtypes: float64(36), int64(3), str(3)
memory usage: 4.4 MB

In [10]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TELEFON_SABIT": "hanede sabit telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_OYUNKONSOL": "evde olan oyun konsolunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_ADSL": "internet bağlantı türü adsl"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_UYDU": "internet bağlantı türü kablo tv altyapısı üzerinden kablolu"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_FIBER": "internet bağlantı türü fiber bağlantı, ethernet, PLC vb"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_KABLOSUZ_SABIT": "internet bağlantı türü kablolu sabit internet "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_3G": "internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MODEM_3G": "internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb."}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_DARBANT": "internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS) "}, inplace=True)
df.rename(columns={"BT_ACIKLAMA": "hanede var olan bilişim cihazları açıklaması"}, inplace=True)

In [11]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

In [12]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2016temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2016temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

# 2016 fert-hane crosss tabloları

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2016.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_22804\3804746976.py:2: DtypeWarning: Columns (0: hanede var olan bilişim cihazları açıklaması) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2016.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,cevapsız fert,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,NaN,50,1,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10011,2,1.0,NaN,49,2,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
2,2016,10011,3,2.0,1.0,21,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
3,2016,10011,4,NaN,NaN,15,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
4,2016,10012,1,1.0,NaN,43,2,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,4528,50.41,1630,36.01
erkek,4455,49.59,2897,63.99
toplam,8983,100.00,4527,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,53,42.4,1803,45.89
erkek,72,57.6,2126,54.11
toplam,125,100.0,3929,100.00

In [3]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 1]
    yok_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2015,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2016 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["online sağlık hizmeti kullanımı"] == 1]
toplam_yok = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2016,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2016 = pd.concat(
    [gelir_online_saglik_2016, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,51.89,48.11,582,33.33,66.67,579
1,2015,2,52.20,47.80,1205,35.71,64.29,913
2,2015,3,51.89,48.11,1800,34.90,65.10,1020
3,2015,4,49.36,50.64,2360,36.35,63.65,1106
4,2015,5,49.34,50.66,3036,38.83,61.17,909

In [4]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 1]
    yok_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2016,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2016 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["online sağlık hizmeti kullanımı"] == 1]
toplam_yok = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2016,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2016 = pd.concat(
    [gelir_online_saglik_2016, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2016)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2016,1,51.89,48.11,582,33.33,66.67,579
1,2016,2,52.20,47.80,1205,35.71,64.29,913
2,2016,3,51.89,48.11,1800,34.90,65.10,1020
3,2016,4,49.36,50.64,2360,36.35,63.65,1106
4,2016,5,49.34,50.66,3036,38.83,61.17,909
5,2016,frekans,4528.00,4455.00,8983,1630.00,2897.00,4527

In [2]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_4528\100049498.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,40.00,60.00,5,51.85,48.15,162
1,2015,2,37.50,62.50,16,46.63,53.37,326
2,2015,3,52.63,47.37,19,44.67,55.33,638
3,2015,4,33.33,66.67,30,45.44,54.56,975
4,2015,5,45.45,54.55,55,45.90,54.10,1828
5,2015,toplam,53.00,72.00,125,1803.00,2126.00,3929

In [3]:
# =========================================================
# YAŞ GRUBU x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUBU OLUŞTUR
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ONLINE SAĞLIK HİZMETİ KULLANIMI VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK HİZMETİ KULLANIMI YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2015,

        "yaş": yas,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "yaş": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_online_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_online_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_22804\3050251590.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,15-30,55.80,44.20,3812,38.38,61.62,1928
1,2015,31-45,49.08,50.92,3633,36.29,63.71,1543
2,2015,46-60,41.65,58.35,1311,31.58,68.42,877
3,2015,60+,31.72,68.28,227,29.61,70.39,179
4,2015,toplam,4528.00,4455.00,8983,1630.00,2897.00,4527

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2016.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_19836\1145362891.py:2: DtypeWarning: Columns (0: hanede var olan bilişim cihazları açıklaması) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2016.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,cevapsız fert,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,NaN,50,1,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10011,2,1.0,NaN,49,2,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
2,2016,10011,3,2.0,1.0,21,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
3,2016,10011,4,NaN,NaN,15,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
4,2016,10012,1,1.0,NaN,43,2,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_640\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,48.72,51.28,39,51.88,48.12,1910
1,2024,31-45,46.43,53.57,56,42.75,57.25,1579
2,2024,46-60,22.73,77.27,22,33.51,66.49,382
3,2024,60+,37.50,62.50,8,15.52,84.48,58
4,2024,toplam,53.00,72.00,125,1803.00,2126.00,3929

In [3]:
# =========================================================
# EĞİTİM x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM KATEGORİLERİ
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    elif x in [0,1,2]:
        return "ilkokulvealtı"

    elif x in [3,4]:
        return "ortaokul/lise"

    elif x in [5]:
        return "üniversite"

    else:
        return "üniversiteüstü"

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    alt = df[df["egitim_grup"] == egitim]

    # ONLINE SAĞLIK VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2015,

        "eğitim": egitim,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "eğitim": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_online_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_online_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_640\2604698892.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,ilkokulvealtı,53.46,46.54,3283,36.84,63.16,2929
1,2015,ortaokul/lise,49.55,50.45,3669,34.86,65.14,1245
2,2015,üniversite,48.52,51.48,1723,32.79,67.21,308
3,2015,üniversiteüstü,38.64,61.36,308,35.56,64.44,45
4,2015,toplam,4528.00,4455.00,8983,1630.00,2897.00,4527

In [6]:
# =========================================================
# EĞİTİM x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM KATEGORİLERİ
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    # İLKOKUL VE ALTI
    elif x in [0, 1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [5, 6, 511, 512]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [7, 52, 53]:
        return "üniversiteüstü"

    else:
        return None

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    alt = df[df["egitim_grup"] == egitim]

    # ONLINE SAĞLIK VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2016,

        "eğitim": egitim,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2016,

    "eğitim": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_online_2016 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_online_2016)

C:\Users\dilara\AppData\Local\Temp\ipykernel_640\988942446.py:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2016,ilkokulvealtı,53.46,46.54,3283,36.84,63.16,2929
1,2016,ortaokul/lise,49.55,50.45,3669,34.86,65.14,1245
2,2016,üniversite,47.25,52.75,1983,32.75,67.25,342
3,2016,üniversiteüstü,37.50,62.50,48,45.45,54.55,11
4,2016,toplam,4528.00,4455.00,8983,1630.00,2897.00,4527

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_19836\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_19836\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,13,16,29,377,415,792
1,2025,ortaokul/lise,16,27,43,775,910,1685
2,2025,üniversite,24,28,52,636,776,1412
3,2025,üniversiteüstü,0,1,1,15,25,40
4,,toplam,53,72,125,1803,2126,3929