In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2017.csv", sep = ";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,...,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15490 entries, 0 to 15489
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   15490 non-null  int64
 1   BULTEN_NO                      15490 non-null  int64
 2   CEVAPLILIK_DURUM               15490 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           13487 non-null  float64
 4   MEKTUP_BROSUR                  13487 non-null  float64
 5   BT_BILG_MASAUSTU               12781 non-null  float64
 6   BT_BILG_TASINABILIR            12781 non-null  float64
 7   BT_TABLET                      12781 non-null  float64
 8   BT_TEL_CEP                     12781 non-null  float64
 9   BT_OYUNKONSOL                  12781 non-null  float64
 10  BT_TEL_SABIT                   12781 non-null  float64
 11  BT_FOTOGRAF_KAMERA             12781 non-null  float64
 12  BT_DVD_VCD_OYNATICI            12781 non-null  float64
 13  BT_INTBAGLANAN_TV              12781 non-null  float64
 14  BT_DIGER                       12781 non-null  float64
 15  HANE_BILGISAYAR_KULLANIM       12781 non-null  float64
 16  HANE_INTERNET_ERISIM_DURUMU    12781 non-null  float64
 17  HANE_INTERNET_ERISIM_KULLANIM  9888 non-null   float64
 18  INT_BAGLANMA_MASAUSTU          9888 non-null   float64
 19  INT_BAGLANMA_TASINABILIR       9888 non-null   float64
 20  INT_BAGLANMA_TABLET            9888 non-null   float64
 21  INT_BAGLANMA_TEL_CEP           9888 non-null   float64
 22  INT_BAGLANMA_DIGER_CIHAZ       9888 non-null   float64
 23  INT_BAGLANMA_TV                9888 non-null   float64
 24  INT_BAGLANTI_SABIT_GENIS       9888 non-null   float64
 25  INT_BAGLANTI_MOBIL_GENIS       9888 non-null   float64
 26  INT_BAGLANTI_CEVIRMELI_ISDN    9888 non-null   float64
 27  INT_BAGLANTI_TEL_DARBANT       9888 non-null   float64
 28  INT_BAGLANMAMA_BASKAYER        2865 non-null   float64
 29  INT_BAGLANMAMA_GEREKYOK        2865 non-null   float64
 30  INT_BAGLANMAMA_FIYAT_CIHAZ     2865 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_BAGLANTI  2865 non-null   float64
 32  INT_BAGLANMAMA_BILMEME         2865 non-null   float64
 33  INT_BAGLANMAMA_GIZLILIK        2865 non-null   float64
 34  INT_BAGLANMAMA_IMKAN_YOK       2865 non-null   float64
 35  INT_BAGLANMAMA_ENGEL           2865 non-null   float64
 36  INT_BAGLANMAMA_DIGER           2865 non-null   float64
 37  HHB                            13487 non-null  float64
 38  HANE_GELIR_AYLIK               12781 non-null  float64
 39  IBBS_1                         15490 non-null  str
 40  HANE_FAKTOR                    13487 non-null  str
dtypes: float64(36), int64(3), str(2)
memory usage: 4.8 MB

In [4]:
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_TEL_SABIT,BT_FOTOGRAF_KAMERA,BT_DVD_VCD_OYNATICI,BT_INTBAGLANAN_TV,BT_DIGER,HANE_BILGISAYAR_KULLANIM,HANE_INTERNET_ERISIM_DURUMU,HANE_INTERNET_ERISIM_KULLANIM,INT_BAGLANMA_MASAUSTU,INT_BAGLANMA_TASINABILIR,INT_BAGLANMA_TABLET,INT_BAGLANMA_TEL_CEP,INT_BAGLANMA_DIGER_CIHAZ,INT_BAGLANMA_TV,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,INT_BAGLANMAMA_BASKAYER,INT_BAGLANMAMA_GEREKYOK,INT_BAGLANMAMA_FIYAT_CIHAZ,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)

In [10]:
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)

In [11]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15485,2017,254510,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1400.0,TRC,"1354,453276"
15486,2017,254610,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,1000.0,TRC,"2112,420995"
15487,2017,254710,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,1400.0,TRC,"1948,374117"
15488,2017,254810,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,1400.0,TRC,"2817,960304"
15489,2017,254910,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,8.0,300.0,TRC,"2953,635066"

In [12]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

# 2017 yılı crosss tabloları

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,6179,49.74,2086,38.08
erkek,6244,50.26,3392,61.92
toplam,12423,100.00,5478,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,104,43.33,2396,45.29
erkek,136,56.67,2894,54.71
toplam,240,100.00,5290,100.00

In [2]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 1]
    yok_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2017,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2017 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["online sağlık hizmeti kullanımı"] == 1]
toplam_yok = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2017= pd.concat(
    [gelir_online_saglik_2017, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_21080\496887858.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,1,52.11,47.89,1021,39.79,60.21,847
1,2017,2,49.94,50.06,1818,37.63,62.37,1225
2,2017,3,51.34,48.66,2462,35.40,64.60,1195
3,2017,4,48.72,51.28,3231,39.10,60.90,1271
4,2017,5,48.86,51.14,3891,39.15,60.85,940
5,2017,frekans,6179.00,6244.00,12423,2086.00,3392.00,5478

In [2]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_9724\100049498.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,41.67,58.33,12,50.20,49.80,255
1,2015,2,32.14,67.86,28,46.24,53.76,545
2,2015,3,45.16,54.84,31,45.80,54.20,882
3,2015,4,32.56,67.44,43,44.98,55.02,1365
4,2015,5,49.21,50.79,126,44.49,55.51,2243
5,2015,toplam,104.00,136.00,240,2396.00,2894.00,5290

In [2]:
# =========================================================
# YAŞ GRUBU x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUBU OLUŞTUR
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ONLINE SAĞLIK HİZMETİ KULLANIMI VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK HİZMETİ KULLANIMI YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2015,

        "yaş": yas,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "yaş": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_online_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_online_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24556\3050251590.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,15-30,53.39,46.61,5005,38.70,61.30,2173
1,2015,31-45,50.18,49.82,5058,40.20,59.80,1898
2,2015,46-60,41.93,58.07,2013,34.30,65.70,1172
3,2015,60+,36.02,63.98,347,34.04,65.96,235
4,2015,toplam,6179.00,6244.00,12423,2086.00,3392.00,5478

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_1920\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,47.54,52.46,61,49.79,50.21,2579
1,2024,31-45,43.31,56.69,127,43.73,56.27,2113
2,2024,46-60,40.00,60.00,45,31.81,68.19,547
3,2024,60+,28.57,71.43,7,27.45,72.55,51
4,2024,toplam,104.00,136.00,240,2396.00,2894.00,5290

In [6]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # VAR
    var_df = temp[temp["online sağlık hizmeti kullanımı"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = temp[temp["online sağlık hizmeti kullanımı"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["online sağlık hizmeti kullanımı"] == 1]
yok_all = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_online_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_online_2017)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,58.45,41.55,2320,45.22,54.78,2030
1,2017,ortaokul/lise,48.56,51.44,6406,33.61,66.39,2865
2,2017,üniversite,46.45,53.55,3649,35.48,64.52,575
3,2017,üniversiteüstü,35.42,64.58,48,12.50,87.50,8
4,2017,toplam,6179.00,6244.00,12423,2086.00,3392.00,5478

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_10076\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_10076\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,11,14,25,201,172,373
1,2025,ortaokul/lise,35,62,97,1167,1442,2609
2,2025,üniversite,56,59,115,1014,1253,2267
3,2025,üniversiteüstü,2,1,3,14,27,41
4,,toplam,104,136,240,2396,2894,5290