In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert_2017.csv" , sep=";")

df.head()

,REFERANS_YIL,BULTEN_NO,FERTNO,CEVAPLILIK_DURUM_FERT,KAPSAMICI_KAPSAMDISI,YAS,CINSIYET,OKUMA_YAZMA,OKUL_BITEN,CALISMA_DURUM,...,EYETENEK_BLGMOBIL_SISTEM_DEG,EYETENEK_YZLM_DOSYA_KOPYALM,EYETENEK_YZLM_METIN_HAZRLM,EYETENEK_YZLM_DOKUMN_OLSTRM,EYETENEK_YZLM_HZPRG_KULLNM,EYETENEK_YZLM_HZPRG_FORML,EYETENEK_YZLM_FOTO_VIDEO,EYETENEK_YZLM_KODYZM,IBBS_1,FERT_FAKTOR
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2169,012791"

In [2]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [3]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [4]:
df.rename(columns={"FERTNO": "fert no"}, inplace=True)

In [5]:
df.rename(columns={"GORUSME_YONTEM_FERT": "fert no"}, inplace=True)
df.rename(columns={"HHSORUMLU_YAKINLIK": "yakınlık durumu"}, inplace=True)
df.rename(columns={"CINSIYET": "cinsiyet"}, inplace=True)
df.rename(columns={"YAS": "yaş"}, inplace=True)
df.rename(columns={"OKUL_BITEN": "eğitim"}, inplace=True)
df.rename(columns={"OKUMA_YAZMA": "okuma yazma durumu"}, inplace=True)
df.rename(columns={"CALISMA_DURUM": "çalışma durumu"}, inplace=True)
df.rename(columns={"CALISMAMA_NEDEN": "çalışmama nedeni"}, inplace=True)
df.rename(columns={"ISTEKI_DURUM": "işteki durumu"}, inplace=True)
df.rename(columns={"DOGUM_YER": "doğduğu ülke"}, inplace=True)
df.rename(columns={"DOGUM_YER_ULKE_KOD": "doğduğu ülke kodu"}, inplace=True)
df.rename(columns={"UYRUK": "uyruk"}, inplace=True)
df.rename(columns={"UYRUK_ULKE_KOD": "uyruk ülke kodu"}, inplace=True)
df.rename(columns={"KULLANIM_CEP": "cep telefonu kullanımı"}, inplace=True)
df.rename(columns={"CEP_SAHIP": "cep telefonuna sahip"}, inplace=True)
df.rename(columns={"SON_KULLANIM_INTERNET": "en son internet ne zaman kullanıldı"}, inplace=True)
df.rename(columns={"KULLANIM_SIKLIK_INTERNET": "internet kullanım sıklığı"}, inplace=True)
df.rename(columns={"INT_FAAL_EPOSTA": "eposta kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_TELEFON": "internet araması"}, inplace=True)
df.rename(columns={"INT_FAAL_SOSYAL_GRKATILIM": "sosyal medya kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_MESAJ": "sosyal medyada mesajlaşma"}, inplace=True)
df.rename(columns={"INT_FAAL_ONLINE_HABER": "online haber okuma"}, inplace=True)
df.rename(columns={"INT_FAAL_MALHIZ_BILGI": "ürün hizmet arama"}, inplace=True)
df.rename(columns={"INT_FAAL_WEBSITE_PAYLASIM": "websitesinde içerik paylaşma"}, inplace=True)
df.rename(columns={"INT_FAAL_OYL_KTLM": "internetten oy katılım"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_KURS": "online kurs"}, inplace=True)
df.rename(columns={"INT_FAAL_ISARAMA": "internetten iş arama"}, inplace=True)
df.rename(columns={"INT_FAAL_BANKA_ISLEM": "internetten satış"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_KURS": "online kurs"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_OGRN_MTRYL": "online eğitim materyal"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_WEB": "online eğitim iletişim"}, inplace=True)
df.rename(columns={"KULLAN_WHATSAPP": "whatsapp kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_INSTAGRAM": "instagram kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_YOUTUBE": "youtube kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_FACEBOOK": "facebook kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_TWITTER": "twitter kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_TELEGRAM": "telegram kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_MALHIZMET_SATIS": ""}, inplace=True)
df.rename(columns={"KULLAN_TIKTOK": "tiktok kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_SNAPCHAT": "snapchat kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_BIP": "bip kullanımı"}, inplace=True)
df.rename(columns={"KULLAN_DIGER": "diğer mobil uygulama kullanımları"}, inplace=True)
df.rename(columns={"EDEVLET_KSL_BILGI_ERISME": "edevlet resmi işlem"}, inplace=True)
df.rename(columns={"EDEVLET_KAMU_BILGI_ERISME": "edevlet kamu bilgi"}, inplace=True)
df.rename(columns={"EDEVLET_BILGI_EDINME": "edevlet hakkında bilgi"}, inplace=True)
df.rename(columns={"EDEVLET_HICBIRI": "edevlette hiçbir sey yapmadı"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_INDIRME": "edevlet form işlemleri"}, inplace=True)
df.rename(columns={"EDEVLET_RANDEVU_REZRVSYN": "edevletten randevu alma"}, inplace=True)
df.rename(columns={"EDEVLET_HESAP_BLG_ALMA": "edevletten bilgi alma"}, inplace=True)
df.rename(columns={"EDEVLET_KSL_VERGI_ONAY": "edevlet vergi işlem"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_BELGE_SRTFKA": "edevlet belge talep"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_YARDIM_HAK": "edevlet yardım talep"}, inplace=True)

In [6]:
df.rename(columns={"ISCO08_MESLEK": "uluslararası meslek"}, inplace=True)

In [7]:
df.rename(columns={"EDEVLET_TALEP_DIGER": "edevlet diğer talepler"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_IHTIYACYOK": "edevletten talepe ihtiyaç yok"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_EKSKBILG": "edevlet kullanımı bilgi eksiği"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_GUVENSIZ": "edevlet güven sorunu"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_EKIMLIKYOK": "edevlet dijital kimlik yok"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_BASKASI": "edevlet işlemlerini başkası yapıyor"}, inplace=True)
df.rename(columns={"EDEVLET_TALEP_HIC_DIGER": "edevlet kullanım diğer"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_ZOR": "edevlet kullanımı zor"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_TEKNIK": "edevlet kullanırken teknik sorunlar"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_E_IMZA_KIMLIK": "edevlet eimza sorunu"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_ODEME": "edevlet ödeme sorunu"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_MOBIL_ERISIM": "edevlet mobil erişim sorunu"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_DIGER": "edevlette diğer sorunlar"}, inplace=True)
df.rename(columns={"EDEVLET_SORUN_HIC": "edevlette sorun yok"}, inplace=True)
df.rename(columns={"EKIMLIK_ERSM_OZEL_AMAC": "ekimliği özel amaç için kullanma"}, inplace=True)
df.rename(columns={"EKIMLIK_KAMU_HZMT": "ekimliği kamu hizmeti için kullanma"}, inplace=True)
df.rename(columns={"EKIMLIK_OZEL_HZMT": "ekimliği özel hizmet için kullanma"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_HBR_DGL": "ekimlikten haberi yok"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_YOK": "ekimlik yok"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_GRKMD": "ekimlik var ama ihtiyaç olmadı"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_GVNSZ": "ekimlik var ama kullanımı güvenli değil"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_TKNK_SRN": "ekimliği teknik sorundan kullanamama"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_AKL_TLF_TBL": "ekimlik mobil erişim yok"}, inplace=True)
df.rename(columns={"EKIMLIK_KLLNMM_SBP_DGR": "ekimlik var ama baska sebeplerle kullanmıyorum"}, inplace=True)

In [8]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_DGR": "ekimlik var ama baska sebeplerle kullanmıyorum"}, inplace=True)
df.rename(columns={"ETICARET_FIZIKSEL": "eticaretten alınan fiziksel mal"}, inplace=True)
df.rename(columns={"WEBSTE_INT_MOBL_ABONE": "internet bağlantı aboneliği"}, inplace=True)
df.rename(columns={"WEBSTE_ELK_SU_ABONE": "elektrik su doğal gaz vb hizmet aboneliği"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_ULASIM": "online ulaşım hizmeti"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_RZV_KONAKLAMA": "online konaklama hizmeti"}, inplace=True)
df.rename(columns={"WEBSTE_BILET": "online etkinlik biletleri"}, inplace=True)
df.rename(columns={"WEBSTE_BILET": "online etkinlik biletleri"}, inplace=True)
df.rename(columns={"WEBSTE_BLG_YZLM": "yazılım indirme sürüm yükseltme"}, inplace=True)
df.rename(columns={"WEBSTE_OYUN_OGE": "oyun indirme sürüm yükseltme"}, inplace=True)
df.rename(columns={"WEBSTE_MUZIK_YAYIN": "online müzik dinleme platformu"}, inplace=True)
df.rename(columns={"WEBSTE_FILM_SPOR": "online film/dizi/video platformu"}, inplace=True)
df.rename(columns={"WEBSTE_DERGI_GAZETE": "online dergi gazete"}, inplace=True)
df.rename(columns={"WEBSTE_OYUN_YAYIN": "oyun yayın platformu"}, inplace=True)
df.rename(columns={"WEBSTE_SAGLK_UYGL": "sağlık/sağlıklı yaşam uygulamaları"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_DIGER": "diğer mobil uygulamalar"}, inplace=True)
df.rename(columns={"WEBSTE_UYGLM_FZKSL_OZL_KSL": "online c2c alışveriş"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_ULASIM_OZL_KSL": "online ulaşım paylaşımı"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_RZV_OZL_KSL": "online p2p konaklama"}, inplace=True)
df.rename(columns={"WEBSTE_HHN_HZMET_OZL_KSL": "online ev hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_HRCM_KEZ_SONUCAY": "eticaret alışveriş sıklık"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_KULLANIM": "web kullanım zorluğu"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_GARANTI": "web garanti bilgi sorun"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_TSLM_YAVAS": "webde yapılan satın almanın teslimat gecikmesi sorunu"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_YUK_MALYE": "webde yapılan satın almanın beklenenden yüksek maliyet"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_YANLIS_MAL": "webde yapılan satın alınanın yanlış/hasarlı olması"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_DOLANDRLKL": "webde yapılan satın almanın dolandırıcılık sorunu"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_SIKAYET": "webde yapılan satın almaların şikayet iade tazminat sorunu"}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_YURTDISI": "yurt dışı web sitelerinde alışveriş engeli "}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_DIGER": "web alısverişlerindeki diğer sorunlar "}, inplace=True)
df.rename(columns={"WEBSTE_HRC_SRN_YOK": "web alışverişlerinde sorun yok"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_SAG_GUV": "eticaret sağlık güven sorunu"}, inplace=True)

In [9]:
df.rename(columns={"SOSMED_RKLM_ETIC_POLICE": "online sigorta işlemleri"}, inplace=True)
df.rename(columns={"SOSMED_RKLM_ETIC_BANKA": "online banka işlemleri"}, inplace=True)
df.rename(columns={"SOSMED_RKLM_ETIC_SENET": "online yatırım işlemleri"}, inplace=True)
df.rename(columns={"EYETENEK_BLGMOBIL_DOSYA_AKT": "dijital beceri dosya transfer"}, inplace=True)
df.rename(columns={"EYETENEK_BLGMOBIL_UYGLM_YUKLM": "dijital beceri uygulama kurulum"}, inplace=True)
df.rename(columns={"EYETENEK_BLGMOBIL_SISTEM_DEG": "dijital beceri ayar değiştirme"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_KLM_ISLEMCI": "dijital beceri ofis yazılımı kullanma"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_DOKUMN_OLSTRM": "dijital beceri doküman oluşturma"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_HZPRG_KULLNM": "dijital beceri tablolama yazılımı kullanma"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_HZPRG_FORML": "dijital beceri tablolama ileri yazılım kullanma"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_FOTO_VIDEO": "dijital beceri foto video düzenleme"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_KODYZM": "dijital beceri kod yazma"}, inplace=True)
df.rename(columns={"EBECERI_ICERIK_SUPHE": "dijital beceri şüpheli içerikle karşılaşma"}, inplace=True)
df.rename(columns={"EBECERI_ICERIK_KONTROL": "dijital beceri şüpheli içerik kontrol etme"}, inplace=True)
df.rename(columns={"EBECERI_ICERIK_KONTROL_BASKA": "dijital beceri bilgi kaynağı kontrolü"}, inplace=True)
df.rename(columns={"EBECERI_ICERIK_KONTROL_TART": "dijital beceri içerik tartışmaya katılım"}, inplace=True)
df.rename(columns={"EBECERI_ICERIK_KONTROL_DIGER": "dijital beceri içerik offline tartışma"}, inplace=True)
df.rename(columns={"EBECERI_KNTRL_ETMEME_BILIYOR": "dijital beceri güvenilmez bilgi farkındalığı"}, inplace=True)
df.rename(columns={"EBECERI_KNTRL_ETMEME_EKSK_BLG": "dijital beceri bilgi beceri eksikliği"}, inplace=True)
df.rename(columns={"EBECERI_KNTRL_ETMEME_DIGER": "dijital beceri bilgiyi kontrol etmeme diğer"}, inplace=True)
df.rename(columns={"INT_KBILGI_KORU_ACKOKUMA": "kvkk gizlilik politikası okuması"}, inplace=True)

In [10]:
df.rename(columns={"INT_KBILGI_KORU_SINIR": "kvkk konum erişimini kısıtlama"}, inplace=True)
df.rename(columns={"INT_KBILGI_KORU_SINIR_SOSYAL": "kvkk sosyal medya gizlilik"}, inplace=True)
df.rename(columns={"INT_KBILGI_KORU_IZINVRMEME": "kvkk veri paylaşım reddetme"}, inplace=True)
df.rename(columns={"INT_KBILGI_KORU_WEBKNTRL": "kvkk web güvenlik kontrolü"}, inplace=True)
df.rename(columns={"INT_KBILGI_KORU_WEB_TALP": "kvkk veri güncelleme silme talep"}, inplace=True)
df.rename(columns={"INT_KBILGI_CEREZ_SNR": "kvkk çerez yönetimi"}, inplace=True)
df.rename(columns={"INT_KBILGI_RKLM_ENDS": "kvkk reklam takip endişesi"}, inplace=True)
df.rename(columns={"INT_KBILGI_ETKNLIK_SNR": "kvkk izleme engelleme yazılım kullanma"}, inplace=True)
df.rename(columns={"INT_HESAP_AC": "online hesap açma"}, inplace=True)
df.rename(columns={"INT_HESAP_SIL": "online hesap silme"}, inplace=True)
df.rename(columns={"INT_HESAP_SIL_SORUN": "online hesap silerken sorun olması"}, inplace=True)
df.rename(columns={"fert_faktor": "fert ağırlık katsayısı"}, inplace=True)

In [11]:
df.rename(columns={"FAALIYET_SINIRLAMA_DURUM": "sağlık problemi nedeni ile faaliyet sınırlaması"}, inplace=True)
df.rename(columns={"FAALIYET_SINIRLAMA_SURE": "sağlık problemi nedeni ile faaliyet sınırlama süresi"}, inplace=True)
df.rename(columns={"INT_FAAL_MUZIK_DINLM": "online müzik dinleme platformu"}, inplace=True)
df.rename(columns={"INT_FAAL_TV": "online film/dizi/video platformu"}, inplace=True)
df.rename(columns={"INT_FAAL_UCRVIDEO_IZLM": "ücretli online film/dizi/video platformu"}, inplace=True)
df.rename(columns={"INT_FAAL_PAYVIDEO_IZLM": "sosyal medyada video izleme"}, inplace=True)
df.rename(columns={"INT_FAAL_OYUN_INDIR_OYNAT": "oyun indirme sürüm yükseltme"}, inplace=True)
df.rename(columns={"INT_FAAL_PODCAST": "podcast dinlemek ve indirmek"}, inplace=True)
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM": "sağlık bilgisi arama"}, inplace=True)
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM_F": "fiziksel sağlık bilgisi arama"}, inplace=True)
df.rename(columns={"INT_FAAL_SAGLIK_RANDEVU_AL": "randevu alma (e-nabız,mhrs vb.)"}, inplace=True)
df.rename(columns={"INT_FAAL_SAGLIK_SONUC_AL": "sağlık sonuçlarını almak"}, inplace=True)
df.rename(columns={"INT_FAAL_SAGLIK_TIBKONS_RECETE": "doktora gitmeden konsültasyonlar ve reçete alma"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_KURS_AMAC_ORGUN": "örgün eğitim için online kurs"}, inplace=True)

In [12]:
df.rename(columns={"INT_FAAL_EGT_KURS_AMAC_IS": "iş için online kurs"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_KURS_AMAC_OZEL": "özel amaç için online kurs"}, inplace=True)
df.rename(columns={"OLCEK_EVDEN_CALISMA": "evden çalışma sıklığı"}, inplace=True)
df.rename(columns={"EVDEN_CALISMA_ISICIN_INT_KUL": "evden çalışırken internet kullanımı "}, inplace=True)
df.rename(columns={"WEBSTE_KITAP_E_SESLI": "ekitap sesli kitap"}, inplace=True)
df.rename(columns={"SON_KULLANIM_ETICARET": "eticaret kullanımı"}, inplace=True)
df.rename(columns={"ETICARET_FIZIKSEL": "eticaretten alınan fiziksel mal"}, inplace=True)
df.rename(columns={"ETICARET_TUR_GIYIM": "eticaret giyim alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_SPOR_MLZ": "eticaret spor malzemesi alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_COCUK_BK_OYN": "eticaret çocuk oyuncakları ve bakım alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_MOTR_ARC_YDK": "eticaret motorlu araç yedekleri alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_DIGER": "eticaretdiğer türler alışverişi"}, inplace=True)

In [13]:
df.rename(columns={"NESN_INT_ENERJI_CHZ": "enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_ALRM_KAM": "internete bağlı alarm güvenlik kamerası ve dedektör kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_AKL_CHZ_ROBOT": "internete bağlı akıllı cihaz ve ev robotu kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_SANL_ASISTAN": "sanal asistan ve akıllı hoparlör kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_HIC": "internete bağlı cihaz kullanmıyor"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_BLG_YOK": "internete bağlı cihaz ve sistemlerden haberi yok"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_IHT_YOK": "internete bağlı cihaz ve sistemlere ihtiyacı yok"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_FYT_COK": "internete bağlı cihaz ve sistemleri pahalı bulma"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_CHZ_UYMSZ": "internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_EKS_BCR": "internete bağlı cihaz kullanımı konusunda beceri eksikliği"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_GZL_KAYG": "internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_GUVN_END": "internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_SGL_END": "internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi"}, inplace=True)
df.rename(columns={"NESN_INT_HIC_DIGER": "internete bağlı cihazı diğer nedenlerle kullanmama"}, inplace=True)
df.rename(columns={"NESN_INT_EV_SMARTTV": "internete bağlı tv kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_EV_OYNKONS": "internete bağlı oyun konsolu kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_EV_AKILSISTM": "internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_AKILL_SAAT": "internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_AKILL_SGLK_CHZ": "internete bağlı sağlık izleme ve tıbbi cihaz kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_AKILL_RBT_OYN": "internete bağlı akıllı robot ve oyuncak kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_AKILLI_ARABA": "internete bağlı akıllı araç ve otomobil kullanımı"}, inplace=True)
df.rename(columns={"NESN_INT_SRN_GUVEN_GIZ": "internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu"}, inplace=True)
df.rename(columns={"NESN_INT_SRN_EMNYT_SAGLIK": "internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"}, inplace=True)

In [14]:
df.rename(columns={"NESN_INT_SRN_ZOR": "internete bağlı cihaz kullanımında ve kurulumundaki sorunlar"}, inplace=True)
df.rename(columns={"NESN_INT_SRN_DIGER": "internete bağlı cihaz kullanımındaki diğer sorunlar"}, inplace=True)
df.rename(columns={"NESN_INT_SRN_HIC": "internete bağlı cihaz kullanımında sorun yaşamama"}, inplace=True)

In [15]:
df.rename(columns={"CIHAZ_DEGISIM_MOBIL_TEL": "mobil telefon değiştirildiğinde yapılan işlem"}, inplace=True)
df.rename(columns={"CIHAZ_DEGISIM_DIZUSTU_TABLET": "dizüstü veya tablet değiştirildiğinde yapılan işlem"}, inplace=True)
df.rename(columns={"CIHAZ_DEGISIM_MASAUSTU": "masaüstü bilgisayar değiştirildiğinde yapılan işlem"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_FIYAT": "cihaz satın alınımında fiyat önceliği"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_MARKA_TASARIM": "cihaz satın alınımında marka tasarım ve boyut önceliği"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_DONANIM": "cihaz satın alınımında teknik donanım ve performans önceliği"}, inplace=True)
df.rename(columns={"CIHAZ_CEVRECITASARIM": "cihaz satın alınımında çevre dostu tasarım önceliği"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_EKGARANTI": "cihaz satın alınımında ek garanti tercihi"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_ENERJIVERIMLILIK": "cihaz satın alınımında enerji verimliliği önceliği"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_GERIALMA": "cihaz satın alınımında geri alım programı etkisi"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_BASKANEDEN": "cihaz satın alınımında diğer faktörler"}, inplace=True)
df.rename(columns={"CIHAZ_ALIS_YOK": "cihaz satın alınımında hiçbir faktörü önemsememe"}, inplace=True)

In [16]:
df.rename(columns={"FERT_INT_MASAUSTU": "masaüstü kullanımı"}, inplace=True)
df.rename(columns={"FERT_INT_DIZUSTU": "dizüstü kullanımı"}, inplace=True)
df.rename(columns={"FERT_INT_TABLET": "tablet kullanımı"}, inplace=True)
df.rename(columns={"FERT_INT_TEL_CEP": "cep telefonu kullanımı"}, inplace=True)

In [17]:
df.rename(columns={"FERT_INT_DIGER_CIHAZ": "diğer cihaz kullanımı"}, inplace=True)
df.rename(columns={"WEBSTE_MUZIK": "online müzik dinleme platformu"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM_FERT": "fert cevap durumu"}, inplace=True)
df.rename(columns={"SONUCAY_KULLANIM_CEP": "cep telefonu kullanımı"}, inplace=True)
df.rename(columns={"EVDEN_CALISMA_SIKLIK": "evden çalışma sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_KSL_VERGI_BEYAN": "edevlette vergi beyani verme yönetimi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_CD_PLK": "eticaret cd plak alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_DVD_BLU_RAY": "eticaret dvd plak alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_ULKE_YURTICI": "eticaret yurt içindeki satıcılar"}, inplace=True)
df.rename(columns={"ETICARET_ULKE_AB": "eticaret avrupa ülkelerindeki satıcılar"}, inplace=True)
df.rename(columns={"ETICARET_ULKE_DIGER": "eticaret diğer ülkelerdeki satıcılar"}, inplace=True)
df.rename(columns={"ETICARET_ULKE_BILINMIYOR": "eticaret satıcısının ülkesi bilinmiyor"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_MAL_ALIS_SAHS": "online c2c alışveriş"}, inplace=True)
df.rename(columns={"WEBSTE_FILM": "online film/dizi/video platformu"}, inplace=True)
df.rename(columns={"WEBSTE_E_KITAP": "ekitap sesli kitap"}, inplace=True)
df.rename(columns={"WEBSTE_OYUN": "oyun yayın platformu"}, inplace=True)
df.rename(columns={"WEBSTE_BILET_SPOR": "online etkinlik biletleri spor"}, inplace=True)
df.rename(columns={"WEBSTE_BILET_KULTUR": "online etkinlik biletleri kültür"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_ULASIM_SRKT": "online şirketlerle ulaşım"}, inplace=True)
df.rename(columns={"WEBSTE_UYGL_RZV_OTEL_ACNT": "online turizm acenteleri ile konaklama"}, inplace=True)

In [18]:
df.rename(columns={"WEBSTE_FILM": "online film/dizi/video platformu"}, inplace=True)
df.rename(columns={"WEBSTE_E_KITAP": "ekitap sesli kitap"}, inplace=True)
df.rename(columns={"WEBSTE_OYUN": "oyun yayın platformu"}, inplace=True)
df.rename(columns={"WEBSTE_HHN_HZMET_SAHS": "online ev hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_EVESYASI": "eticaret ev eşyası alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_CD_DVD": "eticaret cd dvd alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_KITAPDERGI": "eticaret kitap dergi alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_ELKTR_ARC_AKS": "eticaret elektronik cihazlar ve aksesuarı alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_ELEKTRONIK_ARAC": "eticaret elektronik araçlar alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_ILAC": "eticaret ilaç alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_YEMEK_SIPARIS": "eticaret yemek siparişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_HZR_TZ_GIDA": "eticaret gıda ürünleri alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_KOZMETIK": "eticaret kozmetik alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_TMZ_KSL_BKM": "eticaret temizlik ve kişisel bakım ürünleri alışverişi"}, inplace=True)
df.rename(columns={"FAALIYET_SINIRLAMA": "sağlık problemi nedeni ile faaliyet sınırlaması"}, inplace=True)

In [19]:
df.rename(columns={"FERT_FAKTOR": "fert ağırlık katsayısı"}, inplace=True)

In [20]:
df.rename(columns={"WEBSTE_HHN_HZMET": "online ev hizmetleri"}, inplace=True)

In [21]:
df.rename(columns={"CALISMA_SAHIP_IS": "iş sahibi mi"}, inplace=True)

In [22]:
df.rename(columns={"GUNLUK_KULLANIM_INTERNET": "günlük kullanılan internet"}, inplace=True)

In [23]:
df.rename(columns={"EDEVLET_FORM_GONDERME": "edevlet form gönderme"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_IHTIYACYOK": "edevlet form gönderme ihtiyacı yok"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_HIZMET_YOK": "edevlet form gönderme hizmeti yok"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_EKSIK_BILG": "edevlet form gönderme bilgi eksiği"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_GUVENLIK": "edevlet form gönderme güvenlik endişesi"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_DANISMAN": "edevlet form göndermeyi danışman yaptı"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_TRCH": "edevlet form göndermeyi tercih etmedi"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_DIGER": "edevlet form gönderme diğer neden"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_ADLI": "edevlet adli hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_ASAYIS": "edevlet asayiş hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_BLD": "edevlet belediye hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_CVRSL": "edevlet çevresel hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_EGTM": "edevlet eğitim hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_EKONMI": "edevlet ekonomi hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_KULT_SPR": "edevlet kültür spor hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_SAGLIK": "edevlet sağlık hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_SOSYL_GUV": "edevlet sosyal güvenlik hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_ULASTIRMA": "edevlet ulaştırma hizmet sıklığı"}, inplace=True)
df.rename(columns={"EDEVLET_HZMT_SKLK_DIGER": "edevlet diğer hizmet sıklığı"}, inplace=True)

In [24]:
df.rename(columns={"ETICARET_TUR_ACIKLAMA": "eticaret tür açıklama"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_URUNGORME": "eticaret yapmama ürünü görmeden almak istememe"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_TESLIMAT": "eticaret yapmama teslimat endişesi"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_GUVEN": "eticaret yapmama güven sorunu"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_GIZ_GUVEN": "eticaret yapmama gizlilik güvenlik endişesi"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_IADE": "eticaret yapmama iade sorunu"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_GEREKYOK": "eticaret yapmama ihtiyaç yok"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_DIGER": "eticaret yapmama diğer"}, inplace=True)
df.rename(columns={"INT_KBILGI_CEREZ_BILGI": "internet çerez bilgi farkındalığı"}, inplace=True)

In [25]:
df.rename(columns={"ETICARET_YAPMAMA_EKSIKBILGI": "eticaret yapmama bilgi eksikliği"}, inplace=True)

In [26]:
df.rename(columns={"INT_FAAL_WEB_ICERIK_YUKLEME": "websitesinde içerik paylaşma"}, inplace=True)

In [27]:
df.rename(columns={"INT_BULUT_DEPO_KULLANIM": "internet üzerinden bulut depolama kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_EGT_DIGER": "internet üzerinden yapılan diğer eğitim faaliyetleri"}, inplace=True)
df.rename(columns={"AKILLI_TEL_KSL_KULLANIM": "akıllı telefon kullanımı"}, inplace=True)
df.rename(columns={"AKILLI_TEL_GV_UYGL_BULUNMA": "akıllı telefonda güvenlik uygulaması bulunması"}, inplace=True)
df.rename(columns={"AKILLI_TEL_GV_UYGL_YUKLEME": "akıllı telefona güvenlik uygulaması yükleme"}, inplace=True)
df.rename(columns={"AKILLI_TEL_GV_UYGL_BULUNMAMA": "akıllı telefonda güvenlik uygulaması bulunmaması"}, inplace=True)
df.rename(columns={"AKILLI_TEL_GV_UYGL_BILMIYOR": "akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor"}, inplace=True)
df.rename(columns={"AKILLI_TEL_VIRUS_KAYBI": "akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama"}, inplace=True)
df.rename(columns={"AKILLI_TEL_GV_KISIT_IPTAL": "akıllı telefonda güvenlik kısıtlarını iptal etme"}, inplace=True)

In [28]:
df.rename(columns={"ETICARET_TUR_GIDA": "eticaret gıda ürünleri alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_BILG_DONANIM": "eticaret bilgisayar ve donanım alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_TUR_TELEKOM_HIZMET": "eticaret telekomünikasyon hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_KONAKLAMA": "eticaret konaklama hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_SEYAHAT": "eticaret seyahat hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_BILETALIM": "eticaret bilet satın alma"}, inplace=True)
df.rename(columns={"ETICARET_TUR_FILMMUZIK": "eticaret film ve müzik hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_EOGRENME": "eticaret e-öğrenme hizmetleri"}, inplace=True)
df.rename(columns={"ETICARET_TUR_OYUNBILGI_YZLM": "eticaret oyun yazılım ve bilgi ürünleri"}, inplace=True)
df.rename(columns={"ETICARET_FILM_MUZIK": "eticaret film müzik alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_KITAP": "eticaret kitap alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_DERGI_GAZETE": "eticaret dergi gazete alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_BILG_YAZILIM": "eticaret yazılım ve bilgi ürünleri alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_TEKNIK": "eticaret teknik sorunlar"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_BILGI_ZORLUK": "eticaret bilgi ve kullanım zorluğu"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_TESLIM_SURE": "eticaret teslimat süresi sorunu"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_ISLEM_UCRET": "eticaret işlem ve ücret sorunu"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_HASARLI_URUN": "eticaret hasarlı veya yanlış ürün sorunu"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_GUVENLIK_KAYGI": "eticaret güvenlik ve gizlilik kaygısı"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_SIKAYET": "eticaret şikayet ve iade sorunu"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_ENGEL_YURTDISI": "eticaret yurt dışı alışveriş engeli"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_DIGER": "eticaret diğer sorunlar"}, inplace=True)
df.rename(columns={"ETICARET_SORUN_HIC": "eticaret sorun yaşamama"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_KREDIKARTI": "eticaret yapmama kredi kartı kullanmama"}, inplace=True)
df.rename(columns={"ETICARET_YAPMAMA_BASKASI": "eticaret yapmama başkasına yaptırma"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_DOSYA_KOPYALM": "dijital beceri dosya kopyalama"}, inplace=True)
df.rename(columns={"EYETENEK_YZLM_METIN_HAZRLM": "dijital beceri metin hazırlama"}, inplace=True)

In [29]:
df.rename(columns={"MOBIL_INT_CEP": "cep telefonu ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_TASINABILIR": "dizüstü bilgisayar ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_TABLET": "tablet ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_DIGER_CIHAZ": "diğer cihazlar ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_HIC": "internet erişimi için cihaz kullanmıyor"}, inplace=True)

In [30]:
df.rename(columns={"SON_KULLANIM_BILGISAYAR": "bilgisayar son kullanım zamanı"}, inplace=True)
df.rename(columns={"KULLANIM_SIKLIK_BILGISAYAR": "bilgisayar kullanım sıklığı"}, inplace=True)
df.rename(columns={"FERT_INT_TASINABILIR": "dizüstü bilgisayar ile internet kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_KULLANICI_AD_SFR": "internet güvenliği için kullanıcı adı ve şifre kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_SOSMEDYA_HESAP_SFR": "internet güvenliği için sosyal medya hesaplarında şifre kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_TEKKUL_SFR": "internet güvenliği için tek kullanımlık şifre kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_EIMZA": "internet güvenliği için eimza kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_CEP_SMS_SFR": "internet güvenliği için cep telefonu sms ile şifre doğrulama"}, inplace=True)
df.rename(columns={"E_BLG_TNM_TEKKUL_SFR_KUPON": "internet güvenliği için tek kullanımlık şifre kuponu kullanımı"}, inplace=True)
df.rename(columns={"E_BLG_TNM_DIGER": "internet güvenliği için diğer yöntemler"}, inplace=True)
df.rename(columns={"ISYERI_BT_KULLANIM": "işyerinde bilişim teknolojileri kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_URT_STOK_BT_KULLANIM": "işyerinde üretim ve stok için bilişim teknolojileri kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_EPOSTA": "işyerinde e-posta kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_EDOKUMAN": "işyerinde elektronik doküman kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_SOSMEDYA": "işyerinde sosyal medya kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_UYG_KUL": "işyerinde uygulama kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_OZL_YZL_KUL": "işyerinde özel yazılım kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_FAAL_BLGISLEM_GLS": "işyerinde bilişim işlemlerinin gelişmiş kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_NDN_GRV_DEGSM": "işyerinde görev değişimi için internet kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_YENI_OGRN_ZRN": "işyerinde yeni bilgi öğrenme amacıyla internet kullanımı"}, inplace=True)
df.rename(columns={"ISYERI_BT_YETERLILIK": "işyerinde bilişim teknolojileri kullanım yeterliliği"}, inplace=True)
df.rename(columns={"EVDEN_CALISMA": "evden çalışma durumu"}, inplace=True)
df.rename(columns={"EYETENEK_UCRTSZ_ONLINE_KSL_CAL": "dijital beceri ücretsiz online kurs katılım"}, inplace=True)
df.rename(columns={"EYETENEK_UCRT_EGTPRG_KENDI": "dijital beceri ücretli eğitim programı bireysel katılım"}, inplace=True)
df.rename(columns={"EYETENEK_KAMU_UCRTSZ_KURS_KTLM": "dijital beceri kamu tarafından ücretsiz kurs katılım"}, inplace=True)
df.rename(columns={"EYETENEK_UCRT_EGTPRG_ISYERI": "dijital beceri işyeri tarafından eğitim programı katılım"}, inplace=True)
df.rename(columns={"EYETENEK_IS_EGTM_KTLM": "dijital beceri iş ile ilgili eğitim katılım"}, inplace=True)

In [31]:
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi kapsam dışı"}, inplace=True)
df.rename(columns={"MOBIL_INT_CEP_SEBEKE": "cep telefonu şebekesi ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_CEP_KBLSUZ": "cep telefonu kablosuz bağlantı ile internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_TASINABILIR_3G": "taşınabilir bilgisayar ile mobil şebeke internet kullanımı"}, inplace=True)
df.rename(columns={"MOBIL_INT_TASINABILIR_KBLSUZ": "taşınabilir bilgisayar ile kablosuz internet kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_ONLINE_SAGLIK": "online sağlık hizmeti kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_GRUBA_KATILIM": "internet ortamında gruplara katılım"}, inplace=True)
df.rename(columns={"INT_FAAL_SEYAHAT_ISLEM": "online seyahat ve konaklama işlemleri"}, inplace=True)
df.rename(columns={"EDEVLET_FORM_GNDRMM_EIMZA_SRN": "edevlet form gönderiminde eimza sorunu"}, inplace=True)
df.rename(columns={"ETICARET_YURTDISI_FIZIKIESYA": "eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_YURTDISI_WEBSITE_URUN": "eticaret yurt dışı web sitelerinden dijital ürün alışverişi"}, inplace=True)
df.rename(columns={"ETICARET_YURTDISI_TATIL_KONAK": "eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı"}, inplace=True)
df.rename(columns={"ETICARET_YURTDISI_DIGER": "eticaret yurt dışı web sitelerinden diğer alışverişler"}, inplace=True)
df.rename(columns={"IBBS_1":"istatistiki bölge birimleri sınıflaması(Düzey 1)"}, inplace=True)

In [32]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [33]:
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,ürün hizmet arama,websitesinde içerik paylaşma,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,NaN,5.0,1.0,NaN,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,NaN,5.0,3.0,NaN,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2169,012791"

In [34]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2017temizfertbilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2017temizfertbilişim.csv")
aa.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,ürün hizmet arama,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 38,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,NaN,5.0,1.0,NaN,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,NaN,5.0,3.0,NaN,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,6.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2169,012791"