In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2017.csv", sep = ";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,...,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15490 entries, 0 to 15489
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   15490 non-null  int64
 1   BULTEN_NO                      15490 non-null  int64
 2   CEVAPLILIK_DURUM               15490 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           13487 non-null  float64
 4   MEKTUP_BROSUR                  13487 non-null  float64
 5   BT_BILG_MASAUSTU               12781 non-null  float64
 6   BT_BILG_TASINABILIR            12781 non-null  float64
 7   BT_TABLET                      12781 non-null  float64
 8   BT_TEL_CEP                     12781 non-null  float64
 9   BT_OYUNKONSOL                  12781 non-null  float64
 10  BT_TEL_SABIT                   12781 non-null  float64
 11  BT_FOTOGRAF_KAMERA             12781 non-null  float64
 12  BT_DVD_VCD_OYNATICI            12781 non-null  float64
 13  BT_INTBAGLANAN_TV              12781 non-null  float64
 14  BT_DIGER                       12781 non-null  float64
 15  HANE_BILGISAYAR_KULLANIM       12781 non-null  float64
 16  HANE_INTERNET_ERISIM_DURUMU    12781 non-null  float64
 17  HANE_INTERNET_ERISIM_KULLANIM  9888 non-null   float64
 18  INT_BAGLANMA_MASAUSTU          9888 non-null   float64
 19  INT_BAGLANMA_TASINABILIR       9888 non-null   float64
 20  INT_BAGLANMA_TABLET            9888 non-null   float64
 21  INT_BAGLANMA_TEL_CEP           9888 non-null   float64
 22  INT_BAGLANMA_DIGER_CIHAZ       9888 non-null   float64
 23  INT_BAGLANMA_TV                9888 non-null   float64
 24  INT_BAGLANTI_SABIT_GENIS       9888 non-null   float64
 25  INT_BAGLANTI_MOBIL_GENIS       9888 non-null   float64
 26  INT_BAGLANTI_CEVIRMELI_ISDN    9888 non-null   float64
 27  INT_BAGLANTI_TEL_DARBANT       9888 non-null   float64
 28  INT_BAGLANMAMA_BASKAYER        2865 non-null   float64
 29  INT_BAGLANMAMA_GEREKYOK        2865 non-null   float64
 30  INT_BAGLANMAMA_FIYAT_CIHAZ     2865 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_BAGLANTI  2865 non-null   float64
 32  INT_BAGLANMAMA_BILMEME         2865 non-null   float64
 33  INT_BAGLANMAMA_GIZLILIK        2865 non-null   float64
 34  INT_BAGLANMAMA_IMKAN_YOK       2865 non-null   float64
 35  INT_BAGLANMAMA_ENGEL           2865 non-null   float64
 36  INT_BAGLANMAMA_DIGER           2865 non-null   float64
 37  HHB                            13487 non-null  float64
 38  HANE_GELIR_AYLIK               12781 non-null  float64
 39  IBBS_1                         15490 non-null  str
 40  HANE_FAKTOR                    13487 non-null  str
dtypes: float64(36), int64(3), str(2)
memory usage: 4.8 MB

In [4]:
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_TEL_SABIT,BT_FOTOGRAF_KAMERA,BT_DVD_VCD_OYNATICI,BT_INTBAGLANAN_TV,BT_DIGER,HANE_BILGISAYAR_KULLANIM,HANE_INTERNET_ERISIM_DURUMU,HANE_INTERNET_ERISIM_KULLANIM,INT_BAGLANMA_MASAUSTU,INT_BAGLANMA_TASINABILIR,INT_BAGLANMA_TABLET,INT_BAGLANMA_TEL_CEP,INT_BAGLANMA_DIGER_CIHAZ,INT_BAGLANMA_TV,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,INT_BAGLANMAMA_BASKAYER,INT_BAGLANMAMA_GEREKYOK,INT_BAGLANMAMA_FIYAT_CIHAZ,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)

In [10]:
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)

In [11]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15485,2017,254510,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1400.0,TRC,"1354,453276"
15486,2017,254610,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,1000.0,TRC,"2112,420995"
15487,2017,254710,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,1400.0,TRC,"1948,374117"
15488,2017,254810,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,1400.0,TRC,"2817,960304"
15489,2017,254910,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,8.0,300.0,TRC,"2953,635066"

In [12]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

# 2017 yılı crosss tabloları

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,6179,49.74,2086,38.08
erkek,6244,50.26,3392,61.92
toplam,12423,100.00,5478,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,104,43.33,2396,45.29
erkek,136,56.67,2894,54.71
toplam,240,100.00,5290,100.00

In [2]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 1]
    yok_df = alt_df[alt_df["online sağlık hizmeti kullanımı"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2017,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2017 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["online sağlık hizmeti kullanımı"] == 1]
toplam_yok = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2017= pd.concat(
    [gelir_online_saglik_2017, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_21080\496887858.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,1,52.11,47.89,1021,39.79,60.21,847
1,2017,2,49.94,50.06,1818,37.63,62.37,1225
2,2017,3,51.34,48.66,2462,35.40,64.60,1195
3,2017,4,48.72,51.28,3231,39.10,60.90,1271
4,2017,5,48.86,51.14,3891,39.15,60.85,940
5,2017,frekans,6179.00,6244.00,12423,2086.00,3392.00,5478

In [2]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_9724\100049498.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,41.67,58.33,12,50.20,49.80,255
1,2015,2,32.14,67.86,28,46.24,53.76,545
2,2015,3,45.16,54.84,31,45.80,54.20,882
3,2015,4,32.56,67.44,43,44.98,55.02,1365
4,2015,5,49.21,50.79,126,44.49,55.51,2243
5,2015,toplam,104.00,136.00,240,2396.00,2894.00,5290

In [2]:
# =========================================================
# YAŞ GRUBU x ONLINE SAĞLIK HİZMETİ KULLANIMI
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUBU OLUŞTUR
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ONLINE SAĞLIK HİZMETİ KULLANIMI VAR
    online_var = alt[
        alt["online sağlık hizmeti kullanımı"] == 1
    ]

    online_var_cinsiyet = (
        online_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ONLINE SAĞLIK HİZMETİ KULLANIMI YOK
    online_yok = alt[
        alt["online sağlık hizmeti kullanımı"] == 2
    ]

    online_yok_cinsiyet = (
        online_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2015,

        "yaş": yas,

        # VAR
        "var kadın":
            round(online_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(online_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(online_var),

        # YOK
        "yok kadın":
            round(online_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(online_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(online_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "yaş": "toplam",

    "var kadın":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["online sağlık hizmeti kullanımı"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 1]),

    "yok kadın":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["online sağlık hizmeti kullanımı"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["online sağlık hizmeti kullanımı"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_online_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_online_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24556\3050251590.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,15-30,53.39,46.61,5005,38.70,61.30,2173
1,2015,31-45,50.18,49.82,5058,40.20,59.80,1898
2,2015,46-60,41.93,58.07,2013,34.30,65.70,1172
3,2015,60+,36.02,63.98,347,34.04,65.96,235
4,2015,toplam,6179.00,6244.00,12423,2086.00,3392.00,5478

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_1920\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,47.54,52.46,61,49.79,50.21,2579
1,2024,31-45,43.31,56.69,127,43.73,56.27,2113
2,2024,46-60,40.00,60.00,45,31.81,68.19,547
3,2024,60+,28.57,71.43,7,27.45,72.55,51
4,2024,toplam,104.00,136.00,240,2396.00,2894.00,5290

In [6]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # VAR
    var_df = temp[temp["online sağlık hizmeti kullanımı"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = temp[temp["online sağlık hizmeti kullanımı"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["online sağlık hizmeti kullanımı"] == 1]
yok_all = df[df["online sağlık hizmeti kullanımı"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_online_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_online_2017)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,58.45,41.55,2320,45.22,54.78,2030
1,2017,ortaokul/lise,48.56,51.44,6406,33.61,66.39,2865
2,2017,üniversite,46.45,53.55,3649,35.48,64.52,575
3,2017,üniversiteüstü,35.42,64.58,48,12.50,87.50,8
4,2017,toplam,6179.00,6244.00,12423,2086.00,3392.00,5478

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_10076\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_10076\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,11,14,25,201,172,373
1,2025,ortaokul/lise,35,62,97,1167,1442,2609
2,2025,üniversite,56,59,115,1014,1253,2267
3,2025,üniversiteüstü,2,1,3,14,27,41
4,,toplam,104,136,240,2396,2894,5290

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [2]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_9452\3164738277.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_label"] = df["cinsiyet"].replace({

  cinsiyet  toplam   yüzde
0    Erkek   22487   49.32
1    Kadın   23104   50.68
2   Toplam   45591  100.00

In [3]:
import pandas as pd
import numpy as np

gelir_col = "hane gelir aylık"  # gerekirse burayı değiştir

df["gelir_raw"] = (
    df[gelir_col]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .str.extract(r"(\d+\.?\d*)")[0]
)

df["gelir_raw"] = pd.to_numeric(df["gelir_raw"], errors="coerce")

print(df["gelir_raw"].isna().sum())
print(df["gelir_raw"].describe())

temiz = df[df["gelir_raw"].notna()].copy()

temiz["gelir_5li_esit"] = pd.qcut(
    temiz["gelir_raw"].rank(method="first"),
    q=5,
    labels=["1. grup", "2. grup", "3. grup", "4. grup", "5. grup"]
)

df.loc[temiz.index, "gelir_5li_esit"] = temiz["gelir_5li_esit"]

gelir_tablo = pd.DataFrame({
    "toplam": df["gelir_5li_esit"].value_counts().sort_index(),
    "yüzde": round(df["gelir_5li_esit"].value_counts(normalize=True).sort_index() * 100, 2)
})

gelir_tablo.loc["toplam"] = [gelir_tablo["toplam"].sum(), 100]

display(gelir_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_9452\1670307786.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_raw"] = (

904
count    44687.000000
mean      2577.989057
std       2245.871733
min          1.000000
25%       1400.000000
50%       2000.000000
75%       3000.000000
max      60000.000000
Name: gelir_raw, dtype: float64

C:\Users\dilara\AppData\Local\Temp\ipykernel_9452\1670307786.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[temiz.index, "gelir_5li_esit"] = temiz["gelir_5li_esit"]

                toplam  yüzde
gelir_5li_esit
1. grup           8938   20.0
2. grup           8937   20.0
3. grup           8937   20.0
4. grup           8937   20.0
5. grup           8938   20.0
toplam           44687  100.0

In [4]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_9452\3341891636.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

                toplam   yüzde
ilkokulvealtı    13891   47.31
ortaokul/lise    11025   37.55
üniversite        3999   13.62
üniversiteüstü     444    1.51
toplam           29359  100.00

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_9452\1794991821.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

        toplam   yüzde
15-30    10520   23.07
31-45    10079   22.11
46-60     7991   17.53
60+      17001   37.29
toplam   45591  100.00

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [4]:
df["eğitim"].value_counts()

eğitim
2.0     9632
3.0     5564
4.0     5461
1.0     4259
51.0    3999
52.0     387
53.0      57
Name: count, dtype: int64

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT MODEL (2017)
# Bağımlı değişken:
# Online sağlık hizmeti kullanımı
#
# Referans Gruplar:
# Cinsiyet -> Erkek
# Yaş -> 15-30
# Eğitim -> İlkokul ve altı
# =====================================================

# -----------------------------------------------------
# 1) ONLINE SAĞLIK HİZMETİ KULLANIMI
# -----------------------------------------------------

df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1,
    "Hayır": 0,
    "evet": 1,
    "hayır": 0,
    1: 1,
    2: 0,
    0: 0
})

# -----------------------------------------------------
# 2) CİNSİYET
# Erkek = 0
# Kadın = 1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    "erkek": 0,
    "kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# 3) YAŞ KATEGORİLERİ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(
    df["yaş"],
    errors="coerce"
)

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=[
        "15-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas"
)

# REFERANS YAŞ GRUBU
yas_dummy = yas_dummy.drop(
    columns=["yas_15-30"],
    errors="ignore"
)

# -----------------------------------------------------
# 4) EĞİTİM KATEGORİLERİ (2017 yapısı)
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(
    df["eğitim"],
    errors="coerce"
)

def egitim_kategori(x):

    # REFERANS GRUP
    if x in [1]:
        return "Ilkokul_ve_alti"

    elif x in [2, 3, 4]:
        return "Orta_Lise"

    elif x in [51, 52]:
        return "Universite"

    elif x == 53:
        return "Doktora"

    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(
    egitim_kategori
)

egitim_dummy = pd.get_dummies(
    df["egitim_grup"],
    prefix="egitim"
)

# REFERANS EĞİTİM GRUBU
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# -----------------------------------------------------
# 5) GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

# LOG GELİR
df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# 6) MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "online_saglik",
                "cinsiyet_kadin",
                "log_gelir"
            ]
        ],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# 7) TÜM DEĞİŞKENLERİ SAYISALA ÇEVİR
# -----------------------------------------------------

model_df = model_df.apply(
    pd.to_numeric,
    errors="coerce"
)

# Eksik gözlemleri sil
model_df = model_df.dropna()

# -----------------------------------------------------
# 8) X ve y
# -----------------------------------------------------

y = model_df["online_saglik"]

X = model_df.drop(
    columns=["online_saglik"]
)

# CONSTANT
X = sm.add_constant(X)

# FLOAT
X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# 9) KONTROLLER
# -----------------------------------------------------

print("Modelde kullanılan gözlem sayısı:")
print(len(model_df))

print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nModel değişkenleri:")
print(X.columns)

# -----------------------------------------------------
# 10) PROBIT MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# 11) SONUÇLAR
# -----------------------------------------------------

summary_text = result.summary().as_text()

print(summary_text)

C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:49: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:54: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:80: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:103: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:122: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_20392\548043260.py:128: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

Modelde kullanılan gözlem sayısı:
17901

Bağımlı değişken dağılımı:
online_saglik
1.0    12423
0.0     5478
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Doktora', 'egitim_Orta_Lise', 'egitim_Universite'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.573358
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                17901
Model:                         Probit   Df Residuals:                    17892
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.06904
Time:                        19:29:10   Log-Likelihood:                -10264.
converged:                       True   LL-Null:                       -11025.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.2655      0.139    -16.327      0.000      -2.537      -1.994
cinsiyet_kadin        0.3018      0.021     14.657      0.000       0.261       0.342
log_gelir             0.2551      0.017     15.251      0.000       0.222       0.288
yas_31-45             0.0453      0.023      1.963      0.050    6.64e-05       0.090
yas_46-60            -0.2226      0.029     -7.777      0.000      -0.279      -0.166
yas_60+              -0.3870      0.057     -6.832      0.000      -0.498      -0.276
egitim_Doktora        1.0658      0.223      4.772      0.000       0.628       1.504
egitim_Orta_Lise      0.5873      0.063      9.372      0.000       0.464       0.710
egitim_Universite     1.1829      0.067     17.537      0.000       1.051       1.315
=====================================================================================

In [3]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                17901
Model:                         Probit   Df Residuals:                    17892
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.06904
Time:                        19:29:14   Log-Likelihood:                -10264.
converged:                       True   LL-Null:                       -11025.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.2655      0.139    -16.327      0.000      -2.537      -1.994
cinsiyet_kadin        0.3018      0.021     14.657      0.000       0.261       0.342
log_gelir             0.2551      0.017     15.251      0.000       0.222       0.288
yas_31-45             0.0453      0.023      1.963      0.050    6.64e-05       0.090
yas_46-60            -0.2226      0.029     -7.777      0.000      -0.279      -0.166
yas_60+              -0.3870      0.057     -6.832      0.000      -0.498      -0.276
egitim_Doktora        1.0658      0.223      4.772      0.000       0.628       1.504
egitim_Orta_Lise      0.5873      0.063      9.372      0.000       0.464       0.710
egitim_Universite     1.1829      0.067     17.537      0.000       1.051       1.315
=====================================================================================

In [3]:
df["eğitim"].value_counts()

eğitim
2.0     9632
3.0     5564
4.0     5461
1.0     4259
51.0    3999
52.0     387
53.0      57
Name: count, dtype: int64

In [7]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT MODEL
# Bağımlı değişken: Online sağlık hizmeti kullanımı
#
# Referans Gruplar:
# Cinsiyet -> Erkek
# Yaş -> 15-30
# Eğitim -> İlkokul ve altı
# =====================================================

# 1) ONLINE SAĞLIK
df["online_saglik"] = df["online sağlık hizmeti kullanımı"].replace({
    "Evet": 1, "Hayır": 0,
    "evet": 1, "hayır": 0,
    "EVET": 1, "HAYIR": 0,
    1: 1, 2: 0, 0: 0
})

# 2) CİNSİYET
df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0, "Kadın": 1,
    "erkek": 0, "kadın": 1,
    "ERKEK": 0, "KADIN": 1,
    1: 0, 2: 1
})

# 3) YAŞ KATEGORİLERİ
df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(df["yas_grup"], prefix="yas")
yas_dummy = yas_dummy.drop(columns=["yas_15-30"], errors="ignore")

# 4) EĞİTİM KATEGORİLERİ
df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):
    if x in [1]:
        return "Ilkokul_ve_alti"
    elif x in [2, 3, 4]:
        return "Orta_Lise"
    elif x in [51, 52, 53]:
        return "Universite_ve_ustu"
    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

egitim_dummy = pd.get_dummies(df["egitim_grup"], prefix="egitim")

# Referans eğitim: İlkokul ve altı
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# 5) GELİR
df["gelir"] = pd.to_numeric(df["hane gelir aylık"], errors="coerce")
df["log_gelir"] = np.log1p(df["gelir"])

# 6) MODEL DATAFRAME
model_df = pd.concat(
    [
        df[["online_saglik", "cinsiyet_kadin", "log_gelir"]],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# 7) SAYISALA ÇEVİR VE TEMİZLE
model_df = model_df.apply(pd.to_numeric, errors="coerce")
model_df = model_df.dropna()

# 8) X ve y
y = model_df["online_saglik"]
X = model_df.drop(columns=["online_saglik"])

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# 9) KONTROLLER
print("Modelde kullanılan gözlem sayısı:", len(model_df))

print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nEğitim grubu dağılımı:")
print(df["egitim_grup"].value_counts(dropna=False))

print("\nModel değişkenleri:")
print(X.columns)

# 10) PROBIT MODEL
probit_model = sm.Probit(y, X)
result = probit_model.fit()

print(result.summary().as_text())

# 11) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

Modelde kullanılan gözlem sayısı: 17901

Bağımlı değişken dağılımı:
online_saglik
1.0    12423
0.0     5478
Name: count, dtype: int64

Eğitim grubu dağılımı:
egitim_grup
Orta_Lise             20657
NaN                   16232
Universite_ve_ustu     4443
Ilkokul_ve_alti        4259
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Orta_Lise', 'egitim_Universite_ve_ustu'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.573366
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                17901
Model:                         Probit   Df Residuals:                    17893
Method:                           MLE   Df Model:                            7
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.06902
Time:                        19:38:07   Log-Likelihood:                -10264.
converged:                       True   LL-Null:                       -11025.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -2.2620      0.139    -16.319      0.000      -2.534      -1.990
cinsiyet_kadin                0.3020      0.021     14.666      0.000       0.262       0.342
log_gelir                     0.2546      0.017     15.244      0.000       0.222       0.287
yas_31-45                     0.0450      0.023      1.953      0.051      -0.000       0.090
yas_46-60                    -0.2228      0.029     -7.787      0.000      -0.279      -0.167
yas_60+                      -0.3878      0.057     -6.848      0.000      -0.499      -0.277
egitim_Orta_Lise              0.5874      0.063      9.374      0.000       0.465       0.710
egitim_Universite_ve_ustu     1.1818      0.067     17.529      0.000       1.050       1.314
=============================================================================================
       Probit Marginal Effects
=====================================
Dep. Variable:          online_saglik
Method:                          dydx
At:                           overall
=============================================================================================
                               dy/dx    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
cinsiyet_kadin                0.0983      0.007     14.913      0.000       0.085       0.111
log_gelir                     0.0829      0.005     15.511      0.000       0.072       0.093
yas_31-45                     0.0147      0.008      1.954      0.051   -4.57e-05       0.029
yas_46-60                    -0.0726      0.009     -7.824      0.000      -0.091      -0.054
yas_60+                      -0.1263      0.018     -6.873      0.000      -0.162      -0.090
egitim_Orta_Lise              0.1913      0.020      9.447      0.000       0.152       0.231
egitim_Universite_ve_ustu     0.3849      0.021     17.959      0.000       0.343       0.427
=============================================================================================

In [8]:
# 10) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          online_saglik
Method:                          dydx
At:                           overall
=============================================================================================
                               dy/dx    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
cinsiyet_kadin                0.0983      0.007     14.913      0.000       0.085       0.111
log_gelir                     0.0829      0.005     15.511      0.000       0.072       0.093
yas_31-45                     0.0147      0.008      1.954      0.051   -4.57e-05       0.029
yas_46-60                    -0.0726      0.009     -7.824      0.000      -0.091      -0.054
yas_60+                      -0.1263      0.018     -6.873      0.000      -0.162      -0.090
egitim_Orta_Lise              0.1913      0.020      9.447      0.000       0.152       0.231
egitim_Universite_ve_ustu     0.3849      0.021     17.959      0.000       0.343       0.427
=============================================================================================

In [5]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                17901
Model:                         Probit   Df Residuals:                    17893
Method:                           MLE   Df Model:                            7
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.06902
Time:                        19:29:23   Log-Likelihood:                -10264.
converged:                       True   LL-Null:                       -11025.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -2.2620      0.139    -16.319      0.000      -2.534      -1.990
cinsiyet_kadin                0.3020      0.021     14.666      0.000       0.262       0.342
log_gelir                     0.2546      0.017     15.244      0.000       0.222       0.287
yas_31-45                     0.0450      0.023      1.953      0.051      -0.000       0.090
yas_46-60                    -0.2228      0.029     -7.787      0.000      -0.279      -0.167
yas_60+                      -0.3878      0.057     -6.848      0.000      -0.499      -0.277
egitim_Orta_Lise              0.5874      0.063      9.374      0.000       0.465       0.710
egitim_Universite_ve_ustu     1.1818      0.067     17.529      0.000       1.050       1.314
=============================================================================================

In [6]:
# 10) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          online_saglik
Method:                          dydx
At:                           overall
=============================================================================================
                               dy/dx    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
cinsiyet_kadin                0.0983      0.007     14.913      0.000       0.085       0.111
log_gelir                     0.0829      0.005     15.511      0.000       0.072       0.093
yas_31-45                     0.0147      0.008      1.954      0.051   -4.57e-05       0.029
yas_46-60                    -0.0726      0.009     -7.824      0.000      -0.091      -0.054
yas_60+                      -0.1263      0.018     -6.873      0.000      -0.162      -0.090
egitim_Orta_Lise              0.1913      0.020      9.447      0.000       0.152       0.231
egitim_Universite_ve_ustu     0.3849      0.021     17.959      0.000       0.343       0.427
=============================================================================================

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 2 - PROBIT MODEL
# Bağımlı değişken: E-ticaretten ilaç alışverişi
# Gelir değişkeni: hane gelir aylık
# =====================================================

# 1) BAĞIMLI DEĞİŞKEN
df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1, "Hayır": 0,
    "evet": 1, "hayır": 0,
    "EVET": 1, "HAYIR": 0,
    1: 1,
    2: 0,
    0: 0
})

# 2) CİNSİYET
df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0, "Kadın": 1,
    "erkek": 0, "kadın": 1,
    "ERKEK": 0, "KADIN": 1,
    1: 0,
    2: 1
})

# 3) YAŞ KATEGORİLERİ
df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(df["yas_grup"], prefix="yas")
yas_dummy = yas_dummy.drop(columns=["yas_15-30"], errors="ignore")

# 4) EĞİTİM KATEGORİLERİ
df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):
    if x in [0, 1]:
        return "Ilkokul_ve_alti"
    elif x in [2, 3]:
        return "Orta_Lise"
    elif x in [4, 5, 6]:
        return "Universite"
    elif x == 7:
        return "Doktora"
    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

egitim_dummy = pd.get_dummies(df["egitim_grup"], prefix="egitim")
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# 5) GELİR
df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# 6) MODEL DATAFRAME
model_df = pd.concat(
    [
        df[["eticaret_ilac", "cinsiyet_kadin", "log_gelir"]],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# 7) SAYISALA ÇEVİR VE TEMİZLE
model_df = model_df.apply(pd.to_numeric, errors="coerce")

print("Dropna öncesi satır sayısı:", len(model_df))
print("\nEksik değer sayıları:")
print(model_df.isna().sum())

model_df = model_df.dropna()

print("\nDropna sonrası satır sayısı:", len(model_df))

# 8) X ve y
y = model_df["eticaret_ilac"]
X = model_df.drop(columns=["eticaret_ilac"])

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# 9) KONTROLLER
print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nEğitim grubu dağılımı:")
print(df["egitim_grup"].value_counts(dropna=False))

print("\nGelir dağılımı:")
print(df["gelir"].value_counts(dropna=False).head(20))

print("\nModel değişkenleri:")
print(X.columns)

# 10) PROBIT MODEL
probit_model = sm.Probit(y, X)
result = probit_model.fit()

print(result.summary().as_text())

Dropna öncesi satır sayısı: 45591

Eksik değer sayıları:
eticaret_ilac        40061
cinsiyet_kadin           0
log_gelir              904
yas_31-45                0
yas_46-60                0
yas_60+                  0
egitim_Orta_Lise         0
egitim_Universite        0
dtype: int64

Dropna sonrası satır sayısı: 5530

Bağımlı değişken dağılımı:
eticaret_ilac
0.0    5290
1.0     240
Name: count, dtype: int64

Eğitim grubu dağılımı:
egitim_grup
NaN                20675
Orta_Lise          15196
Universite          5461
Ilkokul_ve_alti     4259
Name: count, dtype: int64

Gelir dağılımı:
gelir
2000.0     4967
1500.0     4300
3000.0     4197
1400.0     3860
2500.0     2883
1000.0     2719
4000.0     2080
5000.0     1662
3500.0     1522
1300.0     1257
500.0       949
NaN         904
6000.0      827
1200.0      780
1800.0      731
4500.0      702
2800.0      626
1700.0      607
1600.0      579
10000.0     482
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Orta_Lise', 'egitim_Universite'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.173099
         Iterations 7
                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 5530
Model:                         Probit   Df Residuals:                     5522
Method:                           MLE   Df Model:                            7
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.03081
Time:                        20:55:43   Log-Likelihood:                -957.24
converged:                       True   LL-Null:                       -987.67
Covariance Type:            nonrobust   LLR p-value:                 1.014e-10
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.0380      0.427     -4.770      0.000      -2.875      -1.200
cinsiyet_kadin        0.0119      0.062      0.193      0.847      -0.109       0.133
log_gelir             0.0080      0.051      0.157      0.875      -0.092       0.108
yas_31-45             0.4044      0.070      5.807      0.000       0.268       0.541
yas_46-60             0.5571      0.096      5.827      0.000       0.370       0.744
yas_60+               0.8199      0.220      3.731      0.000       0.389       1.251
egitim_Orta_Lise     -0.1138      0.088     -1.288      0.198      -0.287       0.059
egitim_Universite     0.0041      0.073      0.056      0.955      -0.139       0.148
=====================================================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:31: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:66: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_10100\4003249870.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

In [3]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 5530
Model:                         Probit   Df Residuals:                     5522
Method:                           MLE   Df Model:                            7
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.03081
Time:                        20:55:47   Log-Likelihood:                -957.24
converged:                       True   LL-Null:                       -987.67
Covariance Type:            nonrobust   LLR p-value:                 1.014e-10
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.0380      0.427     -4.770      0.000      -2.875      -1.200
cinsiyet_kadin        0.0119      0.062      0.193      0.847      -0.109       0.133
log_gelir             0.0080      0.051      0.157      0.875      -0.092       0.108
yas_31-45             0.4044      0.070      5.807      0.000       0.268       0.541
yas_46-60             0.5571      0.096      5.827      0.000       0.370       0.744
yas_60+               0.8199      0.220      3.731      0.000       0.389       1.251
egitim_Orta_Lise     -0.1138      0.088     -1.288      0.198      -0.287       0.059
egitim_Universite     0.0041      0.073      0.056      0.955      -0.139       0.148
=====================================================================================

In [4]:
# 10) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          eticaret_ilac
Method:                          dydx
At:                           overall
=====================================================================================
                       dy/dx    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
cinsiyet_kadin        0.0011      0.006      0.193      0.847      -0.010       0.012
log_gelir             0.0007      0.005      0.157      0.875      -0.008       0.010
yas_31-45             0.0362      0.006      5.640      0.000       0.024       0.049
yas_46-60             0.0499      0.009      5.665      0.000       0.033       0.067
yas_60+               0.0734      0.020      3.692      0.000       0.034       0.112
egitim_Orta_Lise     -0.0102      0.008     -1.286      0.198      -0.026       0.005
egitim_Universite     0.0004      0.007      0.056      0.955      -0.012       0.013
=====================================================================================

In [5]:
# =====================================================
# ETİCARET İLAÇ ALIŞVERİŞİ - PROBIT MODEL
# 2018 UYUMLU FINAL KOD
# =====================================================

import pandas as pd
import numpy as np
import statsmodels.api as sm

# -----------------------------------------------------
# BAĞIMLI DEĞİŞKEN
# ETİCARET İLAÇ ALIŞVERİŞİ
# -----------------------------------------------------

df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    "evet": 1,
    "hayır": 0,
    1: 1,
    2: 0,
    0: 0
})

# -----------------------------------------------------
# CİNSİYET
# Erkek = 0
# Kadın = 1
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    "erkek": 0,
    "kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# YAŞ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(
    df["yaş"],
    errors="coerce"
)

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=[
        "15-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas"
)

# REFERANS GRUP
yas_dummy = yas_dummy.drop(
    columns=["yas_15-30"],
    errors="ignore"
)

# -----------------------------------------------------
# EĞİTİM
# 2018 UYUMLU
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(
    df["eğitim"],
    errors="coerce"
)

def egitim_kategori(x):

    # REFERANS
    if x in [1, 2]:
        return "Ilkokul_ve_alti"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "Ortaokul_Lise"

    # ÜNİVERSİTE
    elif x in [51, 511, 512]:
        return "Universite"

    # ÜNİVERSİTEÜSTÜ
    elif x in [52, 53]:
        return "Universiteustu"

    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(
    egitim_kategori
)

egitim_dummy = pd.get_dummies(
    df["egitim_grup"],
    prefix="egitim"
)

# REFERANS:
# İlkokul ve altı

egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# -----------------------------------------------------
# GELİR
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hane gelir aylık"],
    errors="coerce"
)

# LOG GELİR
df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "eticaret_ilac",
                "cinsiyet_kadin",
                "log_gelir"
            ]
        ],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# TÜM DEĞİŞKENLERİ SAYISALA ÇEVİR
# -----------------------------------------------------

model_df = model_df.apply(
    pd.to_numeric,
    errors="coerce"
)

# -----------------------------------------------------
# EKSİK GÖZLEMLERİ SİL
# -----------------------------------------------------

model_df = model_df.dropna()

# -----------------------------------------------------
# X ve y
# -----------------------------------------------------

y = model_df["eticaret_ilac"]

X = model_df.drop(
    columns=["eticaret_ilac"]
)

# CONSTANT
X = sm.add_constant(X)

# FLOAT
X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# SONUÇLAR
# -----------------------------------------------------

summary_text = result.summary().as_text()

print(summary_text)

# -----------------------------------------------------
# MARJİNAL ETKİLER
# -----------------------------------------------------

Optimization terminated successfully.
         Current function value: 0.173157
         Iterations 7
                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 5530
Model:                         Probit   Df Residuals:                     5521
Method:                           MLE   Df Model:                            8
Date:                Sat, 16 May 2026   Pseudo R-squ.:                 0.03048
Time:                        16:07:28   Log-Likelihood:                -957.56
converged:                       True   LL-Null:                       -987.67
Covariance Type:            nonrobust   LLR p-value:                 4.227e-10
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -2.0588      0.410     -5.023      0.000      -2.862      -1.256
cinsiyet_kadin            0.0057      0.062      0.092      0.927      -0.115       0.127
log_gelir                 0.0174      0.052      0.334      0.739      -0.085       0.120
yas_31-45                 0.3867      0.071      5.421      0.000       0.247       0.527
yas_46-60                 0.5344      0.097      5.486      0.000       0.343       0.725
yas_60+                   0.8065      0.220      3.663      0.000       0.375       1.238
egitim_Ortaokul_Lise     -0.0965      0.113     -0.851      0.395      -0.319       0.126
egitim_Universite        -0.0568      0.117     -0.485      0.628      -0.286       0.173
egitim_Universiteustu     0.0315      0.160      0.198      0.843      -0.281       0.344
=========================================================================================

In [6]:
marginal = result.get_margeff()

print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          eticaret_ilac
Method:                          dydx
At:                           overall
=========================================================================================
                           dy/dx    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
cinsiyet_kadin            0.0005      0.006      0.092      0.927      -0.010       0.011
log_gelir                 0.0016      0.005      0.334      0.739      -0.008       0.011
yas_31-45                 0.0346      0.007      5.284      0.000       0.022       0.048
yas_46-60                 0.0479      0.009      5.350      0.000       0.030       0.065
yas_60+                   0.0723      0.020      3.625      0.000       0.033       0.111
egitim_Ortaokul_Lise     -0.0086      0.010     -0.850      0.395      -0.029       0.011
egitim_Universite        -0.0051      0.010     -0.485      0.628      -0.026       0.015
egitim_Universiteustu     0.0028      0.014      0.198      0.843      -0.025       0.031
=========================================================================================

In [1]:
import pandas as pd

fert = pd.read_csv(
    r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2017temizfertbilişim.csv"
)

hane = pd.read_csv(
    r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv"
)

In [2]:
df = fert.merge(
    hane,
    on="bülten no",
    how="left"
)

# Kontrol
print("Fert:", fert.shape)
print("Hane:", hane.shape)
print("Birleşmiş:", df.shape)

df.head()

Fert: (45591, 115)
Hane: (15490, 41)
Birleşmiş: (45591, 155)

,referans yıl_x,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [3]:
df[["yaş", "cinsiyet", "eğitim", "hane büyüklüğü", "hane gelir aylık"]].head(10)

   yaş  cinsiyet  eğitim  hane büyüklüğü  hane gelir aylık
0   11         1     NaN             4.0            5000.0
1   11         2     NaN             4.0            5000.0
2   34         2     2.0             4.0            5000.0
3   39         1     4.0             4.0            5000.0
4   17         1     3.0             3.0            2000.0
5   52         2     2.0             3.0            2000.0
6   53         1     2.0             3.0            2000.0
7   17         1     3.0             3.0            5000.0
8   36         2     4.0             3.0            5000.0
9   46         1     4.0             3.0            5000.0

In [4]:
import os

klasor = r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\düzeltilmiş2017birleşikveriler"
os.makedirs(klasor, exist_ok=True)

df.to_csv(
    klasor + r"\2017birlesmis.csv",
    index=False,
    encoding="utf-8-sig"
)

In [5]:
dff = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\birlesmis_veriler\2017birlesmis.csv")
dff.head()

,referans yıl_x,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [8]:
dff.rename(columns={"referans yıl_x": "referans yıl"}, inplace=True)

In [9]:
dff.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"

In [11]:
dff["istatistiki bölge birimleri sınıflaması (düzey 1)"].value_counts()

istatistiki bölge birimleri sınıflaması (düzey 1)
TR1    5344
TRC    5257
TR6    4750
TR3    4545
TR5    4141
TR4    3978
TRB    3624
TR8    3182
TR7    2918
TRA    2689
TR2    2609
TR9    2554
Name: count, dtype: int64

In [10]:
dff.to_csv(
    klasor + r"\2017ferthane.csv",
    index=False,
    encoding="utf-8-sig"
)

In [11]:
dff=pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\düzeltilmiş2017birleşikveriler\2017ferthane.csv")
dff.head()

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,...,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"