In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert_2017.csv" , sep=";")

df.head()

,REFERANS_YIL,BULTEN_NO,FERTNO,CEVAPLILIK_DURUM_FERT,KAPSAMICI_KAPSAMDISI,YAS,CINSIYET,OKUMA_YAZMA,OKUL_BITEN,CALISMA_DURUM,...,EYETENEK_BLGMOBIL_SISTEM_DEG,EYETENEK_YZLM_DOSYA_KOPYALM,EYETENEK_YZLM_METIN_HAZRLM,EYETENEK_YZLM_DOKUMN_OLSTRM,EYETENEK_YZLM_HZPRG_KULLNM,EYETENEK_YZLM_HZPRG_FORML,EYETENEK_YZLM_FOTO_VIDEO,EYETENEK_YZLM_KODYZM,IBBS_1,FERT_FAKTOR
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2169,012791"

In [3]:
df["BULTEN_NO"].value_counts()

BULTEN_NO
25303     25
22968     20
25306     19
25478     19
12605     18
          ..
243110     1
243410     1
247210     1
247510     1
253910     1
Name: count, Length: 13487, dtype: int64

In [4]:
df["REFERANS_YIL"].value_counts()

REFERANS_YIL
2017    45591
Name: count, dtype: int64

In [5]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [6]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [7]:
df.rename(columns={"FERTNO": "fert no"}, inplace=True)

In [8]:
df.head()

,referans yıl,bülten no,fert no,CEVAPLILIK_DURUM_FERT,KAPSAMICI_KAPSAMDISI,YAS,CINSIYET,OKUMA_YAZMA,OKUL_BITEN,CALISMA_DURUM,...,EYETENEK_BLGMOBIL_SISTEM_DEG,EYETENEK_YZLM_DOSYA_KOPYALM,EYETENEK_YZLM_METIN_HAZRLM,EYETENEK_YZLM_DOKUMN_OLSTRM,EYETENEK_YZLM_HZPRG_KULLNM,EYETENEK_YZLM_HZPRG_FORML,EYETENEK_YZLM_FOTO_VIDEO,EYETENEK_YZLM_KODYZM,IBBS_1,FERT_FAKTOR
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0
2,2017,10011,2,1.0,1,34,2,1.0,2.0,1.0,...,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,TR1,"2527,94537"
3,2017,10011,1,1.0,1,39,1,1.0,4.0,1.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2527,94537"
4,2017,10013,3,1.0,1,17,1,1.0,3.0,3.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,TR1,"2169,012791"