In [2]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert_2018.csv",
    sep=";",
    low_memory=False
)

df.head()

,REFERANS_YIL,BULTEN_NO,FERTNO,CEVAPLILIK_DURUM_FERT,YAS,CINSIYET,OKUMA_YAZMA,OKUL_BITEN,CALISMA_DURUM,CALISMA_SAHIP_IS,...,ISYERI_BT_YENI_OGRN_ZRN,ISYERI_BT_YETERLILIK,EVDEN_CALISMA,EVDEN_CALISMA_ISICIN_INT_KUL,EYETENEK_UCRTSZ_ONLINE_KSL_CAL,EYETENEK_UCRT_EGTPRG_KENDI,EYETENEK_KAMU_UCRTSZ_KURS_KTLM,EYETENEK_UCRT_EGTPRG_ISYERI,EYETENEK_IS_EGTM_KTLM,FAKTOR
0,2018,11058,1,1,19,1,1,4,3,2.0,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301"
1,2018,11058,4,1,16,1,1,3,3,2.0,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301"
2,2018,11325,2,1,34,1,1,2,1,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1749,850517"
3,2018,11863,4,1,22,1,1,51,1,NaN,...,2.0,1.0,90.0,NaN,2.0,2.0,2.0,2.0,2.0,"2848,618139"
4,2018,12096,1,1,27,1,1,4,1,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1775,022946"

In [3]:
df["BULTEN_NO"].value_counts()

BULTEN_NO
11645     9
20176     9
20235     9
24873     9
25713     9
         ..
25674     1
25681     1
25685     1
257110    1
25717     1
Name: count, Length: 12822, dtype: int64

In [4]:
df["REFERANS_YIL"].value_counts()

REFERANS_YIL
2018    28888
Name: count, dtype: int64

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [6]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [7]:
df.rename(columns={"FERTNO": "fert no"}, inplace=True)

In [8]:
df.head()

,referans yıl,bülten no,fert no,CEVAPLILIK_DURUM_FERT,YAS,CINSIYET,OKUMA_YAZMA,OKUL_BITEN,CALISMA_DURUM,CALISMA_SAHIP_IS,...,ISYERI_BT_YENI_OGRN_ZRN,ISYERI_BT_YETERLILIK,EVDEN_CALISMA,EVDEN_CALISMA_ISICIN_INT_KUL,EYETENEK_UCRTSZ_ONLINE_KSL_CAL,EYETENEK_UCRT_EGTPRG_KENDI,EYETENEK_KAMU_UCRTSZ_KURS_KTLM,EYETENEK_UCRT_EGTPRG_ISYERI,EYETENEK_IS_EGTM_KTLM,FAKTOR
0,2018,11058,1,1,19,1,1,4,3,2.0,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301"
1,2018,11058,4,1,16,1,1,3,3,2.0,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301"
2,2018,11325,2,1,34,1,1,2,1,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1749,850517"
3,2018,11863,4,1,22,1,1,51,1,NaN,...,2.0,1.0,90.0,NaN,2.0,2.0,2.0,2.0,2.0,"2848,618139"
4,2018,12096,1,1,27,1,1,4,1,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1775,022946"