In [ ]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HANE_2020.csv" , sep = ";")
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_INTBAGLANAN_TV,HANE_INTERNET_ERISIM_DURUMU,HANE_INTERNET_ERISIM_KULLANIM,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,HANE_GELIR_AYLIK,HHB,IBBS_1,HANE_FAKTOR
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15103 entries, 0 to 15102
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   15103 non-null  int64
 1   BULTEN_NO                      15103 non-null  int64
 2   CEVAPLILIK_DURUM               15103 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           15103 non-null  int64
 4   BT_BILG_MASAUSTU               14498 non-null  float64
 5   BT_BILG_TASINABILIR            14498 non-null  float64
 6   BT_TABLET                      14498 non-null  float64
 7   BT_TEL_CEP                     14498 non-null  float64
 8   BT_OYUNKONSOL                  14498 non-null  float64
 9   BT_INTBAGLANAN_TV              14498 non-null  float64
 10  HANE_INTERNET_ERISIM_DURUMU    14498 non-null  float64
 11  HANE_INTERNET_ERISIM_KULLANIM  12944 non-null  float64
 12  INT_BAGLANTI_SABIT_GENIS       12944 non-null  float64
 13  INT_BAGLANTI_MOBIL_GENIS       12944 non-null  float64
 14  INT_BAGLANTI_CEVIRMELI_ISDN    12944 non-null  float64
 15  INT_BAGLANTI_TEL_DARBANT       12945 non-null  float64
 16  HANE_GELIR_AYLIK               14475 non-null  float64
 17  HHB                            15103 non-null  int64
 18  IBBS_1                         15103 non-null  str
 19  HANE_FAKTOR                    14498 non-null  str
dtypes: float64(13), int64(5), str(2)
memory usage: 2.3 MB

In [6]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)

In [7]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15098,2020,27536,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,10000.0,1,TRC,"1983,882957"
15099,2020,27537,1,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,5000.0,6,TRC,"1481,139799"
15100,2020,27538,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,25000.0,1,TRC,"1753,479525"
15101,2020,27539,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,5750.0,7,TRC,"1895,510798"
15102,2020,275310,1,1,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,7000.0,8,TRC,"1833,591441"

In [8]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2020temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2020temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,...,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
2,2020,10011,3,1.0,27,2,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
3,2020,10012,1,1.0,51,1,1.0,4.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
4,2020,10012,2,1.0,48,2,1.0,2.0,3.0,2.0,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,7600,47.77,3812,43.07
erkek,8308,52.23,5039,56.93
toplam,15908,100.00,8851,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,251,50.2,3051,45.48
erkek,249,49.8,3657,54.52
toplam,500,100.0,6708,100.00

In [3]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["sağlık bilgisi arama"] == 1]
    yok_df = alt_df[alt_df["sağlık bilgisi arama"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2020,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2020 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["sağlık bilgisi arama"] == 1]
toplam_yok = df[df["sağlık bilgisi arama"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2020,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2020= pd.concat(
    [gelir_online_saglik_2020, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2020)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2020,1,47.47,52.53,1799,43.02,56.98,1734
1,2020,2,49.18,50.82,2633,41.92,58.08,1899
2,2020,3,47.50,52.50,3057,43.35,56.65,1954
3,2020,4,46.51,53.49,3926,43.65,56.35,1874
4,2020,5,48.36,51.64,4493,43.53,56.47,1390
5,2020,frekans,7600.00,8308.00,15908,3812.00,5039.00,8851

In [2]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,59.26,40.74,27,48.86,51.14,481
1,2015,2,66.67,33.33,24,49.87,50.13,798
2,2015,3,44.29,55.71,70,45.15,54.85,1123
3,2015,4,48.65,51.35,111,42.14,57.86,1742
4,2015,5,50.00,50.00,268,45.90,54.10,2564
5,2015,toplam,251.00,249.00,500,3051.00,3657.00,6708

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,51.65,48.35,5930,42.77,57.23,2595
1,2017,31-45,47.72,52.28,6310,44.02,55.98,2749
2,2017,46-60,42.72,57.28,3036,42.51,57.49,2658
3,2017,60+,36.23,63.77,632,42.64,57.36,849
4,2017,toplam,7600.00,8308.00,15908,3812.00,5039.00,8851

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,...,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
2,2020,10011,3,1.0,27,2,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
3,2020,10012,1,1.0,51,1,1.0,4.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
4,2020,10012,2,1.0,48,2,1.0,2.0,3.0,2.0,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,57.14,42.86,154,51.75,48.25,3061
1,2024,31-45,47.56,52.44,246,42.77,57.23,2675
2,2024,46-60,43.37,56.63,83,33.96,66.04,857
3,2024,60+,58.82,41.18,17,27.83,72.17,115
4,2024,toplam,251.00,249.00,500,3051.00,3657.00,6708

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,53.58,46.42,3072,50.59,49.41,4066
1,2017,ortaokul/lise,45.57,54.43,7900,36.62,63.38,3886
2,2017,üniversite,44.38,55.62,338,29.55,70.45,44
3,2017,üniversiteüstü,42.86,57.14,84,30.00,70.00,10
4,2017,toplam,7600.00,8308.00,15908,3812.00,5039.00,8851

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,...,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
2,2020,10011,3,1.0,27,2,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
3,2020,10012,1,1.0,51,1,1.0,4.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
4,2020,10012,2,1.0,48,2,1.0,2.0,3.0,2.0,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,13,11,24,220,262,482
1,2025,ortaokul/lise,65,88,153,1395,1781,3176
2,2025,üniversite,171,147,318,1413,1571,2984
3,2025,üniversiteüstü,2,3,5,23,43,66
4,,toplam,251,249,500,3051,3657,6708

In [3]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["randevu_alma"] == 1]

var_kadin = (var_df["cinsiyet"] == 2).sum()
var_erkek = (var_df["cinsiyet"] == 1).sum()
var_toplam = len(var_df)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["randevu_alma"] == 0]

yok_kadin = (yok_df["cinsiyet"] == 2).sum()
yok_erkek = (yok_df["cinsiyet"] == 1).sum()
yok_toplam = len(yok_df)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
#

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020       3728       4449        8177       7684       8898       16582

In [4]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["randevu_alma"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["randevu_alma"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      45.59      54.41        8177      46.34      53.66       16582

In [2]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# SAĞLIK SONUÇLARINI ALMA DEĞİŞKENİ
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["saglik_sonuc"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["saglik_sonuc"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      44.86      55.14        5900      46.48      53.52       18859

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,...,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
2,2020,10011,3,1.0,27,2,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
3,2020,10012,1,1.0,51,1,1.0,4.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
4,2020,10012,2,1.0,48,2,1.0,2.0,3.0,2.0,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"

In [8]:
import pandas as pd
import numpy as np

# =========================================================
# RANDEVU ALMA x GELİR
# HANE GELİR AYLIK → EN DÜŞÜKTEN YÜKSEĞE 5 EŞİT GRUP
# =========================================================

# Geliri küçükten büyüğe sırala
df = df.sort_values("hane gelir aylık").reset_index(drop=True)

# Satır sayısına göre 5 eşit gelir grubu oluştur
df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # RANDEVU VAR
    randevu_var = alt[
        alt["randevu alma (e-nabız,mhrs vb.)"] == 1
    ]

    randevu_var_cinsiyet = (
        randevu_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # RANDEVU YOK
    randevu_yok = alt[
        alt["randevu alma (e-nabız,mhrs vb.)"] == 2
    ]

    randevu_yok_cinsiyet = (
        randevu_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "gelir": gelir,

        "var kadın": round(randevu_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(randevu_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(randevu_var),

        "yok kadın": round(randevu_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(randevu_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(randevu_yok)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["randevu alma (e-nabız,mhrs vb.)"] == 1]
yok_all = df[df["randevu alma (e-nabız,mhrs vb.)"] == 2]

toplam_satiri = pd.DataFrame([{
    "gelir": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

gelir_randevu = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_randevu)

    gelir  var kadın  var erkek  var toplam  yok kadın  yok erkek  yok toplam
0       1      46.25      53.75         774      45.02      54.98        2759
1       2      45.21      54.79        1179      46.47      53.53        3353
2       3      46.04      53.96        1477      45.81      54.19        3534
3       4      43.59      56.41        2129      46.74      53.26        3671
4       5      46.94      53.06        2618      47.44      52.56        3265
5  toplam    3728.00    4449.00        8177    7684.00    8898.00       16582

In [9]:
df["gelir_grup"].value_counts()

gelir_grup
1    10004
3    10004
5    10004
2    10003
4    10003
Name: count, dtype: int64

In [7]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2020

# =========================================================
# DEĞİŞKENLER
# =========================================================
gelir_col = "hane gelir aylık"
saglik_col = "sağlık sonuçlarını almak"

# =========================================================
# GELİRİ NUMERİK YAP
# =========================================================
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# GELİRİ ZORLA 5 EŞİT GRUBA BÖL
# =========================================================
df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# kontrol
print(df["gelir_5li_esit"].value_counts().sort_index())


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df[saglik_col].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

for gelir in gelir_sirasi:

    alt = df[df["gelir_5li_esit"] == gelir]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "gelir_grubu": gelir,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "gelir_grubu": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

gelir_5li_esit
1. grup    9826
2. grup    9826
3. grup    9825
4. grup    9826
5. grup    9826
Name: count, dtype: int64

,yıllar,gelir_grubu,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2020,1. grup,46.51,53.49,430,45.27,54.73,3037
1,2020,2. grup,42.76,57.24,746,46.49,53.51,3672
2,2020,3. grup,45.53,54.47,1019,45.96,54.04,3888
3,2020,4. grup,43.29,56.71,1469,46.37,53.63,4179
4,2020,5. grup,46.01,53.99,2228,47.96,52.04,4047
5,,toplam,44.86,55.14,5900,46.48,53.52,18859

In [12]:
df["eğitim"].value_counts()

eğitim
2.0      10377
4.0       6772
3.0       6167
1.0       3714
512.0     3661
511.0     1786
52.0       383
53.0        95
Name: count, dtype: int64

In [14]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2020

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# RANDEVU ALMA
# =========================================================
df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["randevu"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["randevu"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["randevu"] == 1]
toplam_yok_df = df[df["randevu"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2020,ilkokulvealtı,48.38,51.62,1294,52.65,47.35,5844
1,2020,ortaokul/lise,43.59,56.41,3680,42.18,57.82,8106
2,2020,üniversite,47.22,52.78,2927,45.31,54.69,2432
3,2020,üniversiteüstü,42.03,57.97,276,43.00,57.00,200
4,,toplam,45.59,54.41,8177,46.34,53.66,16582

In [15]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2024

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512, 4, 5, 6]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53, 7]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,ilkokulvealtı,47.18,52.82,710,52.40,47.60,6428
1,2024,ortaokul/lise,42.47,57.53,2557,42.66,57.34,9229
2,2024,üniversite,46.82,53.18,2373,45.98,54.02,2986
3,2024,üniversiteüstü,44.23,55.77,260,40.28,59.72,216
4,,toplam,44.86,55.14,5900,46.48,53.52,18859

In [16]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================

df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["randevu"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["randevu"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["randevu"] == 1]

yok_df = df[df["randevu"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_6768\3536698121.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,52.36,47.64,3077,47.03,52.97,5448
1,2024,31-45,44.58,55.42,3302,47.75,52.25,5757
2,2024,46-60,37.20,62.80,1519,44.60,55.40,4175
3,2024,60+,28.67,71.33,279,42.51,57.49,1202
4,,toplam,45.59,54.41,8177,46.34,53.66,16582

In [17]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================

df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# CROSS TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["saglik_sonuc"] == 1]

yok_df = df[df["saglik_sonuc"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,51.77,48.23,2231,47.95,52.05,6294
1,2024,31-45,43.16,56.84,2440,47.86,52.14,6619
2,2024,46-60,37.29,62.71,1035,43.81,56.19,4659
3,2024,60+,27.32,72.68,194,41.80,58.20,1287
4,,toplam,44.86,55.14,5900,46.48,53.52,18859

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv")
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,...,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
2,2020,10011,3,1.0,27,2,1.0,512.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
3,2020,10012,1,1.0,51,1,1.0,4.0,1.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
4,2020,10012,2,1.0,48,2,1.0,2.0,3.0,2.0,...,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"

In [2]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

  cinsiyet  toplam   yüzde
0    Erkek   24824   49.63
1    Kadın   25194   50.37
2   Toplam   50018  100.00

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

        toplam   yüzde
15-30    11590   23.17
31-45    11031   22.05
46-60     9260   18.51
60+      18137   36.26
toplam   50018  100.00

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

                toplam   yüzde
ilkokulvealtı    14091   42.76
ortaokul/lise    12939   39.26
üniversite        5447   16.53
üniversiteüstü     478    1.45
toplam           32955  100.00

In [4]:
df["eğitim"].value_counts()

eğitim
2.0      10377
4.0       6772
3.0       6167
1.0       3714
512.0     3661
511.0     1786
52.0       383
53.0        95
Name: count, dtype: int64

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# GELİR DEĞİŞKENİ
# =========================================================

gelir_col = "hane gelir aylık"

# numerik yap
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# ZORLA EŞİT 5 GRUP
# =========================================================

df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

frekans = (
    df["gelir_5li_esit"]
    .value_counts()
    .reindex(gelir_sirasi)
)

yuzde = round(
    (
        df["gelir_5li_esit"]
        .value_counts(normalize=True)
        .reindex(gelir_sirasi)
    ) * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

gelir_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame({
    "toplam": [gelir_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

gelir_tablo = pd.concat(
    [gelir_tablo, toplam_satiri]
)

display(gelir_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

         toplam  yüzde
1. grup    9826   20.0
2. grup    9826   20.0
3. grup    9825   20.0
4. grup    9826   20.0
5. grup    9826   20.0
toplam    49129  100.0

In [7]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ
# =========================================================

def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # ilkokul ve altı
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ortaokul / lise
    elif x in [3, 4]:
        return "ortaokul/lise"

    # üniversite
    elif x in [511, 512]:
        return "üniversite"

    # üniversite üstü
    elif x in [52, 53]:
        return "üniversiteüstü"

    else:
        return np.nan

# =========================================================
# YENİ DEĞİŞKEN
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS
# =========================================================

print(df["egitim_grup"].value_counts())

# =========================================================
# YÜZDE + TOPLAM TABLOSU
# =========================================================

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = (
    df["egitim_grup"]
    .value_counts()
    .reindex(egitim_sirasi)
)

yuzde = round(
    (
        df["egitim_grup"]
        .value_counts(normalize=True)
        .reindex(egitim_sirasi)
    ) * 100,
    2
)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat(
    [egitim_tablo, toplam_satiri]
)

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

egitim_grup
ilkokulvealtı     14091
ortaokul/lise     12939
üniversite         5447
üniversiteüstü      478
Name: count, dtype: int64

                toplam   yüzde
ilkokulvealtı    14091   42.76
ortaokul/lise    12939   39.26
üniversite        5447   16.53
üniversiteüstü     478    1.45
toplam           32955  100.00