In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HANE_2020.csv" , sep = ";")
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_INTBAGLANAN_TV,HANE_INTERNET_ERISIM_DURUMU,HANE_INTERNET_ERISIM_KULLANIM,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,HANE_GELIR_AYLIK,HHB,IBBS_1,HANE_FAKTOR
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15103 entries, 0 to 15102
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   15103 non-null  int64
 1   BULTEN_NO                      15103 non-null  int64
 2   CEVAPLILIK_DURUM               15103 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           15103 non-null  int64
 4   BT_BILG_MASAUSTU               14498 non-null  float64
 5   BT_BILG_TASINABILIR            14498 non-null  float64
 6   BT_TABLET                      14498 non-null  float64
 7   BT_TEL_CEP                     14498 non-null  float64
 8   BT_OYUNKONSOL                  14498 non-null  float64
 9   BT_INTBAGLANAN_TV              14498 non-null  float64
 10  HANE_INTERNET_ERISIM_DURUMU    14498 non-null  float64
 11  HANE_INTERNET_ERISIM_KULLANIM  12944 non-null  float64
 12  INT_BAGLANTI_SABIT_GENIS       12944 non-null  float64
 13  INT_BAGLANTI_MOBIL_GENIS       12944 non-null  float64
 14  INT_BAGLANTI_CEVIRMELI_ISDN    12944 non-null  float64
 15  INT_BAGLANTI_TEL_DARBANT       12945 non-null  float64
 16  HANE_GELIR_AYLIK               14475 non-null  float64
 17  HHB                            15103 non-null  int64
 18  IBBS_1                         15103 non-null  str
 19  HANE_FAKTOR                    14498 non-null  str
dtypes: float64(13), int64(5), str(2)
memory usage: 2.3 MB

In [6]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)

In [7]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15098,2020,27536,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,10000.0,1,TRC,"1983,882957"
15099,2020,27537,1,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,5000.0,6,TRC,"1481,139799"
15100,2020,27538,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,25000.0,1,TRC,"1753,479525"
15101,2020,27539,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,5750.0,7,TRC,"1895,510798"
15102,2020,275310,1,1,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,7000.0,8,TRC,"1833,591441"

In [8]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2020temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2020temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10012,1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2000.0,5,TR1,"2480,131065"
2,2020,10013,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2300.0,4,TR1,"1381,349115"
3,2020,10014,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,4500.0,5,TR1,"2209,668548"
4,2020,10016,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2600.0,3,TR1,"2508,214477"