In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HANE_2021_csv.csv" , sep=";")
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,HANE_GELIR_AYLIK,HHB,IBBS_1,HANE_FAKTOR
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14264 entries, 0 to 14263
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 14264 non-null  int64
 1   BULTEN_NO                    14264 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         14264 non-null  int64
 3   BT_BILG_MASAUSTU             13662 non-null  float64
 4   BT_BILG_DIZUSTU              13662 non-null  float64
 5   BT_TABLET                    13662 non-null  float64
 6   BT_TEL_CEP                   13662 non-null  float64
 7   BT_DIGER_CIHAZ               13662 non-null  float64
 8   HANE_INTERNET_ERISIM_DURUMU  13662 non-null  float64
 9   INT_BAGLANTI_SABIT_GENIS     12391 non-null  float64
 10  INT_BAGLANTI_MOBIL_GENIS     12391 non-null  float64
 11  HANE_GELIR_AYLIK             13662 non-null  float64
 12  HHB                          14264 non-null  int64
 13  IBBS_1                       14264 non-null  str
 14  HANE_FAKTOR                  14264 non-null  str
dtypes: float64(9), int64(4), str(2)
memory usage: 1.6 MB

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)

In [6]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"

In [7]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2021temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2021temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"

# 2021 yılı cross tabloları

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2021.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,iş sahibi mi,...,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,52,1,1,2,NaN,1,NaN,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10011,2,49,2,2,2,NaN,3,1.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
2,2021,10011,3,26,1,3,512,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
3,2021,10011,4,21,1,3,4,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
4,2021,10012,3,33,1,1,4,NaN,1,NaN,...,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,8211,48.95,3333,44.12
erkek,8562,51.05,4222,55.88
toplam,16773,100.00,7555,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,645,54.75,4004,48.47
erkek,533,45.25,4256,51.53
toplam,1178,100.00,8260,100.00

In [2]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["sağlık bilgisi arama"] == 1]
    yok_df = alt_df[alt_df["sağlık bilgisi arama"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2021,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2021 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["sağlık bilgisi arama"] == 1]
toplam_yok = df[df["sağlık bilgisi arama"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2021,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2021= pd.concat(
    [gelir_online_saglik_2021, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2021)

C:\Users\dilara\AppData\Local\Temp\ipykernel_27520\827363736.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2021,1,49.49,50.51,1859,47.05,52.95,1694
1,2021,2,50.40,49.60,2899,43.43,56.57,1734
2,2021,3,49.66,50.34,3417,42.03,57.97,1618
3,2021,4,47.91,52.09,3930,46.22,53.78,1482
4,2021,5,48.20,51.80,4668,40.70,59.30,1027
5,2021,frekans,8211.00,8562.00,16773,3333.00,4222.00,7555

In [5]:
# =========================================================
# 2015 - ETİCARETTEN İLAÇ ALIŞVERİŞİ
# GELİR GRUBU + CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# GELİR GRUBU OLUŞTUR
# =========================================================

df = df.sort_values(
    "hane gelir aylık"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇ
# =========================================================

sonuc = []

for grup in [1, 2, 3, 4, 5]:

    grup_df = df[df["gelir_grup"] == grup]

    # VAR
    var_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    # YOK
    yok_df = grup_df[
        grup_df["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    ).round(2)

    sonuc.append({

        "yıl": 2015,

        "gelir": grup,

        # VAR
        "var kadın":
            var_cinsiyet.get(2, 0),

        "var erkek":
            var_cinsiyet.get(1, 0),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            yok_cinsiyet.get(2, 0),

        "yok erkek":
            yok_cinsiyet.get(1, 0),

        "yok toplam":
            len(yok_df)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2015,

    "gelir": "toplam",

    "var kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 2)
        ]),

    "var erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 1) &
            (df["cinsiyet"] == 1)
        ]),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 2)
        ]),

    "yok erkek":
        len(df[
            (df["eticaret ilaç alışverişi"] == 2) &
            (df["cinsiyet"] == 1)
        ]),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2015 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2015)

C:\Users\dilara\AppData\Local\Temp\ipykernel_18348\100049498.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2015,1,61.02,38.98,59,57.08,42.92,678
1,2015,2,50.56,49.44,89,52.10,47.90,1119
2,2015,3,54.37,45.62,160,47.65,52.35,1576
3,2015,4,56.13,43.87,253,47.07,52.93,2065
4,2015,5,54.29,45.71,617,46.46,53.54,2822
5,2015,toplam,645.00,533.00,1178,4004.00,4256.00,8260

In [3]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_18068\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,52.66,47.34,6238,42.64,57.36,2099
1,2017,31-45,49.12,50.88,6370,43.99,56.01,2296
2,2017,46-60,44.70,55.30,3407,45.37,54.63,2290
3,2017,60+,36.15,63.85,758,44.71,55.29,870
4,2017,toplam,8211.00,8562.00,16773,3333.00,4222.00,7555

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2021.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,iş sahibi mi,...,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,52,1,1,2,NaN,1,NaN,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10011,2,49,2,2,2,NaN,3,1.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
2,2021,10011,3,26,1,3,512,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
3,2021,10011,4,21,1,3,4,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
4,2021,10012,3,33,1,1,4,NaN,1,NaN,...,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_17360\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,58.10,41.90,420,53.58,46.42,4048
1,2024,31-45,54.87,45.13,554,46.29,53.71,3089
2,2024,46-60,48.86,51.14,176,36.84,63.16,980
3,2024,60+,39.29,60.71,28,30.77,69.23,143
4,2024,toplam,645.00,533.00,1178,4004.00,4256.00,8260

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_6704\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,55.59,44.41,3274,53.15,46.85,3646
1,2017,ortaokul/lise,46.61,53.39,8363,36.06,63.94,3217
2,2017,üniversite,45.89,54.11,438,26.83,73.17,41
3,2017,üniversiteüstü,42.45,57.55,106,25.00,75.00,12
4,2017,toplam,8211.00,8562.00,16773,3333.00,4222.00,7555

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2021.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,iş sahibi mi,...,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,52,1,1,2,NaN,1,NaN,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10011,2,49,2,2,2,NaN,3,1.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
2,2021,10011,3,26,1,3,512,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
3,2021,10011,4,21,1,3,4,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
4,2021,10012,3,33,1,1,4,NaN,1,NaN,...,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_31280\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_31280\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,28,24,52,343,334,677
1,2025,ortaokul/lise,221,191,412,2017,2185,4202
2,2025,üniversite,379,300,679,1621,1697,3318
3,2025,üniversiteüstü,17,18,35,23,40,63
4,,toplam,645,533,1178,4004,4256,8260

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2021.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,iş sahibi mi,...,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,52,1,1,2,NaN,1,NaN,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10011,2,49,2,2,2,NaN,3,1.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
2,2021,10011,3,26,1,3,512,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
3,2021,10011,4,21,1,3,4,NaN,3,2.0,...,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
4,2021,10012,3,33,1,1,4,NaN,1,NaN,...,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"

In [2]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_27116\3164738277.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_label"] = df["cinsiyet"].replace({

  cinsiyet  toplam   yüzde
0    Erkek   15080   49.39
1    Kadın   15450   50.61
2   Toplam   30530  100.00

In [4]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_10068\1794991821.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

        toplam   yüzde
15-30     8754   28.67
31-45     9451   30.96
46-60     7863   25.75
60+       4462   14.62
toplam   30530  100.00

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

                toplam   yüzde
ilkokulvealtı    12330   40.39
ortaokul/lise    12308   40.31
üniversite        5293   17.34
üniversiteüstü     599    1.96
toplam           30530  100.00

In [7]:
import pandas as pd
import numpy as np

# =========================================================
# GELİR DEĞİŞKENİ
# =========================================================

gelir_col = "hane gelir aylık"

# numerik yap
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# ZORLA EŞİT 5 GRUP
# =========================================================

df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

frekans = (
    df["gelir_5li_esit"]
    .value_counts()
    .reindex(gelir_sirasi)
)

yuzde = round(
    (
        df["gelir_5li_esit"]
        .value_counts(normalize=True)
        .reindex(gelir_sirasi)
    ) * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

gelir_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame({
    "toplam": [gelir_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

gelir_tablo = pd.concat(
    [gelir_tablo, toplam_satiri]
)

display(gelir_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

         toplam  yüzde
1. grup    6106   20.0
2. grup    6106   20.0
3. grup    6106   20.0
4. grup    6106   20.0
5. grup    6106   20.0
toplam    30530  100.0