In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HANE_2021_csv.csv" , sep=";")
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,HANE_GELIR_AYLIK,HHB,IBBS_1,HANE_FAKTOR
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14264 entries, 0 to 14263
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 14264 non-null  int64
 1   BULTEN_NO                    14264 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         14264 non-null  int64
 3   BT_BILG_MASAUSTU             13662 non-null  float64
 4   BT_BILG_DIZUSTU              13662 non-null  float64
 5   BT_TABLET                    13662 non-null  float64
 6   BT_TEL_CEP                   13662 non-null  float64
 7   BT_DIGER_CIHAZ               13662 non-null  float64
 8   HANE_INTERNET_ERISIM_DURUMU  13662 non-null  float64
 9   INT_BAGLANTI_SABIT_GENIS     12391 non-null  float64
 10  INT_BAGLANTI_MOBIL_GENIS     12391 non-null  float64
 11  HANE_GELIR_AYLIK             13662 non-null  float64
 12  HHB                          14264 non-null  int64
 13  IBBS_1                       14264 non-null  str
 14  HANE_FAKTOR                  14264 non-null  str
dtypes: float64(9), int64(4), str(2)
memory usage: 1.6 MB

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)

In [6]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"

In [7]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2021temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2021temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10012,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,3500.0,5,TR1,"2521,501936"
2,2021,10013,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5000.0,3,TR1,"3012,93015"
3,2021,10015,1,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1900.0,4,TR1,"660,8627433"
4,2021,10016,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,10000.0,4,TR1,"2330,263887"