In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HBTKA_HANE_2022_EVAM.xlsx" )
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_20,HHB,IBBS_1,hane_faktor
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13454 entries, 0 to 13453
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 13454 non-null  int64
 1   BULTEN_NO                    13454 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         13454 non-null  int64
 3   BT_BILG_MASAUSTU             13454 non-null  int64
 4   BT_BILG_DIZUSTU              13454 non-null  int64
 5   BT_TABLET                    13454 non-null  int64
 6   BT_TEL_CEP                   13454 non-null  int64
 7   BT_DIGER_CIHAZ               13454 non-null  int64
 8   HANE_INTERNET_ERISIM_DURUMU  13454 non-null  int64
 9   hane_aylik_gelir_grp_20      13454 non-null  int64
 10  HHB                          13454 non-null  int64
 11  IBBS_1                       13454 non-null  str
 12  hane_faktor                  13454 non-null  float64
dtypes: float64(1), int64(11), str(1)
memory usage: 1.3 MB

In [8]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"hane_faktor": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)

In [9]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271

In [10]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2022temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2022temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271