In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HBTKA_HANE_2022_EVAM.xlsx" )
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_20,HHB,IBBS_1,hane_faktor
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13454 entries, 0 to 13453
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 13454 non-null  int64
 1   BULTEN_NO                    13454 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         13454 non-null  int64
 3   BT_BILG_MASAUSTU             13454 non-null  int64
 4   BT_BILG_DIZUSTU              13454 non-null  int64
 5   BT_TABLET                    13454 non-null  int64
 6   BT_TEL_CEP                   13454 non-null  int64
 7   BT_DIGER_CIHAZ               13454 non-null  int64
 8   HANE_INTERNET_ERISIM_DURUMU  13454 non-null  int64
 9   hane_aylik_gelir_grp_20      13454 non-null  int64
 10  HHB                          13454 non-null  int64
 11  IBBS_1                       13454 non-null  str
 12  hane_faktor                  13454 non-null  float64
dtypes: float64(1), int64(11), str(1)
memory usage: 1.3 MB

In [8]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"hane_faktor": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)

In [9]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271

In [10]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2022temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2022temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10017,1,2,1,1,1,2,1,19,2,TR1,3361.134507
3,2022,10018,1,2,1,2,1,2,1,16,3,TR1,3243.679528
4,2022,10019,1,2,1,1,1,1,1,16,2,TR1,1241.614271

# 2022 yılı croas tabloları

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2,1,1,1,2,1,19,2,TR1,3361.134507

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,7715,51.08,3913,43.71
erkek,7389,48.92,5040,56.29
toplam,15104,100.00,8953,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,589,56.2,3982,48.79
erkek,459,43.8,4180,51.21
toplam,1048,100.0,8162,100.00

In [3]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,589,56.2,3982,48.79
erkek,459,43.8,4180,51.21
toplam,1048,100.0,8162,100.00

In [2]:
import pandas as pd

# ======================================================
# GELİR GRUBU
# ======================================================

df = df.sort_values("hane gelir aylık").reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# ======================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# 1 = var, 2 = yok
# cinsiyet: 1 = erkek, 2 = kadın
# ======================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    var_df = alt_df[alt_df["sağlık bilgisi arama"] == 1]
    yok_df = alt_df[alt_df["sağlık bilgisi arama"] == 2]

    var_cinsiyet_yuzde = var_df["cinsiyet"].value_counts(normalize=True) * 100
    yok_cinsiyet_yuzde = yok_df["cinsiyet"].value_counts(normalize=True) * 100

    sonuc.append({
        "yıl": 2021,
        "gelir": gelir,

        "var kadın": round(var_cinsiyet_yuzde.get(2, 0), 2),
        "var erkek": round(var_cinsiyet_yuzde.get(1, 0), 2),
        "var toplam": len(var_df),

        "yok kadın": round(yok_cinsiyet_yuzde.get(2, 0), 2),
        "yok erkek": round(yok_cinsiyet_yuzde.get(1, 0), 2),
        "yok toplam": len(yok_df)
    })

gelir_online_saglik_2021 = pd.DataFrame(sonuc)

# ======================================================
# EN ALT FREKANS SATIRI
# kadın/erkek/toplam hepsi frekans
# ======================================================

toplam_var = df[df["sağlık bilgisi arama"] == 1]
toplam_yok = df[df["sağlık bilgisi arama"] == 2]

toplam_var_cinsiyet = toplam_var["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{
    "yıl": 2021,
    "gelir": "frekans",

    "var kadın": toplam_var_cinsiyet.get(2, 0),
    "var erkek": toplam_var_cinsiyet.get(1, 0),
    "var toplam": len(toplam_var),

    "yok kadın": toplam_yok_cinsiyet.get(2, 0),
    "yok erkek": toplam_yok_cinsiyet.get(1, 0),
    "yok toplam": len(toplam_yok)
}])

gelir_online_saglik_2021= pd.concat(
    [gelir_online_saglik_2021, toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2021)

KeyError: 'hane gelir aylık'

In [3]:
df["hanenin aylık toplam net geliri (20'li gelir grubu)"].value_counts()

hanenin aylık toplam net geliri (20'li gelir grubu)
4     1759
11    1699
10    1627
7     1599
14    1563
5     1549
17    1528
12    1521
2     1510
15    1505
18    1492
8     1422
9     1393
6     1393
3     1392
19    1384
13    1337
16    1325
20    1315
1     1268
Name: count, dtype: int64

In [4]:
df["hanenin aylık toplam net geliri (20'li gelir grubu)"].value_counts().sort_index()

hanenin aylık toplam net geliri (20'li gelir grubu)
1     1268
2     1510
3     1392
4     1759
5     1549
6     1393
7     1599
8     1422
9     1393
10    1627
11    1699
12    1521
13    1337
14    1563
15    1505
16    1325
17    1528
18    1492
19    1384
20    1315
Name: count, dtype: int64

In [5]:
df["hanenin aylık toplam net geliri (20'li gelir grubu)"] \
    .value_counts() \
    .sort_index()

hanenin aylık toplam net geliri (20'li gelir grubu)
1     1268
2     1510
3     1392
4     1759
5     1549
6     1393
7     1599
8     1422
9     1393
10    1627
11    1699
12    1521
13    1337
14    1563
15    1505
16    1325
17    1528
18    1492
19    1384
20    1315
Name: count, dtype: int64

In [6]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI
# GELİR GRUBU x CİNSİYET TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# 20'Lİ GELİRİ 5'LİYE ÇEVİR
# =========================================================

df["gelir_grup"] = pd.cut(
    df["hanenin aylık toplam net geliri (20'li gelir grubu)"],
    bins=[0, 4, 8, 12, 16, 20],
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# SONUÇLAR
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt_df = df[df["gelir_grup"] == gelir]

    # VAR
    toplam_var = alt_df[
        alt_df["sağlık bilgisi arama"] == 1
    ]

    var_cinsiyet = toplam_var["cinsiyet"] \
        .value_counts(normalize=True) * 100

    # YOK
    toplam_yok = alt_df[
        alt_df["sağlık bilgisi arama"] == 2
    ]

    yok_cinsiyet = toplam_yok["cinsiyet"] \
        .value_counts(normalize=True) * 100

    sonuc.append({

        "yıl": 2022,

        "gelir": gelir,

        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(toplam_var),

        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(toplam_yok)

    })

# =========================================================
# TOPLAM / FREKANS SATIRI
# =========================================================

toplam_var_df = df[df["sağlık bilgisi arama"] == 1]
toplam_yok_df = df[df["sağlık bilgisi arama"] == 2]

toplam_var_cinsiyet = toplam_var_df["cinsiyet"].value_counts()
toplam_yok_cinsiyet = toplam_yok_df["cinsiyet"].value_counts()

toplam_satiri = pd.DataFrame([{

    "yıl": 2022,

    "gelir": "frekans",

    "var kadın":
        toplam_var_cinsiyet.get(2, 0),

    "var erkek":
        toplam_var_cinsiyet.get(1, 0),

    "var toplam":
        len(toplam_var_df),

    "yok kadın":
        toplam_yok_cinsiyet.get(2, 0),

    "yok erkek":
        toplam_yok_cinsiyet.get(1, 0),

    "yok toplam":
        len(toplam_yok_df)

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_online_saglik_2022 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_online_saglik_2022)

C:\Users\dilara\AppData\Local\Temp\ipykernel_20992\1533901286.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.cut(

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2022,1,53.10,46.90,1533,45.03,54.97,2014
1,2022,2,51.93,48.07,2694,44.65,55.35,2038
2,2022,3,51.33,48.67,3117,44.24,55.76,2066
3,2022,4,49.86,50.14,3596,41.19,58.81,1544
4,2022,5,50.65,49.35,4164,42.29,57.71,1291
5,2022,frekans,7715.00,7389.00,15104,3913.00,5040.00,8953

In [10]:
df["gelir_grup"].value_counts()

gelir_grup
3    6240
2    5963
1    5929
4    5730
5    5719
Name: count, dtype: int64

In [11]:
df["gelir_grup"] = pd.qcut(
    df["hanenin aylık toplam net geliri (20'li gelir grubu)"],
    q=5,
    labels=[1, 2, 3, 4, 5]
)

In [12]:
df["gelir_grup"].value_counts().sort_index()

gelir_grup
1    5929
2    5963
3    6240
4    5730
5    5719
Name: count, dtype: int64

In [15]:
df["gelir_grup"] = (
    (df["hanenin aylık toplam net geliri (20'li gelir grubu)"] - 1) // 4
) + 1

df["gelir_grup"].value_counts().sort_index()

gelir_grup
1    5929
2    5963
3    6240
4    5730
5    5719
Name: count, dtype: int64

In [16]:
df["gelir_grup"] = pd.qcut(
    df["hanenin aylık toplam net geliri (20'li gelir grubu)"],
    q=5,
    labels=[1, 2, 3, 4, 5]
)

df["gelir_grup"].value_counts().sort_index()

gelir_grup
1    5929
2    5963
3    6240
4    5730
5    5719
Name: count, dtype: int64

In [17]:
import pandas as pd

# önce 20'li gelir grubuna göre sırala
df = df.sort_values(
    "hanenin aylık toplam net geliri (20'li gelir grubu)"
).reset_index(drop=True)

# sonra satır sırasına göre 5 eşit gruba böl
df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# kontrol
df["gelir_grup"].value_counts().sort_index()

gelir_grup
1    5917
2    5916
3    5916
4    5916
5    5916
Name: count, dtype: int64

In [20]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# 20'Lİ GELİR GRUBUNU 5 EŞİT GRUBA ÇEVİR
# =========================================================

df = df.sort_values(
    "hanenin aylık toplam net geliri (20'li gelir grubu)"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2022,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2022,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2022 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2022)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2022,1,53.14,46.86,1528,45.03,54.97,2014
1,2022,2,51.84,48.16,2670,44.76,55.24,2024
2,2022,3,51.06,48.94,2938,44.37,55.63,1954
3,2022,4,50.41,49.59,3682,41.10,58.90,1613
4,2022,5,50.47,49.53,4286,42.28,57.72,1348
5,2022,frekans,7715.00,7389.00,15104,3913.00,5040.00,8953

In [22]:
df["gelir_grup"].value_counts()

gelir_grup
1    5917
2    5916
3    5916
4    5916
5    5916
Name: count, dtype: int64

In [ ]:
# =========================================================
# GELİR GRUBU x ETİCARETTEN İLAÇ ALIŞVERİŞİ
# 2022 → 20'Lİ GELİRİ 5 EŞİT PARÇAYA BÖL
# =========================================================

import pandas as pd

# =========================================================
# 20'Lİ GELİR GRUBUNU 5 EŞİT GRUBA ÇEVİR
# =========================================================

df = df.sort_values(
    "hanenin aylık toplam net geliri (20'li gelir grubu)"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # ETİCARETTEN İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaretten ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARETTEN İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2022,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(eticaret_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(eticaret_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(eticaret_var),

        # YOK
        "yok kadın":
            round(eticaret_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(eticaret_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(eticaret_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2022,

    "gelir": "frekans",

    "var kadın":
        df[df["eticaretten ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaretten ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaretten ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaretten ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaretten ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaretten ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2022 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2022)

C:\Users\dilara\AppData\Local\Temp\ipykernel_21740\1832130389.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = pd.qcut(

KeyError: 'eticaretten ilaç alışverişi'

In [5]:
# =========================================================
# GELİR GRUBU x ETİCARET İLAÇ ALIŞVERİŞİ
# 2022 → 20'Lİ GELİRİ 5 EŞİT GRUBA BÖL
# =========================================================

import pandas as pd

# =========================================================
# 20'Lİ GELİR GRUBUNU 5 EŞİT GRUBA ÇEVİR
# =========================================================

df = df.sort_values(
    "hanenin aylık toplam net geliri (20'li gelir grubu)"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2022,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(eticaret_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(eticaret_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(eticaret_var),

        # YOK
        "yok kadın":
            round(eticaret_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(eticaret_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(eticaret_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2022,

    "gelir": "frekans",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2022 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2022)

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2022,1,63.04,36.96,46,51.99,48.01,577
1,2022,2,65.17,34.83,89,50.25,49.75,1186
2,2022,3,56.00,44.00,150,48.88,51.12,1514
3,2022,4,55.06,44.94,247,47.72,52.28,2043
4,2022,5,54.65,45.35,516,48.24,51.76,2842
5,2022,frekans,589.00,459.00,1048,3982.00,4180.00,8162

In [7]:
df["gelir_grup"].value_counts()

gelir_grup
1    5917
2    5916
3    5916
4    5916
5    5916
Name: count, dtype: int64

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_11852\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,53.77,46.23,5321,42.38,57.62,2369
1,2017,31-45,51.95,48.05,5940,43.79,56.21,2631
2,2017,46-60,47.07,52.93,3085,45.29,54.71,2782
3,2017,60+,41.69,58.31,758,42.44,57.56,1171
4,2017,toplam,7715.00,7389.00,15104,3913.00,5040.00,8953

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2,1,1,1,2,1,19,2,TR1,3361.134507

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31676\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,59.44,40.56,360,52.96,47.04,3727
1,2024,31-45,58.03,41.97,498,47.97,52.03,3233
2,2024,46-60,47.24,52.76,163,38.06,61.94,1051
3,2024,60+,33.33,66.67,27,37.75,62.25,151
4,2024,toplam,589.00,459.00,1048,3982.00,4180.00,8162

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_30828\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,58.20,41.80,2885,53.40,46.60,4197
1,2017,ortaokul/lise,48.52,51.48,7380,35.26,64.74,3732
2,2017,üniversite,47.44,52.56,390,23.75,76.25,80
3,2017,üniversiteüstü,45.71,54.29,70,14.29,85.71,7
4,2017,toplam,7715.00,7389.00,15104,3913.00,5040.00,8953

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2,1,1,1,2,1,19,2,TR1,3361.134507

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_14668\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_14668\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,34,28,62,387,341,728
1,2025,ortaokul/lise,195,163,358,1900,2118,4018
2,2025,üniversite,353,260,613,1677,1696,3373
3,2025,üniversiteüstü,7,8,15,18,25,43
4,,toplam,589,459,1048,3982,4180,8162

In [3]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["randevu_alma"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["randevu_alma"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_14668\566767331.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      46.49      53.51       14938      51.37      48.63        9119

In [3]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# SAĞLIK SONUÇLARINI ALMA DEĞİŞKENİ
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["saglik_sonuc"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["saglik_sonuc"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_6984\398983725.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      45.41      54.59       16729      55.02      44.98        7328

In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2,1,1,1,2,1,19,2,TR1,3361.134507

In [13]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2020

# =========================================================
# DEĞİŞKENLER
# =========================================================
gelir_col = "hanenin aylık toplam net geliri (20'li gelir grubu)"
randevu_col = "randevu alma (e-nabız,mhrs vb.)"

# =========================================================
# GELİR DEĞİŞKENİNİ NUMERİK YAP
# =========================================================
df["gelir_20li"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# GELİRİ ZORLA 5 EŞİT GRUBA BÖL
# (HER GRUPTA YAKLAŞIK AYNI SAYIDA GÖZLEM)
# =========================================================
df["gelir_5li"] = pd.qcut(
    df["gelir_20li"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# kontrol
print(df["gelir_5li"].value_counts().sort_index())


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df[randevu_col].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

for gelir in gelir_sirasi:

    alt = df[df["gelir_5li"] == gelir]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["randevu_alma"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["randevu_alma"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "gelir_grubu": gelir,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["randevu_alma"] == 1]
toplam_yok_df = df[df["randevu_alma"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "gelir_grubu": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

gelir_5li
1. grup    5917
2. grup    5916
3. grup    5916
4. grup    5916
5. grup    5916
Name: count, dtype: int64

,yıllar,gelir_grubu,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2020,1. grup,46.64,53.36,1608,50.08,49.92,1931
1,2020,2. grup,47.11,52.89,2700,50.95,49.05,1994
2,2020,3. grup,45.75,54.25,2955,53.45,46.55,1970
3,2020,4. grup,45.50,54.50,3569,50.33,49.67,1691
4,2020,5. grup,47.39,52.61,4106,51.99,48.01,1533
5,,toplam,46.49,53.51,14938,51.37,48.63,9119

In [15]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2022

# =========================================================
# DEĞİŞKENLER
# =========================================================
gelir_col = "hanenin aylık toplam net geliri (20'li gelir grubu)"
saglik_col = "sağlık sonuçlarını almak"

# =========================================================
# GELİRİ NUMERİK YAP
# =========================================================
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# GELİRİ ZORLA 5 EŞİT GRUBA BÖL
# =========================================================
df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# kontrol
print(df["gelir_5li_esit"].value_counts().sort_index())


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df[saglik_col].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

for gelir in gelir_sirasi:

    alt = df[df["gelir_5li_esit"] == gelir]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "gelir_grubu": gelir,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "gelir_grubu": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

gelir_5li_esit
1. grup    5917
2. grup    5916
3. grup    5916
4. grup    5916
5. grup    5916
Name: count, dtype: int64

,yıllar,gelir_grubu,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2022,1. grup,43.98,56.02,1853,53.50,46.50,1686
1,2022,2. grup,45.09,54.91,3067,55.62,44.38,1627
2,2022,3. grup,45.39,54.61,3289,55.75,44.25,1636
3,2022,4. grup,44.38,55.62,3950,55.11,44.89,1310
4,2022,5. grup,47.09,52.91,4570,55.29,44.71,1069
5,,toplam,45.41,54.59,16729,55.02,44.98,7328

In [16]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2020

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# RANDEVU ALMA
# =========================================================
df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["randevu"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["randevu"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["randevu"] == 1]
toplam_yok_df = df[df["randevu"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_31116\716567252.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_31116\716567252.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2020,ilkokulvealtı,49.79,50.21,2900,59.21,40.79,4182
1,2020,ortaokul/lise,44.29,55.71,7186,43.66,56.34,3926
2,2020,üniversite,48.30,51.70,4391,48.97,51.03,925
3,2020,üniversiteüstü,42.52,57.48,461,47.67,52.33,86
4,,toplam,46.49,53.51,14938,51.37,48.63,9119

In [17]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2024

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512, 4, 5, 6]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53, 7]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,ilkokulvealtı,48.21,51.79,3383,61.88,38.12,3699
1,2024,ortaokul/lise,42.74,57.26,8084,47.62,52.38,3028
2,2024,üniversite,48.14,51.86,4769,50.82,49.18,547
3,2024,üniversiteüstü,43.41,56.59,493,42.59,57.41,54
4,,toplam,45.41,54.59,16729,55.02,44.98,7328

In [18]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================

df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["randevu"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["randevu"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["randevu"] == 1]

yok_df = df[df["randevu"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31116\3536698121.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,50.77,49.23,5159,49.23,50.77,2531
1,2024,31-45,47.44,52.56,5835,53.73,46.27,2736
2,2024,46-60,41.12,58.88,3152,52.15,47.85,2715
3,2024,60+,32.95,67.05,792,48.55,51.45,1137
4,,toplam,46.49,53.51,14938,51.37,48.63,9119

In [19]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================

df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# CROSS TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["saglik_sonuc"] == 1]

yok_df = df[df["saglik_sonuc"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,49.36,50.64,5717,52.86,47.14,1973
1,2024,31-45,46.31,53.69,6538,59.52,40.48,2033
2,2024,46-60,40.49,59.51,3591,55.27,44.73,2276
3,2024,60+,33.07,66.93,883,49.81,50.19,1046
4,,toplam,45.41,54.59,16729,55.02,44.98,7328

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv")
df.head()

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2,1,2,1,1,1,12,3,TR1,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2,1,1,1,2,1,19,2,TR1,3361.134507

In [3]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_22672\3164738277.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_label"] = df["cinsiyet"].replace({

  cinsiyet  toplam   yüzde
0    Erkek   14458   48.88
1    Kadın   15123   51.12
2   Toplam   29581  100.00

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_27400\1794991821.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

        toplam   yüzde
15-30     8097   27.37
31-45     9243   31.25
46-60     7665   25.91
60+       4576   15.47
toplam   29581  100.00

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_27400\3341891636.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

                toplam   yüzde
ilkokulvealtı    11784   39.84
ortaokul/lise    11872   40.13
üniversite        5378   18.18
üniversiteüstü     547    1.85
toplam           29581  100.00

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# GELİR DEĞİŞKENİ
# =========================================================

gelir_col = "hanenin aylık toplam net geliri (20'li gelir grubu)"

# numerik yap
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# ZORLA EŞİT 5 GRUP
# =========================================================

df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

frekans = (
    df["gelir_5li_esit"]
    .value_counts()
    .reindex(gelir_sirasi)
)

yuzde = round(
    (
        df["gelir_5li_esit"]
        .value_counts(normalize=True)
        .reindex(gelir_sirasi)
    ) * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

gelir_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame({
    "toplam": [gelir_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

gelir_tablo = pd.concat(
    [gelir_tablo, toplam_satiri]
)

display(gelir_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

         toplam  yüzde
1. grup    5917   20.0
2. grup    5916   20.0
3. grup    5916   20.0
4. grup    5916   20.0
5. grup    5916   20.0
toplam    29581  100.0