In [1]:
import pandas as pd

df = pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HBTKA_FERT_2022_EVAM.xlsx")

df.head()

,REFERANS_YIL,BULTEN_NO,FERTNO,YAS,CINSIYET,HHSORUMLU_YAKINLIK,GORUSME_YONTEM_FERT,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,...,NESN_INT_AKILLI_ARABA,NESN_INT_SRN_GUVEN_GIZ,NESN_INT_SRN_EMNYT_SAGLIK,NESN_INT_SRN_ZOR,NESN_INT_SRN_DIGER,NESN_INT_SRN_HIC,CIHAZ_DEGISIM_MOBIL_TEL,CIHAZ_DEGISIM_DIZUSTU_TABLET,CIHAZ_DEGISIM_MASAUSTU,FERT_FAKTOR
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,5.0,5.0,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3361.134507

In [2]:
df["BULTEN_NO"].value_counts()

BULTEN_NO
20736     10
20784      9
12589      8
15038      8
16619      8
          ..
252510     1
252910     1
253210     1
253610     1
253810     1
Name: count, Length: 13454, dtype: int64

In [3]:
df["REFERANS_YIL"].value_counts()

REFERANS_YIL
2022    29581
Name: count, dtype: int64

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [5]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [6]:
df.head()

,referans yıl,bülten no,FERTNO,YAS,CINSIYET,HHSORUMLU_YAKINLIK,GORUSME_YONTEM_FERT,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,...,NESN_INT_AKILLI_ARABA,NESN_INT_SRN_GUVEN_GIZ,NESN_INT_SRN_EMNYT_SAGLIK,NESN_INT_SRN_ZOR,NESN_INT_SRN_DIGER,NESN_INT_SRN_HIC,CIHAZ_DEGISIM_MOBIL_TEL,CIHAZ_DEGISIM_DIZUSTU_TABLET,CIHAZ_DEGISIM_MASAUSTU,FERT_FAKTOR
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,5.0,5.0,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3361.134507

In [7]:
df["FERTNO"].value_counts()

FERTNO
1     12027
2     10165
3      3993
4      2034
5       817
6       320
7       113
8        57
9        23
10       13
11       10
12        5
14        2
20        1
29        1
Name: count, dtype: int64

In [8]:
df.rename(columns={"FERTNO": "fert no"}, inplace=True)

In [10]:
df.head()

,referans yıl,bülten no,fert no,YAS,CINSIYET,HHSORUMLU_YAKINLIK,GORUSME_YONTEM_FERT,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,...,NESN_INT_AKILLI_ARABA,NESN_INT_SRN_GUVEN_GIZ,NESN_INT_SRN_EMNYT_SAGLIK,NESN_INT_SRN_ZOR,NESN_INT_SRN_DIGER,NESN_INT_SRN_HIC,CIHAZ_DEGISIM_MOBIL_TEL,CIHAZ_DEGISIM_DIZUSTU_TABLET,CIHAZ_DEGISIM_MASAUSTU,FERT_FAKTOR
0,2022,10012,1,44,1,1,3,2,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,2403.691000
2,2022,10014,2,57,2,2,1,2,NaN,3,...,2.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,2403.691000
3,2022,10014,3,16,2,3,3,3,NaN,3,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,5.0,5.0,2403.691000
4,2022,10017,1,41,2,2,3,53,NaN,1,...,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3361.134507