In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HBTKA_HANE_2023.csv" , sep=";")
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,HANE_FAKTOR
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11289 entries, 0 to 11288
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 11289 non-null  int64
 1   BULTEN_NO                    11289 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         11289 non-null  int64
 3   BT_BILG_MASAUSTU             11289 non-null  int64
 4   BT_BILG_DIZUSTU              11289 non-null  int64
 5   BT_TABLET                    11289 non-null  int64
 6   BT_TEL_CEP                   11289 non-null  int64
 7   BT_DIGER_CIHAZ               11289 non-null  int64
 8   HANE_INTERNET_ERISIM_DURUMU  11289 non-null  int64
 9   hane_aylik_gelir_grp_5       11289 non-null  int64
 10  HHB                          11289 non-null  int64
 11  IBBS_1                       11289 non-null  str
 12  HANE_FAKTOR                  11289 non-null  float64
dtypes: float64(1), int64(11), str(1)
memory usage: 1.1 MB

In [7]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)

In [8]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497

In [9]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2023temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2023temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497

# 2023 yılı cross tabloları

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_10956\2291217157.py:2: DtypeWarning: Columns (0: doğduğu ülke kodu, 1: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,2,1,1,45,3,NaN,1,NaN,...,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,1,2,25,512,NaN,1,NaN,...,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,1,1,58,2,NaN,3,5.0,...,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,2,1,1,25,3,NaN,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10014,3,1,2,40,1,2.0,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,6739,50.06,3228,44.37
erkek,6724,49.94,4047,55.63
toplam,13463,100.00,7275,100.00

In [2]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,615,55.96,3828,49.48
erkek,484,44.04,3908,50.52
toplam,1099,100.00,7736,100.00

In [ ]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# 20'Lİ GELİR GRUBUNU 5 EŞİT GRUBA ÇEVİR
# =========================================================

df = df.sort_values(
    "hanenin aylık toplam net geliri (20'li gelir grubu)"
).reset_index(drop=True)

df["gelir_grup"] = pd.qcut(
    df.index,
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2022,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2022,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2023 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2023)

KeyError: "hanenin aylık toplam net geliri (20'li gelir grubu)"

In [5]:
df["hanenin aylık toplam net geliri (5'li gelir grubu)"].value_counts()

hanenin aylık toplam net geliri (5'li gelir grubu)
3    5096
5    5069
2    4945
4    4921
1    4740
Name: count, dtype: int64

In [6]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# 2023
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# HAZIR 5'Lİ GELİR GRUBU
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2023,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2023,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2023 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2023)

C:\Users\dilara\AppData\Local\Temp\ipykernel_17572\1549255150.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2023,1,52.49,47.51,1446,49.97,50.03,1593
1,2023,2,51.01,48.99,2376,44.03,55.97,1724
2,2023,3,49.03,50.97,2835,43.80,56.20,1532
3,2023,4,50.59,49.41,3113,41.85,58.15,1319
4,2023,5,48.82,51.18,3693,40.65,59.35,1107
5,2023,frekans,6739.00,6724.00,13463,3228.00,4047.00,7275

In [2]:
df.head()

,referans yıl,bülten no,fert no,fert cevap durumu,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,2,1,1,45,3,NaN,1,NaN,...,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,1,2,25,512,NaN,1,NaN,...,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,1,1,58,2,NaN,3,5.0,...,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,2,1,1,25,3,NaN,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10014,3,1,2,40,1,2.0,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007

In [3]:
# =========================================================
# GELİR GRUBU x ETİCARET İLAÇ ALIŞVERİŞİ
# HAZIR 5'Lİ GELİR GRUBU KULLAN
# =========================================================

import pandas as pd

# =========================================================
# 5'Lİ GELİR GRUBUNU KULLAN
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2023,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(eticaret_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(eticaret_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(eticaret_var),

        # YOK
        "yok kadın":
            round(eticaret_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(eticaret_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(eticaret_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2023,

    "gelir": "frekans",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2023 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2023)

C:\Users\dilara\AppData\Local\Temp\ipykernel_28568\4051434244.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2023,1,56.36,43.64,55,56.44,43.56,629
1,2023,2,58.04,41.96,112,52.15,47.85,1185
2,2023,3,57.30,42.70,178,50.73,49.27,1573
3,2023,4,59.32,40.68,263,48.45,51.55,1909
4,2023,5,53.16,46.84,491,46.39,53.61,2440
5,2023,frekans,615.00,484.00,1099,3828.00,3908.00,7736

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_10956\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,54.05,45.95,4651,42.12,57.88,1935
1,2017,31-45,49.80,50.20,5197,44.42,55.58,1999
2,2017,46-60,46.34,53.66,2872,46.80,53.20,2237
3,2017,60+,41.18,58.82,743,43.30,56.70,1104
4,2017,toplam,6739.00,6724.00,13463,3228.00,4047.00,7275

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_31668\2291217157.py:2: DtypeWarning: Columns (0: doğduğu ülke kodu, 1: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,2,1,1,45,3,NaN,1,NaN,...,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,1,2,25,512,NaN,1,NaN,...,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,1,1,58,2,NaN,3,5.0,...,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,2,1,1,25,3,NaN,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10014,3,1,2,40,1,2.0,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007

In [2]:
# =========================================================
# EĞİTİM x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

def egitim_kategori(x):
    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 51, 52]:
        return "üniversite"
    elif x in [6, 7, 53]:
        return "üniversiteüstü"
    else:
        return None

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in ["ilkokulvealtı", "ortaokul/lise", "üniversite", "üniversiteüstü"]:

    alt = df[df["egitim_grup"] == egitim]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "eğitim": egitim,

        "var kadın": round(eticaret_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(eticaret_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(eticaret_var),

        "yok kadın": round(eticaret_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(eticaret_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(eticaret_yok)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{
    "eğitim": "toplam",

    "var kadın": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["eticaret ilaç alışverişi"] == 2])
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_13224\2103775799.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,ilkokulvealtı,58.82,41.18,68,54.52,45.48,664
1,ortaokul/lise,51.49,48.51,369,48.14,51.86,3932
2,üniversite,50.75,49.25,67,42.81,57.19,278
3,üniversiteüstü,38.89,61.11,18,44.44,55.56,63
4,toplam,615.00,484.00,1099,3828.00,3908.00,7736

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_10700\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,65.06,34.94,395,54.06,45.94,3570
1,2024,31-45,55.21,44.79,489,47.71,52.29,3035
2,2024,46-60,44.51,55.49,182,41.27,58.73,996
3,2024,60+,21.21,78.79,33,28.89,71.11,135
4,2024,toplam,615.00,484.00,1099,3828.00,3908.00,7736

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31668\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,56.52,43.48,2622,55.38,44.62,3438
1,2017,ortaokul/lise,47.49,52.51,6383,35.02,64.98,3081
2,2017,üniversite,43.46,56.54,382,32.43,67.57,37
3,2017,üniversiteüstü,38.82,61.18,85,42.86,57.14,14
4,2017,toplam,6739.00,6724.00,13463,3228.00,4047.00,7275

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # ilkokul ve altı
    if x in [0, 1]:
        return "ilkokulvealtı"

    # ortaokul / lise
    elif x in [2, 3, 4]:
        return "ortaokul/lise"

    # üniversite
    elif x in [51, 52]:
        return "üniversite"

    # üniversite üstü
    elif x == 53:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ DEĞİŞKENİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # VAR
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2015,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{
    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()
}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31668\2992515238.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_31668\2992515238.py:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2015,ilkokulvealtı,0,0,0,32,8,40
1,2015,ortaokul/lise,230,207,437,2223,2333,4556
2,2015,üniversite,34,33,67,119,159,278
3,2015,üniversiteüstü,7,11,18,28,35,63
4,,toplam,271,251,522,2402,2535,4937

In [4]:
df[
    (df["eğitim_grup"] == "ilkokulvealtı") &
    (df["ilac_alisveris"] == 1)
]

Empty DataFrame
Columns: [referans yıl, bülten no, fert no, fert cevap durumu, cinsiyet, yaş, eğitim, okuma yazma durumu, çalışma durumu, çalışmama nedeni, işteki durumu, uluslararası meslek, doğduğu ülke, doğduğu ülke kodu, uyruk, uyruk ülke kodu, cep telefonu kullanımı, cep telefonuna sahip, en son internet ne zaman kullanıldı, internet kullanım sıklığı, masaüstü kullanımı, dizüstü kullanımı, tablet kullanımı, cep telefonu kullanımı.1, diğer cihaz kullanımı, eposta kullanımı, internet araması, sosyal medya kullanımı, sosyal medyada mesajlaşma, online haber okuma, sağlık bilgisi arama, ürün hizmet arama, websitesinde içerik paylaşma, internetten oy katılım, internetten iş arama, Unnamed: 35, internetten satış, online kurs, online eğitim materyal, online eğitim iletişim, whatsapp kullanımı, instagram kullanımı, youtube kullanımı, facebook kullanımı, twitter kullanımı, telegram kullanımı, tiktok kullanımı, snapchat kullanımı, bip kullanımı, diğer mobil uygulama kullanımları, evden çalışma sıklığı, evden çalışırken internet kullanımı , edevlet resmi işlem, edevlet kamu bilgi, edevlet hakkında bilgi, edevlette hiçbir sey yapmadı, edevlet form işlemleri, edevletten randevu alma, edevletten bilgi alma, edevlette vergi beyani verme yönetimi, edevlet belge talep, edevlet yardım talep, edevlet diğer talepler, edevletten talepe ihtiyaç yok, edevlet kullanımı bilgi eksiği, edevlet güven sorunu, edevlet dijital kimlik yok, edevlet işlemlerini başkası yapıyor, edevlet kullanım diğer, edevlet kullanımı zor, edevlet kullanırken teknik sorunlar, edevlet mobil erişim sorunu, edevlette diğer sorunlar, edevlette sorun yok, ekimliği özel amaç için kullanma, ekimliği kamu hizmeti için kullanma, ekimliği özel hizmet için kullanma, ekimlikten haberi yok, ekimlik yok, ekimlik var ama ihtiyaç olmadı, ekimlik var ama kullanımı güvenli değil, ekimliği teknik sorundan kullanamama, ekimlik mobil erişim yok, ekimlik var ama baska sebeplerle kullanmıyorum, eticaret kullanımı, eticaret giyim alışverişi, eticaret spor malzemesi alışverişi, eticaret çocuk oyuncakları ve bakım alışverişi, eticaret ev eşyası alışverişi, eticaret cd plak alışverişi, eticaret dvd plak alışverişi, eticaret kitap dergi alışverişi, eticaret elektronik cihazlar ve aksesuarı alışverişi, eticaret elektronik araçlar alışverişi, eticaret ilaç alışverişi, eticaret yemek siparişi, eticaret gıda ürünleri alışverişi, eticaret kozmetik alışverişi, eticaret temizlik ve kişisel bakım ürünleri alışverişi, eticaret motorlu araç yedekleri alışverişi, ...]
Index: []

[0 rows x 176 columns]

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_16636\2291217157.py:2: DtypeWarning: Columns (0: doğduğu ülke kodu, 1: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,2,1,1,45,3,NaN,1,NaN,...,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,1,2,25,512,NaN,1,NaN,...,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,1,1,58,2,NaN,3,5.0,...,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,2,1,1,25,3,NaN,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10014,3,1,2,40,1,2.0,1,NaN,...,2,2,2,1,1,1,5,6,TR1,7267.153007

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_16636\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_16636\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,40,28,68,362,302,664
1,2025,ortaokul/lise,190,179,369,1893,2039,3932
2,2025,üniversite,378,266,644,1545,1532,3077
3,2025,üniversiteüstü,7,11,18,28,35,63
4,,toplam,615,484,1099,3828,3908,7736