In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\HBTKA_HANE_2023.csv" , sep=";")
df.head()

,REFERANS_YIL,BULTEN_NO,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,HANE_FAKTOR
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11289 entries, 0 to 11288
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 11289 non-null  int64
 1   BULTEN_NO                    11289 non-null  int64
 2   KAPSAMICI_KAPSAMDISI         11289 non-null  int64
 3   BT_BILG_MASAUSTU             11289 non-null  int64
 4   BT_BILG_DIZUSTU              11289 non-null  int64
 5   BT_TABLET                    11289 non-null  int64
 6   BT_TEL_CEP                   11289 non-null  int64
 7   BT_DIGER_CIHAZ               11289 non-null  int64
 8   HANE_INTERNET_ERISIM_DURUMU  11289 non-null  int64
 9   hane_aylik_gelir_grp_5       11289 non-null  int64
 10  HHB                          11289 non-null  int64
 11  IBBS_1                       11289 non-null  str
 12  HANE_FAKTOR                  11289 non-null  float64
dtypes: float64(1), int64(11), str(1)
memory usage: 1.1 MB

In [7]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)

In [8]:
df.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497

In [9]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2023temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2023temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,2,1,1,1,1,1,2,1,TR1,4852.032646
2,2023,10013,1,2,2,2,1,2,1,1,1,TR1,4034.256095
3,2023,10014,1,2,2,2,1,1,1,5,6,TR1,7267.153007
4,2023,10015,1,2,2,2,1,2,1,1,1,TR1,4107.325497