In [2]:
import pandas as pd

df = pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2024_fert.xlsx")

df.head()

,BULTEN_NO,REFERANS_YIL,FERTNO,CINSIYET,YAS,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,CALISMAMA_NEDEN,ISTEKI_DURUM,...,CIHAZ_ALIS_FIYAT,CIHAZ_ALIS_MARKA_TASARIM,CIHAZ_ALIS_DONANIM,CIHAZ_CEVRECITASARIM,CIHAZ_ALIS_EKGARANTI,CIHAZ_ALIS_ENERJIVERIMLILIK,CIHAZ_ALIS_GERIALMA,CIHAZ_ALIS_BASKANEDEN,CIHAZ_ALIS_YOK,fert_faktor
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,2.0,1.0,1.0,1.0,2.0,1.0,1.0,NaN,NaN,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1.0,1.0,1.0,2.0,2.0,1.0,2.0,NaN,NaN,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,4061.128983

In [3]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [5]:
df.rename(columns={"FERTNO": "fert no"}, inplace=True)

In [6]:
df.rename(columns={"CINSIYET": "cinsiyet"}, inplace=True)

In [10]:
df.rename(columns={"YAS": "yaş"}, inplace=True)

In [11]:
df.rename(columns={"OKUL_BITEN": "eğitim"}, inplace=True)

In [13]:
df.rename(columns={"OKUMA_YAZMA": "okuma yazma durumu"}, inplace=True)

In [15]:
df.rename(columns={"CALISMA_DURUM": "çalışma durumu"}, inplace=True)

In [16]:
df.rename(columns={"CALISMAMA_NEDEN": "çalışmama nedeni"}, inplace=True)

In [18]:
df.rename(columns={"ISTEKI_DURUM": "işteki durumu"}, inplace=True)

In [19]:
df.rename(columns={"ISCO08": "uluslararası meslek"}, inplace=True)

In [21]:
df.rename(columns={"DOGUM_YER": "doğduğu ülke"}, inplace=True)

In [22]:
df.rename(columns={"DOGUM_YER_ULKE_KOD": "doğduğu ülke kodu"}, inplace=True)

In [23]:
df.rename(columns={"UYRUK": "uyruk"}, inplace=True)

In [24]:
df.rename(columns={"UYRUK_ULKE_KOD": "uyruk ülke kodu"}, inplace=True)

In [26]:
df.rename(columns={"KULLANIM_CEP": "cep telefonu kullanımı"}, inplace=True)

In [28]:
df.rename(columns={"CEP_SAHIP": "cep telefonuna sahip"}, inplace=True)

In [30]:
df.rename(columns={"SON_KULLANIM_INTERNET": "en son internet ne zaman kullanıldı"}, inplace=True)

In [34]:
df.rename(columns={"KULLANIM_SIKLIK_INTERNET": "internet kullanım sıklığı"}, inplace=True)

In [36]:
df.rename(columns={"INT_FAAL_EPOSTA": "eposta kullanımı"}, inplace=True)

In [38]:
df.rename(columns={"INT_FAAL_TELEFON": "internet araması"}, inplace=True)
df.rename(columns={"INT_FAAL_SOSYAL_GRKATILIM": "sosyal medya kullanımı"}, inplace=True)
df.rename(columns={"INT_FAAL_MESAJ": "sosyal medyada mesajlaşma"}, inplace=True)

In [41]:
df.rename(columns={"INT_FAAL_ONLINE_HABER": "online haber okuma"}, inplace=True)

In [43]:
df.rename(columns={"INT_FAAL_MALHIZ_BILGI": "ürün hizmet arama"}, inplace=True)

In [45]:
df.rename(columns={"INT_FAAL_WEBSITE_PAYLASIM": "websitesinde içerik paylaşma"}, inplace=True)
df.rename(columns={"INT_FAAL_OYL_KTLM": "internetten oy katılım"}, inplace=True)

In [47]:
cols = list(df.columns)
len(cols), cols[29:40], cols[29:40]

(158,
 ['INT_FAAL_MUZIK_DINLM',
  'INT_FAAL_TV',
  'INT_FAAL_UCRVIDEO_IZLM',
  'INT_FAAL_PAYVIDEO_IZLM',
  'INT_FAAL_OYUN_INDIR_OYNAT',
  'INT_FAAL_PODCAST',
  'INT_FAAL_SAGLIK_BILGI_ARM',
  'INT_FAAL_SAGLIK_RANDEVU_AL',
  'INT_FAAL_SAGLIK_SONUC_AL',
  'INT_FAAL_SAGLIK_TIBKONS_RECETE',
  'INT_FAAL_MALHIZMET_SATIS'],
 ['INT_FAAL_MUZIK_DINLM',
  'INT_FAAL_TV',
  'INT_FAAL_UCRVIDEO_IZLM',
  'INT_FAAL_PAYVIDEO_IZLM',
  'INT_FAAL_OYUN_INDIR_OYNAT',
  'INT_FAAL_PODCAST',
  'INT_FAAL_SAGLIK_BILGI_ARM',
  'INT_FAAL_SAGLIK_RANDEVU_AL',
  'INT_FAAL_SAGLIK_SONUC_AL',
  'INT_FAAL_SAGLIK_TIBKONS_RECETE',
  'INT_FAAL_MALHIZMET_SATIS'])

In [48]:
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,CIHAZ_ALIS_FIYAT,CIHAZ_ALIS_MARKA_TASARIM,CIHAZ_ALIS_DONANIM,CIHAZ_CEVRECITASARIM,CIHAZ_ALIS_EKGARANTI,CIHAZ_ALIS_ENERJIVERIMLILIK,CIHAZ_ALIS_GERIALMA,CIHAZ_ALIS_BASKANEDEN,CIHAZ_ALIS_YOK,fert_faktor
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,2.0,1.0,1.0,1.0,2.0,1.0,1.0,NaN,NaN,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1.0,1.0,1.0,2.0,2.0,1.0,2.0,NaN,NaN,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,4061.128983