In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2024_hh.xlsx")
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_AKILLITV,BT_AKILLISAAT,BT_OYUNKONSOL,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,HANE_FAKTOR
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12159 entries, 0 to 12158
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 12159 non-null  int64
 1   BULTEN_NO                    12159 non-null  int64
 2   BT_BILG_MASAUSTU             12159 non-null  int64
 3   BT_BILG_DIZUSTU              12159 non-null  int64
 4   BT_TABLET                    12159 non-null  int64
 5   BT_TEL_CEP                   12159 non-null  int64
 6   BT_AKILLITV                  12159 non-null  int64
 7   BT_AKILLISAAT                12159 non-null  int64
 8   BT_OYUNKONSOL                12159 non-null  int64
 9   BT_DIGER_CIHAZ               12159 non-null  int64
 10  HANE_INTERNET_ERISIM_DURUMU  12159 non-null  int64
 11  hane_aylik_gelir_grp_5       12159 non-null  int64
 12  HHB                          12159 non-null  int64
 13  IBBS_1                       12159 non-null  str
 14  HANE_FAKTOR                  12159 non-null  float64
dtypes: float64(1), int64(13), str(1)
memory usage: 1.4 MB

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_AKILLITV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"BT_AKILLISAAT": "hanede akıllı saat var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)

In [5]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933

# 2024 yılı cross tablolarıı

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [ ]:
# =========================================================
# CİNSİYET FREKANS + YÜZDE + TOPLAM
# =========================================================

import pandas as pd

# Etiket
df["cinsiyet_label"] = df["cinsiyet"].replace({
    1: "Erkek",
    2: "Kadın"
})

# Frekans
frekans = df["cinsiyet_label"].value_counts().sort_index()

# Yüzde
yuzde = round(
    df["cinsiyet_label"].value_counts(normalize=True).sort_index() * 100,
    2
)

# Tablo
final_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
}).reset_index()

final_tablo.columns = ["cinsiyet", "toplam", "yüzde"]

# TOPLAM SATIRI
toplam_satiri = pd.DataFrame([{
    "cinsiyet": "Toplam",
    "toplam": final_tablo["toplam"].sum(),
    "yüzde": round(final_tablo["yüzde"].sum(), 2)
}])

# Birleştir
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24744\3164738277.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_label"] = df["cinsiyet"].replace({

  cinsiyet  toplam   yüzde
0    Erkek   12855   48.93
1    Kadın   13418   51.07
2   Toplam   26273  100.00

In [ ]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,7201,51.63,3690,44.17
erkek,6745,48.37,4664,55.83
toplam,13946,100.00,8354,100.00

In [3]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,678,58.0,4166,49.98
erkek,491,42.0,4170,50.02
toplam,1169,100.0,8336,100.00

In [2]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# 2023
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# HAZIR 5'Lİ GELİR GRUBU
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2024 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2024)

C:\Users\dilara\AppData\Local\Temp\ipykernel_15536\4140126126.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,1,56.12,43.88,1504,49.43,50.57,1944
1,2024,2,53.31,46.69,2523,42.45,57.55,1868
2,2024,3,50.53,49.47,2856,43.78,56.22,1720
3,2024,4,50.90,49.10,3446,41.75,58.25,1612
4,2024,5,50.18,49.82,3617,42.15,57.85,1210
5,2024,frekans,7201.00,6745.00,13946,3690.00,4664.00,8354

In [2]:
# =========================================================
# GELİR GRUBU x ETİCARET İLAÇ ALIŞVERİŞİ
# HAZIR 5'Lİ GELİR GRUBU KULLAN
# =========================================================

import pandas as pd

# =========================================================
# 5'Lİ GELİR GRUBUNU KULLAN
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2023,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(eticaret_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(eticaret_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(eticaret_var),

        # YOK
        "yok kadın":
            round(eticaret_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(eticaret_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(eticaret_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2023,

    "gelir": "frekans",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2023 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2023)

C:\Users\dilara\AppData\Local\Temp\ipykernel_10712\4051434244.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2023,1,64.29,35.71,70,56.73,43.27,698
1,2023,2,60.53,39.47,114,51.04,48.96,1295
2,2023,3,57.65,42.35,196,50.06,49.94,1602
3,2023,4,56.41,43.59,273,50.30,49.70,2203
4,2023,5,57.56,42.44,516,47.24,52.76,2538
5,2023,frekans,678.00,491.00,1169,4166.00,4170.00,8336

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_28128\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,54.29,45.71,4695,41.89,58.11,2048
1,2017,31-45,52.23,47.77,5275,43.52,56.48,2275
2,2017,46-60,49.06,50.94,3139,45.73,54.27,2620
3,2017,60+,42.65,57.35,837,45.64,54.36,1411
4,2017,toplam,7201.00,6745.00,13946,3690.00,4664.00,8354

In [ ]:
# =========================================================
# EĞİTİM x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

def egitim_kategori(x):
    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 51, 52]:
        return "üniversite"
    elif x in [6, 7, 53]:
        return "üniversiteüstü"
    else:
        return None

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in ["ilkokulvealtı", "ortaokul/lise", "üniversite", "üniversiteüstü"]:

    alt = df[df["egitim_grup"] == egitim]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "eğitim": egitim,

        "var kadın": round(eticaret_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(eticaret_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(eticaret_var),

        "yok kadın": round(eticaret_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(eticaret_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(eticaret_yok)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{
    "eğitim": "toplam",

    "var kadın": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["eticaret ilaç alışverişi"] == 2])
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_5240\2103775799.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,ilkokulvealtı,53.62,46.38,69,57.63,42.38,800
1,ortaokul/lise,55.25,44.75,467,48.36,51.64,4119
2,üniversite,52.63,47.37,76,47.45,52.55,333
3,üniversiteüstü,50.00,50.00,14,36.96,63.04,46
4,toplam,678.00,491.00,1169,4166.00,4170.00,8336

In [ ]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31336\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,61.39,38.61,417,54.45,45.55,3763
1,2024,31-45,58.71,41.29,511,49.25,50.75,3212
2,2024,46-60,53.48,46.52,187,41.00,59.00,1178
3,2024,60+,40.74,59.26,54,28.42,71.58,183
4,2024,toplam,678.00,491.00,1169,4166.00,4170.00,8336

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_18540\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,59.56,40.44,2668,55.17,44.83,3861
1,2017,ortaokul/lise,48.73,51.27,6706,34.76,65.24,3464
2,2017,üniversite,47.64,52.36,424,36.36,63.64,66
3,2017,üniversiteüstü,40.00,60.00,60,13.33,86.67,15
4,2017,toplam,7201.00,6745.00,13946,3690.00,4664.00,8354

In [ ]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_12800\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_12800\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,37,32,69,461,339,800
1,2025,ortaokul/lise,258,209,467,1992,2127,4119
2,2025,üniversite,376,243,619,1696,1675,3371
3,2025,üniversiteüstü,7,7,14,17,29,46
4,,toplam,678,491,1169,4166,4170,8336

In [3]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["randevu_alma"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["randevu_alma"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24256\566767331.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      49.91      50.09       12860      47.37      52.63        9440

In [5]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# SAĞLIK SONUÇLARINI ALMA DEĞİŞKENİ
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["saglik_sonuc"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["saglik_sonuc"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      50.03      49.97       11664      47.54      52.46       10636

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
df["hanenin aylık toplam net geliri (5'li gelir grubu)"].value_counts()

hanenin aylık toplam net geliri (5'li gelir grubu)
4    5477
1    5405
3    5187
2    5176
5    5028
Name: count, dtype: int64

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2024

# =========================================================
# DEĞİŞKENLER
# =========================================================
gelir_col = "hanenin aylık toplam net geliri (5'li gelir grubu)"
randevu_col = "randevu alma (e-nabız,mhrs vb.)"

# =========================================================
# GELİR DEĞİŞKENİNİ NUMERİK YAP
# =========================================================
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# ZORLA EŞİT 5 GRUP OLUŞTUR
# =========================================================
df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# kontrol
print(df["gelir_5li_esit"].value_counts().sort_index())


# =========================================================
# RANDEVU ALMA
# =========================================================
df["randevu_alma"] = df[randevu_col].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

for gelir in gelir_sirasi:

    alt = df[df["gelir_5li_esit"] == gelir]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["randevu_alma"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["randevu_alma"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "gelir_grubu": gelir,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["randevu_alma"] == 1]
toplam_yok_df = df[df["randevu_alma"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "gelir_grubu": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\2906205158.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_raw"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\2906205158.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_5li_esit"] = pd.qcut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\2906205158.py:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu_alma"] = df[randevu_col].replace({

gelir_5li_esit
1. grup    5255
2. grup    5254
3. grup    5255
4. grup    5254
5. grup    5255
Name: count, dtype: int64

,yıllar,gelir_grubu,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,1. grup,52.64,47.36,1461,52.68,47.32,1904
1,2024,2. grup,50.21,49.79,2432,46.66,53.34,1991
2,2024,3. grup,49.19,50.81,2639,46.25,53.75,1987
3,2024,4. grup,50.05,49.95,3053,44.63,55.37,1806
4,2024,5. grup,48.95,51.05,3275,46.52,53.48,1752
5,,toplam,49.91,50.09,12860,47.37,52.63,9440

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2024

# =========================================================
# DEĞİŞKENLER
# =========================================================
gelir_col = "hanenin aylık toplam net geliri (5'li gelir grubu)"
saglik_col = "sağlık sonuçlarını almak"

# =========================================================
# GELİRİ NUMERİK YAP
# =========================================================
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# GELİRİ ZORLA 5 EŞİT GRUBA BÖL
# =========================================================
df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# kontrol
print(df["gelir_5li_esit"].value_counts().sort_index())


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df[saglik_col].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

for gelir in gelir_sirasi:

    alt = df[df["gelir_5li_esit"] == gelir]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "gelir_grubu": gelir,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "gelir_grubu": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

gelir_5li_esit
1. grup    5255
2. grup    5254
3. grup    5255
4. grup    5254
5. grup    5255
Name: count, dtype: int64

C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\2728312279.py:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["saglik_sonuc"] = df[saglik_col].replace({

,yıllar,gelir_grubu,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,1. grup,53.44,46.56,1177,52.24,47.76,2188
1,2024,2. grup,50.64,49.36,2036,46.88,53.12,2387
2,2024,3. grup,50.00,50.00,2334,45.81,54.19,2292
3,2024,4. grup,49.58,50.42,2844,45.86,54.14,2015
4,2024,5. grup,48.82,51.18,3273,46.75,53.25,1754
5,,toplam,50.03,49.97,11664,47.54,52.46,10636

In [6]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2020

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# RANDEVU ALMA
# =========================================================
df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["randevu"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["randevu"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["randevu"] == 1]
toplam_yok_df = df[df["randevu"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\716567252.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\716567252.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2020,ilkokulvealtı,54.86,45.14,2554,58.31,41.69,3975
1,2020,ortaokul/lise,47.18,52.82,6085,39.19,60.81,4085
2,2020,üniversite,51.16,48.84,3808,40.72,59.28,1228
3,2020,üniversiteüstü,48.18,51.82,413,34.87,65.13,152
4,,toplam,49.91,50.09,12860,47.37,52.63,9440

In [7]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2024

# =========================================================
# EĞİTİM KATEGORİ FONKSİYONU
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)

        # -------------------------------------------------
        # ilkokul ve altı
        # -------------------------------------------------
        if x in [1, 2]:
            return "ilkokulvealtı"

        # -------------------------------------------------
        # ortaokul / lise
        # -------------------------------------------------
        elif x in [3, 4]:
            return "ortaokul/lise"

        # -------------------------------------------------
        # üniversite
        # -------------------------------------------------
        elif x in [511, 512, 4, 5, 6]:
            return "üniversite"

        # -------------------------------------------------
        # üniversite üstü
        # -------------------------------------------------
        elif x in [52, 53, 7]:
            return "üniversiteüstü"

        else:
            return np.nan

    except:
        return np.nan


# =========================================================
# EĞİTİM DEĞİŞKENİ
# =========================================================
df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# CROSS TABLO
# kadın/erkek yüzde
# toplam frekans
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["egitim_grup"] == egitim]

    # =====================================================
    # VAR
    # =====================================================
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_toplam = len(var_df)

    var_kadin = round(
        ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0

    var_erkek = round(
        ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
        2
    ) if var_toplam > 0 else 0


    # =====================================================
    # YOK
    # =====================================================
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_toplam = len(yok_df)

    yok_kadin = round(
        ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0

    yok_erkek = round(
        ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
        2
    ) if yok_toplam > 0 else 0


    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
final_tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_var_df = df[df["saglik_sonuc"] == 1]
toplam_yok_df = df[df["saglik_sonuc"] == 0]

toplam_var = len(toplam_var_df)
toplam_yok = len(toplam_yok_df)

toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": round(
        ((toplam_var_df["cinsiyet"] == 2).sum() / toplam_var) * 100,
        2
    ),

    "erkek_var": round(
        ((toplam_var_df["cinsiyet"] == 1).sum() / toplam_var) * 100,
        2
    ),

    "toplam_var": toplam_var,

    "kadın_yok": round(
        ((toplam_yok_df["cinsiyet"] == 2).sum() / toplam_yok) * 100,
        2
    ),

    "erkek_yok": round(
        ((toplam_yok_df["cinsiyet"] == 1).sum() / toplam_yok) * 100,
        2
    ),

    "toplam_yok": toplam_yok

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [final_tablo, toplam_satiri],
    ignore_index=True
)

display(final_tablo)


# =========================================================
# EXCEL AKTAR

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,ilkokulvealtı,54.53,45.47,1977,58.02,41.98,4552
1,2024,ortaokul/lise,47.59,52.41,5478,39.75,60.25,4692
2,2024,üniversite,51.57,48.43,3756,39.92,60.08,1280
3,2024,üniversiteüstü,47.02,52.98,453,34.82,65.18,112
4,,toplam,50.03,49.97,11664,47.54,52.46,10636

In [8]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================

df["randevu"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["randevu"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["randevu"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["randevu"] == 1]

yok_df = df[df["randevu"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_18492\3536698121.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grubu"] = df["yaş"].apply(yas_grup)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,55.03,44.97,4307,42.57,57.43,2436
1,2024,31-45,49.93,50.07,4883,49.01,50.99,2667
2,2024,46-60,45.70,54.30,2886,49.39,50.61,2873
3,2024,60+,37.24,62.76,784,48.43,51.57,1464
4,,toplam,49.91,50.09,12860,47.37,52.63,9440

In [9]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):
    if pd.isna(yas):
        return np.nan
    elif 15 <= yas <= 30:
        return "15-30"
    elif 31 <= yas <= 45:
        return "31-45"
    elif 46 <= yas <= 60:
        return "46-60"
    else:
        return "60+"

df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# SAĞLIK SONUÇLARINI ALMA
# =========================================================

df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})

# =========================================================
# CROSS TABLO
# =========================================================

sonuc = []

for grup in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grubu"] == grup]

    # VAR
    var_df = alt[alt["saglik_sonuc"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"] == 2).mean() * 100, 2
    )

    var_erkek = round(
        (var_df["cinsiyet"] == 1).mean() * 100, 2
    )

    var_toplam = len(var_df)

    # YOK
    yok_df = alt[alt["saglik_sonuc"] == 0]

    yok_kadin = round(
        (yok_df["cinsiyet"] == 2).mean() * 100, 2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"] == 1).mean() * 100, 2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıllar": 2024,

        "yaş": grup,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_df = df[df["saglik_sonuc"] == 1]

yok_df = df[df["saglik_sonuc"] == 0]

toplam_satiri = pd.DataFrame([{

    "yıllar": "",

    "yaş": "toplam",

    "kadın_var": round((var_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_var": round((var_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_var": len(var_df),

    "kadın_yok": round((yok_df["cinsiyet"] == 2).mean() * 100, 2),
    "erkek_yok": round((yok_df["cinsiyet"] == 1).mean() * 100, 2),
    "toplam_yok": len(yok_df)

}])

# =========================================================
# FİNAL TABLO
# =========================================================

final_tablo = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(final_tablo)

,yıllar,yaş,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2024,15-30,55.12,44.88,3922,44.13,55.87,2821
1,2024,31-45,49.74,50.26,4540,49.40,50.60,3010
2,2024,46-60,45.75,54.25,2551,48.97,51.03,3208
3,2024,60+,38.10,61.90,651,47.15,52.85,1597
4,,toplam,50.03,49.97,11664,47.54,52.46,10636

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# YAŞ GRUPLARI
# =========================================================

def yas_grup(yas):

    if pd.isna(yas):
        return np.nan

    elif 15 <= yas <= 30:
        return "15-30"

    elif 31 <= yas <= 45:
        return "31-45"

    elif 46 <= yas <= 60:
        return "46-60"

    else:
        return "60+"

# yeni değişken
df["yas_grubu"] = df["yaş"].apply(yas_grup)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

frekans = df["yas_grubu"].value_counts().sort_index()

yuzde = round(
    df["yas_grubu"].value_counts(normalize=True).sort_index() * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

yas_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# toplam satırı
toplam_satiri = pd.DataFrame({
    "toplam": [yas_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

yas_tablo = pd.concat([yas_tablo, toplam_satiri])

display(yas_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

        toplam   yüzde
15-30     7015   26.70
31-45     7937   30.21
46-60     6929   26.37
60+       4392   16.72
toplam   26273  100.00

In [5]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM GRUPLAMA
# =========================================================
def egitim_kategori(x):
    try:
        x = int(x)
    except:
        return np.nan

    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 6, 51, 511, 512]:
        return "üniversite"
    elif x in [7, 52, 53]:
        return "üniversiteüstü"
    else:
        return np.nan

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# FREKANS + YÜZDE
# =========================================================
egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

frekans = df["egitim_grup"].value_counts().reindex(egitim_sirasi)
yuzde = round(df["egitim_grup"].value_counts(normalize=True).reindex(egitim_sirasi) * 100, 2)

egitim_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame({
    "toplam": [egitim_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

egitim_tablo = pd.concat([egitim_tablo, toplam_satiri])

display(egitim_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

                toplam   yüzde
ilkokulvealtı     9942   37.84
ortaokul/lise    10686   40.67
üniversite        5080   19.34
üniversiteüstü     565    2.15
toplam           26273  100.00

In [1]:
import pandas as pd
import numpy as np

# =========================================================
# GELİR DEĞİŞKENİ
# =========================================================

gelir_col = "hanenin aylık toplam net geliri (5'li gelir grubu)"

# numerik yap
df["gelir_raw"] = pd.to_numeric(
    df[gelir_col],
    errors="coerce"
)

# =========================================================
# ZORLA EŞİT 5 GRUP
# =========================================================

df["gelir_5li_esit"] = pd.qcut(
    df["gelir_raw"].rank(method="first"),
    q=5,
    labels=[
        "1. grup",
        "2. grup",
        "3. grup",
        "4. grup",
        "5. grup"
    ]
)

# =========================================================
# FREKANS + YÜZDE
# =========================================================

gelir_sirasi = [
    "1. grup",
    "2. grup",
    "3. grup",
    "4. grup",
    "5. grup"
]

frekans = (
    df["gelir_5li_esit"]
    .value_counts()
    .reindex(gelir_sirasi)
)

yuzde = round(
    (
        df["gelir_5li_esit"]
        .value_counts(normalize=True)
        .reindex(gelir_sirasi)
    ) * 100,
    2
)

# =========================================================
# TABLO
# =========================================================

gelir_tablo = pd.DataFrame({
    "toplam": frekans,
    "yüzde": yuzde
})

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame({
    "toplam": [gelir_tablo["toplam"].sum()],
    "yüzde": [100]
}, index=["toplam"])

gelir_tablo = pd.concat(
    [gelir_tablo, toplam_satiri]
)

display(gelir_tablo)

# =========================================================
# EXCEL AKTAR
# =========================================================

NameError: name 'df' is not defined

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# =====================================================
# MODEL 1 - PROBIT MODEL
# Bağımlı değişken: Online sağlık hizmeti kullanımı
# Gelir: 5'li gelir grubu
# Eğitim: Orta/Lise, Üniversite, Doktora ayrı
# =====================================================

# 1) ONLINE SAĞLIK
df["online_saglik"] = df["sağlık bilgisi arama"].replace({
    "Evet": 1, "Hayır": 0,
    "evet": 1, "hayır": 0,
    "EVET": 1, "HAYIR": 0,
    1: 1, 2: 0, 0: 0
})

# 2) CİNSİYET
df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0, "Kadın": 1,
    "erkek": 0, "kadın": 1,
    "ERKEK": 0, "KADIN": 1,
    1: 0, 2: 1
})

# 3) YAŞ KATEGORİLERİ
df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=["15-30", "31-45", "46-60", "60+"]
)

yas_dummy = pd.get_dummies(df["yas_grup"], prefix="yas")
yas_dummy = yas_dummy.drop(columns=["yas_15-30"], errors="ignore")

# 4) EĞİTİM KATEGORİLERİ
df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")

def egitim_kategori(x):
    if x in [1]:
        return "Ilkokul_ve_alti"
    elif x in [2, 3, 4]:
        return "Orta_Lise"
    elif x in [511, 512, 52]:
        return "Universite"
    elif x in [53]:
        return "Doktora"
    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)

egitim_dummy = pd.get_dummies(df["egitim_grup"], prefix="egitim")

# Referans eğitim grubu: İlkokul ve altı
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# 5) GELİR - 5'Lİ GELİR GRUBU
df["gelir"] = pd.to_numeric(
    df["hanenin aylık toplam net geliri (5'li gelir grubu)"],
    errors="coerce"
)

df["log_gelir"] = np.log1p(df["gelir"])

# 6) MODEL DATAFRAME
model_df = pd.concat(
    [
        df[["online_saglik", "cinsiyet_kadin", "log_gelir"]],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

model_df = model_df.apply(pd.to_numeric, errors="coerce")

print("Dropna öncesi satır sayısı:", len(model_df))
print("\nEksik değer sayıları:")
print(model_df.isna().sum())

model_df = model_df.dropna()

print("\nDropna sonrası satır sayısı:", len(model_df))

# 7) X ve y
y = model_df["online_saglik"]
X = model_df.drop(columns=["online_saglik"])

X = sm.add_constant(X)

X = X.astype(float)
y = y.astype(float)

# 8) KONTROLLER
print("\nBağımlı değişken dağılımı:")
print(y.value_counts())

print("\nEğitim grubu dağılımı:")
print(df["egitim_grup"].value_counts(dropna=False))

print("\nGelir dağılımı:")
print(df["gelir"].value_counts(dropna=False).sort_index())

print("\nModel değişkenleri:")
print(X.columns)

# 9) PROBIT MODEL
probit_model = sm.Probit(y, X)
result = probit_model.fit()

print(result.summary().as_text())

C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["online_saglik"] = df["sağlık bilgisi arama"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(df["yaş"], errors="coerce")
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:31: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(df["eğitim"], errors="coerce")
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:55: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:66: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_10444\2427353671.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

Dropna öncesi satır sayısı: 26273

Eksik değer sayıları:
online_saglik        3973
cinsiyet_kadin          0
log_gelir               0
yas_31-45               0
yas_46-60               0
yas_60+                 0
egitim_Doktora          0
egitim_Orta_Lise        0
egitim_Universite       0
dtype: int64

Dropna sonrası satır sayısı: 22300

Bağımlı değişken dağılımı:
online_saglik
1.0    13946
0.0     8354
Name: count, dtype: int64

Eğitim grubu dağılımı:
egitim_grup
Orta_Lise          18288
Universite          5570
Ilkokul_ve_alti     2340
Doktora               75
Name: count, dtype: int64

Gelir dağılımı:
gelir
1    5405
2    5176
3    5187
4    5477
5    5028
Name: count, dtype: int64

Model değişkenleri:
Index(['const', 'cinsiyet_kadin', 'log_gelir', 'yas_31-45', 'yas_46-60',
       'yas_60+', 'egitim_Doktora', 'egitim_Orta_Lise', 'egitim_Universite'],
      dtype='str')
Optimization terminated successfully.
         Current function value: 0.596308
         Iterations 5
                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                22300
Model:                         Probit   Df Residuals:                    22291
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.09837
Time:                        10:18:17   Log-Likelihood:                -13298.
converged:                       True   LL-Null:                       -14749.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -1.2390      0.062    -19.920      0.000      -1.361      -1.117
cinsiyet_kadin        0.2451      0.018     13.587      0.000       0.210       0.280
log_gelir             0.4185      0.025     16.426      0.000       0.369       0.468
yas_31-45             0.0151      0.023      0.661      0.508      -0.030       0.060
yas_46-60            -0.3123      0.024    -13.167      0.000      -0.359      -0.266
yas_60+              -0.6716      0.033    -20.607      0.000      -0.735      -0.608
egitim_Doktora        1.5282      0.177      8.647      0.000       1.182       1.875
egitim_Orta_Lise      0.9418      0.051     18.403      0.000       0.841       1.042
egitim_Universite     1.4838      0.055     27.065      0.000       1.376       1.591
=====================================================================================

In [3]:
summary_text = result.summary().as_text()

print(summary_text)

                          Probit Regression Results
==============================================================================
Dep. Variable:          online_saglik   No. Observations:                22300
Model:                         Probit   Df Residuals:                    22291
Method:                           MLE   Df Model:                            8
Date:                Fri, 15 May 2026   Pseudo R-squ.:                 0.09837
Time:                        10:18:19   Log-Likelihood:                -13298.
converged:                       True   LL-Null:                       -14749.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -1.2390      0.062    -19.920      0.000      -1.361      -1.117
cinsiyet_kadin        0.2451      0.018     13.587      0.000       0.210       0.280
log_gelir             0.4185      0.025     16.426      0.000       0.369       0.468
yas_31-45             0.0151      0.023      0.661      0.508      -0.030       0.060
yas_46-60            -0.3123      0.024    -13.167      0.000      -0.359      -0.266
yas_60+              -0.6716      0.033    -20.607      0.000      -0.735      -0.608
egitim_Doktora        1.5282      0.177      8.647      0.000       1.182       1.875
egitim_Orta_Lise      0.9418      0.051     18.403      0.000       0.841       1.042
egitim_Universite     1.4838      0.055     27.065      0.000       1.376       1.591
=====================================================================================

In [4]:
# 10) MARGINAL EFFECTS
marginal = result.get_margeff()
print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          online_saglik
Method:                          dydx
At:                           overall
=====================================================================================
                       dy/dx    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
cinsiyet_kadin        0.0832      0.006     13.750      0.000       0.071       0.095
log_gelir             0.1421      0.008     16.724      0.000       0.125       0.159
yas_31-45             0.0051      0.008      0.661      0.508      -0.010       0.020
yas_46-60            -0.1060      0.008    -13.318      0.000      -0.122      -0.090
yas_60+              -0.2280      0.011    -21.220      0.000      -0.249      -0.207
egitim_Doktora        0.5188      0.060      8.688      0.000       0.402       0.636
egitim_Orta_Lise      0.3197      0.017     18.818      0.000       0.286       0.353
egitim_Universite     0.5037      0.018     28.387      0.000       0.469       0.538
=====================================================================================

In [2]:
# =====================================================
# ETİCARET İLAÇ ALIŞVERİŞİ - PROBIT MODEL
# GELİR = 5'Lİ GELİR GRUBU
# =====================================================

import pandas as pd
import numpy as np
import statsmodels.api as sm

# -----------------------------------------------------
# BAĞIMLI DEĞİŞKEN
# -----------------------------------------------------

df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    "evet": 1,
    "hayır": 0,
    1: 1,
    2: 0,
    0: 0
})

# -----------------------------------------------------
# CİNSİYET
# -----------------------------------------------------

df["cinsiyet_kadin"] = df["cinsiyet"].replace({
    "Erkek": 0,
    "Kadın": 1,
    "erkek": 0,
    "kadın": 1,
    1: 0,
    2: 1
})

# -----------------------------------------------------
# YAŞ
# -----------------------------------------------------

df["yas"] = pd.to_numeric(
    df["yaş"],
    errors="coerce"
)

df["yas_grup"] = pd.cut(
    df["yas"],
    bins=[14, 30, 45, 60, 120],
    labels=[
        "15-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

yas_dummy = pd.get_dummies(
    df["yas_grup"],
    prefix="yas"
)

# REFERANS
yas_dummy = yas_dummy.drop(
    columns=["yas_15-30"],
    errors="ignore"
)

# -----------------------------------------------------
# EĞİTİM
# -----------------------------------------------------

df["egitim_sayi"] = pd.to_numeric(
    df["eğitim"],
    errors="coerce"
)

def egitim_kategori(x):

    # REFERANS
    if x in [1, 2]:
        return "Ilkokul_ve_alti"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "Ortaokul_Lise"

    # ÜNİVERSİTE
    elif x in [51, 511, 512]:
        return "Universite"

    # ÜNİVERSİTEÜSTÜ
    elif x in [52, 53]:
        return "Universiteustu"

    else:
        return np.nan

df["egitim_grup"] = df["egitim_sayi"].apply(
    egitim_kategori
)

egitim_dummy = pd.get_dummies(
    df["egitim_grup"],
    prefix="egitim"
)

# REFERANS
egitim_dummy = egitim_dummy.drop(
    columns=["egitim_Ilkokul_ve_alti"],
    errors="ignore"
)

# -----------------------------------------------------
# GELİR
# 5'Lİ GELİR GRUBU
# -----------------------------------------------------

df["gelir"] = pd.to_numeric(
    df["hanenin aylık toplam net geliri (5'li gelir grubu)"],
    errors="coerce"
)

# LOG GELİR
df["log_gelir"] = np.log1p(df["gelir"])

# -----------------------------------------------------
# MODEL DATAFRAME
# -----------------------------------------------------

model_df = pd.concat(
    [
        df[
            [
                "eticaret_ilac",
                "cinsiyet_kadin",
                "log_gelir"
            ]
        ],
        yas_dummy,
        egitim_dummy
    ],
    axis=1
)

# -----------------------------------------------------
# SAYISALA ÇEVİR
# -----------------------------------------------------

model_df = model_df.apply(
    pd.to_numeric,
    errors="coerce"
)

# -----------------------------------------------------
# EKSİKLERİ TEMİZLE
# -----------------------------------------------------

model_df = model_df.dropna()

# -----------------------------------------------------
# X ve y
# -----------------------------------------------------

y = model_df["eticaret_ilac"]

X = model_df.drop(
    columns=["eticaret_ilac"]
)

# CONSTANT
X = sm.add_constant(X)

# FLOAT
X = X.astype(float)
y = y.astype(float)

# -----------------------------------------------------
# MODEL
# -----------------------------------------------------

probit_model = sm.Probit(y, X)

result = probit_model.fit()

# -----------------------------------------------------
# SONUÇLAR
# -----------------------------------------------------

summary_text = result.summary().as_text()

print(summary_text)

Optimization terminated successfully.
         Current function value: 0.362574
         Iterations 6
                          Probit Regression Results
==============================================================================
Dep. Variable:          eticaret_ilac   No. Observations:                 9505
Model:                         Probit   Df Residuals:                     9496
Method:                           MLE   Df Model:                            8
Date:                Sat, 16 May 2026   Pseudo R-squ.:                 0.02752
Time:                        18:44:46   Log-Likelihood:                -3446.3
converged:                       True   LL-Null:                       -3543.8
Covariance Type:            nonrobust   LLR p-value:                 6.941e-38
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -2.1278      0.105    -20.199      0.000      -2.334      -1.921
cinsiyet_kadin            0.2080      0.034      6.102      0.000       0.141       0.275
log_gelir                 0.2985      0.057      5.228      0.000       0.187       0.410
yas_31-45                 0.1652      0.039      4.289      0.000       0.090       0.241
yas_46-60                 0.2094      0.052      3.995      0.000       0.107       0.312
yas_60+                   0.6321      0.096      6.590      0.000       0.444       0.820
egitim_Ortaokul_Lise      0.2256      0.070      3.237      0.001       0.089       0.362
egitim_Universite         0.3884      0.070      5.520      0.000       0.250       0.526
egitim_Universiteustu     0.4936      0.094      5.263      0.000       0.310       0.677
=========================================================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eticaret_ilac"] = df["eticaret ilaç alışverişi"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["cinsiyet_kadin"] = df["cinsiyet"].replace({
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:46: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:72: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_sayi"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["egitim_sayi"].apply(
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir"] = pd.to_numeric(
C:\Users\dilara\AppData\Local\Temp\ipykernel_2280\686088388.py:124: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["log_gelir"] = np.log1p(df["gelir"])

In [3]:
# -----------------------------------------------------
# MARJİNAL ETKİLER
# -----------------------------------------------------

marginal = result.get_margeff()

print(marginal.summary())

       Probit Marginal Effects
=====================================
Dep. Variable:          eticaret_ilac
Method:                          dydx
At:                           overall
=========================================================================================
                           dy/dx    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
cinsiyet_kadin            0.0412      0.007      6.104      0.000       0.028       0.054
log_gelir                 0.0591      0.011      5.227      0.000       0.037       0.081
yas_31-45                 0.0327      0.008      4.290      0.000       0.018       0.048
yas_46-60                 0.0415      0.010      3.996      0.000       0.021       0.062
yas_60+                   0.1252      0.019      6.600      0.000       0.088       0.162
egitim_Ortaokul_Lise      0.0447      0.014      3.237      0.001       0.018       0.072
egitim_Universite         0.0770      0.014      5.520      0.000       0.050       0.104
egitim_Universiteustu     0.0978      0.019      5.266      0.000       0.061       0.134
=========================================================================================