In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2024_hh.xlsx")
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_AKILLITV,BT_AKILLISAAT,BT_OYUNKONSOL,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,HANE_FAKTOR
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12159 entries, 0 to 12158
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 12159 non-null  int64
 1   BULTEN_NO                    12159 non-null  int64
 2   BT_BILG_MASAUSTU             12159 non-null  int64
 3   BT_BILG_DIZUSTU              12159 non-null  int64
 4   BT_TABLET                    12159 non-null  int64
 5   BT_TEL_CEP                   12159 non-null  int64
 6   BT_AKILLITV                  12159 non-null  int64
 7   BT_AKILLISAAT                12159 non-null  int64
 8   BT_OYUNKONSOL                12159 non-null  int64
 9   BT_DIGER_CIHAZ               12159 non-null  int64
 10  HANE_INTERNET_ERISIM_DURUMU  12159 non-null  int64
 11  hane_aylik_gelir_grp_5       12159 non-null  int64
 12  HHB                          12159 non-null  int64
 13  IBBS_1                       12159 non-null  str
 14  HANE_FAKTOR                  12159 non-null  float64
dtypes: float64(1), int64(13), str(1)
memory usage: 1.4 MB

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_AKILLITV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"BT_AKILLISAAT": "hanede akıllı saat var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)

In [5]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933

# 2024 yılı cross tablolarıı

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [ ]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,7201,51.63,3690,44.17
erkek,6745,48.37,4664,55.83
toplam,13946,100.00,8354,100.00

In [3]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

,eticaret ilaç alışverişi var,eticaret ilaç alışverişi var yüzde,eticaret ilaç alışverişi yok,eticaret ilaç alışverişi yok yüzde
kadın,678,58.0,4166,49.98
erkek,491,42.0,4170,50.02
toplam,1169,100.0,8336,100.00

In [2]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# 2023
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# HAZIR 5'Lİ GELİR GRUBU
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2024 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2024)

C:\Users\dilara\AppData\Local\Temp\ipykernel_15536\4140126126.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,1,56.12,43.88,1504,49.43,50.57,1944
1,2024,2,53.31,46.69,2523,42.45,57.55,1868
2,2024,3,50.53,49.47,2856,43.78,56.22,1720
3,2024,4,50.90,49.10,3446,41.75,58.25,1612
4,2024,5,50.18,49.82,3617,42.15,57.85,1210
5,2024,frekans,7201.00,6745.00,13946,3690.00,4664.00,8354

In [2]:
# =========================================================
# GELİR GRUBU x ETİCARET İLAÇ ALIŞVERİŞİ
# HAZIR 5'Lİ GELİR GRUBU KULLAN
# =========================================================

import pandas as pd

# =========================================================
# 5'Lİ GELİR GRUBUNU KULLAN
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2023,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(eticaret_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(eticaret_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(eticaret_var),

        # YOK
        "yok kadın":
            round(eticaret_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(eticaret_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(eticaret_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2023,

    "gelir": "frekans",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_eticaret_2023 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_eticaret_2023)

C:\Users\dilara\AppData\Local\Temp\ipykernel_10712\4051434244.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2023,1,64.29,35.71,70,56.73,43.27,698
1,2023,2,60.53,39.47,114,51.04,48.96,1295
2,2023,3,57.65,42.35,196,50.06,49.94,1602
3,2023,4,56.41,43.59,273,50.30,49.70,2203
4,2023,5,57.56,42.44,516,47.24,52.76,2538
5,2023,frekans,678.00,491.00,1169,4166.00,4170.00,8336

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_28128\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,54.29,45.71,4695,41.89,58.11,2048
1,2017,31-45,52.23,47.77,5275,43.52,56.48,2275
2,2017,46-60,49.06,50.94,3139,45.73,54.27,2620
3,2017,60+,42.65,57.35,837,45.64,54.36,1411
4,2017,toplam,7201.00,6745.00,13946,3690.00,4664.00,8354

In [ ]:
# =========================================================
# EĞİTİM x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

def egitim_kategori(x):
    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 51, 52]:
        return "üniversite"
    elif x in [6, 7, 53]:
        return "üniversiteüstü"
    else:
        return None

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in ["ilkokulvealtı", "ortaokul/lise", "üniversite", "üniversiteüstü"]:

    alt = df[df["egitim_grup"] == egitim]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "eğitim": egitim,

        "var kadın": round(eticaret_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(eticaret_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(eticaret_var),

        "yok kadın": round(eticaret_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(eticaret_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(eticaret_yok)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{
    "eğitim": "toplam",

    "var kadın": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["eticaret ilaç alışverişi"] == 2])
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_5240\2103775799.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,ilkokulvealtı,53.62,46.38,69,57.63,42.38,800
1,ortaokul/lise,55.25,44.75,467,48.36,51.64,4119
2,üniversite,52.63,47.37,76,47.45,52.55,333
3,üniversiteüstü,50.00,50.00,14,36.96,63.04,46
4,toplam,678.00,491.00,1169,4166.00,4170.00,8336

In [ ]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
# =========================================================
# YAŞ x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# YAŞ GRUPLARI
# =========================================================

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    var_df = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    var_cinsiyet = (
        var_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    yok_df = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    yok_cinsiyet = (
        yok_df["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2024,

        "yaş": yas,

        # VAR
        "var kadın":
            round(var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(var_df),

        # YOK
        "yok kadın":
            round(yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(yok_df)

    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2024,

    "yaş": "toplam",

    "var kadın":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["eticaret ilaç alışverişi"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

yas_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_31336\2876047059.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2024,15-30,61.39,38.61,417,54.45,45.55,3763
1,2024,31-45,58.71,41.29,511,49.25,50.75,3212
2,2024,46-60,53.48,46.52,187,41.00,59.00,1178
3,2024,60+,40.74,59.26,54,28.42,71.58,183
4,2024,toplam,678.00,491.00,1169,4166.00,4170.00,8336

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_18540\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,59.56,40.44,2668,55.17,44.83,3861
1,2017,ortaokul/lise,48.73,51.27,6706,34.76,65.24,3464
2,2017,üniversite,47.64,52.36,424,36.36,63.64,66
3,2017,üniversiteüstü,40.00,60.00,60,13.33,86.67,15
4,2017,toplam,7201.00,6745.00,13946,3690.00,4664.00,8354

In [ ]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv")
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,...,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,...,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
2,10012,2024,2,2,40,52,NaN,1,NaN,1.0,...,1,1,1,2,1,1,5,2,TR1,4555.431051
3,10013,2024,1,2,27,4,NaN,1,NaN,1.0,...,1,1,1,1,1,1,3,2,TR1,4061.128983
4,10013,2024,2,1,24,4,NaN,3,3.0,NaN,...,1,1,1,1,1,1,3,2,TR1,4061.128983

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_12800\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)
C:\Users\dilara\AppData\Local\Temp\ipykernel_12800\1077536611.py:57: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({

,yıllar,eğitim,kadın_var,erkek_var,toplam_var,kadın_yok,erkek_yok,toplam_yok
0,2025,ilkokulvealtı,37,32,69,461,339,800
1,2025,ortaokul/lise,258,209,467,1992,2127,4119
2,2025,üniversite,376,243,619,1696,1675,3371
3,2025,üniversiteüstü,7,7,14,17,29,46
4,,toplam,678,491,1169,4166,4170,8336

In [3]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# RANDEVU ALMA DEĞİŞKENİ
# =========================================================
df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["randevu_alma"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["randevu_alma"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24256\566767331.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["randevu_alma"] = df["randevu alma (e-nabız,mhrs vb.)"].replace({

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      49.91      50.09       12860      47.37      52.63        9440

In [5]:
import pandas as pd

# =========================================================
# YIL
# =========================================================
YIL = 2020


# =========================================================
# SAĞLIK SONUÇLARINI ALMA DEĞİŞKENİ
# =========================================================
df["saglik_sonuc"] = df["sağlık sonuçlarını almak"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# VAR
# =========================================================
var_df = df[df["saglik_sonuc"] == 1]

var_toplam = len(var_df)

var_kadin = round(
    ((var_df["cinsiyet"] == 2).sum() / var_toplam) * 100,
    2
)

var_erkek = round(
    ((var_df["cinsiyet"] == 1).sum() / var_toplam) * 100,
    2
)


# =========================================================
# YOK
# =========================================================
yok_df = df[df["saglik_sonuc"] == 0]

yok_toplam = len(yok_df)

yok_kadin = round(
    ((yok_df["cinsiyet"] == 2).sum() / yok_toplam) * 100,
    2
)

yok_erkek = round(
    ((yok_df["cinsiyet"] == 1).sum() / yok_toplam) * 100,
    2
)


# =========================================================
# TABLO
# =========================================================
final_tablo = pd.DataFrame([{

    "yıllar": YIL,

    "kadın_var": var_kadin,
    "erkek_var": var_erkek,
    "toplam_var": var_toplam,

    "kadın_yok": yok_kadin,
    "erkek_yok": yok_erkek,
    "toplam_yok": yok_toplam

}])


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)

   yıllar  kadın_var  erkek_var  toplam_var  kadın_yok  erkek_yok  toplam_yok
0    2020      50.03      49.97       11664      47.54      52.46       10636