In [1]:
import pandas as pd 

df = pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\cbtka_2024_tr.xlsx")
df.head()

,BULTEN_NO,FERTNO,CINSIYET,DOGUM_TARIH_GUN,DOGUM_TARIH_AY,DOGUM_TARIH_YIL,YAS,DOGUM_YER,DOGUM_YER_ULKE_KOD,UYRUK,...,DIJITALOYUN_FAZLA_ZAMAN_EBVEYN,DIJITALOYUN_OYNAMAMA_MUTSUZ,DIJITALOYUN_SORMLULUK_AKSATMA,DIJITALOYUN_PLAN_SURE_ASIMI,EKRAN_NEDEN_AZ_DERS_CALISMA,EKRAN_NEDEN_AZ_ZAMAN_AILE,EKRAN_NEDEN_AZ_KITAP_OKUMA,EKRAN_NEDEN_AZ_UYKU,EKRAN_NEDEN_AZ_ZAMAN_ARKADAS,FAKTOR
0,1000068682,3,2,29.0,11.0,2008,15,1,NaN,1,...,NaN,NaN,NaN,NaN,1,2,1,1,2,2708.208779
1,1000610731,2,1,19.0,1.0,2010,14,1,NaN,1,...,2.0,2.0,2.0,2.0,1,1,2,2,2,2702.125252
2,1000610731,5,2,3.0,12.0,2008,15,1,NaN,1,...,NaN,NaN,NaN,NaN,2,2,2,2,2,2702.125252
3,1000610731,6,2,12.0,7.0,2011,12,1,NaN,1,...,NaN,NaN,NaN,NaN,2,2,1,2,2,2702.125252
4,1000952935,5,2,13.0,3.0,2013,11,1,NaN,1,...,2.0,1.0,1.0,2.0,2,2,2,2,2,1373.157249

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [5]:
df

,bülten no,fert no,cinsiyet,doğum tarihi gün,doğum tarihi ay,doğum tarihi yıl,yaş,doğum yeri,doğum yeri ülke kodu,uyruk,uyruk ülke kodu,HHSORUMLU_YAKINLIK,OKUL_BITEN,OKUMA_YAZMA,EGITIM_DEVAM,OKUL_DEVAM,KENDI_KUL_MASAUSTU,KENDI_KUL_DIZUSTU,KENDI_KUL_TABLET,KENDI_KUL_CEP,KENDI_KUL_SAAT,KENDI_KUL_OYN_KNSL,BILG_OYUN_SIKLIK,SPOR_YAPMA_SIKLIK,KITAP_OKUMA_SIKLIK,DIGER_HOBI_SIKLIK,EGLENME_DISARI_SIKLIK,INT_GEZINME_SIKLIK,TV_IZLEME_SIKLIK,CEP_KULLANIM,CEP_KULLANIM_SIKLIK,CEP_SURE_HAFTAICI,CEP_SURE_HAFTASONU,CEP_AMAC_KONUSMA,CEP_AMAC_MESAJ,CEP_AMAC_SOSYALMEDYA,CEP_AMAC_OYUN,CEP_AMAC_FILM,CEP_AMAC_MUZK,CEP_AMAC_INTERNET,CEP_AMAC_DERS,CEP_AMAC_DERS_ONLINE,CEP_KONT_YARIMSAAT,CEP_KONT_UYKU_ONCESI,CEP_KONT_UYANINCA,CEP_KONT_TV_IZLERKEN,CEP_KONT_TOPLU_YEMEK,BILGISAYAR_KULLANIM,BILG_TUR_MASAUSTU,BILG_TUR_DIZUSTU,BILG_TUR_TABLET,BILG_KULLANIM_SIKLIK,BILG_SURE_HAFTAICI,BILG_SURE_HAFTASONU,BILG_FAAL_OYUN,BILG_FAAL_DERS,BILG_FAAL_ONLINEDERS,BILG_FAAL_FILM_MUZIK,BILG_FAAL_INTERNET,BILG_FAAL_SOSYALMEDYA,INTERNET_KULLANIM,INT_KULLANIM_SIKLIK,INT_SURE_HAFTAICI,INT_SURE_HAFTASONU,INT_FAAL_ODEV_ONLINEDERS,INT_FAAL_SOSYALMEDYA,INT_FAAL_EPOSTA,INT_FAAL_MESAJ_ARAMA,INT_FAAL_OYUN,INT_FAAL_MUZIK,INT_FAAL_VIDEO,INT_FAAL_MALHIZ_BILGI,INT_FAAL_ETICARET,INT_FAAL_DIGER,INT_FAAL_DIGER_ACIKLAMA,SOSYALMEDYA_KULLANIM,KULLAN_YOUTUBE,KULLAN_INSTAGRAM,KULLAN_TWITTER,KULLAN_FACEBOOK,KULLAN_TIKTOK,KULLAN_SNAPCHAT,KULLAN_PINTEREST,KULLAN_DIGER,KULLAN_DIGER_ACIKLAMA,SOSYALMEDYA_SIKLIK,SOSYALMEDYA_SURE_HAFTAICI,SOSYALMEDYA_SURE_HAFTASONU,DIJITALOYUN_OYNAMA,DIJITALOYUN_SIKLIK,DIJITALOYUN_SURE_HAFTAICI,DIJITALOYUN_SURE_HAFTASONU,DIJITALOYUN_FAAL_ROL,DIJITALOYUN_FAAL_TAKTIK,DIJITALOYUN_FAAL_SPOR,DIJITALOYUN_FAAL_MACERA,DIJITALOYUN_FAAL_SAVAS,DIJITALOYUN_FAAL_SIMULASYON,DIJITALOYUN_FAZLA_ZAMAN,DIJITALOYUN_FAZLA_ZAMAN_EBVEYN,DIJITALOYUN_OYNAMAMA_MUTSUZ,DIJITALOYUN_SORMLULUK_AKSATMA,DIJITALOYUN_PLAN_SURE_ASIMI,EKRAN_NEDEN_AZ_DERS_CALISMA,EKRAN_NEDEN_AZ_ZAMAN_AILE,EKRAN_NEDEN_AZ_KITAP_OKUMA,EKRAN_NEDEN_AZ_UYKU,EKRAN_NEDEN_AZ_ZAMAN_ARKADAS,FAKTOR
0,1000068682,3,2,29.0,11.0,2008,15,1,NaN,1,NaN,3,3,NaN,1,4.0,1,2,2,1,2,2,13,5,23,5,6,6,5,1,16.0,4.0,4.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1,1.0,2.0,2.0,13.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1,16.0,4.0,4.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,NaN,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,16.0,3.0,3.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,1,2,2708.208779
1,1000610731,2,1,19.0,1.0,2010,14,1,NaN,1,NaN,3,3,NaN,1,4.0,2,2,2,1,1,2,5,5,5,6,23,6,5,1,17.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,3.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,NaN,1,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,16.0,1.0,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1,1,2,2,2,2702.125252
2,1000610731,5,2,3.0,12.0,2008,15,1,NaN,1,NaN,3,3,NaN,1,4.0,2,2,2,1,2,2,5,13,13,5,13,5,5,1,16.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.0,4.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,2702.125252
3,1000610731,6,2,12.0,7.0,2011,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,2,2,2,5,13,6,5,13,5,13,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,2,2,2702.125252
4,1000952935,5,2,13.0,3.0,2013,11,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,1,1,2,2,29,5,6,13,6,13,13,1,17.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1,2.0,2.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,1,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,9.0,NaN,NaN,1,17.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2,2,2,2,2,1373.157249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7067,5496588756,3,2,16.0,3.0,2012,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,1,2,1,2,2,23,13,6,13,13,6,6,1,16.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,2.0,1.0,2.0,17.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1,16.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,17.0,2.0,3.0,1,16.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,1,1,1,1,1109.099054
7068,5496588756,4,2,3.0,9.0,2013,10,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,1,2,2,23,13,6,13,13,6,13,1,16.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1,2.0,1.0,2.0,16.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1,16.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,16.0,2.0,3.0,1,16.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,1,1,1,1,1109.099054
7069,5496588756,5,2,13.0,10.0,2017,6,1,NaN,1,NaN,3,0,NaN,1,0.0,2,2,2,2,2,2,23,23,13,6,6,13,6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,1.0,2.0,17.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1,17.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2,2,2,2,2,1109.099054
7070,5497885698,5,2,7.0,6.0,2013,10,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,2,2,2,13,5,6,6,6,13,6,1,17.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1,2.0,1.0,2.0,17.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1,17.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,17.0,1.0,2.0,1,17.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2,2,2,1,2,1807.975305
7071,5499264058,4,1,1.0,6.0,2011,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,1,2,2,5,5,23,6,6,6,13,1,16.0,3.0,4.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,3.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,1,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,16.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,2,1038.276631

In [4]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"FERTNO": "fert no"}, inplace=True)
df.rename(columns={"CINSIYET": "cinsiyet"}, inplace=True)
df.rename(columns={"DOGUM_TARIH_GUN": "doğum tarihi gün"}, inplace=True)
df.rename(columns={"DOGUM_TARIH_AY": "doğum tarihi ay"}, inplace=True)
df.rename(columns={"DOGUM_TARIH_YIL": "doğum tarihi yıl"}, inplace=True)
df.rename(columns={"YAS": "yaş"}, inplace=True)
df.rename(columns={"DOGUM_YER": "doğum yeri"}, inplace=True)
df.rename(columns={"DOGUM_YER_ULKE_KOD": "doğum yeri ülke kodu"}, inplace=True)
df.rename(columns={"UYRUK": "uyruk"}, inplace=True)
df.rename(columns={"UYRUK_ULKE_KOD": "uyruk ülke kodu"}, inplace=True)

In [12]:
df.rename(columns={"HHSORUMLU_YAKINLIK": "yakınlık durumu"}, inplace=True)
df.rename(columns={"OKUL_BITEN": "eğitim"}, inplace=True)
df.rename(columns={"OKUMA_YAZMA": "okuma yazma durumu"}, inplace=True)
df.rename(columns={"EGITIM_DEVAM": "eğitime devam etme durumu"}, inplace=True)
df.rename(columns={"OKUL_DEVAM": "devam edilen okul"}, inplace=True)
df.rename(columns={"KENDI_KUL_MASAUSTU": "çocuğun kendi masaüstü bilgisayarı"}, inplace=True)
df.rename(columns={"KENDI_KUL_DIZUSTU": "çocuğun kendi dizüstü bilgisayarı"}, inplace=True)
df.rename(columns={"KENDI_KUL_TABLET": "çocuğun kendi tableti"}, inplace=True)
df.rename(columns={"KENDI_KUL_CEP": "çocuğun kendi cep telefonu"}, inplace=True)
df.rename(columns={"KENDI_KUL_SAAT": "çocuğun kendi akıllı saati"}, inplace=True)
df.rename(columns={"KENDI_KUL_OYN_KNSL": "çocuğun kendi oyun konsolu"}, inplace=True)
df.rename(columns={"BILG_OYUN_SIKLIK": "bilgisayar oyunu oynama sıklığı"}, inplace=True)
df.rename(columns={"SPOR_YAPMA_SIKLIK": "spor yapma sıklığı"}, inplace=True)
df.rename(columns={"KITAP_OKUMA_SIKLIK": "kitap okuma sıklığı"}, inplace=True)
df.rename(columns={"DIGER_HOBI_SIKLIK": "diğer hobiler sıklığı"}, inplace=True)
df.rename(columns={"EGLENME_DISARI_SIKLIK": "eğlenmek için dışarı çıkma sıklığı"}, inplace=True)
df.rename(columns={"INT_GEZINME_SIKLIK": "internette gezinme sıklığı"}, inplace=True)
df.rename(columns={"TV_IZLEME_SIKLIK": "tv programları izleme sıklığı"}, inplace=True)
df.rename(columns={"CEP_KULLANIM": "cep telefonu kullanım durumu"}, inplace=True)
df.rename(columns={"CEP_KULLANIM_SIKLIK": "cep telefonu kullanım sıklığı"}, inplace=True)

In [14]:
df.rename(columns={"CEP_SURE_HAFTAICI": "hafta içi cep telefonu ortalama kullanımı"}, inplace=True)
df.rename(columns={"CEP_SURE_HAFTASONU": "hafta sonu cep telefonu ortalama kullanımı"}, inplace=True)
df.rename(columns={"CEP_AMAC_KONUSMA": "cep telefonu konuşma amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_MESAJ": "cep telefonu mesaj amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_SOSYALMEDYA": "cep telefonu sosyal medya amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_OYUN": "cep telefonu oyun amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_FILM": "cep telefonu film amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_MUZK": "cep telefonu müzik amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_INTERNET": "cep telefonu internette gezinme amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_DERS": "cep telefonu ders/ödev amaçlı"}, inplace=True)
df.rename(columns={"CEP_AMAC_DERS_ONLINE": "cep telefonu online derse katılma amaçlı"}, inplace=True)
df.rename(columns={"CEP_KONT_YARIMSAAT": "çocuk yarım saatte bir telefonunu kontrol ediyor"}, inplace=True)

In [ ]:
df.rename(columns={"CEP_KONT_UYKU_ONCESI": ""}, inplace=True)
df.rename(columns={"CEP_KONT_UYANINCA": ""}, inplace=True)
df.rename(columns={"CEP_KONT_TV_IZLERKEN": ""}, inplace=True)
df.rename(columns={"CEP_KONT_TOPLU_YEMEK": ""}, inplace=True)
df.rename(columns={"BILGISAYAR_KULLANIM": ""}, inplace=True)
df.rename(columns={"BILG_TUR_MASAUSTU": ""}, inplace=True)
df.rename(columns={"BILG_TUR_DIZUSTU": ""}, inplace=True)
df.rename(columns={"BILG_TUR_TABLET	": ""}, inplace=True)

In [15]:
df

,bülten no,fert no,cinsiyet,doğum tarihi gün,doğum tarihi ay,doğum tarihi yıl,yaş,doğum yeri,doğum yeri ülke kodu,uyruk,uyruk ülke kodu,yakınlık durumu,eğitim,okuma yazma durumu,eğitime devam etme durumu,devam edilen okul,çocuğun kendi masaüstü bilgisayarı,çocuğun kendi dizüstü bilgisayarı,çocuğun kendi tableti,çocuğun kendi cep telefonu,çocuğun kendi akıllı saati,çocuğun kendi oyun konsolu,bilgisayar oyunu oynama sıklığı,spor yapma sıklığı,kitap okuma sıklığı,diğer hobiler sıklığı,eğlenmek için dışarı çıkma sıklığı,internette gezinme sıklığı,tv programları izleme sıklığı,cep telefonu kullanım durumu,cep telefonu kullanım sıklığı,hafta içi cep telefonu ortalama kullanımı,hafta sonu cep telefonu ortalama kullanımı,cep telefonu konuşma amaçlı,cep telefonu mesaj amaçlı,cep telefonu sosyal medya amaçlı,cep telefonu oyun amaçlı,cep telefonu film amaçlı,cep telefonu müzik amaçlı,cep telefonu internette gezinme amaçlı,cep telefonu ders/ödev amaçlı,cep telefonu online derse katılma amaçlı,çocuk yarım saatte bir telefonunu kontrol ediyor,CEP_KONT_UYKU_ONCESI,CEP_KONT_UYANINCA,CEP_KONT_TV_IZLERKEN,CEP_KONT_TOPLU_YEMEK,BILGISAYAR_KULLANIM,BILG_TUR_MASAUSTU,BILG_TUR_DIZUSTU,BILG_TUR_TABLET,BILG_KULLANIM_SIKLIK,BILG_SURE_HAFTAICI,BILG_SURE_HAFTASONU,BILG_FAAL_OYUN,BILG_FAAL_DERS,BILG_FAAL_ONLINEDERS,BILG_FAAL_FILM_MUZIK,BILG_FAAL_INTERNET,BILG_FAAL_SOSYALMEDYA,INTERNET_KULLANIM,INT_KULLANIM_SIKLIK,INT_SURE_HAFTAICI,INT_SURE_HAFTASONU,INT_FAAL_ODEV_ONLINEDERS,INT_FAAL_SOSYALMEDYA,INT_FAAL_EPOSTA,INT_FAAL_MESAJ_ARAMA,INT_FAAL_OYUN,INT_FAAL_MUZIK,INT_FAAL_VIDEO,INT_FAAL_MALHIZ_BILGI,INT_FAAL_ETICARET,INT_FAAL_DIGER,INT_FAAL_DIGER_ACIKLAMA,SOSYALMEDYA_KULLANIM,KULLAN_YOUTUBE,KULLAN_INSTAGRAM,KULLAN_TWITTER,KULLAN_FACEBOOK,KULLAN_TIKTOK,KULLAN_SNAPCHAT,KULLAN_PINTEREST,KULLAN_DIGER,KULLAN_DIGER_ACIKLAMA,SOSYALMEDYA_SIKLIK,SOSYALMEDYA_SURE_HAFTAICI,SOSYALMEDYA_SURE_HAFTASONU,DIJITALOYUN_OYNAMA,DIJITALOYUN_SIKLIK,DIJITALOYUN_SURE_HAFTAICI,DIJITALOYUN_SURE_HAFTASONU,DIJITALOYUN_FAAL_ROL,DIJITALOYUN_FAAL_TAKTIK,DIJITALOYUN_FAAL_SPOR,DIJITALOYUN_FAAL_MACERA,DIJITALOYUN_FAAL_SAVAS,DIJITALOYUN_FAAL_SIMULASYON,DIJITALOYUN_FAZLA_ZAMAN,DIJITALOYUN_FAZLA_ZAMAN_EBVEYN,DIJITALOYUN_OYNAMAMA_MUTSUZ,DIJITALOYUN_SORMLULUK_AKSATMA,DIJITALOYUN_PLAN_SURE_ASIMI,EKRAN_NEDEN_AZ_DERS_CALISMA,EKRAN_NEDEN_AZ_ZAMAN_AILE,EKRAN_NEDEN_AZ_KITAP_OKUMA,EKRAN_NEDEN_AZ_UYKU,EKRAN_NEDEN_AZ_ZAMAN_ARKADAS,FAKTOR
0,1000068682,3,2,29.0,11.0,2008,15,1,NaN,1,NaN,3,3,NaN,1,4.0,1,2,2,1,2,2,13,5,23,5,6,6,5,1,16.0,4.0,4.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1,1.0,2.0,2.0,13.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1,16.0,4.0,4.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,NaN,1,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,16.0,3.0,3.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,1,2,2708.208779
1,1000610731,2,1,19.0,1.0,2010,14,1,NaN,1,NaN,3,3,NaN,1,4.0,2,2,2,1,1,2,5,5,5,6,23,6,5,1,17.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,3.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,NaN,1,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,16.0,1.0,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1,1,2,2,2,2702.125252
2,1000610731,5,2,3.0,12.0,2008,15,1,NaN,1,NaN,3,3,NaN,1,4.0,2,2,2,1,2,2,5,13,13,5,13,5,5,1,16.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.0,4.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,2702.125252
3,1000610731,6,2,12.0,7.0,2011,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,2,2,2,5,13,6,5,13,5,13,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,2,2,2702.125252
4,1000952935,5,2,13.0,3.0,2013,11,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,1,1,2,2,29,5,6,13,6,13,13,1,17.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1,2.0,2.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,1,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,9.0,NaN,NaN,1,17.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2,2,2,2,2,1373.157249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7067,5496588756,3,2,16.0,3.0,2012,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,1,2,1,2,2,23,13,6,13,13,6,6,1,16.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,2.0,1.0,2.0,17.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1,16.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,17.0,2.0,3.0,1,16.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,1,1,1,1,1109.099054
7068,5496588756,4,2,3.0,9.0,2013,10,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,1,2,2,23,13,6,13,13,6,13,1,16.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1,2.0,1.0,2.0,16.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1,16.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,16.0,2.0,3.0,1,16.0,2.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1,1,1,1,1,1109.099054
7069,5496588756,5,2,13.0,10.0,2017,6,1,NaN,1,NaN,3,0,NaN,1,0.0,2,2,2,2,2,2,23,23,13,6,6,13,6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,1.0,2.0,17.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1,17.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2,2,2,2,2,1109.099054
7070,5497885698,5,2,7.0,6.0,2013,10,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,2,2,2,13,5,6,6,6,13,6,1,17.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1,2.0,1.0,2.0,17.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1,17.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,17.0,1.0,2.0,1,17.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2,2,2,1,2,1807.975305
7071,5499264058,4,1,1.0,6.0,2011,12,1,NaN,1,NaN,3,2,NaN,1,3.0,2,2,2,1,2,2,5,5,23,6,6,6,13,1,16.0,3.0,4.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.0,3.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,1,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,16.0,2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,2,1038.276631