In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2025_hh.xlsx")
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,MAH_DEG_L1,HANE_FAKTOR
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,MAH_DEG_L1,HANE_FAKTOR
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11924 entries, 0 to 11923
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 11924 non-null  int64
 1   BULTEN_NO                    11924 non-null  int64
 2   BT_BILG_MASAUSTU             11924 non-null  int64
 3   BT_BILG_DIZUSTU              11924 non-null  int64
 4   BT_TABLET                    11924 non-null  int64
 5   HANE_INTERNET_ERISIM_DURUMU  11924 non-null  int64
 6   hane_aylik_gelir_grp_5       11924 non-null  int64
 7   HHB                          11924 non-null  int64
 8   IBBS_1                       11924 non-null  str
 9   MAH_DEG_L1                   11924 non-null  int64
 10  HANE_FAKTOR                  11924 non-null  float64
dtypes: float64(1), int64(9), str(1)
memory usage: 1.0 MB

In [7]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)

In [9]:
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [13]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2025temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2025temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684