In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2025_hh.xlsx")
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,MAH_DEG_L1,HANE_FAKTOR
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,MAH_DEG_L1,HANE_FAKTOR
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11924 entries, 0 to 11923
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 11924 non-null  int64
 1   BULTEN_NO                    11924 non-null  int64
 2   BT_BILG_MASAUSTU             11924 non-null  int64
 3   BT_BILG_DIZUSTU              11924 non-null  int64
 4   BT_TABLET                    11924 non-null  int64
 5   HANE_INTERNET_ERISIM_DURUMU  11924 non-null  int64
 6   hane_aylik_gelir_grp_5       11924 non-null  int64
 7   HHB                          11924 non-null  int64
 8   IBBS_1                       11924 non-null  str
 9   MAH_DEG_L1                   11924 non-null  int64
 10  HANE_FAKTOR                  11924 non-null  float64
dtypes: float64(1), int64(9), str(1)
memory usage: 1.0 MB

In [7]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)

In [9]:
df.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

In [13]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2025temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2025temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,2025,10011,2,1,2,1,1,2,TR1,3,3045.660009
1,2025,10012,2,1,1,1,5,3,TR1,3,2295.674589
2,2025,10013,2,1,1,1,2,3,TR1,3,3813.920274
3,2025,10014,1,1,1,1,5,1,TR1,3,4798.158090
4,2025,10015,2,1,1,1,5,4,TR1,3,2994.977684

# 2025 yılı cross tabloları

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2025.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_7772\207573108.py:2: DtypeWarning: Columns (0: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2025.csv")

,bülten no,referans yıl,fert no,cinsiyet,yaş,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,3813.920274,2,1,1,1,2,3,TR1,3,3813.920274

In [2]:
# =========================================================
# ONLINE SAĞLIK HİZMETİ KULLANIMI (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
online_var = df[df["sağlık bilgisi arama"] == 1]["cinsiyet"] \
    .value_counts()

online_var_yuzde = round(
    df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
online_yok = df[df["sağlık bilgisi arama"] == 2]["cinsiyet"] \
    .value_counts()

online_yok_yuzde = round(
    df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
online_tablo = pd.DataFrame({

    "online sağlık hizmeti kullanımı var": [
        online_var.get(2, 0),
        online_var.get(1, 0),
        online_var.sum()
    ],

    "online sağlık hizmeti kullanımı var yüzde": [
        online_var_yuzde.get(2, 0),
        online_var_yuzde.get(1, 0),
        100
    ],

    "online sağlık hizmeti kullanımı yok": [
        online_yok.get(2, 0),
        online_yok.get(1, 0),
        online_yok.sum()
    ],

    "online sağlık hizmeti kullanımı yok yüzde": [
        online_yok_yuzde.get(2, 0),
        online_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(online_tablo)

,online sağlık hizmeti kullanımı var,online sağlık hizmeti kullanımı var yüzde,online sağlık hizmeti kullanımı yok,online sağlık hizmeti kullanımı yok yüzde
kadın,7342,52.2,3784,44.85
erkek,6723,47.8,4653,55.15
toplam,14065,100.0,8437,100.00

In [4]:
# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ (VAR / YOK)
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# VAR
eticaret_var = df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"] \
    .value_counts()

eticaret_var_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# YOK
eticaret_yok = df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"] \
    .value_counts()

eticaret_yok_yuzde = round(
    df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"]
    .value_counts(normalize=True) * 100,
    2
)

# TABLO
eticaret_tablo = pd.DataFrame({

    "eticaret ilaç alışverişi var": [
        eticaret_var.get(2, 0),
        eticaret_var.get(1, 0),
        eticaret_var.sum()
    ],

    "eticaret ilaç alışverişi var yüzde": [
        eticaret_var_yuzde.get(2, 0),
        eticaret_var_yuzde.get(1, 0),
        100
    ],

    "eticaret ilaç alışverişi yok": [
        eticaret_yok.get(2, 0),
        eticaret_yok.get(1, 0),
        eticaret_yok.sum()
    ],

    "eticaret ilaç alışverişi yok yüzde": [
        eticaret_yok_yuzde.get(2, 0),
        eticaret_yok_yuzde.get(1, 0),
        100
    ]

},

index=["kadın", "erkek", "toplam"]

)

display(eticaret_tablo)

KeyError: 'eticaret ilaç alışverişi'

In [2]:
# =========================================================
# GELİR GRUBU x SAĞLIK BİLGİSİ ARAMA
# 2023
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# HAZIR 5'Lİ GELİR GRUBU
# =========================================================

df["gelir_grup"] = df[
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# =========================================================
# TABLO
# =========================================================

sonuc = []

for gelir in [1, 2, 3, 4, 5]:

    alt = df[df["gelir_grup"] == gelir]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[
        alt["sağlık bilgisi arama"] == 1
    ]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[
        alt["sağlık bilgisi arama"] == 2
    ]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({

        "yıl": 2025,

        "gelir": gelir,

        # VAR
        "var kadın":
            round(saglik_var_cinsiyet.get(2, 0), 2),

        "var erkek":
            round(saglik_var_cinsiyet.get(1, 0), 2),

        "var toplam":
            len(saglik_var),

        # YOK
        "yok kadın":
            round(saglik_yok_cinsiyet.get(2, 0), 2),

        "yok erkek":
            round(saglik_yok_cinsiyet.get(1, 0), 2),

        "yok toplam":
            len(saglik_yok)

    })

# =========================================================
# FREKANS SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{

    "yıl": 2025,

    "gelir": "frekans",

    "var kadın":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "var erkek":
        df[df["sağlık bilgisi arama"] == 1]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "var toplam":
        len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(2, 0),

    "yok erkek":
        df[df["sağlık bilgisi arama"] == 2]["cinsiyet"]
        .value_counts()
        .get(1, 0),

    "yok toplam":
        len(df[df["sağlık bilgisi arama"] == 2])

}])

# =========================================================
# BİRLEŞTİR
# =========================================================

gelir_saglik_2025 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(gelir_saglik_2025)

C:\Users\dilara\AppData\Local\Temp\ipykernel_23040\4012982903.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_grup"] = df[

,yıl,gelir,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2025,1,56.84,43.16,1608,51.82,48.18,1839
1,2025,2,53.53,46.47,2576,44.65,55.35,1989
2,2025,3,52.33,47.67,3042,43.99,56.01,1923
3,2025,4,50.65,49.35,3210,40.73,59.27,1527
4,2025,5,50.45,49.55,3629,40.98,59.02,1159
5,2025,frekans,7342.00,6723.00,14065,3784.00,4653.00,8437

In [2]:
# =========================================================
# YAŞ GRUBU x SAĞLIK BİLGİSİ ARAMA
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[15, 30, 45, 60, 100],
    labels=["15-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

sonuc = []

for yas in ["15-30", "31-45", "46-60", "60+"]:

    alt = df[df["yas_grup"] == yas]

    # SAĞLIK BİLGİSİ ARAMA VAR
    saglik_var = alt[alt["sağlık bilgisi arama"] == 1]

    saglik_var_cinsiyet = (
        saglik_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # SAĞLIK BİLGİSİ ARAMA YOK
    saglik_yok = alt[alt["sağlık bilgisi arama"] == 2]

    saglik_yok_cinsiyet = (
        saglik_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "yıl": 2017,
        "yaş": yas,

        "var kadın": round(saglik_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(saglik_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(saglik_var),

        "yok kadın": round(saglik_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(saglik_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(saglik_yok)
    })

# =========================================================
# TOPLAM SATIRI - FREKANS
# =========================================================

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "yaş": "toplam",

    "var kadın": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["sağlık bilgisi arama"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["sağlık bilgisi arama"] == 1]),

    "yok kadın": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["sağlık bilgisi arama"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["sağlık bilgisi arama"] == 2])
}])

yas_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(yas_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24408\1184860868.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

,yıl,yaş,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,15-30,54.04,45.96,4489,41.89,58.11,2022
1,2017,31-45,53.50,46.50,5310,46.20,53.80,2158
2,2017,46-60,50.28,49.72,3355,46.09,53.91,2725
3,2017,60+,42.59,57.41,911,44.65,55.35,1532
4,2017,toplam,7342.00,6723.00,14065,3784.00,4653.00,8437

In [3]:
# =========================================================
# EĞİTİM x ETİCARET İLAÇ ALIŞVERİŞİ
# CİNSİYETE GÖRE FREKANS + YÜZDE TABLOSU
# =========================================================

import pandas as pd

# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

def egitim_kategori(x):
    if x in [0, 1, 2]:
        return "ilkokulvealtı"
    elif x in [3, 4]:
        return "ortaokul/lise"
    elif x in [5, 51, 52]:
        return "üniversite"
    elif x in [6, 7, 53]:
        return "üniversiteüstü"
    else:
        return None

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# TABLO
# =========================================================

sonuc = []

for egitim in ["ilkokulvealtı", "ortaokul/lise", "üniversite", "üniversiteüstü"]:

    alt = df[df["egitim_grup"] == egitim]

    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    eticaret_var = alt[
        alt["eticaret ilaç alışverişi"] == 1
    ]

    eticaret_var_cinsiyet = (
        eticaret_var["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    eticaret_yok = alt[
        alt["eticaret ilaç alışverişi"] == 2
    ]

    eticaret_yok_cinsiyet = (
        eticaret_yok["cinsiyet"]
        .value_counts(normalize=True) * 100
    )

    sonuc.append({
        "eğitim": egitim,

        "var kadın": round(eticaret_var_cinsiyet.get(2, 0), 2),
        "var erkek": round(eticaret_var_cinsiyet.get(1, 0), 2),
        "var toplam": len(eticaret_var),

        "yok kadın": round(eticaret_yok_cinsiyet.get(2, 0), 2),
        "yok erkek": round(eticaret_yok_cinsiyet.get(1, 0), 2),
        "yok toplam": len(eticaret_yok)
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

toplam_satiri = pd.DataFrame([{
    "eğitim": "toplam",

    "var kadın": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(2, 0),
    "var erkek": df[df["eticaret ilaç alışverişi"] == 1]["cinsiyet"].value_counts().get(1, 0),
    "var toplam": len(df[df["eticaret ilaç alışverişi"] == 1]),

    "yok kadın": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(2, 0),
    "yok erkek": df[df["eticaret ilaç alışverişi"] == 2]["cinsiyet"].value_counts().get(1, 0),
    "yok toplam": len(df[df["eticaret ilaç alışverişi"] == 2])
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_eticaret = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_eticaret)

C:\Users\dilara\AppData\Local\Temp\ipykernel_24408\2103775799.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

KeyError: 'eticaret ilaç alışverişi'

In [2]:
import pandas as pd
import numpy as np

# =========================================================
# EĞİTİM KATEGORİLERİ (2017)
# =========================================================

def egitim_kategori(x):

    if pd.isna(x):
        return None

    x = int(x)

    # İLKOKUL VE ALTI
    if x in [1, 2]:
        return "ilkokulvealtı"

    # ORTAOKUL / LİSE
    elif x in [3, 4]:
        return "ortaokul/lise"

    # ÜNİVERSİTE
    elif x in [51, 52]:
        return "üniversite"

    # ÜNİVERSİTE ÜSTÜ
    elif x in [53]:
        return "üniversiteüstü"

    else:
        return None


# =========================================================
# EĞİTİM GRUBU OLUŞTUR
# =========================================================

df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

# =========================================================
# SONUÇ LİSTESİ
# =========================================================

sonuc = []

for grup in [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]:

    temp = df[df["egitim_grup"] == grup]

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = VAR
    # =====================================================

    var_df = temp[temp["sağlık bilgisi arama"] == 1]

    var_kadin = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    var_erkek = round(
        (var_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    var_toplam = len(var_df)

    # =====================================================
    # SAĞLIK BİLGİSİ ARAMA = YOK
    # =====================================================

    yok_df = temp[temp["sağlık bilgisi arama"] == 2]

    yok_kadin = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(2, 0)) * 100,
        2
    )

    yok_erkek = round(
        (yok_df["cinsiyet"].value_counts(normalize=True).get(1, 0)) * 100,
        2
    )

    yok_toplam = len(yok_df)

    sonuc.append({
        "yıl": 2017,
        "eğitim": grup,
        "var kadın": var_kadin,
        "var erkek": var_erkek,
        "var toplam": var_toplam,
        "yok kadın": yok_kadin,
        "yok erkek": yok_erkek,
        "yok toplam": yok_toplam
    })

# =========================================================
# TOPLAM SATIRI
# =========================================================

var_all = df[df["sağlık bilgisi arama"] == 1]
yok_all = df[df["sağlık bilgisi arama"] == 2]

toplam_satiri = pd.DataFrame([{
    "yıl": 2017,
    "eğitim": "toplam",

    "var kadın": len(var_all[var_all["cinsiyet"] == 2]),
    "var erkek": len(var_all[var_all["cinsiyet"] == 1]),
    "var toplam": len(var_all),

    "yok kadın": len(yok_all[yok_all["cinsiyet"] == 2]),
    "yok erkek": len(yok_all[yok_all["cinsiyet"] == 1]),
    "yok toplam": len(yok_all)
}])

# =========================================================
# BİRLEŞTİR
# =========================================================

egitim_saglik_2017 = pd.concat(
    [pd.DataFrame(sonuc), toplam_satiri],
    ignore_index=True
)

display(egitim_saglik_2017)

C:\Users\dilara\AppData\Local\Temp\ipykernel_7772\2140524588.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_grup"] = df["eğitim"].apply(egitim_kategori)

,yıl,eğitim,var kadın,var erkek,var toplam,yok kadın,yok erkek,yok toplam
0,2017,ilkokulvealtı,60.55,39.45,2740,55.40,44.60,4025
1,2017,ortaokul/lise,48.70,51.30,6632,35.31,64.69,3427
2,2017,üniversite,51.00,49.00,402,33.33,66.67,69
3,2017,üniversiteüstü,50.00,50.00,70,36.36,63.64,11
4,2017,toplam,7342.00,6723.00,14065,3784.00,4653.00,8437

In [3]:
import pandas as pd
import numpy as np

# =========================================================
# YIL
# =========================================================
YIL = 2025


# =========================================================
# TÜM YILLARA UYUMLU EĞİTİM KATEGORİSİ
# =========================================================
def egitim_kategori(x):

    try:
        x = int(x)
    except:
        return np.nan

    # -------------------------------------------------
    # İLKOKUL VE ALTI
    # -------------------------------------------------
    if x in [0, 1, 2]:
        return "ilkokulvealtı"

    # -------------------------------------------------
    # ORTAOKUL / LİSE
    # -------------------------------------------------
    elif x in [3, 4]:
        return "ortaokul/lise"

    # -------------------------------------------------
    # ÜNİVERSİTE
    # -------------------------------------------------
    elif x in [5, 6, 51, 52, 511, 512]:
        return "üniversite"

    # -------------------------------------------------
    # ÜNİVERSİTE ÜSTÜ
    # -------------------------------------------------
    elif x in [7, 53]:
        return "üniversiteüstü"

    else:
        return np.nan


# =========================================================
# EĞİTİM GRUBU
# =========================================================
df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)


# =========================================================
# ETİCARET İLAÇ ALIŞVERİŞİ
# =========================================================
df["ilac_alisveris"] = df["eticaret ilaç alışverişi"].replace({
    "Evet": 1,
    "Hayır": 0,
    1: 1,
    2: 0
})


# =========================================================
# SONUÇ TABLOSU
# =========================================================
sonuc = []

egitim_sirasi = [
    "ilkokulvealtı",
    "ortaokul/lise",
    "üniversite",
    "üniversiteüstü"
]

for egitim in egitim_sirasi:

    alt = df[df["eğitim_grup"] == egitim]

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ VAR
    # =====================================================
    var_df = alt[alt["ilac_alisveris"] == 1]

    var_kadin = (var_df["cinsiyet"] == 2).sum()
    var_erkek = (var_df["cinsiyet"] == 1).sum()
    var_toplam = len(var_df)

    # =====================================================
    # ETİCARET İLAÇ ALIŞVERİŞİ YOK
    # =====================================================
    yok_df = alt[alt["ilac_alisveris"] == 0]

    yok_kadin = (yok_df["cinsiyet"] == 2).sum()
    yok_erkek = (yok_df["cinsiyet"] == 1).sum()
    yok_toplam = len(yok_df)

    # =====================================================
    # SATIR EKLE
    # =====================================================
    sonuc.append({

        "yıllar": YIL,
        "eğitim": egitim,

        "kadın_var": var_kadin,
        "erkek_var": var_erkek,
        "toplam_var": var_toplam,

        "kadın_yok": yok_kadin,
        "erkek_yok": yok_erkek,
        "toplam_yok": yok_toplam
    })


# =========================================================
# DATAFRAME
# =========================================================
tablo = pd.DataFrame(sonuc)


# =========================================================
# TOPLAM SATIRI
# =========================================================
toplam_satiri = pd.DataFrame([{

    "yıllar": "",
    "eğitim": "toplam",

    "kadın_var": tablo["kadın_var"].sum(),
    "erkek_var": tablo["erkek_var"].sum(),
    "toplam_var": tablo["toplam_var"].sum(),

    "kadın_yok": tablo["kadın_yok"].sum(),
    "erkek_yok": tablo["erkek_yok"].sum(),
    "toplam_yok": tablo["toplam_yok"].sum()

}])


# =========================================================
# FİNAL TABLO
# =========================================================
final_tablo = pd.concat(
    [tablo, toplam_satiri],
    ignore_index=True
)


# =========================================================
# GÖSTER
# =========================================================
display(final_tablo)


# =========================================================
# EXCEL AKTAR
# =========================================================

C:\Users\dilara\AppData\Local\Temp\ipykernel_7772\1077536611.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["eğitim_grup"] = df["eğitim"].apply(egitim_kategori)

KeyError: 'eticaret ilaç alışverişi'

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2025.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_11420\207573108.py:2: DtypeWarning: Columns (0: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2025.csv")

,bülten no,referans yıl,fert no,cinsiyet,yaş,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,...,fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,3813.920274,2,1,1,1,2,3,TR1,3,3813.920274