In [3]:
import pandas as pd

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [5]:
fert2015 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2015temizfertbilişim.csv")
fert2015.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022"
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564"
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,1.0,1.0,3.0,2.0,NaN,NaN,4.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"2147,205564"
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,1.0,3.0,3.0,2.0,NaN,NaN,5.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,TR1,"2147,205564"
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,1.0,1.0,3.0,2.0,NaN,NaN,4.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"1939,806488"

In [6]:
hane2015= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2015temizhanebilişim.csv")
hane2015.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10013,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0
3,2015,10014,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,2,"2631,116861",TR1,1,1.0,1.0
4,2015,10015,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,4,"3031,290825",TR1,1,1.0,1.0

In [7]:
yıl2015 = fert2015.merge(
    hane2015,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [8]:
yıl2015.info()

<class 'pandas.DataFrame'>
RangeIndex: 35850 entries, 0 to 35849
Columns: 174 entries, referans yıl to hane bilgilendirme mektubunun ulaşma durumu
dtypes: float64(162), int64(7), str(5)
memory usage: 48.9 MB

In [9]:
yıl2015.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0

In [10]:
fert2016 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2016temizfertbilişim.csv")
fert2016.head()

,referans yıl,bülten no,fert no,fert cevap durumu,cevapsız fert,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,internet araması,online c2c alışveriş,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması.1,sosyal medya kullanımı,online haber okuma,ürün hizmet arama,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,websitesinde içerik paylaşma,websitesinde içerik paylaşma.1,online sağlık hizmeti kullanımı,"randevu alma (e-nabız,mhrs vb.)",online seyahat ve konaklama işlemleri,Unnamed: 46,internetten satış,online banka işlemleri,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sıklık,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı
0,2016,10011,1,1.0,NaN,50,1,1.0,3.0,1.0,NaN,5.0,3.0,NaN,1.0,6.0,1.0,6.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318"
1,2016,10011,2,1.0,NaN,49,2,1.0,3.0,3.0,2.0,NaN,NaN,4.0,1.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318"
2,2016,10011,3,2.0,1.0,21,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
3,2016,10011,4,NaN,NaN,15,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,TR1,"1506,565318"
4,2016,10012,1,1.0,NaN,43,2,1.0,1.0,3.0,2.0,NaN,NaN,4.0,90.0,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,TR1,"1567,389768"

In [11]:
hane2016= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2016temizhanebilişim.csv")
hane2016.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

In [12]:
yıl2016 = fert2016.merge(
    hane2016,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [13]:
yıl2016.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,cevapsız fert,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,internet araması,online c2c alışveriş,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması.1,sosyal medya kullanımı,online haber okuma,ürün hizmet arama,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,websitesinde içerik paylaşma,websitesinde içerik paylaşma.1,online sağlık hizmeti kullanımı,"randevu alma (e-nabız,mhrs vb.)",online seyahat ve konaklama işlemleri,Unnamed: 46,internetten satış,online banka işlemleri,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sıklık,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,NaN,50,1,1.0,3.0,1.0,NaN,5.0,3.0,NaN,1.0,6.0,1.0,6.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318",1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10011,2,1.0,NaN,49,2,1.0,3.0,3.0,2.0,NaN,NaN,4.0,1.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318",1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"

In [14]:
hane2017= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv")
hane2017.head()
fert2017 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2017temizfertbilişim.csv")
fert2017.head()
yıl2017 = fert2017.merge(
    hane2017,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [15]:
yıl2017.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,kapsam içi kapsam dışı,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,ürün hizmet arama,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 38,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,3,NaN,1,11,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10011,4,NaN,1,11,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,0,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"

In [16]:
hane2018= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2018temizhanebilişim.csv")
hane2018.head()
fert2018 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2018temizfertbilişim.csv")
fert2018.head()
yıl2018 = fert2018.merge(
    hane2018,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [17]:
yıl2018.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,cep telefonu kullanımı,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,günlük kullanılan internet,masaüstü kullanımı,dizüstü bilgisayar ile internet kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,ürün hizmet arama,online müzik dinleme platformu,online film/dizi/video platformu,ücretli online film/dizi/video platformu,sosyal medyada video izleme,oyun indirme sürüm yükseltme,sağlık bilgisi arama,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 40,internetten satış,internet üzerinden bulut depolama kullanımı,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanefaktor
0,2018,11058,1,1,19,1,1,4,3,2.0,NaN,NaN,3.0,1,1,6.0,1,6.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,2.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301",1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2000.0,4,TR1,"3852,219301"
1,2018,11058,4,1,16,1,1,3,3,2.0,NaN,NaN,3.0,1,1,6.0,1,6.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,99.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301",1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2000.0,4,TR1,"3852,219301"

In [18]:
hane2019= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2019temizhanebilişim.csv")
hane2019.head()
fert2019 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2019temizfertbilişim.csv")
fert2019.head()
yıl2019= fert2019.merge(
    hane2017,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [19]:
yıl2019.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,cep telefonu kullanımı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,günlük kullanılan internet,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,tablet ile internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,ürün hizmet arama,websitesinde içerik paylaşma,internetten oy katılım,internetten iş arama,websitesinde içerik paylaşma.1,online müzik dinleme platformu,Unnamed: 34,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama başkasına yaptırma,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2019,17848,2,1.0,43,2,1.0,2.0,1.0,NaN,9.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,"862,0739407",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,10011,1,1.0,68,2,1.0,2.0,3.0,2.0,NaN,NaN,5.0,1.0,1.0,13.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,"2210,281659",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
hane2020= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2020temizhanebilişim.csv")
hane2020.head()
fert2020 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2020temizfertbilişim.csv")
fert2020.head()
yıl2020= fert2020.merge(
    hane2020,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [21]:
yıl2020.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,günlük kullanılan internet,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,ürün hizmet arama,online haber okuma,websitesinde içerik paylaşma,online müzik dinleme platformu,online film/dizi/video platformu,ücretli online film/dizi/video platformu,sosyal medyada video izleme,oyun indirme sürüm yükseltme,sağlık bilgisi arama,"randevu alma (e-nabız,mhrs vb.)",sağlık sonuçlarını almak,Unnamed: 33,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret giyim alışverişi,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret ev eşyası alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret kitap dergi alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret elektronik araçlar alışverişi,eticaret ilaç alışverişi,eticaret yemek siparişi,eticaret gıda ürünleri alışverişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,Unnamed: 73,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2020,10011,1,1.0,61,1,1.0,512.0,1.0,NaN,2262.0,3.0,NaN,1.0,1.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,1.0,129.0,2499.862115,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"
1,2020,10011,2,1.0,55,2,1.0,512.0,3.0,1.0,2262.0,3.0,NaN,1.0,1.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,129.0,2499.862115,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,9000.0,3,TR1,"2499,862115"

In [22]:
hane2021= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2021temizhanebilişim.csv")
hane2021.head()
fert2021 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2021temizfertbilişim.csv")
fert2021.head()
yıl2021= fert2021.merge(
    hane2021,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [23]:
yıl2021.head(2)

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,günlük kullanılan internet,masaüstü kullanımı,dizüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,ürün hizmet arama,websitesinde içerik paylaşma,internetten oy katılım,internetten iş arama,Unnamed: 33,internetten satış,online kurs,online eğitim materyal,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form göndermeyi danışman yaptı,edevlet form göndermeyi tercih etmedi,edevlet form gönderme diğer neden,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret kullanımı,eticaret giyim alışverişi,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret ev eşyası alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret kitap dergi alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret elektronik araçlar alışverişi,eticaret ilaç alışverişi,eticaret yemek siparişi,eticaret gıda ürünleri alışverişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,eticaretdiğer türler alışverişi,eticaret tür açıklama,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online c2c alışveriş,online müzik dinleme platformu,online film/dizi/video platformu,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,eticaret alışveriş sıklık,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama güven sorunu,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama ihtiyaç yok,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri ofis yazılımı kullanma,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,internet çerez bilgi farkındalığı,kvkk çerez yönetimi,kvkk izleme engelleme yazılım kullanma,fert ağırlık katsayısı,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,sabit internet (ev interneti),mobil internet,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2021,10011,1,52,1,1,2,NaN,1,NaN,6121.0,3.0,NaN,1,1.0,1,6.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,4.0,5.0,5.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3802.312141,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"
1,2021,10011,2,49,2,2,2,NaN,3,1.0,9211.0,4.0,NaN,1,1.0,1,6.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,2.0,5.0,5.0,2.0,5.0,4.0,5.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3802.312141,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3000.0,5,TR1,"3802,312141"

In [24]:
hane2022= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2022temizhanebilişim.csv")
hane2022.head()
fert2022 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2022temizfertbilişim.csv")
fert2022.head()
yıl2022= fert2022.merge(
    hane2022,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [25]:
yıl2022.head(2)

,referans yıl,bülten no,fert no,yaş,cinsiyet,yakınlık durumu,fert no.1,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,ürün hizmet arama,online haber okuma,websitesinde içerik paylaşma,internetten oy katılım,online müzik dinleme platformu,online film/dizi/video platformu,ücretli online film/dizi/video platformu,sosyal medyada video izleme,oyun indirme sürüm yükseltme,sağlık bilgisi arama,"randevu alma (e-nabız,mhrs vb.)",sağlık sonuçlarını almak,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,internetten satış,online kurs,online eğitim materyal,online eğitim iletişim,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlet hakkında bilgi,edevlette hiçbir sey yapmadı,edevlet form işlemleri,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,eticaret kullanımı,eticaret giyim alışverişi,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret ev eşyası alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret kitap dergi alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret elektronik araçlar alışverişi,eticaret ilaç alışverişi,eticaret yemek siparişi,eticaret gıda ürünleri alışverişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online c2c alışveriş,online müzik dinleme platformu.1,online film/dizi/video platformu.1,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,WEBSTE_HHN_HZMET,online ev hizmetleri,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,fert ağırlık katsayısı,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (20'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2022,10012,1,44,1,1,3,2,NaN,1,NaN,1.0,9112.0,1,NaN,1,NaN,213,1,1.0,1,16.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,3960.165238,1,2,2,2,1,2,1,12,1,TR1,3960.165238
1,2022,10014,1,61,1,1,3,2,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,213,1,1.0,1,16.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,2.0,2.0,3.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,5.0,5.0,2403.691000,1,2,1,2,1,1,1,12,3,TR1,2403.691000

In [26]:
hane2023= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2023temizhanebilişim.csv")
hane2023.head()
fert2023 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2023temizfertbilişim.csv")
fert2023.head()
yıl2023= fert2023.merge(
    hane2023,
    on=["referans yıl", "bülten no"],
    how="left"
)

C:\Users\dilara\AppData\Local\Temp\ipykernel_8424\1016793533.py:3: DtypeWarning: Columns (0: doğduğu ülke kodu, 1: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  fert2023 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2023temizfertbilişim.csv")

In [27]:
yıl2023.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,masaüstü kullanımı,dizüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,ürün hizmet arama,websitesinde içerik paylaşma,internetten oy katılım,internetten iş arama,Unnamed: 35,internetten satış,online kurs,online eğitim materyal,online eğitim iletişim,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,evden çalışma sıklığı,evden çalışırken internet kullanımı,edevlet resmi işlem,edevlet kamu bilgi,edevlet hakkında bilgi,edevlette hiçbir sey yapmadı,edevlet form işlemleri,edevletten randevu alma,edevletten bilgi alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet dijital kimlik yok,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,eticaret kullanımı,eticaret giyim alışverişi,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret ev eşyası alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret kitap dergi alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret elektronik araçlar alışverişi,eticaret ilaç alışverişi,eticaret yemek siparişi,eticaret gıda ürünleri alışverişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online c2c alışveriş,online müzik dinleme platformu,online film/dizi/video platformu,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,eticaret alışveriş sıklık,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri ofis yazılımı kullanma,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,kvkk izleme engelleme yazılım kullanma,fert ağırlık katsayısı,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2023,10011,2,1,1,45,3,NaN,1,NaN,3.0,5221.0,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,5.0,NaN,1.0,2.0,1.0,NaN,2.0,2.0,2.0,4.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,4.107.325.497,1,2,1,2,1,2,1,2,1,TR1,4107.325497
1,2023,10012,1,1,2,25,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,1.0,5.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.852.032.646,1,2,1,1,1,1,1,2,1,TR1,4852.032646

In [28]:
hane2024= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv")
hane2024.head()
fert2024 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2024temizfertbilişim.csv")
fert2024.head()
yıl2024= fert2024.merge(
    hane2024,
    on=["referans yıl", "bülten no"],
    how="left"
)

In [29]:
yıl2024.head(2)

,bülten no,referans yıl,fert no,cinsiyet,yaş,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,sağlık problemi nedeni ile faaliyet sınırlama süresi,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,ürün hizmet arama,online haber okuma,websitesinde içerik paylaşma,internetten oy katılım,online müzik dinleme platformu,online film/dizi/video platformu,ücretli online film/dizi/video platformu,sosyal medyada video izleme,oyun indirme sürüm yükseltme,podcast dinlemek ve indirmek,sağlık bilgisi arama,"randevu alma (e-nabız,mhrs vb.)",sağlık sonuçlarını almak,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,internetten satış,online kurs,online eğitim materyal,online eğitim iletişim,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,online hesap açma,online hesap silme,online hesap silerken sorun olması,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,evden çalışma sıklığı,evden çalışırken internet kullanımı,edevlet resmi işlem,edevlet kamu bilgi,edevlet hakkında bilgi,edevlette hiçbir sey yapmadı,edevlet form işlemleri,edevletten randevu alma,edevletten bilgi alma,edevlet vergi işlem,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet dijital kimlik yok,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet eimza sorunu,edevlet ödeme sorunu,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,eticaret kullanımı,eticaret giyim alışverişi,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret ev eşyası alışverişi,eticaret cd dvd alışverişi,eticaret kitap dergi alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret elektronik araçlar alışverişi,eticaret ilaç alışverişi,eticaret yemek siparişi,eticaret gıda ürünleri alışverişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,eticaretdiğer türler alışverişi,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,ekitap sesli kitap,yazılım indirme sürüm yükseltme,oyun indirme sürüm yükseltme.1,online müzik dinleme platformu.1,online film/dizi/video platformu.1,online dergi gazete,oyun yayın platformu,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,10011,2024,2,2,54,512,NaN,1,NaN,1.0,2612.0,1,NaN,1,NaN,6,NaN,1,1.0,1,16.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,NaN,1.0,2.0,1.0,NaN,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,5.0,5.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,3853.130313,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,10012,2024,1,1,41,52,NaN,1,NaN,1.0,2611.0,1,NaN,1,NaN,6,NaN,1,1.0,1,16.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4555.431051,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051

In [30]:
hane2025= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2025temizhanebilişim.csv")
hane2025.head()
fert2025 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2025temizfertbilişim.csv")
fert2025.head()
yıl2025= fert2025.merge(
    hane2025,
    on=["referans yıl", "bülten no"],
    how="left"
)

C:\Users\dilara\AppData\Local\Temp\ipykernel_8424\2516001873.py:3: DtypeWarning: Columns (0: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  fert2025 = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\fert bilişim temiz veriler\2025temizfertbilişim.csv")

In [31]:
yıl2025.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,masaüstü kullanımı,dizüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün hizmet arama,ürün güvenliği hakkında arama,websitesinde içerik paylaşma,internetten oy katılım,internetten iş arama,Unnamed: 38,internetten satış,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,online kurs,online eğitim materyal,online eğitim iletişim,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlet hakkında bilgi,edevlette hiçbir sey yapmadı,edevlet form işlemleri,edevletten randevu alma,edevletten bilgi alma,edevlet vergi işlem,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet dijital kimlik yok,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet eimza sorunu,edevlet ödeme sorunu,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,eticaret kullanımı,eticaretten alınan fiziksel mal,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,ekitap sesli kitap,yazılım indirme sürüm yükseltme,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu,online dergi gazete,oyun yayın platformu,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online c2c alışveriş,online ulaşım paylaşımı,online p2p konaklama,online ev hizmetleri,eticaret alışveriş sıklık,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret sağlık güven sorunu,online sigorta işlemleri,online banka işlemleri,online yatırım işlemleri,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri ofis yazılımı kullanma,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,kvkk reklam takip endişesi,kvkk izleme engelleme yazılım kullanma,online hesap açma,online hesap silme,online hesap silerken sorun olması,fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanehalkı adresinin kır veya kent olma durumu,hane ağırlık katsayısı
0,10011,2025,3,1,65,1,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009,2,1,2,1,1,2,TR1,3,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589,2,1,1,1,5,3,TR1,3,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274,2,1,1,1,2,3,TR1,3,3813.920274

In [32]:
yıl2015.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2015.csv", index=False)

In [33]:
yıl2016.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2016.csv", index=False)
yıl2017.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2017.csv", index=False)
yıl2018.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2018.csv", index=False)
yıl2019.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2019.csv", index=False)
yıl2020.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2020.csv", index=False)
yıl2021.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2021.csv", index=False)
yıl2022.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2022.csv", index=False)
yıl2023.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2023.csv", index=False)
yıl2024.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2024.csv", index=False)
yıl2025.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\yıl2025.csv", index=False)

In [34]:
yıl2015.head()

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1,"3316,216022",TR1,1,1.0,2.0
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
2,2015,10012,2,1.0,CEVAPLI FERT,NaN,1.0,NaN,48,2,1.0,1.0,3.0,2.0,NaN,NaN,4.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
3,2015,10012,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,54,1,1.0,3.0,3.0,2.0,NaN,NaN,5.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3,"2147,205564",TR1,1,1.0,2.0
4,2015,10013,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,39,2,1.0,1.0,3.0,2.0,NaN,NaN,4.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"1939,806488",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,4,"1939,806488",TR1,1,1.0,2.0

In [35]:
yıl2016.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,cevapsız fert,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,internet araması,online c2c alışveriş,cep telefonu ile internet kullanımı,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması.1,sosyal medya kullanımı,online haber okuma,ürün hizmet arama,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,websitesinde içerik paylaşma,websitesinde içerik paylaşma.1,online sağlık hizmeti kullanımı,"randevu alma (e-nabız,mhrs vb.)",online seyahat ve konaklama işlemleri,Unnamed: 46,internetten satış,online banka işlemleri,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sıklık,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,NaN,50,1,1.0,3.0,1.0,NaN,5.0,3.0,NaN,1.0,6.0,1.0,6.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318",1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10011,2,1.0,NaN,49,2,1.0,3.0,3.0,2.0,NaN,NaN,4.0,1.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,TR1,"1506,565318",1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"

In [36]:
yıl2017["online sağlık hizmeti kullanımı"]

0        NaN
1        NaN
2        1.0
3        1.0
4        1.0
        ...
45586    NaN
45587    NaN
45588    NaN
45589    NaN
45590    NaN
Name: online sağlık hizmeti kullanımı, Length: 45591, dtype: float64

In [37]:
yıl2018.head()

,referans yıl,bülten no,fert no,fert cevap durumu,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,cep telefonu kullanımı,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,günlük kullanılan internet,masaüstü kullanımı,dizüstü bilgisayar ile internet kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,ürün hizmet arama,online müzik dinleme platformu,online film/dizi/video platformu,ücretli online film/dizi/video platformu,sosyal medyada video izleme,oyun indirme sürüm yükseltme,sağlık bilgisi arama,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 40,internetten satış,internet üzerinden bulut depolama kullanımı,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,fert ağırlık katsayısı,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanefaktor
0,2018,11058,1,1,19,1,1,4,3,2.0,NaN,NaN,3.0,1,1,6.0,1,6.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,2.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301",1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2000.0,4,TR1,"3852,219301"
1,2018,11058,4,1,16,1,1,3,3,2.0,NaN,NaN,3.0,1,1,6.0,1,6.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,99.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"3852,219301",1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2000.0,4,TR1,"3852,219301"
2,2018,11325,2,1,34,1,1,2,1,NaN,9.0,1.0,NaN,1,90,NaN,1,6.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1749,850517",1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1600.0,5,TR1,"1749,850517"
3,2018,11863,4,1,22,1,1,51,1,NaN,5.0,1.0,NaN,1,1,6.0,1,6.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,90.0,NaN,2.0,2.0,2.0,2.0,2.0,"2848,618139",1,1,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,7500.0,4,TR2,"2848,618139"
4,2018,12096,1,1,27,1,1,4,1,NaN,5.0,1.0,NaN,1,1,6.0,1,6.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,"1775,022946",1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2000.0,4,TR2,"1775,022946"

In [38]:
yıl2018.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [39]:
yıl2019.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [40]:
yıl2020.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [41]:
yıl2021.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [42]:
yıl2022.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [43]:
yıl2023.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [44]:
yıl2024.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [45]:
yıl2025.rename(
    columns={
        "sağlık bilgisi arama": "online sağlık hizmeti kullanımı"
    },
    inplace=True
)

In [46]:
yıl2018["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        2.0
3        2.0
4        1.0
        ...
28883    NaN
28884    2.0
28885    2.0
28886    NaN
28887    2.0
Name: online sağlık hizmeti kullanımı, Length: 28888, dtype: float64

In [47]:
yıl2019["online sağlık hizmeti kullanımı"]

0        NaN
1        2.0
2        2.0
3        NaN
4        1.0
        ...
45055    NaN
45056    NaN
45057    NaN
45058    NaN
45059    NaN
Name: online sağlık hizmeti kullanımı, Length: 45060, dtype: float64

In [48]:
yıl2020["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        1.0
3        1.0
4        2.0
        ...
50013    2.0
50014    2.0
50015    2.0
50016    NaN
50017    NaN
Name: online sağlık hizmeti kullanımı, Length: 50018, dtype: float64

In [49]:
yıl2021["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
30525    1.0
30526    1.0
30527    NaN
30528    NaN
30529    1.0
Name: online sağlık hizmeti kullanımı, Length: 30530, dtype: float64

In [50]:
yıl2022["online sağlık hizmeti kullanımı"]

0        2.0
1        2.0
2        2.0
3        1.0
4        1.0
        ...
29576    1.0
29577    1.0
29578    2.0
29579    1.0
29580    1.0
Name: online sağlık hizmeti kullanımı, Length: 29581, dtype: float64

In [51]:
yıl2023["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        2.0
3        2.0
4        2.0
        ...
24766    NaN
24767    2.0
24768    1.0
24769    1.0
24770    2.0
Name: online sağlık hizmeti kullanımı, Length: 24771, dtype: float64

In [52]:
yıl2024["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
26268    1.0
26269    NaN
26270    2.0
26271    NaN
26272    NaN
Name: online sağlık hizmeti kullanımı, Length: 26273, dtype: float64

In [53]:
yıl2025["online sağlık hizmeti kullanımı"]

0        1.0
1        1.0
2        1.0
3        1.0
4        2.0
        ...
25488    NaN
25489    NaN
25490    NaN
25491    1.0
25492    1.0
Name: online sağlık hizmeti kullanımı, Length: 25493, dtype: float64

In [54]:
#BİRLEŞTİRME İŞLEMİ : hiçbir değişken dışarıda bırakılmadan hepsi birleşti.

In [55]:
df= pd.concat(
    [
        yıl2015,
        yıl2016,
        yıl2017,
        yıl2018,
        yıl2019,
        yıl2020,
        yıl2021,
        yıl2022,
        yıl2023,
        yıl2024,
        yıl2025
    ],
    ignore_index=True,
    sort=False
)

In [56]:
df.shape
df["referans yıl"].value_counts().sort_index()

referans yıl
2015    35850
2016    39754
2017    45591
2018    28888
2019    45060
2020    50018
2021    30530
2022    29581
2023    24771
2024    26273
2025    25493
Name: count, dtype: int64

In [57]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [58]:
df.tail(2)

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
381807,2025,240910,1,NaN,NaN,NaN,NaN,NaN,31,1,NaN,4.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2.0,1.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,2.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,5374.040852,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5374.040852,TRC,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1.0,NaN,NaN,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,2.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,1.0,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,2.0,NaN,NaN,2.0,1.0,2.0,NaN,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,2.0,1130.0,1.0
381808,2025,240910,1,NaN,NaN,NaN,NaN,NaN,29,2,NaN,4.0,1.0,NaN,9112.0,1.0,NaN,NaN,NaN,1.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,2.0,2.0,1.0,NaN,NaN,1.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,2.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,5374.040852,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,5374.040852,TRC,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1.0,NaN,NaN,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,NaN,1.0,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,2.0,NaN,NaN,2.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,NaN,NaN,NaN,3.0,1.0,2.0,1130.0,1.0

In [59]:
df.to_csv(
    r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv",
    index=False,
    encoding="utf-8-sig"
)

In [60]:
df=pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_8424\3599974089.py:1: DtypeWarning: Columns (0: fert durum, 1: istatistiki bölge birimleri sınıflaması(Düzey 1), 2: fert ağırlık katsayısı, 3: hane ağırlık katsayısı, 4: istatistiki bölge birimleri sınıflaması (düzey 1), 5: hanede var olan bilişim cihazları açıklaması, 6: hanefaktor, 7: eticaret tür açıklama, 8: doğduğu ülke kodu, 9: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1.0,"3316,216022",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3.0,"2147,205564",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv", low_memory=False)

print(df.shape)
print(df.columns.tolist())

(381809, 468)
['referans yıl', 'bülten no', 'fert no', 'fert cevap durumu', 'fert durum', 'cevapsız fert', 'cevaplayan fert', 'cevaplayan fert no', 'yaş', 'cinsiyet', 'okuma yazma durumu', 'eğitim', 'çalışma durumu', 'iş sahibi mi', 'uluslararası meslek', 'işteki durumu', 'çalışmama nedeni', 'bilgisayar son kullanım zamanı', 'bilgisayar kullanım sıklığı', 'en son internet ne zaman kullanıldı', 'internet kullanım sıklığı', 'nternet kullanım yeri ev', 'internet kullanım yeri işyeri', 'internet kullanım yeri eğitim', 'internet kullanım yeri internet cafe', 'internet kullanım yeri başka ev', 'internet kullanım yeri kablosuz alan', 'internet kullanım yeri diğer', 'cep telefonu şebekesi ile internet kullanımı', 'cep telefonu kablosuz bağlantı ile internet kullanımı', 'mobil internet taşınabilir cihaz şebeke', 'taşınabilir bilgisayar ile kablosuz internet kullanımı', 'diğer cihazlar ile internet kullanımı', 'internet erişimi için cihaz kullanmıyor', 'eposta kullanımı', 'internet araması', 'sosyal medya kullanımı', 'sosyal medya kullanım sıklığı', 'websitesinde içerik paylaşma', 'online haber okuma', 'online sağlık hizmeti kullanımı', 'online kurs hakkında bilgi arama', 'genel bilgi arama', 'ürün hizmet arama', 'yazılım indirme', 'websitesinde içerik paylaşma.1', 'internetten oy katılım', 'internetten iş arama', 'internet ortamında gruplara katılım', 'online seyahat ve konaklama işlemleri', 'Unnamed: 50', 'internetten satış', 'internet üzerinden bulut depolama kullanımı', 'online kurs', 'online eğitim materyal', 'online eğitim iletişim', 'internet üzerinden yapılan diğer eğitim faaliyetleri', 'edevlet hakkında bilgi', 'edevlet form işlemleri', 'edevlet form gönderme', 'edevlet form gönderme ihtiyacı yok', 'edevlet form gönderme hizmeti yok', 'edevlet form gönderme bilgi eksiği', 'edevlet form gönderme güvenlik endişesi', 'edevlet form gönderiminde eimza sorunu', 'edevlet form göndermeyi danışman yaptı', 'edevlet form gönderme diğer neden', 'eticaret kullanımı', 'eticaret gıda ürünleri alışverişi', 'eticaret ev eşyası alışverişi', 'eticaret ilaç alışverişi', 'eticaret giyim alışverişi', 'eticaret bilgisayar ve donanım alışverişi', 'eticaret elektronik araçlar alışverişi', 'eticaret telekomünikasyon hizmetleri', 'eticaret finansal hizmetler', 'eticaret konaklama hizmetleri', 'eticaret seyahat hizmetleri', 'eticaret bilet satın alma', 'eticaret film ve müzik hizmetleri', 'eticaret kitap dergi alışverişi', 'eticaret e-öğrenme hizmetleri', 'eticaret oyun yazılım ve bilgi ürünleri', 'eticaretdiğer türler alışverişi', 'eticaret yurt içindeki satıcılar', 'eticaret avrupa ülkelerindeki satıcılar', 'eticaret diğer ülkelerdeki satıcılar', 'eticaret satıcısının ülkesi bilinmiyor', 'eticaret alışveriş sayısı', 'eticaret harcama miktarı', 'eticaret teknik sorunlar', 'eticaret bilgi ve kullanım zorluğu', 'eticaret teslimat süresi sorunu', 'eticaret işlem ve ücret sorunu', 'eticaret hasarlı veya yanlış ürün sorunu', 'eticaret güvenlik ve gizlilik kaygısı', 'eticaret şikayet ve iade sorunu', 'eticaret yurt dışı alışveriş engeli', 'eticaret diğer sorunlar', 'eticaret sorun yaşamama', 'eticaret yapmama ürünü görmeden almak istememe', 'eticaret yapmama bilgi eksikliği', 'eticaret yapmama teslimat endişesi', 'eticaret yapmama gizlilik güvenlik endişesi', 'eticaret yapmama iade sorunu', 'eticaret yapmama kredi kartı kullanmama', 'eticaret yapmama diğer', 'dijital beceri dosya transfer', 'dijital beceri uygulama kurulum', 'dijital beceri ayar değiştirme', 'dijital beceri dosya kopyalama', 'dijital beceri metin hazırlama', 'dijital beceri doküman oluşturma', 'dijital beceri tablolama yazılımı kullanma', 'dijital beceri tablolama ileri yazılım kullanma', 'dijital beceri foto video düzenleme', 'dijital beceri kod yazma', 'internet güvenlik virüs sorunu', 'internet kişisel bilgi ihlali', 'internet şifre çalınması', 'internet kredi kartı dolandırıcılığı', 'internet uygunsuz site erişimi', 'güvenlik nedeniyle eticaret vazgeçme', 'güvenlik nedeniyle banka işlemi vazgeçme', 'güvenlik nedeniyle sosyal medya vazgeçme', 'güvenlik nedeniyle kamu hizmeti vazgeçme', 'güvenlik nedeniyle yazılım indirme vazgeçme', 'güvenlik nedeniyle mobil bağlantı vazgeçme', 'internet güvenlik veri yedekleme', 'kvkk çerez yönetimi', 'internet güvenlik ayar değiştirme', 'istatistiki bölge birimleri sınıflaması(Düzey 1)', 'fert ağırlık katsayısı', 'hanede masaüstü bilgisayar var mı', 'hanede dizüstü bilgisayar var mı', 'hanede cep telefonu var mı', 'hanede oyun konsolu var mı', 'hanede sabit telefonu var mı', 'hanede dijital fotoğraf makinesi var mı', 'hanede dvd/vcd oynatıcı var mı', 'hanede akıllı tv var mı', 'hanede diğer olan bilişim ekipmanları', 'hane bilgisayar kullanım durumu', 'hane internet erişim durumu', 'internet erişimi olan hanelerin internet kullanım durumu', 'evde olan masaüstü bilgisayarın internete bağlanma durumu', 'evde olan dizüstü bilgisayarın internete bağlanma durumu', 'evde olan cep telefonunun internete bağlanma durumu', 'evde olan oyun konsolunun internete bağlanma durumu', 'evde olan tv internete bağlanma durumu', 'evde olan diğer cihazların internete bağlanma durumu', 'internet bağlantı türü adsl', 'internet bağlantı türü kablo tv altyapısı üzerinden kablolu', 'internet bağlantı türü fiber bağlantı, ethernet, PLC vb', 'internet bağlantı türü kablolu sabit internet ', 'internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı', 'internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.', 'internet bağlantı türü çevirmeli bağlantı veya ısdn ', 'internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS) ', 'evden internete bağlanmıyor başka yerden bağlanıyor', 'haneden kimsenin internete bağlanmasına gerek yok', 'bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor', 'internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor', 'internete bağlanmayı bilmediği için evden internete bağlanmıyor', 'gizlilik/güvenlik endişesi ile evden internete bağlanmıyor', 'bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor', 'evden internete bağlanmama diğer', 'hane gelir aylık', 'hane büyüklüğü', 'hane ağırlık katsayısı', 'istatistiki bölge birimleri sınıflaması (düzey 1)', 'cevaplılık durum', 'kapsam içi/dışı', 'hane bilgilendirme mektubunun ulaşma durumu', 'akıllı tv ile internet kullanımı', 'online film/dizi/video platformu', 'sosyal medyada video izleme', 'online c2c alışveriş', 'cep telefonu ile internet kullanımı', 'dizüstü bilgisayar ile internet kullanımı', 'taşınabilir bilgisayar ile mobil şebeke internet kullanımı', 'internet araması.1', 'oyun indirme sürüm yükseltme', 'online müzik dinleme platformu', 'online film/dizi/video platformu.1', 'ücretli online film/dizi/video platformu', 'sosyal medyada video izleme.1', 'randevu alma (e-nabız,mhrs vb.)', 'Unnamed: 46', 'online banka işlemleri', 'eticaret alışveriş sıklık', 'ürün hizmet arama.1', 'fiyat karşılaştırma', 'müşteri yorum inceleme', 'sosyal medya reklamı sonrası alışveriş', 'online yatırım işlemleri', 'online sigorta işlemleri', 'online banka işlemleri.1', 'kişisel bilgi paylaşımı ad soyad', 'kişisel bilgi paylaşımı iletişim bilgileri', 'kişisel bilgi paylaşımı ödeme bilgileri', 'kişisel bilgi paylaşımı diğer bilgiler', 'kişisel bilgi paylaşmama', 'kvkk gizlilik politikası okuması', 'kvkk konum erişimini kısıtlama', 'kvkk sosyal medya gizlilik', 'kvkk veri paylaşım reddetme', 'kvkk web güvenlik kontrolü', 'kvkk veri güncelleme silme talep', 'kvkk izleme engelleme yazılım kullanma', 'kapsam içi kapsam dışı', 'hanede tablet var mı', 'hanede sabit hatlı telefon var mı', 'hanede var olan bilişim cihazları açıklaması', 'evde olan tabletin internete bağlanma durumu', 'sabit internet (ev interneti)', 'mobil internet', 'cep telefonu üzerinden darbant bağlantı', 'kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor', 'Unnamed: 38', 'eticaret film müzik alışverişi', 'eticaret kitap alışverişi', 'eticaret dergi gazete alışverişi', 'eticaret yazılım ve bilgi ürünleri alışverişi', 'eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi', 'eticaret yurt dışı web sitelerinden dijital ürün alışverişi', 'eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı', 'eticaret yurt dışı web sitelerinden diğer alışverişler', 'cep telefonu kullanımı', 'günlük kullanılan internet', 'masaüstü kullanımı', 'tablet kullanımı', 'cep telefonu kullanımı.1', 'diğer cihaz kullanımı', 'dizüstü bilgisayar ile internet kullanımı.1', 'tablet ile internet kullanımı', 'Unnamed: 40', 'internet güvenliği için kullanıcı adı ve şifre kullanımı', 'internet güvenliği için sosyal medya hesaplarında şifre kullanımı', 'internet güvenliği için tek kullanımlık şifre kullanımı', 'internet güvenliği için eimza kullanımı', 'internet güvenliği için cep telefonu sms ile şifre doğrulama', 'internet güvenliği için tek kullanımlık şifre kuponu kullanımı', 'internet güvenliği için diğer yöntemler', 'akıllı telefon kullanımı', 'akıllı telefonda güvenlik uygulaması bulunması', 'akıllı telefona güvenlik uygulaması yükleme', 'akıllı telefonda güvenlik uygulaması bulunmaması', 'akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor', 'akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama', 'akıllı telefonda güvenlik kısıtlarını iptal etme', 'işyerinde bilişim teknolojileri kullanımı', 'işyerinde üretim ve stok için bilişim teknolojileri kullanımı', 'işyerinde e-posta kullanımı', 'işyerinde elektronik doküman kullanımı', 'işyerinde sosyal medya kullanımı', 'işyerinde uygulama kullanımı', 'işyerinde özel yazılım kullanımı', 'işyerinde bilişim işlemlerinin gelişmiş kullanımı', 'işyerinde görev değişimi için internet kullanımı', 'işyerinde yeni bilgi öğrenme amacıyla internet kullanımı', 'işyerinde bilişim teknolojileri kullanım yeterliliği', 'evden çalışma durumu', 'evden çalışırken internet kullanımı ', 'dijital beceri ücretsiz online kurs katılım', 'dijital beceri ücretli eğitim programı bireysel katılım', 'dijital beceri kamu tarafından ücretsiz kurs katılım', 'dijital beceri işyeri tarafından eğitim programı katılım', 'dijital beceri iş ile ilgili eğitim katılım', 'masaüstü bilgisayarın internete bağlanma durumu', 'dizüstü bilgisayarın internete bağlanma durumu', 'tablerin internete bağlanma durumı', 'cep telefonunun internete bağlanma durumu', 'diğer cihazların internete bağlanma durumu', 'tv internete bağlanma durumu', 'hanefaktor', 'sosyal medyada mesajlaşma', 'Unnamed: 34', 'eticaret yapmama başkasına yaptırma', 'cep telefonuna sahip', 'sağlık sonuçlarını almak', 'Unnamed: 33', 'eticaret spor malzemesi alışverişi', 'eticaret çocuk oyuncakları ve bakım alışverişi', 'eticaret cd plak alışverişi', 'eticaret dvd plak alışverişi', 'eticaret elektronik cihazlar ve aksesuarı alışverişi', 'eticaret yemek siparişi', 'eticaret kozmetik alışverişi', 'eticaret temizlik ve kişisel bakım ürünleri alışverişi', 'eticaret motorlu araç yedekleri alışverişi', 'Unnamed: 73', 'yakınlık durumu', 'dizüstü kullanımı', 'edevlet form göndermeyi tercih etmedi', 'edevlet adli hizmet sıklığı', 'edevlet asayiş hizmet sıklığı', 'edevlet belediye hizmet sıklığı', 'edevlet çevresel hizmet sıklığı', 'edevlet eğitim hizmet sıklığı', 'edevlet ekonomi hizmet sıklığı', 'edevlet kültür spor hizmet sıklığı', 'edevlet sağlık hizmet sıklığı', 'edevlet sosyal güvenlik hizmet sıklığı', 'edevlet ulaştırma hizmet sıklığı', 'edevlet diğer hizmet sıklığı', 'eticaret tür açıklama', 'ekitap sesli kitap', 'oyun yayın platformu', 'yazılım indirme sürüm yükseltme', 'sağlık/sağlıklı yaşam uygulamaları', 'diğer mobil uygulamalar', 'online etkinlik biletleri spor', 'online etkinlik biletleri kültür', 'internet bağlantı aboneliği', 'elektrik su doğal gaz vb hizmet aboneliği', 'online ev hizmetleri', 'online ev hizmetleri.1', 'online şirketlerle ulaşım', 'online ulaşım paylaşımı', 'online turizm acenteleri ile konaklama', 'online p2p konaklama', 'web kullanım zorluğu', 'web garanti bilgi sorun', 'webde yapılan satın almanın teslimat gecikmesi sorunu', 'webde yapılan satın almanın beklenenden yüksek maliyet', 'webde yapılan satın alınanın yanlış/hasarlı olması', 'webde yapılan satın almanın dolandırıcılık sorunu', 'webde yapılan satın almaların şikayet iade tazminat sorunu', 'yurt dışı web sitelerinde alışveriş engeli ', 'web alısverişlerindeki diğer sorunlar ', 'web alışverişlerinde sorun yok', 'eticaret yapmama güven sorunu', 'eticaret yapmama ihtiyaç yok', 'dijital beceri ofis yazılımı kullanma', 'dijital beceri şüpheli içerikle karşılaşma', 'dijital beceri şüpheli içerik kontrol etme', 'dijital beceri bilgi kaynağı kontrolü', 'dijital beceri içerik tartışmaya katılım', 'dijital beceri içerik offline tartışma', 'dijital beceri güvenilmez bilgi farkındalığı', 'dijital beceri bilgi beceri eksikliği', 'dijital beceri bilgiyi kontrol etmeme diğer', 'internet çerez bilgi farkındalığı', 'hanede diğer cihazlar var mı', 'fert no.1', 'doğduğu ülke', 'doğduğu ülke kodu', 'uyruk', 'uyruk ülke kodu', 'sağlık problemi nedeni ile faaliyet sınırlaması', 'doktora gitmeden konsültasyonlar ve reçete alma', 'Unnamed: 39', 'örgün eğitim için online kurs', 'iş için online kurs', 'özel amaç için online kurs', 'whatsapp kullanımı', 'instagram kullanımı', 'youtube kullanımı', 'facebook kullanımı', 'twitter kullanımı', 'telegram kullanımı', 'tiktok kullanımı', 'snapchat kullanımı', 'bip kullanımı', 'diğer mobil uygulama kullanımları', 'edevlet resmi işlem', 'edevlet kamu bilgi', 'edevlette hiçbir sey yapmadı', 'edevletten randevu alma', 'edevlette vergi beyani verme yönetimi', 'edevlet belge talep', 'edevlet yardım talep', 'edevlet diğer talepler', 'edevletten talepe ihtiyaç yok', 'edevlet kullanımı bilgi eksiği', 'edevlet güven sorunu', 'edevlet işlemlerini başkası yapıyor', 'edevlet kullanım diğer', 'edevlet kullanımı zor', 'edevlet kullanırken teknik sorunlar', 'edevlet mobil erişim sorunu', 'edevlette diğer sorunlar', 'edevlette sorun yok', 'online müzik dinleme platformu.1', 'WEBSTE_HHN_HZMET', 'enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı', 'internete bağlı alarm güvenlik kamerası ve dedektör kullanımı', 'internete bağlı akıllı cihaz ve ev robotu kullanımı', 'sanal asistan ve akıllı hoparlör kullanımı', 'internete bağlı cihaz kullanmıyor', 'internete bağlı cihaz ve sistemlerden haberi yok', 'internete bağlı cihaz ve sistemlere ihtiyacı yok', 'internete bağlı cihaz ve sistemleri pahalı bulma', 'internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması', 'internete bağlı cihaz kullanımı konusunda beceri eksikliği', 'internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe', 'internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi', 'internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi', 'internete bağlı cihazı diğer nedenlerle kullanmama', 'internete bağlı tv kullanımı', 'internete bağlı oyun konsolu kullanımı', 'internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı', 'internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı', 'internete bağlı sağlık izleme ve tıbbi cihaz kullanımı', 'internete bağlı akıllı robot ve oyuncak kullanımı', 'internete bağlı akıllı araç ve otomobil kullanımı', 'internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu', 'internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi', 'internete bağlı cihaz kullanımında ve kurulumundaki sorunlar', 'internete bağlı cihaz kullanımındaki diğer sorunlar', 'internete bağlı cihaz kullanımında sorun yaşamama', 'mobil telefon değiştirildiğinde yapılan işlem', 'dizüstü veya tablet değiştirildiğinde yapılan işlem', 'masaüstü bilgisayar değiştirildiğinde yapılan işlem', "hanenin aylık toplam net geliri (20'li gelir grubu)", 'Unnamed: 35', 'evden çalışma sıklığı', 'edevletten bilgi alma', 'edevlet dijital kimlik yok', 'ekimliği özel amaç için kullanma', 'ekimliği kamu hizmeti için kullanma', 'ekimliği özel hizmet için kullanma', 'ekimlikten haberi yok', 'ekimlik yok', 'ekimlik var ama ihtiyaç olmadı', 'ekimlik var ama kullanımı güvenli değil', 'ekimliği teknik sorundan kullanamama', 'ekimlik mobil erişim yok', 'ekimlik var ama baska sebeplerle kullanmıyorum', "hanenin aylık toplam net geliri (5'li gelir grubu)", 'sağlık problemi nedeni ile faaliyet sınırlama süresi', 'podcast dinlemek ve indirmek', 'online hesap açma', 'online hesap silme', 'online hesap silerken sorun olması', 'edevlet vergi işlem', 'edevlet eimza sorunu', 'edevlet ödeme sorunu', 'eticaret cd dvd alışverişi', 'online ulaşım hizmeti', 'online konaklama hizmeti', 'online etkinlik biletleri', 'oyun indirme sürüm yükseltme.1', 'online dergi gazete', 'cihaz satın alınımında fiyat önceliği', 'cihaz satın alınımında marka tasarım ve boyut önceliği', 'cihaz satın alınımında teknik donanım ve performans önceliği', 'cihaz satın alınımında çevre dostu tasarım önceliği', 'cihaz satın alınımında ek garanti tercihi', 'cihaz satın alınımında enerji verimliliği önceliği', 'cihaz satın alınımında geri alım programı etkisi', 'cihaz satın alınımında diğer faktörler', 'cihaz satın alınımında hiçbir faktörü önemsememe', 'BT_TEL_CEP', 'hanede akıllı saat var mı', 'fiziksel sağlık bilgisi arama', 'ruhsal sağlık bilgisi arama', 'ürün güvenliği hakkında arama', 'yapay zeka kullanımı', 'yapay zeka özel amaç kullanımı', 'yapay zeka iş için kullanımı', 'yapay zeka eğitim için kullanımı', 'yapay zeka kullanmama nedeni', 'eticaretten alınan fiziksel mal', 'eticaret sağlık güven sorunu', 'kvkk reklam takip endişesi', 'hanehalkı adresinin kır veya kent olma durumu']

In [ ]:
# ============================================================
# PANEL PROBIT ANALİZİ 
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import os
import numpy as np
import pandas as pd
import statsmodels.api as sm

from statsmodels.discrete.discrete_model import Probit
from statsmodels.stats.outliers_influence import variance_inflation_factor

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import openpyxl


# ============================================================
# 1) AYARLAR
# ============================================================

DATA_PATH = r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv"
OUT_DIR = r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik"

EXCEL_PATH = os.path.join(OUT_DIR, "panel_probit_sorunsuz_final.xlsx")
GRAFIK_PATH = os.path.join(OUT_DIR, "panel_probit_sorunsuz_grafik.png")


# ============================================================
# 2) VERİ YÜKLE
# ============================================================

COLS = [
    "referans yıl",
    "online sağlık hizmeti kullanımı",
    "eticaret ilaç alışverişi",
    "cinsiyet",
    "yaş",
    "eğitim",
    "hane gelir aylık",
    "hanenin aylık toplam net geliri (20'li gelir grubu)",
    "hanenin aylık toplam net geliri (5'li gelir grubu)",
]

print("=" * 70)
print("VERİ YÜKLENİYOR...")
print("=" * 70)

df_raw = pd.read_csv(DATA_PATH, usecols=COLS, low_memory=False)

print(f"Ham veri boyutu: {df_raw.shape}")


# ============================================================
# 3) TEMEL DEĞİŞKENLER
# ============================================================

df_raw["yil"] = pd.to_numeric(df_raw["referans yıl"], errors="coerce")
df_raw["yas"] = pd.to_numeric(df_raw["yaş"], errors="coerce")

df_raw["saglik_online"] = np.where(
    df_raw["online sağlık hizmeti kullanımı"] == 1,
    1,
    np.where(df_raw["online sağlık hizmeti kullanımı"] == 2, 0, np.nan)
)

df_raw["ilac_eticaret"] = np.where(
    df_raw["eticaret ilaç alışverişi"] == 1,
    1,
    np.where(df_raw["eticaret ilaç alışverişi"] == 2, 0, np.nan)
)


# ============================================================
# 4) EĞİTİM
# ============================================================

EGT_MAP = {
    0.0: 0,
    1.0: 1,
    2.0: 2,
    3.0: 3,
    4.0: 4,
    5.0: 5,
    51.0: 5,
    511.0: 5,
    512.0: 5,
    52.0: 5,
    53.0: 6,
    6.0: 6,
    7.0: 6,
}

df_raw["egitim_ord"] = pd.to_numeric(
    df_raw["eğitim"],
    errors="coerce"
).map(EGT_MAP)


# ============================================================
# 5) GELİRİ TEK 5'Lİ STANDARDA ÇEVİR
# ============================================================

df_raw["gelir_5li_std"] = np.nan

df_raw["gelir_kaynak"] = pd.Series(
    pd.NA,
    index=df_raw.index,
    dtype="object"
)

df_raw["gelir_aylik_num"] = pd.to_numeric(
    df_raw["hane gelir aylık"],
    errors="coerce"
)

for year in sorted(df_raw["yil"].dropna().unique()):

    mask_year = (
        (df_raw["yil"] == year) &
        df_raw["gelir_aylik_num"].notna() &
        (df_raw["gelir_aylik_num"] > 0)
    )

    if mask_year.sum() >= 5:

        try:
            gelir_5li = pd.qcut(
                df_raw.loc[mask_year, "gelir_aylik_num"],
                q=5,
                labels=[1, 2, 3, 4, 5],
                duplicates="drop"
            )

            df_raw.loc[mask_year, "gelir_5li_std"] = pd.to_numeric(
                gelir_5li,
                errors="coerce"
            )

            df_raw.loc[mask_year, "gelir_kaynak"] = "ayliktan_5liye"

        except Exception as e:
            print(f"{year} gelir dönüşüm hatası:", e)


def convert_20_to_5(x):

    if pd.isna(x):
        return np.nan

    try:
        x = int(float(x))
    except:
        return np.nan

    if 1 <= x <= 4:
        return 1
    elif 5 <= x <= 8:
        return 2
    elif 9 <= x <= 12:
        return 3
    elif 13 <= x <= 16:
        return 4
    elif 17 <= x <= 20:
        return 5

    return np.nan


gelir_20li = pd.to_numeric(
    df_raw["hanenin aylık toplam net geliri (20'li gelir grubu)"],
    errors="coerce"
)

mask_20li = (
    df_raw["gelir_5li_std"].isna() &
    gelir_20li.notna()
)

df_raw.loc[mask_20li, "gelir_5li_std"] = gelir_20li[mask_20li].apply(
    convert_20_to_5
)

df_raw.loc[mask_20li, "gelir_kaynak"] = "20liden_5liye"


gelir_5li_orj = pd.to_numeric(
    df_raw["hanenin aylık toplam net geliri (5'li gelir grubu)"],
    errors="coerce"
)

mask_5li = (
    df_raw["gelir_5li_std"].isna() &
    gelir_5li_orj.notna()
)

df_raw.loc[mask_5li, "gelir_5li_std"] = gelir_5li_orj[mask_5li]
df_raw.loc[mask_5li, "gelir_kaynak"] = "orijinal_5li"


print("\nGELİR KAYNAKLARI")
print(df_raw["gelir_kaynak"].value_counts(dropna=False))

print("\nGELİR 5'Lİ DAĞILIM")
print(df_raw["gelir_5li_std"].value_counts(dropna=False).sort_index())


# ============================================================
# 6) BAĞIMSIZ DEĞİŞKENLER
# ============================================================

df_raw["kadin"] = np.where(
    df_raw["cinsiyet"] == 2,
    1,
    np.where(df_raw["cinsiyet"] == 1, 0, np.nan)
)

df_raw["yas31_45"] = np.where(
    (df_raw["yas"] >= 31) & (df_raw["yas"] <= 45),
    1,
    0
)

df_raw["yas46_60"] = np.where(
    (df_raw["yas"] >= 46) & (df_raw["yas"] <= 60),
    1,
    0
)

df_raw["yas60ustu"] = np.where(
    df_raw["yas"] > 60,
    1,
    0
)

df_raw["egitim_orta_lise"] = np.where(
    df_raw["egitim_ord"].isin([3, 4]),
    1,
    0
)

df_raw["egitim_universite"] = np.where(
    df_raw["egitim_ord"] == 5,
    1,
    0
)

df_raw["egitim_uni_ustu"] = np.where(
    df_raw["egitim_ord"] == 6,
    1,
    0
)

df_raw["log_gelir"] = np.log(df_raw["gelir_5li_std"])


# ============================================================
# 7) YIL DUMMYLERİ
# Referans yıl: 2015
# ============================================================

for year in [
    2016, 2017, 2018, 2019, 2020,
    2021, 2022, 2023, 2024, 2025
]:

    df_raw[f"yil_{year}"] = np.where(
        df_raw["yil"] == year,
        1,
        0
    )


X_COLS = [
    "kadin",
    "log_gelir",
    "yas31_45",
    "yas46_60",
    "yas60ustu",
    "egitim_orta_lise",
    "egitim_universite",
    "egitim_uni_ustu",
    "yil_2016",
    "yil_2017",
    "yil_2018",
    "yil_2019",
    "yil_2020",
    "yil_2021",
    "yil_2022",
    "yil_2023",
    "yil_2024",
    "yil_2025"
]


# ============================================================
# 8) YARDIMCI FONKSİYONLAR
# ============================================================

def clean_X(X):

    X = X.copy()

    # sonsuz değerleri temizle
    X = X.replace([np.inf, -np.inf], np.nan)

    # tamamen boş sütunları sil
    X = X.dropna(axis=1, how="all")

    # tek değerli sütunları sil
    nunique = X.nunique(dropna=True)
    drop_cols = nunique[nunique <= 1].index.tolist()

    if len(drop_cols) > 0:
        print("\nModelden çıkarılan sabit değişkenler:")
        print(drop_cols)

    X = X.drop(columns=drop_cols, errors="ignore")

    return X


def safe_summary_table(model):

    try:
        return pd.DataFrame(model.summary2().tables[1])
    except Exception:
        return pd.DataFrame({
            "Coef.": model.params,
            "Std.Err.": model.bse,
            "z": model.tvalues,
            "P>|z|": model.pvalues,
            "[0.025": model.conf_int()[0],
            "0.975]": model.conf_int()[1]
        })


def safe_marginal_effects(model, X):

    try:
        margeff = model.get_margeff(at="overall")
        arr = margeff.margeff
        se = margeff.margeff_se
        z = margeff.tvalues
        p = margeff.pvalues
        ci = margeff.conf_int()

        names = [c for c in X.columns if c != "const"]

        min_len = min(
            len(names),
            len(arr),
            len(se),
            len(z),
            len(p),
            len(ci)
        )

        return pd.DataFrame({
            "Degisken": names[:min_len],
            "dy_dx": arr[:min_len],
            "Std_Hata": se[:min_len],
            "z": z[:min_len],
            "P_degeri": p[:min_len],
            "CI_alt": ci[:min_len, 0],
            "CI_ust": ci[:min_len, 1]
        })

    except Exception as e:
        return pd.DataFrame({
            "Hata": [str(e)]
        })


def run_model(dep_var, title):

    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)

    X = df_raw[X_COLS].copy()
    y = df_raw[dep_var].copy()

    model_df = pd.concat([X, y], axis=1)
    model_df = model_df.replace([np.inf, -np.inf], np.nan)
    model_df = model_df.dropna()

    y = model_df[dep_var]
    X = model_df.drop(columns=[dep_var])

    X = clean_X(X)

    X = sm.add_constant(X, has_constant="add")

    print("Gözlem Sayısı:", len(model_df))
    print("Bağımlı değişken dağılımı:")
    print(y.value_counts())

    try:
        model = Probit(y, X).fit(
            method="newton",
            maxiter=500,
            disp=False
        )
    except Exception as e:
        print("Newton hata verdi, BFGS deneniyor:")
        print(e)

        model = Probit(y, X).fit(
            method="bfgs",
            maxiter=1000,
            disp=False
        )

    print(model.summary())

    summary_df = safe_summary_table(model)
    marginal_df = safe_marginal_effects(model, X)

    return model, summary_df, marginal_df, X, y


def calculate_vif(X):

    vif_X = X.copy()

    if "const" in vif_X.columns:
        vif_X = vif_X.drop(columns=["const"])

    vif_X = vif_X.astype(float)

    vif_df = pd.DataFrame()
    vif_df["Degisken"] = vif_X.columns

    vif_df["VIF"] = [
        variance_inflation_factor(vif_X.values, i)
        for i in range(vif_X.shape[1])
    ]

    return vif_df


# ============================================================
# 9) MODELLER
# ============================================================

model_online, online_summary, online_marginal, X_online, y_online = run_model(
    "saglik_online",
    "MODEL 1 - ONLINE SAĞLIK HİZMETİ"
)

model_eticaret, eticaret_summary, eticaret_marginal, X_eticaret, y_eticaret = run_model(
    "ilac_eticaret",
    "MODEL 2 - E-TİCARET İLAÇ ALIŞVERİŞİ"
)


# ============================================================
# 10) VIF
# ============================================================

vif_online = calculate_vif(X_online)
vif_eticaret = calculate_vif(X_eticaret)

print("\nVIF ONLINE")
print(vif_online)

print("\nVIF ETICARET")
print(vif_eticaret)


# ============================================================
# 11) GRAFİK
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

MODELS = [
    (model_online, y_online, "Online Sağlık", axes[0]),
    (model_eticaret, y_eticaret, "E-Ticaret İlaç", axes[1])
]

for model, y, title, ax in MODELS:

    probs = model.predict()

    plot_df = pd.DataFrame({
        "yil": df_raw.loc[y.index, "yil"],
        "prob": probs,
        "y": y
    })

    agg = plot_df.groupby("yil").agg(
        tahmin=("prob", "mean"),
        gozlem=("y", "mean")
    )

    x_pos = range(len(agg))

    ax.bar(
        x_pos,
        agg["tahmin"],
        alpha=0.7,
        label="Tahmin"
    )

    ax.plot(
        list(x_pos),
        agg["gozlem"],
        "o-",
        linewidth=2,
        label="Gözlenen"
    )

    ax.set_xticks(list(x_pos))
    ax.set_xticklabels(
        agg.index.astype(int),
        rotation=45
    )

    ax.set_title(title)
    ax.set_ylim(0, 1)
    ax.legend()

plt.tight_layout()
plt.savefig(GRAFIK_PATH, dpi=150, bbox_inches="tight")

print("\nGrafik kaydedildi:")
print(GRAFIK_PATH)


# ============================================================
# 12) EXCEL'E AKTAR
# ============================================================

with pd.ExcelWriter(EXCEL_PATH, engine="openpyxl") as writer:

    online_summary.to_excel(
        writer,
        sheet_name="Online_Probit"
    )

    online_marginal.to_excel(
        writer,
        sheet_name="Online_Marjinal",
        index=False
    )

    eticaret_summary.to_excel(
        writer,
        sheet_name="Eticaret_Probit"
    )

    eticaret_marginal.to_excel(
        writer,
        sheet_name="Eticaret_Marjinal",
        index=False
    )

    vif_online.to_excel(
        writer,
        sheet_name="VIF_Online",
        index=False
    )

    vif_eticaret.to_excel(
        writer,
        sheet_name="VIF_Eticaret",
        index=False
    )

    df_raw["gelir_kaynak"].value_counts(dropna=False).reset_index().to_excel(
        writer,
        sheet_name="Gelir_Kaynagi",
        index=False
    )

    df_raw["gelir_5li_std"].value_counts(dropna=False).sort_index().reset_index().to_excel(
        writer,
        sheet_name="Gelir_Dagilim",
        index=False
    )

    df_raw["yil"].value_counts(dropna=False).sort_index().reset_index().to_excel(
        writer,
        sheet_name="Yillara_Gore_Gozlem",
        index=False
    )

    pd.DataFrame({
        "Degisken": X_online.columns,
        "Modelde_Kullanildi": "Evet"
    }).to_excel(
        writer,
        sheet_name="Model_Degiskenleri",
        index=False
    )

    pd.DataFrame({
        "Bilgi": [
            "Toplam Satır",
            "Toplam Sütun",
            "Excel Yolu",
            "Grafik Yolu",
            "Not"
        ],
        "Deger": [
            df_raw.shape[0],
            df_raw.shape[1],
            EXCEL_PATH,
            GRAFIK_PATH,
            "Sabit/tek değerli değişkenler otomatik silindi."
        ]
    }).to_excel(
        writer,
        sheet_name="Genel_Bilgi",
        index=False
    )


print("\n" + "=" * 70)
print("ANALİZ TAMAMLANDI")
print("=" * 70)

print("\nExcel:")
print(EXCEL_PATH)

print("\nGrafik:")
print(GRAFIK_PATH)

======================================================================
VERİ YÜKLENİYOR...
======================================================================
Ham veri boyutu: (381809, 9)

GELİR KAYNAKLARI
gelir_kaynak
ayliktan_5liye    226263
orijinal_5li       76537
<NA>               49428
20liden_5liye      29581
Name: count, dtype: int64

GELİR 5'Lİ DAĞILIM
gelir_5li_std
1.0    69269
2.0    72606
3.0    64917
4.0    63316
5.0    62273
NaN    49428
Name: count, dtype: int64

======================================================================
MODEL 1 - ONLINE SAĞLIK HİZMETİ
======================================================================

Modelden çıkarılan sabit değişkenler:
['yil_2019']
Gözlem Sayısı: 199800
Bağımlı değişken dağılımı:
saglik_online
1.0    130889
0.0     68911
Name: count, dtype: int64
                          Probit Regression Results
==============================================================================
Dep. Variable:          saglik_online   No. Observations:               199800
Model:                         Probit   Df Residuals:                   199782
Method:                           MLE   Df Model:                           17
Date:                Sat, 16 May 2026   Pseudo R-squ.:                  0.1042
Time:                        21:42:04   Log-Likelihood:            -1.1530e+05
converged:                       True   LL-Null:                   -1.2872e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -0.3615      0.016    -23.035      0.000      -0.392      -0.331
kadin                 0.2598      0.006     42.303      0.000       0.248       0.272
log_gelir             0.2679      0.006     44.456      0.000       0.256       0.280
yas31_45              0.1477      0.008     19.491      0.000       0.133       0.163
yas46_60             -0.1052      0.009    -12.131      0.000      -0.122      -0.088
yas60ustu            -0.4453      0.013    -34.701      0.000      -0.470      -0.420
egitim_orta_lise      0.5508      0.007     73.574      0.000       0.536       0.565
egitim_universite     1.0085      0.010    104.785      0.000       0.990       1.027
egitim_uni_ustu       1.0819      0.046     23.557      0.000       0.992       1.172
yil_2016              0.0082      0.017      0.472      0.637      -0.026       0.042
yil_2017             -0.0531      0.017     -3.192      0.001      -0.086      -0.021
yil_2018             -0.0338      0.016     -2.057      0.040      -0.066      -0.002
yil_2020             -0.1251      0.016     -7.928      0.000      -0.156      -0.094
yil_2021              0.0166      0.016      1.044      0.296      -0.015       0.048
yil_2022             -0.1690      0.016    -10.679      0.000      -0.200      -0.138
yil_2023             -0.1020      0.016     -6.275      0.000      -0.134      -0.070
yil_2024             -0.1666      0.016    -10.377      0.000      -0.198      -0.135
yil_2025             -0.1550      0.016     -9.653      0.000      -0.186      -0.124
=====================================================================================

======================================================================
MODEL 2 - E-TİCARET İLAÇ ALIŞVERİŞİ
======================================================================

Modelden çıkarılan sabit değişkenler:
['yil_2019', 'yil_2025']
Gözlem Sayısı: 63516
Bağımlı değişken dağılımı:
ilac_eticaret
0.0    57785
1.0     5731
Name: count, dtype: int64
                          Probit Regression Results
==============================================================================
Dep. Variable:          ilac_eticaret   No. Observations:                63516
Model:                         Probit   Df Residuals:                    63499
Method:                           MLE   Df Model:                           16
Date:                Sat, 16 May 2026   Pseudo R-squ.:                 0.05932
Time:                        21:42:07   Log-Likelihood:                -18108.
converged:                       True   LL-Null:                       -19250.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.4669      0.056    -44.197      0.000      -2.576      -2.357
kadin                 0.1411      0.015      9.647      0.000       0.112       0.170
log_gelir             0.1847      0.018     10.119      0.000       0.149       0.220
yas31_45              0.2019      0.016     12.263      0.000       0.170       0.234
yas46_60              0.2922      0.023     12.843      0.000       0.248       0.337
yas60ustu             0.4737      0.047     10.112      0.000       0.382       0.565
egitim_orta_lise      0.0547      0.029      1.869      0.062      -0.003       0.112
egitim_universite     0.3034      0.029     10.416      0.000       0.246       0.360
egitim_uni_ustu       0.3538      0.064      5.562      0.000       0.229       0.479
yil_2016             -0.0077      0.059     -0.131      0.896      -0.123       0.108
yil_2017              0.1359      0.053      2.542      0.011       0.031       0.241
yil_2018              0.1382      0.052      2.650      0.008       0.036       0.240
yil_2020              0.3580      0.050      7.186      0.000       0.260       0.456
yil_2021              0.7070      0.047     14.944      0.000       0.614       0.800
yil_2022              0.6427      0.048     13.523      0.000       0.550       0.736
yil_2023              0.7034      0.048     14.803      0.000       0.610       0.797
yil_2024              0.6965      0.047     14.717      0.000       0.604       0.789
=====================================================================================

VIF ONLINE
             Degisken       VIF
0               kadin  1.851651
1           log_gelir  4.986240
2            yas31_45  2.039122
3            yas46_60  1.808954
4           yas60ustu  1.259429
5    egitim_orta_lise  2.832772
6   egitim_universite  2.127086
7     egitim_uni_ustu  1.035954
8            yil_2016  1.398187
9            yil_2017  1.636902
10           yil_2018  1.665405
11           yil_2020  1.838366
12           yil_2021  1.840857
13           yil_2022  1.861662
14           yil_2023  1.746899
15           yil_2024  1.819180
16           yil_2025  1.834246

VIF ETICARET
             Degisken       VIF
0               kadin  1.894056
1           log_gelir  7.781671
2            yas31_45  1.927942
3            yas46_60  1.336327
4           yas60ustu  1.051565
5    egitim_orta_lise  5.261544
6   egitim_universite  5.288480
7     egitim_uni_ustu  1.145353
8            yil_2016  1.578454
9            yil_2017  1.914260
10           yil_2018  2.050157
11           yil_2020  2.162723
12           yil_2021  2.502503
13           yil_2022  2.492591
14           yil_2023  2.422420
15           yil_2024  2.525074

Grafik kaydedildi:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_sorunsuz_grafik.png

======================================================================
ANALİZ TAMAMLANDI
======================================================================

Excel:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_sorunsuz_final.xlsx

Grafik:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_sorunsuz_grafik.png

In [1]:
# ============================================================
# PANEL PROBIT ANALİZİ - FINAL KOD
# GELİR: 5'Lİ KATEGORİ
# REFERANS GELİR = GELİR 1 (EN DÜŞÜK)
# MODELE: gelir2, gelir3, gelir4, gelir5 girer
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import os
import numpy as np
import pandas as pd
import statsmodels.api as sm

from statsmodels.discrete.discrete_model import Probit
from statsmodels.stats.outliers_influence import variance_inflation_factor

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import openpyxl


# ============================================================
# 1) AYARLAR
# ============================================================

DATA_PATH = r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv"

OUT_DIR = r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik"

EXCEL_PATH = os.path.join(
    OUT_DIR,
    "panel_probit_gelir_dummy_final.xlsx"
)

GRAFIK_PATH = os.path.join(
    OUT_DIR,
    "panel_probit_gelir_dummy_grafik.png"
)


# ============================================================
# 2) VERİ YÜKLE
# ============================================================

COLS = [
    "referans yıl",
    "online sağlık hizmeti kullanımı",
    "eticaret ilaç alışverişi",
    "cinsiyet",
    "yaş",
    "eğitim",
    "hane gelir aylık",
    "hanenin aylık toplam net geliri (20'li gelir grubu)",
    "hanenin aylık toplam net geliri (5'li gelir grubu)",
]

print("=" * 70)
print("VERİ YÜKLENİYOR...")
print("=" * 70)

df_raw = pd.read_csv(
    DATA_PATH,
    usecols=COLS,
    low_memory=False
)

print("Ham veri boyutu:", df_raw.shape)


# ============================================================
# 3) TEMEL DEĞİŞKENLER
# ============================================================

df_raw["yil"] = pd.to_numeric(
    df_raw["referans yıl"],
    errors="coerce"
)

df_raw["yas"] = pd.to_numeric(
    df_raw["yaş"],
    errors="coerce"
)

# ------------------------------------------------------------
# Online sağlık
# ------------------------------------------------------------

df_raw["saglik_online"] = np.where(
    df_raw["online sağlık hizmeti kullanımı"] == 1,
    1,
    np.where(
        df_raw["online sağlık hizmeti kullanımı"] == 2,
        0,
        np.nan
    )
)

# ------------------------------------------------------------
# E-ticaret ilaç
# ------------------------------------------------------------

df_raw["ilac_eticaret"] = np.where(
    df_raw["eticaret ilaç alışverişi"] == 1,
    1,
    np.where(
        df_raw["eticaret ilaç alışverişi"] == 2,
        0,
        np.nan
    )
)


# ============================================================
# 4) EĞİTİM KODLAMA
# REFERANS: İLKOKUL VE ALTI
# ============================================================

egitim_num = pd.to_numeric(
    df_raw["eğitim"],
    errors="coerce"
)

# Ortaokul/Lise
df_raw["egitim_orta_lise"] = np.where(
    egitim_num.isin([3, 4]),
    1,
    np.where(egitim_num.notna(), 0, np.nan)
)

# Üniversite
df_raw["egitim_universite"] = np.where(
    egitim_num.isin([5, 51, 511, 512, 52]),
    1,
    np.where(egitim_num.notna(), 0, np.nan)
)

# Üniversite üstü
df_raw["egitim_uni_ustu"] = np.where(
    egitim_num.isin([53, 6, 7]),
    1,
    np.where(egitim_num.notna(), 0, np.nan)
)


# ============================================================
# 5) GELİRİ TEK 5'Lİ STANDART HALE GETİR
# ============================================================

df_raw["gelir_5li_std"] = np.nan

df_raw["gelir_kaynak"] = pd.Series(
    pd.NA,
    index=df_raw.index,
    dtype="object"
)

# ============================================================
# 5.1 AYLIK GELİR → HER YIL KENDİ İÇİNDE 5'Lİ GRUP
# ============================================================

df_raw["gelir_aylik_num"] = pd.to_numeric(
    df_raw["hane gelir aylık"],
    errors="coerce"
)

for year in sorted(df_raw["yil"].dropna().unique()):

    mask_year = (
        (df_raw["yil"] == year) &
        df_raw["gelir_aylik_num"].notna() &
        (df_raw["gelir_aylik_num"] > 0)
    )

    if mask_year.sum() >= 5:

        try:

            gelir_5li = pd.qcut(
                df_raw.loc[mask_year, "gelir_aylik_num"],
                q=5,
                labels=[1, 2, 3, 4, 5],
                duplicates="drop"
            )

            df_raw.loc[
                mask_year,
                "gelir_5li_std"
            ] = pd.to_numeric(
                gelir_5li,
                errors="coerce"
            )

            df_raw.loc[
                mask_year,
                "gelir_kaynak"
            ] = "ayliktan_5liye"

        except Exception as e:

            print(f"{year} gelir dönüşüm hatası:")
            print(e)


# ============================================================
# 5.2 20'Lİ GELİR → 5'Lİ GELİR
# ============================================================

def convert_20_to_5(x):

    if pd.isna(x):
        return np.nan

    try:
        x = int(float(x))
    except:
        return np.nan

    if 1 <= x <= 4:
        return 1

    elif 5 <= x <= 8:
        return 2

    elif 9 <= x <= 12:
        return 3

    elif 13 <= x <= 16:
        return 4

    elif 17 <= x <= 20:
        return 5

    return np.nan


gelir_20li = pd.to_numeric(
    df_raw["hanenin aylık toplam net geliri (20'li gelir grubu)"],
    errors="coerce"
)

mask_20li = (
    df_raw["gelir_5li_std"].isna() &
    gelir_20li.notna()
)

df_raw.loc[
    mask_20li,
    "gelir_5li_std"
] = gelir_20li[mask_20li].apply(convert_20_to_5)

df_raw.loc[
    mask_20li,
    "gelir_kaynak"
] = "20liden_5liye"


# ============================================================
# 5.3 HAZIR 5'Lİ GELİR
# ============================================================

gelir_5li_orj = pd.to_numeric(
    df_raw["hanenin aylık toplam net geliri (5'li gelir grubu)"],
    errors="coerce"
)

mask_5li = (
    df_raw["gelir_5li_std"].isna() &
    gelir_5li_orj.notna()
)

df_raw.loc[
    mask_5li,
    "gelir_5li_std"
] = gelir_5li_orj[mask_5li]

df_raw.loc[
    mask_5li,
    "gelir_kaynak"
] = "orijinal_5li"


print("\nGELİR KAYNAKLARI")
print(
    df_raw["gelir_kaynak"].value_counts(dropna=False)
)

print("\nGELİR 5'Lİ DAĞILIM")
print(
    df_raw["gelir_5li_std"]
    .value_counts(dropna=False)
    .sort_index()
)


# ============================================================
# 6) GELİR DUMMYLERİ
# REFERANS: GELİR 1
# ============================================================

df_raw["gelir2"] = np.where(
    df_raw["gelir_5li_std"] == 2,
    1,
    np.where(df_raw["gelir_5li_std"].notna(), 0, np.nan)
)

df_raw["gelir3"] = np.where(
    df_raw["gelir_5li_std"] == 3,
    1,
    np.where(df_raw["gelir_5li_std"].notna(), 0, np.nan)
)

df_raw["gelir4"] = np.where(
    df_raw["gelir_5li_std"] == 4,
    1,
    np.where(df_raw["gelir_5li_std"].notna(), 0, np.nan)
)

df_raw["gelir5"] = np.where(
    df_raw["gelir_5li_std"] == 5,
    1,
    np.where(df_raw["gelir_5li_std"].notna(), 0, np.nan)
)


# ============================================================
# 7) DİĞER BAĞIMSIZ DEĞİŞKENLER
# ============================================================

# ------------------------------------------------------------
# Cinsiyet
# REFERANS: ERKEK
# ------------------------------------------------------------

df_raw["kadin"] = np.where(
    df_raw["cinsiyet"] == 2,
    1,
    np.where(df_raw["cinsiyet"] == 1, 0, np.nan)
)

# ------------------------------------------------------------
# Yaş grupları
# REFERANS: 15-30
# ------------------------------------------------------------

df_raw["yas31_45"] = np.where(
    (df_raw["yas"] >= 31) &
    (df_raw["yas"] <= 45),
    1,
    np.where(df_raw["yas"].notna(), 0, np.nan)
)

df_raw["yas46_60"] = np.where(
    (df_raw["yas"] >= 46) &
    (df_raw["yas"] <= 60),
    1,
    np.where(df_raw["yas"].notna(), 0, np.nan)
)

df_raw["yas60ustu"] = np.where(
    df_raw["yas"] > 60,
    1,
    np.where(df_raw["yas"].notna(), 0, np.nan)
)


# ============================================================
# 8) YIL DUMMYLERİ
# REFERANS: 2015
# ============================================================

for year in [
    2016, 2017, 2018, 2019, 2020,
    2021, 2022, 2023, 2024, 2025
]:

    df_raw[f"yil_{year}"] = np.where(
        df_raw["yil"] == year,
        1,
        np.where(df_raw["yil"].notna(), 0, np.nan)
    )


# ============================================================
# 9) MODEL DEĞİŞKENLERİ
# ============================================================

X_COLS = [

    "kadin",

    "gelir2",
    "gelir3",
    "gelir4",
    "gelir5",

    "yas31_45",
    "yas46_60",
    "yas60ustu",

    "egitim_orta_lise",
    "egitim_universite",
    "egitim_uni_ustu",

    "yil_2016",
    "yil_2017",
    "yil_2018",
    "yil_2019",
    "yil_2020",
    "yil_2021",
    "yil_2022",
    "yil_2023",
    "yil_2024",
    "yil_2025"
]


# ============================================================
# 10) YARDIMCI FONKSİYONLAR
# ============================================================

def clean_X(X):

    X = X.copy()

    X = X.replace(
        [np.inf, -np.inf],
        np.nan
    )

    X = X.dropna(axis=1, how="all")

    nunique = X.nunique(dropna=True)

    drop_cols = nunique[
        nunique <= 1
    ].index.tolist()

    if len(drop_cols) > 0:

        print("\nModelden çıkarılan sabit değişkenler:")
        print(drop_cols)

    X = X.drop(
        columns=drop_cols,
        errors="ignore"
    )

    return X


def safe_summary_table(model):

    try:

        return pd.DataFrame(
            model.summary2().tables[1]
        )

    except Exception:

        conf = model.conf_int()

        return pd.DataFrame({

            "Coef.": model.params,
            "Std.Err.": model.bse,
            "z": model.tvalues,
            "P>|z|": model.pvalues,
            "[0.025": conf[0],
            "0.975]": conf[1]

        })


def safe_marginal_effects(model, X):

    try:

        margeff = model.get_margeff(
            at="overall"
        )

        arr = margeff.margeff
        se = margeff.margeff_se
        z = margeff.tvalues
        p = margeff.pvalues
        ci = margeff.conf_int()

        names = [
            c for c in X.columns
            if c != "const"
        ]

        min_len = min(
            len(names),
            len(arr),
            len(se),
            len(z),
            len(p),
            len(ci)
        )

        return pd.DataFrame({

            "Degisken": names[:min_len],
            "dy_dx": arr[:min_len],
            "Std_Hata": se[:min_len],
            "z": z[:min_len],
            "P_degeri": p[:min_len],
            "CI_alt": ci[:min_len, 0],
            "CI_ust": ci[:min_len, 1]

        })

    except Exception as e:

        return pd.DataFrame({
            "Hata": [str(e)]
        })


def run_model(dep_var, title):

    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)

    X = df_raw[X_COLS].copy()

    y = df_raw[dep_var].copy()

    model_df = pd.concat(
        [X, y],
        axis=1
    )

    model_df = model_df.replace(
        [np.inf, -np.inf],
        np.nan
    )

    model_df = model_df.dropna()

    y = model_df[dep_var]

    X = model_df.drop(
        columns=[dep_var]
    )

    X = clean_X(X)

    X = sm.add_constant(
        X,
        has_constant="add"
    )

    print("Gözlem Sayısı:", len(model_df))

    print("\nBağımlı değişken dağılımı:")
    print(y.value_counts())

    try:

        model = Probit(y, X).fit(
            method="newton",
            maxiter=500,
            disp=False
        )

    except Exception as e:

        print("\nNewton hata verdi:")
        print(e)

        print("\nBFGS deneniyor...")

        model = Probit(y, X).fit(
            method="bfgs",
            maxiter=1000,
            disp=False
        )

    print(model.summary())

    summary_df = safe_summary_table(model)

    marginal_df = safe_marginal_effects(
        model,
        X
    )

    return (
        model,
        summary_df,
        marginal_df,
        X,
        y
    )


def calculate_vif(X):

    vif_X = X.copy()

    if "const" in vif_X.columns:

        vif_X = vif_X.drop(
            columns=["const"]
        )

    vif_X = vif_X.astype(float)

    vif_df = pd.DataFrame()

    vif_df["Degisken"] = vif_X.columns

    vif_df["VIF"] = [

        variance_inflation_factor(
            vif_X.values,
            i
        )

        for i in range(vif_X.shape[1])

    ]

    return vif_df


# ============================================================
# 11) MODELLER
# ============================================================

(
    model_online,
    online_summary,
    online_marginal,
    X_online,
    y_online
) = run_model(

    "saglik_online",
    "MODEL 1 - ONLINE SAĞLIK HİZMETİ"

)

(
    model_eticaret,
    eticaret_summary,
    eticaret_marginal,
    X_eticaret,
    y_eticaret
) = run_model(

    "ilac_eticaret",
    "MODEL 2 - E-TİCARET İLAÇ ALIŞVERİŞİ"

)


# ============================================================
# 12) VIF
# ============================================================

vif_online = calculate_vif(X_online)

vif_eticaret = calculate_vif(X_eticaret)

print("\nVIF ONLINE")
print(vif_online)

print("\nVIF ETICARET")
print(vif_eticaret)


# ============================================================
# 13) GRAFİK
# ============================================================

fig, axes = plt.subplots(
    1,
    2,
    figsize=(14, 5),
    sharey=True
)

MODELS = [

    (
        model_online,
        y_online,
        "Online Sağlık",
        axes[0]
    ),

    (
        model_eticaret,
        y_eticaret,
        "E-Ticaret İlaç",
        axes[1]
    )

]

for model, y, title, ax in MODELS:

    probs = model.predict()

    plot_df = pd.DataFrame({

        "yil": df_raw.loc[y.index, "yil"],
        "prob": probs,
        "y": y

    })

    agg = plot_df.groupby("yil").agg(

        tahmin=("prob", "mean"),
        gozlem=("y", "mean")

    )

    x_pos = range(len(agg))

    ax.bar(
        x_pos,
        agg["tahmin"],
        alpha=0.7,
        label="Tahmin"
    )

    ax.plot(
        list(x_pos),
        agg["gozlem"],
        "o-",
        linewidth=2,
        label="Gözlenen"
    )

    ax.set_xticks(list(x_pos))

    ax.set_xticklabels(
        agg.index.astype(int),
        rotation=45
    )

    ax.set_title(title)

    ax.set_ylim(0, 1)

    ax.legend()

plt.tight_layout()

plt.savefig(
    GRAFIK_PATH,
    dpi=150,
    bbox_inches="tight"
)

print("\nGrafik kaydedildi:")
print(GRAFIK_PATH)


# ============================================================
# 14) EXCEL'E AKTAR
# ============================================================

with pd.ExcelWriter(
    EXCEL_PATH,
    engine="openpyxl"
) as writer:

    online_summary.to_excel(
        writer,
        sheet_name="Online_Probit"
    )

    online_marginal.to_excel(
        writer,
        sheet_name="Online_Marjinal",
        index=False
    )

    eticaret_summary.to_excel(
        writer,
        sheet_name="Eticaret_Probit"
    )

    eticaret_marginal.to_excel(
        writer,
        sheet_name="Eticaret_Marjinal",
        index=False
    )

    vif_online.to_excel(
        writer,
        sheet_name="VIF_Online",
        index=False
    )

    vif_eticaret.to_excel(
        writer,
        sheet_name="VIF_Eticaret",
        index=False
    )

    df_raw[
        "gelir_kaynak"
    ].value_counts(dropna=False).reset_index().to_excel(

        writer,
        sheet_name="Gelir_Kaynagi",
        index=False

    )

    df_raw[
        "gelir_5li_std"
    ].value_counts(dropna=False).sort_index().reset_index().to_excel(

        writer,
        sheet_name="Gelir_Dagilim",
        index=False

    )

    df_raw[
        "yil"
    ].value_counts(dropna=False).sort_index().reset_index().to_excel(

        writer,
        sheet_name="Yillara_Gore_Gozlem",
        index=False

    )

    pd.DataFrame({

        "Degisken": X_online.columns,
        "Modelde_Kullanildi": "Evet"

    }).to_excel(

        writer,
        sheet_name="Model_Degiskenleri",
        index=False

    )


print("\n" + "=" * 70)
print("ANALİZ TAMAMLANDI")
print("=" * 70)

print("\nExcel:")
print(EXCEL_PATH)

print("\nGrafik:")
print(GRAFIK_PATH)

======================================================================
VERİ YÜKLENİYOR...
======================================================================
Ham veri boyutu: (381809, 9)

GELİR KAYNAKLARI
gelir_kaynak
ayliktan_5liye    226263
orijinal_5li       76537
<NA>               49428
20liden_5liye      29581
Name: count, dtype: int64

GELİR 5'Lİ DAĞILIM
gelir_5li_std
1.0    69269
2.0    72606
3.0    64917
4.0    63316
5.0    62273
NaN    49428
Name: count, dtype: int64

======================================================================
MODEL 1 - ONLINE SAĞLIK HİZMETİ
======================================================================

Modelden çıkarılan sabit değişkenler:
['yil_2019']
Gözlem Sayısı: 199800

Bağımlı değişken dağılımı:
saglik_online
1.0    130889
0.0     68911
Name: count, dtype: int64
                          Probit Regression Results
==============================================================================
Dep. Variable:          saglik_online   No. Observations:               199800
Model:                         Probit   Df Residuals:                   199779
Method:                           MLE   Df Model:                           20
Date:                Sun, 17 May 2026   Pseudo R-squ.:                  0.1043
Time:                        12:56:59   Log-Likelihood:            -1.1529e+05
converged:                       True   LL-Null:                   -1.2872e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -0.3523      0.016    -21.709      0.000      -0.384      -0.320
kadin                 0.2595      0.006     42.233      0.000       0.247       0.271
gelir2                0.1767      0.010     17.311      0.000       0.157       0.197
gelir3                0.2682      0.010     26.053      0.000       0.248       0.288
gelir4                0.3545      0.010     34.275      0.000       0.334       0.375
gelir5                0.4447      0.011     41.007      0.000       0.423       0.466
yas31_45              0.1475      0.008     19.464      0.000       0.133       0.162
yas46_60             -0.1070      0.009    -12.314      0.000      -0.124      -0.090
yas60ustu            -0.4469      0.013    -34.785      0.000      -0.472      -0.422
egitim_orta_lise      0.5497      0.007     73.378      0.000       0.535       0.564
egitim_universite     1.0008      0.010    102.075      0.000       0.982       1.020
egitim_uni_ustu       1.0639      0.046     23.060      0.000       0.973       1.154
yil_2016              0.0082      0.017      0.471      0.638      -0.026       0.042
yil_2017             -0.0508      0.017     -3.049      0.002      -0.083      -0.018
yil_2018             -0.0319      0.016     -1.938      0.053      -0.064       0.000
yil_2020             -0.1228      0.016     -7.777      0.000      -0.154      -0.092
yil_2021              0.0178      0.016      1.114      0.265      -0.013       0.049
yil_2022             -0.1667      0.016    -10.523      0.000      -0.198      -0.136
yil_2023             -0.0999      0.016     -6.143      0.000      -0.132      -0.068
yil_2024             -0.1641      0.016    -10.214      0.000      -0.196      -0.133
yil_2025             -0.1523      0.016     -9.471      0.000      -0.184      -0.121
=====================================================================================

======================================================================
MODEL 2 - E-TİCARET İLAÇ ALIŞVERİŞİ
======================================================================

Modelden çıkarılan sabit değişkenler:
['yil_2019', 'yil_2025']
Gözlem Sayısı: 63516

Bağımlı değişken dağılımı:
ilac_eticaret
0.0    57785
1.0     5731
Name: count, dtype: int64
                          Probit Regression Results
==============================================================================
Dep. Variable:          ilac_eticaret   No. Observations:                63516
Model:                         Probit   Df Residuals:                    63496
Method:                           MLE   Df Model:                           19
Date:                Sun, 17 May 2026   Pseudo R-squ.:                 0.06034
Time:                        12:57:04   Log-Likelihood:                -18088.
converged:                       True   LL-Null:                       -19250.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -2.3645      0.059    -39.938      0.000      -2.481      -2.248
kadin                 0.1399      0.015      9.554      0.000       0.111       0.169
gelir2               -0.0112      0.037     -0.302      0.763      -0.084       0.062
gelir3                0.0755      0.035      2.132      0.033       0.006       0.145
gelir4                0.1105      0.034      3.246      0.001       0.044       0.177
gelir5                0.2415      0.033      7.247      0.000       0.176       0.307
yas31_45              0.1994      0.016     12.093      0.000       0.167       0.232
yas46_60              0.2827      0.023     12.390      0.000       0.238       0.327
yas60ustu             0.4689      0.047     10.005      0.000       0.377       0.561
egitim_orta_lise      0.0497      0.029      1.697      0.090      -0.008       0.107
egitim_universite     0.2811      0.029      9.571      0.000       0.224       0.339
egitim_uni_ustu       0.3108      0.064      4.852      0.000       0.185       0.436
yil_2016             -0.0035      0.059     -0.059      0.953      -0.119       0.112
yil_2017              0.1419      0.054      2.651      0.008       0.037       0.247
yil_2018              0.1474      0.052      2.824      0.005       0.045       0.250
yil_2020              0.3691      0.050      7.398      0.000       0.271       0.467
yil_2021              0.7174      0.047     15.143      0.000       0.625       0.810
yil_2022              0.6540      0.048     13.740      0.000       0.561       0.747
yil_2023              0.7161      0.048     15.046      0.000       0.623       0.809
yil_2024              0.7092      0.047     14.959      0.000       0.616       0.802
=====================================================================================

VIF ONLINE
             Degisken       VIF
0               kadin  1.854912
1              gelir2  2.145047
2              gelir3  2.177576
3              gelir4  2.310220
4              gelir5  2.723424
5            yas31_45  2.053075
6            yas46_60  1.810115
7           yas60ustu  1.259721
8    egitim_orta_lise  2.837714
9   egitim_universite  2.197660
10    egitim_uni_ustu  1.045736
11           yil_2016  1.478947
12           yil_2017  1.742720
13           yil_2018  1.802928
14           yil_2020  1.978910
15           yil_2021  1.998394
16           yil_2022  2.009565
17           yil_2023  1.874666
18           yil_2024  1.956791
19           yil_2025  1.980662

VIF ETICARET
             Degisken       VIF
0               kadin  1.902172
1              gelir2  2.370768
2              gelir3  2.792191
3              gelir4  3.460022
4              gelir5  5.185479
5            yas31_45  1.939215
6            yas46_60  1.338391
7           yas60ustu  1.051757
8    egitim_orta_lise  5.374290
9   egitim_universite  5.331243
10    egitim_uni_ustu  1.154248
11           yil_2016  1.690167
12           yil_2017  2.068147
13           yil_2018  2.268899
14           yil_2020  2.367619
15           yil_2021  2.793056
16           yil_2022  2.776109
17           yil_2023  2.700468
18           yil_2024  2.824390

Grafik kaydedildi:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_gelir_dummy_grafik.png

======================================================================
ANALİZ TAMAMLANDI
======================================================================

Excel:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_gelir_dummy_final.xlsx

Grafik:
C:\Users\dilara\Desktop\Hane halkı bilişim tüik\panel_probit_gelir_dummy_grafik.png