In [15]:
import pandas as pd
df=pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv")
df.head()

C:\Users\dilara\AppData\Local\Temp\ipykernel_15048\3041872158.py:2: DtypeWarning: Columns (0: fert durum, 1: istatistiki bölge birimleri sınıflaması(Düzey 1), 2: fert ağırlık katsayısı, 3: hane ağırlık katsayısı, 4: istatistiki bölge birimleri sınıflaması (düzey 1), 5: hanede var olan bilişim cihazları açıklaması, 6: hanefaktor, 7: eticaret tür açıklama, 8: doğduğu ülke kodu, 9: uyruk ülke kodu) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\ferthane\bütünveriler.csv")

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1.0,"3316,216022",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3.0,"2147,205564",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [17]:
df.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1.0,"3316,216022",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3.0,"2147,205564",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
print(df["referans yıl"].value_counts().sort_index())

referans yıl
2015    35850
2016    39754
2017    45591
2018    28888
2019    45060
2020    50018
2021    30530
2022    29581
2023    24771
2024    26273
2025    25493
Name: count, dtype: int64

In [19]:
df["hanenin aylık toplam net geliri (20'li gelir grubu)"].value_counts()

hanenin aylık toplam net geliri (20'li gelir grubu)
4.0     1759
11.0    1699
10.0    1627
7.0     1599
14.0    1563
5.0     1549
17.0    1528
12.0    1521
2.0     1510
15.0    1505
18.0    1492
8.0     1422
9.0     1393
6.0     1393
3.0     1392
19.0    1384
13.0    1337
16.0    1325
20.0    1315
1.0     1268
Name: count, dtype: int64

In [20]:
df["hanenin aylık toplam net geliri (5'li gelir grubu)"].value_counts()

hanenin aylık toplam net geliri (5'li gelir grubu)
3.0    15727
4.0    15379
2.0    15310
1.0    15110
5.0    15011
Name: count, dtype: int64

In [21]:
df.head(1)

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1.0,"3316,216022",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
keywords = ["cinsiyet", "yas", "gelir", "medeni"]

for col in df.columns:
    if any(k in col for k in keywords):
        print(col)

cinsiyet
eticaret ev eşyası alışverişi
hane gelir aylık
hanenin aylık toplam net geliri (20'li gelir grubu)
hanenin aylık toplam net geliri (5'li gelir grubu)

In [23]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.columns

Index(['referans yıl', 'bülten no', 'fert no', 'fert cevap durumu',
       'fert durum', 'cevapsız fert', 'cevaplayan fert', 'cevaplayan fert no',
       'yaş', 'cinsiyet',
       ...
       'ürün güvenliği hakkında arama', 'yapay zeka kullanımı',
       'yapay zeka özel amaç kullanımı', 'yapay zeka iş için kullanımı',
       'yapay zeka eğitim için kullanımı', 'yapay zeka kullanmama nedeni',
       'eticaretten alınan fiziksel mal', 'eticaret sağlık güven sorunu',
       'kvkk reklam takip endişesi',
       'hanehalkı adresinin kır veya kent olma durumu'],
      dtype='str', length=468)

##### Öncelikle frequency’ye bakalım.Verinin kadın/erkek, gelir, yaş, medeni durum… yüzdeleri.

In [24]:
df.head(2)

,referans yıl,bülten no,fert no,fert cevap durumu,fert durum,cevapsız fert,cevaplayan fert,cevaplayan fert no,yaş,cinsiyet,okuma yazma durumu,eğitim,çalışma durumu,iş sahibi mi,uluslararası meslek,işteki durumu,çalışmama nedeni,bilgisayar son kullanım zamanı,bilgisayar kullanım sıklığı,en son internet ne zaman kullanıldı,internet kullanım sıklığı,nternet kullanım yeri ev,internet kullanım yeri işyeri,internet kullanım yeri eğitim,internet kullanım yeri internet cafe,internet kullanım yeri başka ev,internet kullanım yeri kablosuz alan,internet kullanım yeri diğer,cep telefonu şebekesi ile internet kullanımı,cep telefonu kablosuz bağlantı ile internet kullanımı,mobil internet taşınabilir cihaz şebeke,taşınabilir bilgisayar ile kablosuz internet kullanımı,diğer cihazlar ile internet kullanımı,internet erişimi için cihaz kullanmıyor,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medya kullanım sıklığı,websitesinde içerik paylaşma,online haber okuma,online sağlık hizmeti kullanımı,online kurs hakkında bilgi arama,genel bilgi arama,ürün hizmet arama,yazılım indirme,websitesinde içerik paylaşma.1,internetten oy katılım,internetten iş arama,internet ortamında gruplara katılım,online seyahat ve konaklama işlemleri,Unnamed: 50,internetten satış,internet üzerinden bulut depolama kullanımı,online kurs,online eğitim materyal,online eğitim iletişim,internet üzerinden yapılan diğer eğitim faaliyetleri,edevlet hakkında bilgi,edevlet form işlemleri,edevlet form gönderme,edevlet form gönderme ihtiyacı yok,edevlet form gönderme hizmeti yok,edevlet form gönderme bilgi eksiği,edevlet form gönderme güvenlik endişesi,edevlet form gönderiminde eimza sorunu,edevlet form göndermeyi danışman yaptı,edevlet form gönderme diğer neden,eticaret kullanımı,eticaret gıda ürünleri alışverişi,eticaret ev eşyası alışverişi,eticaret ilaç alışverişi,eticaret giyim alışverişi,eticaret bilgisayar ve donanım alışverişi,eticaret elektronik araçlar alışverişi,eticaret telekomünikasyon hizmetleri,eticaret finansal hizmetler,eticaret konaklama hizmetleri,eticaret seyahat hizmetleri,eticaret bilet satın alma,eticaret film ve müzik hizmetleri,eticaret kitap dergi alışverişi,eticaret e-öğrenme hizmetleri,eticaret oyun yazılım ve bilgi ürünleri,eticaretdiğer türler alışverişi,eticaret yurt içindeki satıcılar,eticaret avrupa ülkelerindeki satıcılar,eticaret diğer ülkelerdeki satıcılar,eticaret satıcısının ülkesi bilinmiyor,eticaret alışveriş sayısı,eticaret harcama miktarı,eticaret teknik sorunlar,eticaret bilgi ve kullanım zorluğu,eticaret teslimat süresi sorunu,eticaret işlem ve ücret sorunu,eticaret hasarlı veya yanlış ürün sorunu,eticaret güvenlik ve gizlilik kaygısı,eticaret şikayet ve iade sorunu,eticaret yurt dışı alışveriş engeli,eticaret diğer sorunlar,eticaret sorun yaşamama,eticaret yapmama ürünü görmeden almak istememe,eticaret yapmama bilgi eksikliği,eticaret yapmama teslimat endişesi,eticaret yapmama gizlilik güvenlik endişesi,eticaret yapmama iade sorunu,eticaret yapmama kredi kartı kullanmama,eticaret yapmama diğer,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri dosya kopyalama,dijital beceri metin hazırlama,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,internet güvenlik virüs sorunu,internet kişisel bilgi ihlali,internet şifre çalınması,internet kredi kartı dolandırıcılığı,internet uygunsuz site erişimi,güvenlik nedeniyle eticaret vazgeçme,güvenlik nedeniyle banka işlemi vazgeçme,güvenlik nedeniyle sosyal medya vazgeçme,güvenlik nedeniyle kamu hizmeti vazgeçme,güvenlik nedeniyle yazılım indirme vazgeçme,güvenlik nedeniyle mobil bağlantı vazgeçme,internet güvenlik veri yedekleme,kvkk çerez yönetimi,internet güvenlik ayar değiştirme,istatistiki bölge birimleri sınıflaması(Düzey 1),fert ağırlık katsayısı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit telefonu var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan oyun konsolunun internete bağlanma durumu,evde olan tv internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,internet bağlantı türü adsl,internet bağlantı türü kablo tv altyapısı üzerinden kablolu,"internet bağlantı türü fiber bağlantı, ethernet, PLC vb",internet bağlantı türü kablolu sabit internet,"internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı","internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb.",internet bağlantı türü çevirmeli bağlantı veya ısdn,"internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS)",evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı,istatistiki bölge birimleri sınıflaması (düzey 1),cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,akıllı tv ile internet kullanımı,online film/dizi/video platformu,sosyal medyada video izleme,online c2c alışveriş,cep telefonu ile internet kullanımı,dizüstü bilgisayar ile internet kullanımı,taşınabilir bilgisayar ile mobil şebeke internet kullanımı,internet araması.1,oyun indirme sürüm yükseltme,online müzik dinleme platformu,online film/dizi/video platformu.1,ücretli online film/dizi/video platformu,sosyal medyada video izleme.1,"randevu alma (e-nabız,mhrs vb.)",Unnamed: 46,online banka işlemleri,eticaret alışveriş sıklık,ürün hizmet arama.1,fiyat karşılaştırma,müşteri yorum inceleme,sosyal medya reklamı sonrası alışveriş,online yatırım işlemleri,online sigorta işlemleri,online banka işlemleri.1,kişisel bilgi paylaşımı ad soyad,kişisel bilgi paylaşımı iletişim bilgileri,kişisel bilgi paylaşımı ödeme bilgileri,kişisel bilgi paylaşımı diğer bilgiler,kişisel bilgi paylaşmama,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk izleme engelleme yazılım kullanma,kapsam içi kapsam dışı,hanede tablet var mı,hanede sabit hatlı telefon var mı,hanede var olan bilişim cihazları açıklaması,evde olan tabletin internete bağlanma durumu,sabit internet (ev interneti),mobil internet,cep telefonu üzerinden darbant bağlantı,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,Unnamed: 38,eticaret film müzik alışverişi,eticaret kitap alışverişi,eticaret dergi gazete alışverişi,eticaret yazılım ve bilgi ürünleri alışverişi,eticaret yurt dışı web sitelerinden fiziksel ürün alışverişi,eticaret yurt dışı web sitelerinden dijital ürün alışverişi,eticaret yurt dışı web sitelerinden tatil ve konaklama hizmeti alımı,eticaret yurt dışı web sitelerinden diğer alışverişler,cep telefonu kullanımı,günlük kullanılan internet,masaüstü kullanımı,tablet kullanımı,cep telefonu kullanımı.1,diğer cihaz kullanımı,dizüstü bilgisayar ile internet kullanımı.1,tablet ile internet kullanımı,Unnamed: 40,internet güvenliği için kullanıcı adı ve şifre kullanımı,internet güvenliği için sosyal medya hesaplarında şifre kullanımı,internet güvenliği için tek kullanımlık şifre kullanımı,internet güvenliği için eimza kullanımı,internet güvenliği için cep telefonu sms ile şifre doğrulama,internet güvenliği için tek kullanımlık şifre kuponu kullanımı,internet güvenliği için diğer yöntemler,akıllı telefon kullanımı,akıllı telefonda güvenlik uygulaması bulunması,akıllı telefona güvenlik uygulaması yükleme,akıllı telefonda güvenlik uygulaması bulunmaması,akıllı telefonda güvenlik uygulaması olup olmadığını bilmiyor,akıllı telefonda virüs veya zararlı yazılım nedeniyle kayıp yaşama,akıllı telefonda güvenlik kısıtlarını iptal etme,işyerinde bilişim teknolojileri kullanımı,işyerinde üretim ve stok için bilişim teknolojileri kullanımı,işyerinde e-posta kullanımı,işyerinde elektronik doküman kullanımı,işyerinde sosyal medya kullanımı,işyerinde uygulama kullanımı,işyerinde özel yazılım kullanımı,işyerinde bilişim işlemlerinin gelişmiş kullanımı,işyerinde görev değişimi için internet kullanımı,işyerinde yeni bilgi öğrenme amacıyla internet kullanımı,işyerinde bilişim teknolojileri kullanım yeterliliği,evden çalışma durumu,evden çalışırken internet kullanımı,dijital beceri ücretsiz online kurs katılım,dijital beceri ücretli eğitim programı bireysel katılım,dijital beceri kamu tarafından ücretsiz kurs katılım,dijital beceri işyeri tarafından eğitim programı katılım,dijital beceri iş ile ilgili eğitim katılım,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,hanefaktor,sosyal medyada mesajlaşma,Unnamed: 34,eticaret yapmama başkasına yaptırma,cep telefonuna sahip,sağlık sonuçlarını almak,Unnamed: 33,eticaret spor malzemesi alışverişi,eticaret çocuk oyuncakları ve bakım alışverişi,eticaret cd plak alışverişi,eticaret dvd plak alışverişi,eticaret elektronik cihazlar ve aksesuarı alışverişi,eticaret yemek siparişi,eticaret kozmetik alışverişi,eticaret temizlik ve kişisel bakım ürünleri alışverişi,eticaret motorlu araç yedekleri alışverişi,Unnamed: 73,yakınlık durumu,dizüstü kullanımı,edevlet form göndermeyi tercih etmedi,edevlet adli hizmet sıklığı,edevlet asayiş hizmet sıklığı,edevlet belediye hizmet sıklığı,edevlet çevresel hizmet sıklığı,edevlet eğitim hizmet sıklığı,edevlet ekonomi hizmet sıklığı,edevlet kültür spor hizmet sıklığı,edevlet sağlık hizmet sıklığı,edevlet sosyal güvenlik hizmet sıklığı,edevlet ulaştırma hizmet sıklığı,edevlet diğer hizmet sıklığı,eticaret tür açıklama,ekitap sesli kitap,oyun yayın platformu,yazılım indirme sürüm yükseltme,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online etkinlik biletleri spor,online etkinlik biletleri kültür,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ev hizmetleri,online ev hizmetleri.1,online şirketlerle ulaşım,online ulaşım paylaşımı,online turizm acenteleri ile konaklama,online p2p konaklama,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret yapmama güven sorunu,eticaret yapmama ihtiyaç yok,dijital beceri ofis yazılımı kullanma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,internet çerez bilgi farkındalığı,hanede diğer cihazlar var mı,fert no.1,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,sağlık problemi nedeni ile faaliyet sınırlaması,doktora gitmeden konsültasyonlar ve reçete alma,Unnamed: 39,örgün eğitim için online kurs,iş için online kurs,özel amaç için online kurs,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlette hiçbir sey yapmadı,edevletten randevu alma,edevlette vergi beyani verme yönetimi,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,online müzik dinleme platformu.1,WEBSTE_HHN_HZMET,enerji tasarrufu amaçlı evde internete bağlı cihaz kullanımı,internete bağlı alarm güvenlik kamerası ve dedektör kullanımı,internete bağlı akıllı cihaz ve ev robotu kullanımı,sanal asistan ve akıllı hoparlör kullanımı,internete bağlı cihaz kullanmıyor,internete bağlı cihaz ve sistemlerden haberi yok,internete bağlı cihaz ve sistemlere ihtiyacı yok,internete bağlı cihaz ve sistemleri pahalı bulma,internete bağlı cihazların diğer cihaz ve sistemler ile uyumsuz olması,internete bağlı cihaz kullanımı konusunda beceri eksikliği,internete bağlı cihaz kullanırken veri gizliliği ve korunması hakkında endişe,internete bağlı cihaza siber saldırı ve güvenlik ihlali endişesi,internete bağlı cihazın emniyet ve sağlık riski oluşturması endişesi,internete bağlı cihazı diğer nedenlerle kullanmama,internete bağlı tv kullanımı,internete bağlı oyun konsolu kullanımı,internete bağlı ev ses sistemi ve akıllı hoparlör kullanımı,internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı,internete bağlı sağlık izleme ve tıbbi cihaz kullanımı,internete bağlı akıllı robot ve oyuncak kullanımı,internete bağlı akıllı araç ve otomobil kullanımı,internete bağlı cihaz kullanımında güvenlik ve veri gizliliği sorunu,internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi,internete bağlı cihaz kullanımında ve kurulumundaki sorunlar,internete bağlı cihaz kullanımındaki diğer sorunlar,internete bağlı cihaz kullanımında sorun yaşamama,mobil telefon değiştirildiğinde yapılan işlem,dizüstü veya tablet değiştirildiğinde yapılan işlem,masaüstü bilgisayar değiştirildiğinde yapılan işlem,hanenin aylık toplam net geliri (20'li gelir grubu),Unnamed: 35,evden çalışma sıklığı,edevletten bilgi alma,edevlet dijital kimlik yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimlik var ama ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,hanenin aylık toplam net geliri (5'li gelir grubu),sağlık problemi nedeni ile faaliyet sınırlama süresi,podcast dinlemek ve indirmek,online hesap açma,online hesap silme,online hesap silerken sorun olması,edevlet vergi işlem,edevlet eimza sorunu,edevlet ödeme sorunu,eticaret cd dvd alışverişi,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,oyun indirme sürüm yükseltme.1,online dergi gazete,cihaz satın alınımında fiyat önceliği,cihaz satın alınımında marka tasarım ve boyut önceliği,cihaz satın alınımında teknik donanım ve performans önceliği,cihaz satın alınımında çevre dostu tasarım önceliği,cihaz satın alınımında ek garanti tercihi,cihaz satın alınımında enerji verimliliği önceliği,cihaz satın alınımında geri alım programı etkisi,cihaz satın alınımında diğer faktörler,cihaz satın alınımında hiçbir faktörü önemsememe,BT_TEL_CEP,hanede akıllı saat var mı,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün güvenliği hakkında arama,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,eticaretten alınan fiziksel mal,eticaret sağlık güven sorunu,kvkk reklam takip endişesi,hanehalkı adresinin kır veya kent olma durumu
0,2015,10011,1,1.0,CEVAPLI FERT,NaN,1.0,NaN,58,1,1.0,1.0,3.0,2.0,NaN,NaN,5.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,"3316,216022",2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1.0,"3316,216022",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,10012,3,1.0,CEVAPLI FERT,NaN,1.0,NaN,20,1,1.0,3.0,3.0,2.0,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,TR1,"2147,205564",2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3.0,"2147,205564",TR1,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df["yas_grup"] = pd.cut(
    df["yaş"],
    bins=[0, 15, 30, 45, 60, 120],
    labels=["0-15", "16-30", "31-45", "46-60", "60+"]
)

C:\Users\dilara\AppData\Local\Temp\ipykernel_15048\864289371.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["yas_grup"] = pd.cut(

In [26]:
def freq_table(df, col):
    frekans = df[col].value_counts(dropna=False)
    yuzde = df[col].value_counts(normalize=True, dropna=False) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)

In [27]:
print("\nCİNSİYET")
print(freq_table(df, "cinsiyet"))

CİNSİYET
          Frekans  Yüzde
cinsiyet
2          193937  50.79
1          187872  49.21

In [28]:
import pandas as pd
import numpy as np

# 1) Kolon isimlerini aynen kullanacağız
col_raw = "hane gelir aylık"
col_20  = "hanenin aylık toplam net geliri (20'li gelir grubu)"
col_5   = "hanenin aylık toplam net geliri (5'li gelir grubu)"

# 2) Yeni standart değişken
df["gelir_5li"] = np.nan

# 3) Önce hazır 5'li gelir grubunu al
df.loc[df[col_5].notna(), "gelir_5li"] = df.loc[df[col_5].notna(), col_5]

# 4) 5'li boşsa, 20'li gelir grubunu 5'liye çevir
mask_20 = df["gelir_5li"].isna() & df[col_20].notna()

df.loc[mask_20, "gelir_5li"] = (
    ((df.loc[mask_20, col_20].astype(float) - 1) // 4) + 1
)

# 5) Hâlâ boşsa, sayısal hane gelir aylık üzerinden 5'li grup oluştur
mask_raw = df["gelir_5li"].isna() & df[col_raw].notna()

df.loc[mask_raw, "gelir_5li"] = pd.qcut(
    df.loc[mask_raw, col_raw],
    q=5,
    labels=[1, 2, 3, 4, 5],
    duplicates="drop"
)

# 6) Sayısal formata çevir
df["gelir_5li"] = pd.to_numeric(df["gelir_5li"], errors="coerce")

# 7) Kontrol
print("Eksik gelir_5li sayısı:", df["gelir_5li"].isna().sum())
print(df["gelir_5li"].value_counts(dropna=False).sort_index())

Eksik gelir_5li sayısı: 48247
gelir_5li
1.0    69688
2.0    77981
3.0    53096
4.0    67769
5.0    65028
NaN    48247
Name: count, dtype: int64

C:\Users\dilara\AppData\Local\Temp\ipykernel_15048\2681994059.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["gelir_5li"] = np.nan

In [29]:
def freq_table(df, col):
    tablo = df[col].value_counts(dropna=False).to_frame("Frekans")
    tablo["Yüzde"] = (df[col].value_counts(normalize=True, dropna=False) * 100).round(2)
    return tablo

print(freq_table(df, "gelir_5li"))

           Frekans  Yüzde
gelir_5li
2.0          77981  20.42
1.0          69688  18.25
4.0          67769  17.75
5.0          65028  17.03
3.0          53096  13.91
NaN          48247  12.64

In [30]:
cols = [
    "hane gelir aylık",
    "hanenin aylık toplam net geliri (20'li gelir grubu)",
    "hanenin aylık toplam net geliri (5'li gelir grubu)"
]

# 1) Üç gelir kolonunda eksik sayıları
print(df[cols].isna().sum())

# 2) Üçü de boş olan satır sayısı
print("Üçü de boş:", df[cols].isna().all(axis=1).sum())

# 3) hane gelir aylık gerçekten sayısal mı?
print(df["hane gelir aylık"].head(20))
print(df["hane gelir aylık"].dtype)
print(df["hane gelir aylık"].value_counts(dropna=False).head(20))

hane gelir aylık                                       154365
hanenin aylık toplam net geliri (20'li gelir grubu)    352228
hanenin aylık toplam net geliri (5'li gelir grubu)     305272
dtype: int64
Üçü de boş: 48247
0     1000.0
1     3000.0
2     3000.0
3     3000.0
4     2000.0
5     2000.0
6     2000.0
7     2000.0
8     4500.0
9     4500.0
10    3500.0
11    3500.0
12    3500.0
13    3500.0
14    2000.0
15    2000.0
16    2000.0
17    2500.0
18    2500.0
19    1500.0
Name: hane gelir aylık, dtype: float64
float64
hane gelir aylık
NaN        154365
2000.0      21306
3000.0      21104
1500.0      17423
2500.0      15253
1000.0      13725
5000.0      12154
4000.0      11477
3500.0       8220
1300.0       6779
6000.0       5476
1400.0       5336
4500.0       4299
500.0        4293
1600.0       4072
1200.0       4011
10000.0      3791
7000.0       3298
2300.0       3161
1800.0       2821
Name: count, dtype: int64

In [31]:
df_clean = df[df["gelir_5li"].notna()].copy()

In [32]:
print("Yeni veri boyutu:", df_clean.shape)
print(df_clean["gelir_5li"].value_counts())

Yeni veri boyutu: (333562, 470)
gelir_5li
2.0    77981
1.0    69688
4.0    67769
5.0    65028
3.0    53096
Name: count, dtype: int64

In [33]:
print(freq_table(df_clean, "gelir_5li"))

           Frekans  Yüzde
gelir_5li
2.0          77981  23.38
1.0          69688  20.89
4.0          67769  20.32
5.0          65028  19.50
3.0          53096  15.92

In [34]:
def freq_table(df, col):
    frekans = df[col].value_counts(dropna=False)
    yuzde = df[col].value_counts(normalize=True, dropna=False) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)

In [35]:
# çıktıyı al
print(freq_table(df, "cinsiyet"))

          Frekans  Yüzde
cinsiyet
2          193937  50.79
1          187872  49.21

In [36]:
def freq_table(df, col):
    frekans = df[col].value_counts(dropna=False)
    yuzde = df[col].value_counts(normalize=True, dropna=False) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)

In [37]:
print(freq_table(df, "yas_grup"))

          Frekans  Yüzde
yas_grup
31-45       98618  25.83
16-30       91423  23.94
46-60       81880  21.45
60+         54697  14.33
0-15        52690  13.80
NaN          2501   0.66

In [38]:
print(freq_table(df[df["yas_grup"].notna()], "yas_grup"))

          Frekans  Yüzde
yas_grup
31-45       98618  26.00
16-30       91423  24.10
46-60       81880  21.59
60+         54697  14.42
0-15        52690  13.89

In [39]:
df["eğitim"].value_counts()

eğitim
2.0      87858
4.0      57520
3.0      54137
1.0      44639
512.0    21052
51.0     12660
511.0    10047
0.0       7177
52.0      4132
5.0       3928
53.0       755
6.0        535
7.0        122
Name: count, dtype: int64

In [40]:
def freq_table_clean(df, col):
    temp = df[df[col].notna()]
    
    frekans = temp[col].value_counts()
    yuzde = temp[col].value_counts(normalize=True) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)

In [41]:
def egitim_grup(x):
    if x in [0, 1]:
        return "İlkokul ve altı"
    
    elif x in [2, 3]:
        return "Ortaokul ve lise"
    
    elif x in [4, 5, 6, 511, 512, 51]:
        return "Üniversite"
    
    elif x in [52, 53, 7]:
        return "Üniversite üstü"
    
    else:
        return None

df["egitim_kategori"] = df["eğitim"].apply(egitim_grup)

print(freq_table_clean(df, "egitim_kategori"))

C:\Users\dilara\AppData\Local\Temp\ipykernel_15048\2515414278.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["egitim_kategori"] = df["eğitim"].apply(egitim_grup)

                  Frekans  Yüzde
egitim_kategori
Ortaokul ve lise   141995  46.62
Üniversite         105742  34.72
İlkokul ve altı     51816  17.01
Üniversite üstü      5009   1.64

Sağlık amaçlı internet kullanımı, ilaç alımı, fiziksel hastalıklarla ilgili arama, ruhsal hastalıklarla ilgili arama, mhrs/enabız kullanımı, rapor alımı, sonuç bakma vs. hangi sorular varsa hepsinin yüzdelerine bakalım ve tablolaştıralım.

In [42]:
def freq_table_clean(df, col):
    temp = df[df[col].notna()]
    
    frekans = temp[col].value_counts()
    yuzde = temp[col].value_counts(normalize=True) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)

In [43]:
print("📊 Sağlık bilgi arama")
print(freq_table_clean(df, "online sağlık hizmeti kullanımı"))

print("\n📊 İlaç alma")
print(freq_table_clean(df, "eticaret ilaç alışverişi"))

print("\n📊 Randevu alma")
print(freq_table_clean(df, "randevu alma (e-nabız,mhrs vb.)"))

print("\n📊 Sonuç bakma")
print(freq_table_clean(df, "sağlık sonuçlarını almak"))

print("\n📊 Konsültasyon")
print(freq_table_clean(df, "doktora gitmeden konsültasyonlar ve reçete alma"))

print("\n📊 Sağlık uygulaması")
print(freq_table_clean(df, "sağlık/sağlıklı yaşam uygulamaları"))

print("\n📊 Fiziksel sağlık arama")
print(freq_table_clean(df, "fiziksel sağlık bilgisi arama"))

print("\n📊 Ruhsal sağlık arama")
print(freq_table_clean(df, "ruhsal sağlık bilgisi arama"))

📊 Sağlık bilgi arama
                                 Frekans  Yüzde
online sağlık hizmeti kullanımı
1.0                               145195  65.78
2.0                                75524  34.22

📊 İlaç alma
                          Frekans  Yüzde
eticaret ilaç alışverişi
2.0                         65500  91.51
1.0                          6073   8.49

📊 Randevu alma
                                 Frekans  Yüzde
randevu alma (e-nabız,mhrs vb.)
2.0                                57069  54.87
1.0                                46946  45.13

📊 Sonuç bakma
                          Frekans  Yüzde
sağlık sonuçlarını almak
2.0                         36823  51.78
1.0                         34293  48.22

📊 Konsültasyon
                                                 Frekans  Yüzde
doktora gitmeden konsültasyonlar ve reçete alma
2.0                                                40169  86.65
1.0                                                 6188  13.35

📊 Sağlık uygulaması
                                    Frekans  Yüzde
sağlık/sağlıklı yaşam uygulamaları
2.0                                   44265  93.84
1.0                                    2907   6.16

📊 Fiziksel sağlık arama
                               Frekans  Yüzde
fiziksel sağlık bilgisi arama
1.0                              13464  95.73
2.0                                601   4.27

📊 Ruhsal sağlık arama
                             Frekans  Yüzde
ruhsal sağlık bilgisi arama
2.0                             7595   54.0
1.0                             6470   46.0

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 381809 entries, 0 to 381808
Columns: 471 entries, referans yıl to egitim_kategori
dtypes: category(1), float64(454), int64(5), object(5), str(6)
memory usage: 1.3+ GB

In [45]:
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

In [46]:
def freq_table_clean(df, col):
    temp = df[df[col].notna()]
    
    frekans = temp[col].value_counts()
    yuzde = temp[col].value_counts(normalize=True) * 100
    
    tablo = pd.concat([frekans, yuzde], axis=1)
    tablo.columns = ["Frekans", "Yüzde"]
    
    return tablo.round(2)


# 🔴 TÜM SAĞLIK DEĞİŞKENLERİ
cols = [
    "online sağlık hizmeti kullanımı",
    "eticaret ilaç alışverişi",
    "randevu alma (e-nabız,mhrs vb.)",
    "sağlık sonuçlarını almak",
    "doktora gitmeden konsültasyonlar ve reçete alma",
    "edevlet sağlık hizmet sıklığı",
    "edevlet sosyal güvenlik hizmet sıklığı",
    "sağlık/sağlıklı yaşam uygulamaları",
    "sağlık problemi nedeni ile faaliyet sınırlaması",
    "internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı",
    "internete bağlı sağlık izleme ve tıbbi cihaz kullanımı",
    "internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi",
    "fiziksel sağlık bilgisi arama",
    "ruhsal sağlık bilgisi arama"
]


# 🔥 TEK TEK TABLOLAŞTIR
for col in cols:
    if col in df.columns:
        print(f"\n📊 {col.upper()}")
        print(freq_table_clean(df, col))
    else:
        print(f"\n❌ {col} veri setinde yok (normal)")

📊 ONLINE SAĞLIK HIZMETI KULLANIMI
                                 Frekans  Yüzde
online sağlık hizmeti kullanımı
1.0                               145195  65.78
2.0                                75524  34.22

📊 ETICARET ILAÇ ALIŞVERIŞI
                          Frekans  Yüzde
eticaret ilaç alışverişi
2.0                         65500  91.51
1.0                          6073   8.49

📊 RANDEVU ALMA (E-NABIZ,MHRS VB.)
                                 Frekans  Yüzde
randevu alma (e-nabız,mhrs vb.)
2.0                                57069  54.87
1.0                                46946  45.13

📊 SAĞLIK SONUÇLARINI ALMAK
                          Frekans  Yüzde
sağlık sonuçlarını almak
2.0                         36823  51.78
1.0                         34293  48.22

📊 DOKTORA GITMEDEN KONSÜLTASYONLAR VE REÇETE ALMA
                                                 Frekans  Yüzde
doktora gitmeden konsültasyonlar ve reçete alma
2.0                                                40169  86.65
1.0                                                 6188  13.35

📊 EDEVLET SAĞLIK HIZMET SIKLIĞI
                               Frekans  Yüzde
edevlet sağlık hizmet sıklığı
4.0                               7598  43.97
5.0                               4942  28.60
2.0                               4740  27.43

📊 EDEVLET SOSYAL GÜVENLIK HIZMET SIKLIĞI
                                        Frekans  Yüzde
edevlet sosyal güvenlik hizmet sıklığı
5.0                                       10160  58.80
4.0                                        5207  30.13
2.0                                        1913  11.07

📊 SAĞLIK/SAĞLIKLI YAŞAM UYGULAMALARI
                                    Frekans  Yüzde
sağlık/sağlıklı yaşam uygulamaları
2.0                                   44265  93.84
1.0                                    2907   6.16

📊 SAĞLIK PROBLEMI NEDENI ILE FAALIYET SINIRLAMASI
                                                 Frekans  Yüzde
sağlık problemi nedeni ile faaliyet sınırlaması
213.0                                              24365  43.62
6.0                                                21688  38.83
116.0                                               3578   6.41
5.0                                                 3060   5.48
115.0                                               1638   2.93
4.0                                                 1525   2.73

📊 INTERNETE BAĞLI SAAT VE GIYILEBILIR TEKNOLOJI ÜRÜNLERI KULLANIMI
                                                                  Frekans  Yüzde
internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı
2.0                                                                 42805  92.34
1.0                                                                  3552   7.66

📊 INTERNETE BAĞLI SAĞLIK IZLEME VE TIBBI CIHAZ KULLANIMI
                                                        Frekans  Yüzde
internete bağlı sağlık izleme ve tıbbi cihaz kullanımı
2.0                                                       45351  97.83
1.0                                                        1006   2.17

📊 INTERNETE BAĞLI CIHAZ KULLANIMINDA EMNIYET VE SAĞLIK RISKI ENDIŞESI
                                                                     Frekans  Yüzde
internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi
2.0                                                                    21578  97.13
1.0                                                                      638   2.87

📊 FIZIKSEL SAĞLIK BILGISI ARAMA
                               Frekans  Yüzde
fiziksel sağlık bilgisi arama
1.0                              13464  95.73
2.0                                601   4.27

📊 RUHSAL SAĞLIK BILGISI ARAMA
                             Frekans  Yüzde
ruhsal sağlık bilgisi arama
2.0                             7595   54.0
1.0                             6470   46.0

In [47]:
part2 = [
    "doktora gitmeden konsültasyonlar ve reçete alma",
    "edevlet sağlık hizmet sıklığı",
    "edevlet sosyal güvenlik hizmet sıklığı",
]

for col in part2:
    print("\n" + "="*70)
    print(col.upper())
    print("="*70)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

======================================================================
DOKTORA GITMEDEN KONSÜLTASYONLAR VE REÇETE ALMA
======================================================================
                                                 Frekans  Yüzde
doktora gitmeden konsültasyonlar ve reçete alma
2.0                                                40169  86.65
1.0                                                 6188  13.35

======================================================================
EDEVLET SAĞLIK HIZMET SIKLIĞI
======================================================================
                               Frekans  Yüzde
edevlet sağlık hizmet sıklığı
4.0                               7598  43.97
5.0                               4942  28.60
2.0                               4740  27.43

======================================================================
EDEVLET SOSYAL GÜVENLIK HIZMET SIKLIĞI
======================================================================
                                        Frekans  Yüzde
edevlet sosyal güvenlik hizmet sıklığı
5.0                                       10160  58.80
4.0                                        5207  30.13
2.0                                        1913  11.07

In [48]:
part3 = [
    "sağlık problemi nedeni ile faaliyet sınırlaması",
    "internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı",
    "internete bağlı sağlık izleme ve tıbbi cihaz kullanımı",
    "internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"
]

for col in part3:
    print("\n" + "="*70)
    print(col.upper())
    print("="*70)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

======================================================================
SAĞLIK PROBLEMI NEDENI ILE FAALIYET SINIRLAMASI
======================================================================
                                                 Frekans  Yüzde
sağlık problemi nedeni ile faaliyet sınırlaması
213.0                                              24365  43.62
6.0                                                21688  38.83
116.0                                               3578   6.41
5.0                                                 3060   5.48
115.0                                               1638   2.93
4.0                                                 1525   2.73

======================================================================
INTERNETE BAĞLI SAAT VE GIYILEBILIR TEKNOLOJI ÜRÜNLERI KULLANIMI
======================================================================
                                                                  Frekans  Yüzde
internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı
2.0                                                                 42805  92.34
1.0                                                                  3552   7.66

======================================================================
INTERNETE BAĞLI SAĞLIK IZLEME VE TIBBI CIHAZ KULLANIMI
======================================================================
                                                        Frekans  Yüzde
internete bağlı sağlık izleme ve tıbbi cihaz kullanımı
2.0                                                       45351  97.83
1.0                                                        1006   2.17

======================================================================
INTERNETE BAĞLI CIHAZ KULLANIMINDA EMNIYET VE SAĞLIK RISKI ENDIŞESI
======================================================================
                                                                     Frekans  Yüzde
internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi
2.0                                                                    21578  97.13
1.0                                                                      638   2.87

In [49]:
part1 = [
    "online sağlık hizmeti kullanımı",
    "eticaret ilaç alışverişi",
    "randevu alma (e-nabız,mhrs vb.)"
]

for col in part1:
    print("\n" + "="*60)
    print(col.upper())
    print("="*60)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

============================================================
ONLINE SAĞLIK HIZMETI KULLANIMI
============================================================
                                 Frekans  Yüzde
online sağlık hizmeti kullanımı
1.0                               145195  65.78
2.0                                75524  34.22

============================================================
ETICARET ILAÇ ALIŞVERIŞI
============================================================
                          Frekans  Yüzde
eticaret ilaç alışverişi
2.0                         65500  91.51
1.0                          6073   8.49

============================================================
RANDEVU ALMA (E-NABIZ,MHRS VB.)
============================================================
                                 Frekans  Yüzde
randevu alma (e-nabız,mhrs vb.)
2.0                                57069  54.87
1.0                                46946  45.13

In [50]:
part2 = [
    "sağlık sonuçlarını almak",
    "doktora gitmeden konsültasyonlar ve reçete alma",
    "edevlet sağlık hizmet sıklığı"
]

for col in part2:
    print("\n" + "="*60)
    print(col.upper())
    print("="*60)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

============================================================
SAĞLIK SONUÇLARINI ALMAK
============================================================
                          Frekans  Yüzde
sağlık sonuçlarını almak
2.0                         36823  51.78
1.0                         34293  48.22

============================================================
DOKTORA GITMEDEN KONSÜLTASYONLAR VE REÇETE ALMA
============================================================
                                                 Frekans  Yüzde
doktora gitmeden konsültasyonlar ve reçete alma
2.0                                                40169  86.65
1.0                                                 6188  13.35

============================================================
EDEVLET SAĞLIK HIZMET SIKLIĞI
============================================================
                               Frekans  Yüzde
edevlet sağlık hizmet sıklığı
4.0                               7598  43.97
5.0                               4942  28.60
2.0                               4740  27.43

In [51]:
part3 = [
    "edevlet sosyal güvenlik hizmet sıklığı",
    "sağlık/sağlıklı yaşam uygulamaları",
    "sağlık problemi nedeni ile faaliyet sınırlaması"
]

for col in part3:
    print("\n" + "="*60)
    print(col.upper())
    print("="*60)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

============================================================
EDEVLET SOSYAL GÜVENLIK HIZMET SIKLIĞI
============================================================
                                        Frekans  Yüzde
edevlet sosyal güvenlik hizmet sıklığı
5.0                                       10160  58.80
4.0                                        5207  30.13
2.0                                        1913  11.07

============================================================
SAĞLIK/SAĞLIKLI YAŞAM UYGULAMALARI
============================================================
                                    Frekans  Yüzde
sağlık/sağlıklı yaşam uygulamaları
2.0                                   44265  93.84
1.0                                    2907   6.16

============================================================
SAĞLIK PROBLEMI NEDENI ILE FAALIYET SINIRLAMASI
============================================================
                                                 Frekans  Yüzde
sağlık problemi nedeni ile faaliyet sınırlaması
213.0                                              24365  43.62
6.0                                                21688  38.83
116.0                                               3578   6.41
5.0                                                 3060   5.48
115.0                                               1638   2.93
4.0                                                 1525   2.73

In [52]:
part4 = [
    "internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı",
    "internete bağlı sağlık izleme ve tıbbi cihaz kullanımı",
    "internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"
]

for col in part4:
    print("\n" + "="*60)
    print(col.upper())
    print("="*60)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

============================================================
INTERNETE BAĞLI SAAT VE GIYILEBILIR TEKNOLOJI ÜRÜNLERI KULLANIMI
============================================================
                                                                  Frekans  Yüzde
internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı
2.0                                                                 42805  92.34
1.0                                                                  3552   7.66

============================================================
INTERNETE BAĞLI SAĞLIK IZLEME VE TIBBI CIHAZ KULLANIMI
============================================================
                                                        Frekans  Yüzde
internete bağlı sağlık izleme ve tıbbi cihaz kullanımı
2.0                                                       45351  97.83
1.0                                                        1006   2.17

============================================================
INTERNETE BAĞLI CIHAZ KULLANIMINDA EMNIYET VE SAĞLIK RISKI ENDIŞESI
============================================================
                                                                     Frekans  Yüzde
internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi
2.0                                                                    21578  97.13
1.0                                                                      638   2.87

In [53]:
part5 = [
    "fiziksel sağlık bilgisi arama",
    "ruhsal sağlık bilgisi arama"
]

for col in part5:
    print("\n" + "="*60)
    print(col.upper())
    print("="*60)
    
    if col in df.columns:
        print(freq_table_clean(df, col).to_string())
    else:
        print("Bu kolon veri setinde yok.")

============================================================
FIZIKSEL SAĞLIK BILGISI ARAMA
============================================================
                               Frekans  Yüzde
fiziksel sağlık bilgisi arama
1.0                              13464  95.73
2.0                                601   4.27

============================================================
RUHSAL SAĞLIK BILGISI ARAMA
============================================================
                             Frekans  Yüzde
ruhsal sağlık bilgisi arama
2.0                             7595   54.0
1.0                             6470   46.0

Sonra da cross-tab lar yapalım

In [54]:
# df_clean'i yeniden oluştur
df_clean = df[df["gelir_5li"].notna()].copy()

# label kolonlarını df_clean içinde oluştur
df_clean["saglik_internet_label"] = df_clean["online sağlık hizmeti kullanımı"].map({
    1: "Kullanıyor",
    2: "Kullanmıyor"
})

df_clean["cinsiyet_label"] = df_clean["cinsiyet"].map({
    1: "Erkek",
    2: "Kadın"
})

# boşları çıkar
df_ct = df_clean[
    df_clean["saglik_internet_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

# crosstab
ct = pd.crosstab(
    df_ct["gelir_5li"],
    [df_ct["saglik_internet_label"], df_ct["cinsiyet_label"]],
    normalize="index"
) * 100

ct.columns = [f"{a} {b}" for a, b in ct.columns]

# kolon eksikse hata vermesin
istenen_sira = [
    "Kullanıyor Erkek",
    "Kullanıyor Kadın",
    "Kullanmıyor Erkek",
    "Kullanmıyor Kadın"
]

ct = ct.reindex(columns=istenen_sira).fillna(0).round(2)

print(ct.to_string())

           Kullanıyor Erkek  Kullanıyor Kadın  Kullanmıyor Erkek  Kullanmıyor Kadın
gelir_5li
1.0                   23.20             25.52              28.75              22.53
2.0                   28.74             30.19              24.04              17.03
3.0                   31.14             31.64              21.37              15.85
4.0                   34.98             34.17              18.23              12.62
5.0                   39.23             37.83              13.29               9.65

In [55]:
# label
df_clean["ilac_alimi_label"] = df_clean["eticaret ilaç alışverişi"].map({
    1: "Var",
    2: "Yok"
})

# crosstab
ct_ilac = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["ilac_alimi_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon isimlerini düzelt
ct_ilac.columns = [f"{a} {b}" for a, b in ct_ilac.columns]

istenen = [
    "Var Kadın", "Var Erkek",
    "Yok Kadın", "Yok Erkek"
]

ct_ilac = ct_ilac.reindex(columns=istenen).fillna(0).round(2)

print(ct_ilac.to_string())

           Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
gelir_5li
1.0             3.64       2.83      49.06      44.46
2.0             3.13       2.37      46.48      48.01
3.0             4.08       3.46      45.37      47.09
4.0             4.26       3.70      42.82      49.22
5.0             6.36       5.51      40.76      47.37

In [56]:
# label
df_clean["randevu_label"] = df_clean["randevu alma (e-nabız,mhrs vb.)"].map({
    1: "Var",
    2: "Yok"
})

# crosstab
ct_randevu = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["randevu_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

# kolonları düzelt
ct_randevu.columns = [f"{a} {b}" for a, b in ct_randevu.columns]

istenen = [
    "Var Kadın", "Var Erkek",
    "Yok Kadın", "Yok Erkek"
]

ct_randevu = ct_randevu.reindex(columns=istenen).fillna(0).round(2)

print(ct_randevu.to_string())

           Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
gelir_5li
1.0            16.76      17.47      31.12      34.64
2.0            18.89      20.46      28.78      31.87
3.0            20.87      23.40      26.59      29.14
4.0            22.06      25.35      24.47      28.11
5.0            25.50      28.01      22.13      24.36

In [57]:
# label
df_clean["sonuc_label"] = df_clean["sağlık sonuçlarını almak"].map({
    1: "Var",
    2: "Yok"
})

# crosstab
ct_sonuc = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["sonuc_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon isimleri
ct_sonuc.columns = [f"{a} {b}" for a, b in ct_sonuc.columns]

istenen = [
    "Var Kadın", "Var Erkek",
    "Yok Kadın", "Yok Erkek"
]

ct_sonuc = ct_sonuc.reindex(columns=istenen).fillna(0).round(2)

print(ct_sonuc.to_string())

           Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
gelir_5li
1.0            18.12      20.04      31.24      30.60
2.0            21.67      24.23      26.38      27.72
3.0            21.00      23.89      26.56      28.55
4.0            23.13      27.05      23.63      26.18
5.0            26.03      29.09      21.68      23.20

In [58]:
# label
df_clean["konsultasyon_label"] = df_clean["doktora gitmeden konsültasyonlar ve reçete alma"].map({
    1: "Var",
    2: "Yok"
})

# crosstab
ct_kons = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["konsultasyon_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

# kolonları düzelt
ct_kons.columns = [f"{a} {b}" for a, b in ct_kons.columns]

istenen = [
    "Var Kadın", "Var Erkek",
    "Yok Kadın", "Yok Erkek"
]

ct_kons = ct_kons.reindex(columns=istenen).fillna(0).round(2)

print(ct_kons.to_string())

           Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
gelir_5li
1.0             4.80       5.10      45.60      44.49
2.0             6.08       6.41      42.66      44.84
3.0             5.59       6.63      42.67      45.11
4.0             6.71       7.68      40.91      44.70
5.0             7.81       8.68      40.62      42.89

In [59]:
def edevlet_kategori(x):
    if x in [2, 3]:
        return "Haftada"
    elif x in [4]:
        return "Ayda"
    elif x in [5]:
        return "Hiç"
    else:
        return None

df_clean["edevlet_label"] = df_clean["edevlet sağlık hizmet sıklığı"].apply(edevlet_kategori)

In [60]:
ct_edevlet = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["edevlet_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_edevlet.columns = [f"{a} {b}" for a, b in ct_edevlet.columns]

print(ct_edevlet.round(2).to_string())

           Ayda Erkek  Ayda Kadın  Haftada Erkek  Haftada Kadın  Hiç Erkek  Hiç Kadın
gelir_5li
1.0             21.35       17.48          10.03          10.32      25.36      15.47
2.0             20.94       15.66          12.28          11.05      23.41      16.65
3.0             23.99       16.73          12.92          10.89      21.49      13.99
4.0             25.04       18.33          13.50          12.77      18.89      11.47
5.0             26.34       19.98          16.21          13.65      13.92       9.92

In [61]:
def edevlet_sgk(x):
    if x in [2, 3]:
        return "Haftada"
    elif x == 4:
        return "Ayda"
    elif x == 5:
        return "Hiç"
    else:
        return None

df_clean["edevlet_sgk_label"] = df_clean["edevlet sosyal güvenlik hizmet sıklığı"].apply(edevlet_sgk)

ct_sgk = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["edevlet_sgk_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_sgk.columns = [f"{a} {b}" for a, b in ct_sgk.columns]

print(ct_sgk.round(2).to_string())

           Ayda Erkek  Ayda Kadın  Haftada Erkek  Haftada Kadın  Hiç Erkek  Hiç Kadın
gelir_5li
1.0             17.34        7.31           5.44           3.72      33.95      32.23
2.0             16.08        6.76           5.69           4.37      34.87      32.23
3.0             17.80        8.75           6.90           3.33      33.69      29.52
4.0             19.50        9.22           7.52           3.45      30.41      29.91
5.0             20.89       12.11           7.64           3.93      27.93      27.50

In [62]:
df_clean["uygulama_label"] = df_clean["sağlık/sağlıklı yaşam uygulamaları"].map({
    1: "Var",
    2: "Yok"
})

ct_app = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["uygulama_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_app.columns = [f"{a} {b}" for a, b in ct_app.columns]

print(ct_app.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0             2.78       2.85      41.06      53.31
2.0             2.25       3.36      45.04      49.35
3.0             2.58       2.94      46.47      48.00
4.0             2.69       2.63      47.99      46.69
5.0             3.79       3.48      47.64      45.09

In [63]:
df_clean["giyilebilir_label"] = df_clean["internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı"].map({
    1: "Var",
    2: "Yok"
})

ct_giy = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["giyilebilir_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_giy.columns = [f"{a} {b}" for a, b in ct_giy.columns]
print(ct_giy.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0             0.87       1.10      48.72      49.31
2.0             1.78       1.63      49.48      47.11
3.0             2.77       2.37      48.97      45.90
4.0             4.58       4.05      47.80      43.57
5.0             8.97       7.78      42.60      40.65

In [64]:
df_clean["cihaz_label"] = df_clean["internete bağlı sağlık izleme ve tıbbi cihaz kullanımı"].map({
    1: "Var",
    2: "Yok"
})

ct_cihaz = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["cihaz_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_cihaz.columns = [f"{a} {b}" for a, b in ct_cihaz.columns]
print(ct_cihaz.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0             0.41       0.43      49.18      49.98
2.0             0.55       0.52      50.71      48.23
3.0             0.71       0.73      51.03      47.54
4.0             0.97       0.97      51.41      46.65
5.0             2.52       2.46      49.05      45.97

In [65]:
df_clean["risk_label"] = df_clean["internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"].map({
    1: "Var",
    2: "Yok"
})

ct_risk = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["risk_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_risk.columns = [f"{a} {b}" for a, b in ct_risk.columns]

print(ct_risk.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0             1.66       1.42      45.47      51.45
2.0             1.62       1.47      47.86      49.05
3.0             1.20       1.32      50.03      47.45
4.0             1.44       1.48      50.28      46.80
5.0             1.50       1.39      50.30      46.81

In [66]:
df_clean["fiziksel_label"] = df_clean["fiziksel sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

ct_fiziksel = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["fiziksel_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_fiziksel.columns = [f"{a} {b}" for a, b in ct_fiziksel.columns]

print(ct_fiziksel.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0            40.61      54.54       2.55       2.30
2.0            44.29      50.70       2.17       2.83
3.0            45.36      50.30       2.30       2.04
4.0            46.88      48.91       2.46       1.74
5.0            47.40      49.10       2.15       1.35

In [67]:
df_clean["ruhsal_label"] = df_clean["ruhsal sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

ct_ruhsal = pd.crosstab(
    df_clean["gelir_5li"],
    [df_clean["ruhsal_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

ct_ruhsal.columns = [f"{a} {b}" for a, b in ct_ruhsal.columns]

print(ct_ruhsal.round(2).to_string())

           Var Erkek  Var Kadın  Yok Erkek  Yok Kadın
gelir_5li
1.0            17.16      27.24      26.00      29.60
2.0            19.18      25.50      27.29      28.03
3.0            19.13      25.08      28.53      27.25
4.0            20.50      25.89      28.85      24.77
5.0            22.46      26.34      27.09      24.11

In [68]:
def yas_grup(x):
    if pd.isna(x):
        return None
    elif x <= 15:
        return "0-15"
    elif x <= 30:
        return "16-30"
    elif x <= 45:
        return "31-45"
    elif x <= 60:
        return "46-60"
    else:
        return "60+"

df_clean["yas_grup"] = df_clean["yaş"].apply(yas_grup)

In [69]:
ct_yas = pd.crosstab(
    df_clean["yas_grup"],
    [df_clean["saglik_internet_label"], df_clean["cinsiyet_label"]],
    normalize="index"
) * 100

In [70]:
ct_yas.columns = [f"{a} {b}" for a, b in ct_yas.columns]

ct_yas = ct_yas[[
    "Kullanıyor Kadın",
    "Kullanıyor Erkek",
    "Kullanmıyor Kadın",
    "Kullanmıyor Erkek"
]].round(2)

print(ct_yas.to_string())

          Kullanıyor Kadın  Kullanıyor Erkek  Kullanmıyor Kadın  Kullanmıyor Erkek
yas_grup
16-30                37.45             32.24              12.31              18.00
31-45                35.81             35.44              12.17              16.58
46-60                25.78             31.06              18.66              24.51
60+                  16.62             25.87              24.63              32.88

In [71]:
# 1. yaş grubu
def yas_grup(x):
    if pd.isna(x):
        return None
    elif x <= 15:
        return "0-15"
    elif x <= 30:
        return "16-30"
    elif x <= 45:
        return "31-45"
    elif x <= 60:
        return "46-60"
    else:
        return "60+"

df_clean["yas_grup"] = df_clean["yaş"].apply(yas_grup)

# 2. label'lar (emin ol)
df_clean["saglik_internet_label"] = df_clean["online sağlık hizmeti kullanımı"].map({
    1: "Kullanıyor",
    2: "Kullanmıyor"
})

df_clean["cinsiyet_label"] = df_clean["cinsiyet"].map({
    1: "Erkek",
    2: "Kadın"
})

# 3. boşları temizle
df_yas = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["saglik_internet_label"].notna() &
    df_clean["cinsiyet_label"].notna()
]

# 4. crosstab
ct_yas = pd.crosstab(
    df_yas["yas_grup"],
    [df_yas["saglik_internet_label"], df_yas["cinsiyet_label"]],
    normalize="index"
) * 100

# 5. kolon düzeni (senin Excel ile birebir)
ct_yas.columns = [f"{a} {b}" for a, b in ct_yas.columns]

ct_yas = ct_yas.reindex(columns=[
    "Kullanıyor Kadın",
    "Kullanıyor Erkek",
    "Kullanmıyor Kadın",
    "Kullanmıyor Erkek"
]).round(2)

print(ct_yas.to_string())

          Kullanıyor Kadın  Kullanıyor Erkek  Kullanmıyor Kadın  Kullanmıyor Erkek
yas_grup
16-30                37.45             32.24              12.31              18.00
31-45                35.81             35.44              12.17              16.58
46-60                25.78             31.06              18.66              24.51
60+                  16.62             25.87              24.63              32.88

In [72]:
# 1) Label oluştur
df_clean["eticaret_ilac_label"] = df_clean["eticaret ilaç alışverişi"].map({
    1: "Var",
    2: "Yok"
})

# 2) Yaş grubu yoksa tekrar oluştur
def yas_grup(x):
    if pd.isna(x):
        return None
    elif x <= 15:
        return "0-15"
    elif x <= 30:
        return "16-30"
    elif x <= 45:
        return "31-45"
    elif x <= 60:
        return "46-60"
    else:
        return "60+"

df_clean["yas_grup"] = df_clean["yaş"].apply(yas_grup)

# 3) Boşları çıkar
df_yas_ilac = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["eticaret_ilac_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

# 4) Cross-tab
ct_yas_eticaret = pd.crosstab(
    df_yas_ilac["yas_grup"],
    [df_yas_ilac["eticaret_ilac_label"], df_yas_ilac["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_eticaret.columns = [f"{a} {b}" for a, b in ct_yas_eticaret.columns]

ct_yas_eticaret = ct_yas_eticaret.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_eticaret.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          3.98       2.75      49.10      44.18
31-45          5.71       4.77      40.80      48.73
46-60          5.44       6.45      32.52      55.59
60+            5.65      10.19      23.72      60.45

In [73]:
# label oluştur
df_clean["randevu_label"] = df_clean["randevu alma (e-nabız,mhrs vb.)"].map({
    1: "Var",
    2: "Yok"
})

# filtre
df_yas_randevu = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["randevu_label"].notna() &
    df_clean["cinsiyet_label"].notna()
]

# crosstab
ct_yas_randevu = pd.crosstab(
    df_yas_randevu["yas_grup"],
    [df_yas_randevu["randevu_label"], df_yas_randevu["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_yas_randevu.columns = [f"{a} {b}" for a, b in ct_yas_randevu.columns]

ct_yas_randevu = ct_yas_randevu.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_randevu.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30         25.15      22.33      24.83      27.69
31-45         23.18      25.85      24.92      26.04
46-60         16.30      23.28      27.80      32.62
60+           10.11      20.80      31.05      38.05

In [74]:
# label
df_clean["sonuc_label"] = df_clean["sağlık sonuçlarını almak"].map({
    1: "Var",
    2: "Yok"
})

# filtre
df_yas_sonuc = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["sonuc_label"].notna() &
    df_clean["cinsiyet_label"].notna()
]

# crosstab
ct_yas_sonuc = pd.crosstab(
    df_yas_sonuc["yas_grup"],
    [df_yas_sonuc["sonuc_label"], df_yas_sonuc["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_yas_sonuc.columns = [f"{a} {b}" for a, b in ct_yas_sonuc.columns]

ct_yas_sonuc = ct_yas_sonuc.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_sonuc.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30         26.76      24.97      23.10      25.17
31-45         25.19      28.52      23.28      23.01
46-60         17.37      24.09      28.12      30.43
60+           10.48      20.06      32.01      37.44

In [75]:
# label
df_clean["recete_label"] = df_clean["doktora gitmeden konsültasyonlar ve reçete alma"].map({
    1: "Var",
    2: "Yok"
})

# filtre
df_yas_recete = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["recete_label"].notna() &
    df_clean["cinsiyet_label"].notna()
]

# crosstab
ct_yas_recete = pd.crosstab(
    df_yas_recete["yas_grup"],
    [df_yas_recete["recete_label"], df_yas_recete["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_yas_recete.columns = [f"{a} {b}" for a, b in ct_yas_recete.columns]

ct_yas_recete = ct_yas_recete.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_recete.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          7.86       7.52      42.53      42.10
31-45          7.07       7.98      42.45      42.50
46-60          4.73       6.15      42.15      46.97
60+            2.39       4.24      41.03      52.33

In [76]:
# 1) e-devlet sağlık sıklığı label oluştur
def edevlet_saglik_grup(x):
    if x == 2:
        return "Haftada"
    elif x == 4:
        return "Ayda"
    elif x == 5:
        return "Hiç"
    else:
        return None

df_clean["edevlet_saglik_label"] = df_clean["edevlet sağlık hizmet sıklığı"].apply(edevlet_saglik_grup)

# 2) yaş grubu ve cinsiyet boş olmayanları al
df_yas_edevlet = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["edevlet_saglik_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

# 3) crosstab
ct_yas_edevlet = pd.crosstab(
    df_yas_edevlet["yas_grup"],
    [df_yas_edevlet["edevlet_saglik_label"], df_yas_edevlet["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_edevlet.columns = [f"{a} {b}" for a, b in ct_yas_edevlet.columns]

ct_yas_edevlet = ct_yas_edevlet.reindex(columns=[
    "Haftada Kadın",
    "Haftada Erkek",
    "Ayda Kadın",
    "Ayda Erkek",
    "Hiç Kadın",
    "Hiç Erkek"
]).round(2)

print(ct_yas_edevlet.to_string())

          Haftada Kadın  Haftada Erkek  Ayda Kadın  Ayda Erkek  Hiç Kadın  Hiç Erkek
yas_grup
16-30             13.63          11.63       21.24       22.98      13.31      17.21
31-45             13.71          15.58       18.27       25.04      11.06      16.35
46-60             10.48          17.14       16.27       28.17       9.34      18.60
60+                8.67          20.53       13.87       31.60       8.13      17.20

In [77]:
# label oluştur
def edevlet_sgk_grup(x):
    if x == 2:
        return "Haftada"
    elif x == 4:
        return "Ayda"
    elif x == 5:
        return "Hiç"
    else:
        return None

df_clean["edevlet_sgk_label"] = df_clean["edevlet sosyal güvenlik hizmet sıklığı"].apply(edevlet_sgk_grup)

# filtre
df_yas_sgk = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["edevlet_sgk_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

# crosstab
ct_yas_sgk = pd.crosstab(
    df_yas_sgk["yas_grup"],
    [df_yas_sgk["edevlet_sgk_label"], df_yas_sgk["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_yas_sgk.columns = [f"{a} {b}" for a, b in ct_yas_sgk.columns]

ct_yas_sgk = ct_yas_sgk.reindex(columns=[
    "Haftada Kadın",
    "Haftada Erkek",
    "Ayda Kadın",
    "Ayda Erkek",
    "Hiç Kadın",
    "Hiç Erkek"
]).round(2)

print(ct_yas_sgk.to_string())

          Haftada Kadın  Haftada Erkek  Ayda Kadın  Ayda Erkek  Hiç Kadın  Hiç Erkek
yas_grup
16-30              3.57           5.03       10.97       15.58      33.65      31.20
31-45              4.56           9.29       11.71       23.11      26.76      24.57
46-60              3.11           8.09        8.21       21.86      24.77      33.96
60+                1.33           6.13        4.27       16.27      25.07      46.93

In [78]:
def saglik_uygulama_grup(x):
    if x == 1:
        return "Var"
    elif x == 2:
        return "Yok"
    else:
        return None

df_clean["saglik_uygulama_label"] = df_clean["sağlık/sağlıklı yaşam uygulamaları"].apply(saglik_uygulama_grup)

In [79]:
df_yas_app = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["saglik_uygulama_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

In [80]:
ct_yas_app = pd.crosstab(
    df_yas_app["yas_grup"],
    [df_yas_app["saglik_uygulama_label"], df_yas_app["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_app.columns = [f"{a} {b}" for a, b in ct_yas_app.columns]

ct_yas_app = ct_yas_app.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_app.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          3.60       2.69      50.65      43.06
31-45          3.15       3.32      46.61      46.93
46-60          1.81       3.35      39.41      55.43
60+            1.07       3.49      31.69      63.76

In [81]:
def giyilebilir_grup(x):
    if x == 1:
        return "Var"
    elif x == 2:
        return "Yok"
    else:
        return None

df_clean["giyilebilir_label"] = df_clean["internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı"].apply(giyilebilir_grup)

In [82]:
df_yas_giyilebilir = df_clean[
    df_clean["yas_grup"].notna() &
    df_clean["giyilebilir_label"].notna() &
    df_clean["cinsiyet_label"].notna()
].copy()

In [83]:
ct_yas_giyilebilir = pd.crosstab(
    df_yas_giyilebilir["yas_grup"],
    [df_yas_giyilebilir["giyilebilir_label"], df_yas_giyilebilir["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_giyilebilir.columns = [f"{a} {b}" for a, b in ct_yas_giyilebilir.columns]

ct_yas_giyilebilir = ct_yas_giyilebilir.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_giyilebilir.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          4.88       5.22      45.51      44.39
31-45          4.55       4.90      44.97      45.58
46-60          1.68       2.42      45.20      50.71
60+            0.91       1.36      42.52      55.21

In [84]:
# label oluştur
df_clean["tibbi_cihaz_label"] = df_clean["internete bağlı sağlık izleme ve tıbbi cihaz kullanımı"].map({
    1: "Var",
    2: "Yok"
})

# sadece gerekli 3 kolonla çalış
temp = df_clean[["yas_grup", "tibbi_cihaz_label", "cinsiyet_label"]].dropna()

ct_yas_cihaz = pd.crosstab(
    temp["yas_grup"],
    [temp["tibbi_cihaz_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_cihaz.columns = [f"{a} {b}" for a, b in ct_yas_cihaz.columns]

ct_yas_cihaz = ct_yas_cihaz.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_cihaz.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          1.15       1.05      49.23      48.57
31-45          1.25       1.25      48.27      49.23
46-60          0.89       1.05      45.98      52.07
60+            0.67       0.77      42.76      55.81

In [85]:
# Risk endişesi label
df_clean["risk_label"] = df_clean["internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"].map({
    1: "Var",
    2: "Yok"
})

# sadece gerekli kolonlarla hafif tablo
temp = df_clean[["yas_grup", "risk_label", "cinsiyet_label"]].dropna()

ct_yas_risk = pd.crosstab(
    temp["yas_grup"],
    [temp["risk_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_yas_risk.columns = [f"{a} {b}" for a, b in ct_yas_risk.columns]

ct_yas_risk = ct_yas_risk.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_risk.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30          1.21       1.22      50.07      47.49
31-45          1.53       1.45      48.71      48.31
46-60          1.52       1.72      43.75      53.01
60+            1.42       1.87      41.60      55.10

In [86]:
# label oluştur
df_clean["fiziksel_saglik_label"] = df_clean["fiziksel sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

# sadece gerekli kolonlar (memory hatası yaşamamak için!)
temp = df_clean[["yas_grup", "fiziksel_saglik_label", "cinsiyet_label"]].dropna()

# crosstab
ct_yas_fiziksel = pd.crosstab(
    temp["yas_grup"],
    [temp["fiziksel_saglik_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon isimlerini düzelt
ct_yas_fiziksel.columns = [f"{a} {b}" for a, b in ct_yas_fiziksel.columns]

# sıralama (excel ile birebir)
ct_yas_fiziksel = ct_yas_fiziksel.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_fiziksel.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30         51.93      43.66       2.12       2.29
31-45         51.85      44.35       1.66       2.15
46-60         48.14      47.30       2.15       2.41
60+           40.18      54.56       2.41       2.85

In [87]:
# 1. label oluştur
df_clean["ruhsal_saglik_label"] = df_clean["ruhsal sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

# 2. küçük dataset
temp = df_clean[["yas_grup", "ruhsal_saglik_label", "cinsiyet_label"]].dropna()

# 3. crosstab
ct_yas_ruhsal = pd.crosstab(
    temp["yas_grup"],
    [temp["ruhsal_saglik_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# 4. kolon isimlerini düzelt
ct_yas_ruhsal.columns = [f"{a} {b}" for a, b in ct_yas_ruhsal.columns]

# 5. sıralama
ct_yas_ruhsal = ct_yas_ruhsal.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_yas_ruhsal.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30         27.56      20.72      26.49      25.24
31-45         26.74      19.60      26.76      26.89
46-60         24.14      20.06      26.14      29.66
60+           19.54      19.87      23.05      37.54

In [88]:
# label (zaten varsa tekrar yazmana gerek yok)
df_clean["saglik_internet_label"] = df_clean["online sağlık hizmeti kullanımı"].map({
    1: "Var",
    2: "Yok"
})

# eğitim label (senin kategorine göre!)
df_clean["egitim_label"] = df_clean["eğitim"].map({
    0: "İlkokul ve altı",
    1: "Ortaokul/Lise",
    2: "Üniversite",
    3: "Üniversite üstü"
})

# küçük dataset
temp = df_clean[["egitim_label", "saglik_internet_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim = pd.crosstab(
    temp["egitim_label"],
    [temp["saglik_internet_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_egitim.columns = [f"{a} {b}" for a, b in ct_egitim.columns]

ct_egitim = ct_egitim.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        22.76      14.50      39.05      23.68
Üniversite           26.40      21.18      24.58      27.84
Üniversite üstü      29.89      32.43      13.42      24.27
İlkokul ve altı      22.47      10.11      36.52      30.90

In [89]:
# label oluştur
df_clean["eticaret_ilac_label"] = df_clean["eticaret ilaç alışverişi"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "eticaret_ilac_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_eticaret = pd.crosstab(
    temp["egitim_label"],
    [temp["eticaret_ilac_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_egitim_eticaret.columns = [f"{a} {b}" for a, b in ct_egitim_eticaret.columns]

ct_egitim_eticaret = ct_egitim_eticaret.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_eticaret.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         2.32       3.48      51.23      42.96
Üniversite            3.40       2.99      47.23      46.39
Üniversite üstü       2.04       2.40      44.11      51.45
İlkokul ve altı       3.85       0.00      69.23      26.92

In [90]:
temp = df_clean[["egitim_label", "randevu_label", "cinsiyet_label"]].dropna()

ct_egitim_randevu = pd.crosstab(
    temp["egitim_label"],
    [temp["randevu_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_randevu.columns = [f"{a} {b}" for a, b in ct_egitim_randevu.columns]

ct_egitim_randevu = ct_egitim_randevu.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_randevu.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        11.10       8.40      49.19      31.30
Üniversite           15.03      14.96      35.93      34.08
Üniversite üstü      17.27      20.61      26.40      35.73
İlkokul ve altı       8.57       3.33      54.29      33.81

In [91]:
temp = df_clean[["egitim_label", "sonuc_label", "cinsiyet_label"]].dropna()

ct_egitim_sonuc = pd.crosstab(
    temp["egitim_label"],
    [temp["sonuc_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_sonuc.columns = [f"{a} {b}" for a, b in ct_egitim_sonuc.columns]

ct_egitim_sonuc = ct_egitim_sonuc.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_sonuc.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        10.62       5.35      64.56      19.46
Üniversite           15.19      15.77      36.85      32.19
Üniversite üstü      17.22      22.31      25.55      34.92

In [92]:
# sağlık sonuçlarını almak label
df_clean["sonuc_label"] = df_clean["sağlık sonuçlarını almak"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "sonuc_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_sonuc = pd.crosstab(
    temp["egitim_label"],
    [temp["sonuc_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon düzeni
ct_egitim_sonuc.columns = [f"{a} {b}" for a, b in ct_egitim_sonuc.columns]

ct_egitim_sonuc = ct_egitim_sonuc.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_sonuc.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        10.62       5.35      64.56      19.46
Üniversite           15.19      15.77      36.85      32.19
Üniversite üstü      17.22      22.31      25.55      34.92

In [93]:
# label oluştur
df_clean["recete_label"] = df_clean["doktora gitmeden konsültasyonlar ve reçete alma"].map({
    1: "Var",
    2: "Yok"
})

# temp dataset
temp = df_clean[["egitim_label", "recete_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_recete = pd.crosstab(
    temp["egitim_label"],
    [temp["recete_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon isimleri
ct_egitim_recete.columns = [f"{a} {b}" for a, b in ct_egitim_recete.columns]

# sıralama
ct_egitim_recete = ct_egitim_recete.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_recete.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         3.47       1.49      74.41      20.63
Üniversite            4.02       3.94      49.18      42.86
Üniversite üstü       4.81       6.47      39.16      49.56

In [94]:
# e-devlet sağlık hizmet sıklığı label
def edevlet_saglik_grup(x):
    if x == 2:
        return "Haftada"
    elif x == 4:
        return "Ayda"
    elif x == 5:
        return "Hiç"
    else:
        return None

df_clean["edevlet_saglik_label"] = df_clean["edevlet sağlık hizmet sıklığı"].apply(edevlet_saglik_grup)

# küçük dataset
temp = df_clean[["egitim_label", "edevlet_saglik_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_edevlet = pd.crosstab(
    temp["egitim_label"],
    [temp["edevlet_saglik_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_edevlet.columns = [f"{a} {b}" for a, b in ct_egitim_edevlet.columns]

ct_egitim_edevlet = ct_egitim_edevlet.reindex(columns=[
    "Haftada Kadın",
    "Haftada Erkek",
    "Ayda Kadın",
    "Ayda Erkek",
    "Hiç Kadın",
    "Hiç Erkek"
]).round(2)

print(ct_egitim_edevlet.to_string())

                 Haftada Kadın  Haftada Erkek  Ayda Kadın  Ayda Erkek  Hiç Kadın  Hiç Erkek
egitim_label
Ortaokul/Lise            12.50           6.25       21.63       10.58      30.77      18.27
Üniversite               10.36          11.30       17.56       22.95      14.94      22.89
Üniversite üstü           8.49          12.28       16.12       26.10      12.40      24.61

In [95]:
# e-devlet sosyal güvenlik hizmet sıklığı label
def edevlet_sgk_grup(x):
    if x == 2:
        return "Haftada"
    elif x == 4:
        return "Ayda"
    elif x == 5:
        return "Hiç"
    else:
        return None

df_clean["edevlet_sgk_label"] = df_clean["edevlet sosyal güvenlik hizmet sıklığı"].apply(edevlet_sgk_grup)

# küçük dataset
temp = df_clean[["egitim_label", "edevlet_sgk_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_sgk = pd.crosstab(
    temp["egitim_label"],
    [temp["edevlet_sgk_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_sgk.columns = [f"{a} {b}" for a, b in ct_egitim_sgk.columns]

ct_egitim_sgk = ct_egitim_sgk.reindex(columns=[
    "Haftada Kadın",
    "Haftada Erkek",
    "Ayda Kadın",
    "Ayda Erkek",
    "Hiç Kadın",
    "Hiç Erkek"
]).round(2)

print(ct_egitim_sgk.to_string())

                 Haftada Kadın  Haftada Erkek  Ayda Kadın  Ayda Erkek  Hiç Kadın  Hiç Erkek
egitim_label
Ortaokul/Lise             4.81           2.88        9.13        9.13      50.96      23.08
Üniversite                3.57           6.85        7.24       18.51      32.05      31.79
Üniversite üstü           2.45           6.76        6.20       18.94      28.36      37.29

In [96]:
# sağlık/sağlıklı yaşam uygulamaları label
df_clean["saglik_uygulama_label"] = df_clean["sağlık/sağlıklı yaşam uygulamaları"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "saglik_uygulama_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_app = pd.crosstab(
    temp["egitim_label"],
    [temp["saglik_uygulama_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_app.columns = [f"{a} {b}" for a, b in ct_egitim_app.columns]

ct_egitim_app = ct_egitim_app.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_app.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         6.67       1.33      66.22      25.78
Üniversite            2.28       2.00      51.23      44.49
Üniversite üstü       2.10       2.23      45.46      50.21

In [97]:
# giyilebilir teknoloji label
df_clean["giyilebilir_label"] = df_clean["internete bağlı saat ve giyilebilir teknoloji ürünleri kullanımı"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "giyilebilir_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_giyilebilir = pd.crosstab(
    temp["egitim_label"],
    [temp["giyilebilir_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_giyilebilir.columns = [f"{a} {b}" for a, b in ct_egitim_giyilebilir.columns]

ct_egitim_giyilebilir = ct_egitim_giyilebilir.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_giyilebilir.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         0.62       0.06      77.26      22.06
Üniversite            0.78       0.81      52.42      45.99
Üniversite üstü       2.26       2.96      41.71      53.07

In [98]:
# internete bağlı sağlık izleme ve tıbbi cihaz kullanımı label
df_clean["tibbi_cihaz_label"] = df_clean["internete bağlı sağlık izleme ve tıbbi cihaz kullanımı"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "tibbi_cihaz_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_cihaz = pd.crosstab(
    temp["egitim_label"],
    [temp["tibbi_cihaz_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_cihaz.columns = [f"{a} {b}" for a, b in ct_egitim_cihaz.columns]

ct_egitim_cihaz = ct_egitim_cihaz.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_cihaz.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         0.50       0.25      77.39      21.87
Üniversite            0.55       0.33      52.65      46.47
Üniversite üstü       0.43       0.63      43.54      55.40

In [99]:
# internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi label
df_clean["risk_label"] = df_clean["internete bağlı cihaz kullanımında emniyet ve sağlık riski endişesi"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "risk_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_risk = pd.crosstab(
    temp["egitim_label"],
    [temp["risk_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_risk.columns = [f"{a} {b}" for a, b in ct_egitim_risk.columns]

ct_egitim_risk = ct_egitim_risk.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_risk.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise         2.07       0.52      78.81      18.60
Üniversite            1.31       1.31      54.61      42.77
Üniversite üstü       1.42       1.37      44.16      53.05

In [100]:
# fiziksel sağlık arama label
df_clean["fiziksel_saglik_label"] = df_clean["fiziksel sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "fiziksel_saglik_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_fiziksel = pd.crosstab(
    temp["egitim_label"],
    [temp["fiziksel_saglik_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_fiziksel.columns = [f"{a} {b}" for a, b in ct_egitim_fiziksel.columns]

ct_egitim_fiziksel = ct_egitim_fiziksel.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_fiziksel.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        72.89      18.07       7.23       1.81
Üniversite           56.25      38.38       3.03       2.33
Üniversite üstü      47.08      48.08       2.00       2.83

In [101]:
# fiziksel sağlık arama label
df_clean["fiziksel_saglik_label"] = df_clean["ruhsal sağlık bilgisi arama"].map({
    1: "Var",
    2: "Yok"
})

# küçük dataset
temp = df_clean[["egitim_label", "fiziksel_saglik_label", "cinsiyet_label"]].dropna()

# crosstab
ct_egitim_fiziksel = pd.crosstab(
    temp["egitim_label"],
    [temp["fiziksel_saglik_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_egitim_fiziksel.columns = [f"{a} {b}" for a, b in ct_egitim_fiziksel.columns]

ct_egitim_fiziksel = ct_egitim_fiziksel.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_fiziksel.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_label
Ortaokul/Lise        31.33       5.42      48.80      14.46
Üniversite           27.23      16.01      32.05      24.71
Üniversite üstü      21.86      20.64      27.22      30.27

In [102]:
df.columns

Index(['referans yıl', 'bülten no', 'fert no', 'fert cevap durumu', 'fert durum', 'cevapsız fert', 'cevaplayan fert', 'cevaplayan fert no', 'yaş', 'cinsiyet',
       ...
       'yapay zeka iş için kullanımı', 'yapay zeka eğitim için kullanımı', 'yapay zeka kullanmama nedeni', 'eticaretten alınan fiziksel mal', 'eticaret sağlık güven sorunu', 'kvkk reklam takip endişesi', 'hanehalkı adresinin kır veya kent olma durumu', 'yas_grup', 'gelir_5li', 'egitim_kategori'], dtype='str', length=471)

In [103]:
df_clean["hane internet erişim durumu"].value_counts()

hane internet erişim durumu
1.0     291456
2.0      41407
99.0       699
Name: count, dtype: int64

In [104]:
df_clean["internet_label"] = df_clean["hane internet erişim durumu"].map({
    1.0: "Var",
    2.0: "Yok"
})

In [105]:
df_clean = df_clean[df_clean["hane internet erişim durumu"] != 99.0]

In [106]:
temp = df_clean[["gelir_5li", "internet_label", "cinsiyet_label"]].dropna()

ct_gelir_internet = pd.crosstab(
    temp["gelir_5li"],
    [temp["internet_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

ct_gelir_internet.columns = [f"{a} {b}" for a, b in ct_gelir_internet.columns]

ct_gelir_internet = ct_gelir_internet.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_gelir_internet)

           Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
gelir_5li
1.0            35.44      31.38      18.26      14.93
2.0            43.13      41.67       7.94       7.26
3.0            47.03      46.32       3.41       3.24
4.0            47.53      48.83       1.82       1.82
5.0            48.43      50.64       0.46       0.47

In [113]:
# 1) İnternet erişim label
df_clean["internet_label"] = df_clean["hane internet erişim durumu"].map({
    1.0: "Var",
    2.0: "Yok"
})

# 2) Sadece gerekli kolonlar
temp = df_clean[["yas_grup", "internet_label", "cinsiyet_label"]].dropna()

# 3) Yaş x İnternet erişimi x Cinsiyet
ct_yas_internet = pd.crosstab(
    temp["yas_grup"],
    [temp["internet_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# 4) Kolon isimleri
ct_yas_internet.columns = [f"{a} {b}" for a, b in ct_yas_internet.columns]

# 5) Kolon sırası
ct_yas_internet = ct_yas_internet.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

# 6) Yaş sırası
ct_yas_internet = ct_yas_internet.reindex([
    "16-30",
    "31-45",
    "46-60",
    "60+"
])

print(ct_yas_internet.to_string())

          Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
yas_grup
16-30         47.94      46.48       2.97       2.61
31-45         47.80      45.90       3.27       3.03
46-60         43.48      44.27       6.96       5.28
60+           33.39      32.99      18.42      15.20

In [115]:
# =========================================================
# EĞİTİM × İNTERNET ERİŞİM İMKANI
# =========================================================

# internet erişim label
df_clean["internet_label"] = df_clean["hane internet erişim durumu"].map({
    1.0: "Var",
    2.0: "Yok"
})

# gerekli kolonlar
temp = df_clean[[
    "eğitim",
    "internet_label",
    "cinsiyet_label"
]].dropna()

# crosstab
ct_egitim_internet = pd.crosstab(
    temp["eğitim"],
    [temp["internet_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# kolon isimleri
ct_egitim_internet.columns = [
    f"{a} {b}" for a, b in ct_egitim_internet.columns
]

# kolon sırası
ct_egitim_internet = ct_egitim_internet.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

print(ct_egitim_internet.to_string())

        Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
eğitim
0.0         38.57       8.15      41.37      11.91
1.0         49.02      19.68      20.02      11.29
2.0         45.88      40.52       6.48       7.11
3.0         41.78      52.77       2.08       3.37
4.0         43.30      54.46       0.85       1.39
5.0         43.09      51.91       1.71       3.29
6.0         39.44      59.25       0.75       0.56
7.0         40.16      59.84       0.00       0.00
51.0        44.48      52.21       1.26       2.04
52.0        43.73      55.65       0.25       0.37
53.0        39.94      58.86       0.45       0.75
511.0       49.01      50.45       0.21       0.33
512.0       47.05      52.70       0.08       0.18

In [116]:
# =========================================================
# EĞİTİM × İNTERNET ERİŞİM İMKANI
# =========================================================

# ---------------------------------------------------------
# 1) İNTERNET ERİŞİM LABEL
# ---------------------------------------------------------
df_clean["internet_label"] = df_clean["hane internet erişim durumu"].map({
    1.0: "Var",
    2.0: "Yok"
})

# ---------------------------------------------------------
# 2) EĞİTİMİ KATEGORİZE ET
# ---------------------------------------------------------
df_clean["egitim_kategori"] = df_clean["eğitim"].replace({

    # İlkokul ve altı
    0: "İlkokul ve altı",
    1: "İlkokul ve altı",

    # Ortaokul / Lise
    2: "Ortaokul/Lise",
    3: "Ortaokul/Lise",
    4: "Ortaokul/Lise",

    # Üniversite
    5: "Üniversite",

    # Üniversite üstü
    6: "Üniversite üstü",
    7: "Üniversite üstü",

    # Alternatif eski kodlar
    51: "Üniversite",
    52: "Üniversite",
    53: "Üniversite üstü",
    511: "Üniversite",
    512: "Üniversite üstü"
})

# ---------------------------------------------------------
# 3) GEREKLİ KOLONLAR
# ---------------------------------------------------------
temp = df_clean[[
    "egitim_kategori",
    "internet_label",
    "cinsiyet_label"
]].dropna()

# ---------------------------------------------------------
# 4) CROSSTAB
# ---------------------------------------------------------
ct_egitim_internet = pd.crosstab(
    temp["egitim_kategori"],
    [temp["internet_label"], temp["cinsiyet_label"]],
    normalize="index"
) * 100

# ---------------------------------------------------------
# 5) KOLON İSİMLERİ
# ---------------------------------------------------------
ct_egitim_internet.columns = [
    f"{a} {b}" for a, b in ct_egitim_internet.columns
]

# ---------------------------------------------------------
# 6) KOLON SIRASI
# ---------------------------------------------------------
ct_egitim_internet = ct_egitim_internet.reindex(columns=[
    "Var Kadın",
    "Var Erkek",
    "Yok Kadın",
    "Yok Erkek"
]).round(2)

# ---------------------------------------------------------
# 7) EĞİTİM SIRASI
# ---------------------------------------------------------
ct_egitim_internet = ct_egitim_internet.reindex([
    "İlkokul ve altı",
    "Ortaokul/Lise",
    "Üniversite",
    "Üniversite üstü"
])

# ---------------------------------------------------------
# 8) SONUÇ
# ---------------------------------------------------------
print(ct_egitim_internet.to_string())

                 Var Kadın  Var Erkek  Yok Kadın  Yok Erkek
egitim_kategori
İlkokul ve altı      47.47      17.97      23.18      11.38
Ortaokul/Lise        44.02      47.89       3.65       4.44
Üniversite           45.93      51.95       0.78       1.33
Üniversite üstü      46.62      53.07       0.10       0.21